// TEF Canada blanc-04 — shared constants and the paper plan.
//
// ── The paper plan ──────────────────────────────────────────────────────────
//
// GENERATED by `scripts/plan-paper.ts 4`, approved as
// `exam-blueprints/PLAN-tef-blanc-04.md`, and pasted here as the ledger the
// planner reads back when it draws paper 5.
//
// A comment rather than data on purpose: nothing at runtime needs it, but
// `plan-paper.ts` scans this header for `TEF-\d+` to know what is spent. Do not
// reformat the ids out of it.
//
//   CO-A   TEF-231 · TEF-232 · TEF-233 · TEF-235
//   CO-B   TEF-201 · TEF-249 · TEF-261 · TEF-264
//   CO-C   TEF-174 · TEF-180
//   CO-D   TEF-77
//   CO-E   TEF-70
//   CO-F   TEF-54
//   CO-G   TEF-79 · TEF-158 · TEF-246 · TEF-170 · TEF-128 · TEF-124 · TEF-169 · TEF-247
//          TEF-177 · TEF-140 · TEF-135 · TEF-187 · TEF-248 · TEF-189 · TEF-149 · TEF-139
//          TEF-198
//   CE-A   TEF-241 · TEF-242 · TEF-243 · TEF-245 · TEF-250 · TEF-252 · TEF-253
//   CE-BC (no topic: gap-fill is written to the grammar point, per TOPICS)
//   CE-DE  TEF-262 · TEF-263
//   CE-F   TEF-42 · TEF-52
//   CE-G   TEF-64
//   EE-A   TEF-165
//   EE-B   TEF-62
//   EO-A   TEF-219
//   EO-B   TEF-254
//
// 46 of the bank's 255 situations, none of them twice, and none shared with
// blanc-01, blanc-02 or blanc-03. `scripts/plan-paper.test.ts` asserts both, against every
// other paper's ledger rather than a hardcoded one.
//
// ── Integrity ───────────────────────────────────────────────────────────────
//
// Every proper noun in the finished stimuli is invented (STANDARD-common §6.1),
// and none of the earlier papers' names are reused: a candidate sitting all
// three should not meet Sainte-Ambre, Nervaux or Aubercy again. This paper's places are
// Aubercy, Grandvaux, Pierrefonte, Mesnil-Doré and Valcourt. Every figure is
// either invented and attributed to an invented source, or is a plain fact of
// the document itself. No real institution, business or person appears.
import { NOTES_CLOSED, NOTES_OPEN, taskIdFor, paperIdFor, FORMAT, FORMAT_VERSION, uniq } from '../tef/common.ts';

export { NOTES_CLOSED, NOTES_OPEN, FORMAT, FORMAT_VERSION, uniq };

export const VARIANT = 'blanc-04';
export const PAPER_ID = paperIdFor(VARIANT, 4);
export const taskId = taskIdFor(VARIANT);

/**
 * Where a miss in this block routes back to for review.
 *
 * GENERATED by `scripts/tef/pick-items.ts 3` from the published corpus. Every
 * entry was filled at the block's own band; the script reports any theme that
 * could not rather than padding it out.
 */

/**
 * Where a miss in this block routes back to for review.
 *
 * GENERATED by `scripts/tef/pick-items.ts 4`.
 *
 * THREE ROUTINGS WERE MOVED BY HAND, and the generator is what found them. It
 * reports a theme two blocks need at bands that share nothing, because a
 * theme-keyed table cannot route both:
 *
 *   la-ville   CO-D wanted it at B2-C1, CO-G at A2-B1, and it carries nothing
 *              above A2. CO-D routes to `hebergement` (B2) instead, which suits
 *              a chronicle on empty housing; la-ville stays A2 for CO-G.
 *   musique    CO-C wanted it at B2-C1 and it carries nothing above A2. CO-C
 *              routes to `questions-sociales` (B2). Its other user, EO-B, is an
 *              open task and routes nothing at all.
 *   examens-et-diplomes  needed at A2-B1 by two block G documents and at B2 by
 *              CE-F. Left at B2, which is right for CE-F; block G's target list
 *              is a union of sixteen themes, so a few B2 ids in it are immaterial.
 */
export const ITEMS = {
  animauxDomestiques: ['fr.a2.animaux-domestiques.001', 'fr.a2.animaux-domestiques.002', 'fr.a2.animaux-domestiques.003', 'fr.a2.animaux-domestiques.004', 'fr.a2.animaux-domestiques.005'],
  argentQuotidien: ['fr.b1.argent-quotidien.001', 'fr.b1.argent-quotidien.002', 'fr.b1.argent-quotidien.003', 'fr.b1.argent-quotidien.004', 'fr.b1.argent-quotidien.005'],
  auRestaurant: ['fr.a2.au-restaurant.001', 'fr.a2.au-restaurant.002', 'fr.a2.au-restaurant.003', 'fr.a2.au-restaurant.004', 'fr.a2.au-restaurant.005'],
  bricolage: ['fr.a2.bricolage.001', 'fr.a2.bricolage.002', 'fr.a2.bricolage.003', 'fr.a2.bricolage.004', 'fr.a2.bricolage.005'],
  cinema: ['fr.a2.cinema.001', 'fr.a2.cinema.002', 'fr.a2.cinema.003', 'fr.a2.cinema.004', 'fr.a2.cinema.005'],
  corps: ['fr.a2.corps.001', 'fr.a2.corps.002', 'fr.a2.corps.003', 'fr.a2.corps.004', 'fr.a2.corps.005'],
  courses: ['fr.a2.courses.001', 'fr.a2.courses.002', 'fr.a2.courses.003', 'fr.a2.courses.004', 'fr.a2.courses.005'],
  cuisine: ['fr.b1.cuisine.001', 'fr.b1.cuisine.002', 'fr.b1.cuisine.003', 'fr.b1.cuisine.004', 'fr.b1.cuisine.005'],
  deplacements: ['fr.a2.deplacements.001', 'fr.a2.deplacements.002', 'fr.a2.deplacements.003', 'fr.a2.deplacements.004', 'fr.a2.deplacements.005'],
  ecole: ['fr.a2.ecole.001', 'fr.a2.ecole.002', 'fr.a2.ecole.003', 'fr.a2.ecole.004', 'fr.a2.ecole.005'],
  ecologie: ['fr.b1.ecologie.001', 'fr.b1.ecologie.002', 'fr.b1.ecologie.003', 'fr.b1.ecologie.004', 'fr.b1.ecologie.005'],
  ethique: ['fr.b2.ethique.001', 'fr.b2.ethique.002', 'fr.b2.ethique.003', 'fr.b2.ethique.004', 'fr.b2.ethique.005'],
  examensEtDiplomes: ['fr.a2.examens-et-diplomes.001', 'fr.a2.examens-et-diplomes.002', 'fr.a2.examens-et-diplomes.003', 'fr.a2.examens-et-diplomes.004', 'fr.a2.examens-et-diplomes.005'],
  famille: ['fr.a2.famille.001', 'fr.a2.famille.002', 'fr.a2.famille.003', 'fr.a2.famille.004', 'fr.a2.famille.005'],
  hebergement: ['fr.b2.hebergement.001', 'fr.b2.hebergement.002', 'fr.b2.hebergement.003', 'fr.b2.hebergement.004', 'fr.b2.hebergement.005'],
  internet: ['fr.b1.internet.001', 'fr.b1.internet.002', 'fr.b1.internet.003', 'fr.b1.internet.004', 'fr.b1.internet.005'],
  journalisme: ['fr.b2.journalisme.001', 'fr.b2.journalisme.002', 'fr.b2.journalisme.003', 'fr.b2.journalisme.004', 'fr.b2.journalisme.005'],
  laVille: ['fr.a2.la-ville.001', 'fr.a2.la-ville.002', 'fr.a2.la-ville.003', 'fr.a2.la-ville.004', 'fr.a2.la-ville.005'],
  litterature: ['fr.b1.litterature.001', 'fr.b1.litterature.002', 'fr.b1.litterature.003', 'fr.b1.litterature.004', 'fr.b1.litterature.005'],
  maison: ['fr.a2.maison.001', 'fr.a2.maison.002', 'fr.a2.maison.003', 'fr.a2.maison.004', 'fr.a2.maison.005'],
  musees: ['fr.b1.musees.001', 'fr.b1.musees.002', 'fr.b1.musees.003', 'fr.b1.musees.004', 'fr.b1.musees.005'],
  musique: ['fr.a2.musique.001', 'fr.a2.musique.002', 'fr.a2.musique.003', 'fr.a2.musique.004', 'fr.a2.musique.005'],
  objets: ['fr.a2.objets.001', 'fr.a2.objets.002', 'fr.a2.objets.003', 'fr.a2.objets.004', 'fr.a2.objets.005'],
  quebecEtFrancophonie: ['fr.b2.quebec-et-francophonie.003', 'fr.b2.quebec-et-francophonie.006', 'fr.b2.quebec-et-francophonie.007', 'fr.b2.quebec-et-francophonie.008', 'fr.b2.quebec-et-francophonie.009'],
  questionsSociales: ['fr.b1.questions-sociales.001', 'fr.b1.questions-sociales.002', 'fr.b1.questions-sociales.003', 'fr.b1.questions-sociales.004', 'fr.b1.questions-sociales.005'],
  rechercheEmploi: ['fr.a2.recherche-emploi.001', 'fr.a2.recherche-emploi.002', 'fr.a2.recherche-emploi.003', 'fr.a2.recherche-emploi.004', 'fr.a2.recherche-emploi.005'],
  sportsEtLoisirs: ['fr.a2.sports-et-loisirs.001', 'fr.a2.sports-et-loisirs.002', 'fr.a2.sports-et-loisirs.003', 'fr.a2.sports-et-loisirs.004', 'fr.a2.sports-et-loisirs.005'],
  technologieQuotidienne: ['fr.a2.technologie-quotidienne.001', 'fr.a2.technologie-quotidienne.002', 'fr.a2.technologie-quotidienne.003', 'fr.a2.technologie-quotidienne.004', 'fr.a2.technologie-quotidienne.005'],
  transportsQuotidiens: ['fr.a2.transports-quotidiens.001', 'fr.a2.transports-quotidiens.002', 'fr.a2.transports-quotidiens.003', 'fr.a2.transports-quotidiens.004', 'fr.a2.transports-quotidiens.005'],
  vetements: ['fr.a2.vetements.001', 'fr.a2.vetements.002', 'fr.a2.vetements.003', 'fr.a2.vetements.004', 'fr.a2.vetements.005'],
  voisinage: ['fr.b1.voisinage.001', 'fr.b1.voisinage.002', 'fr.b1.voisinage.003', 'fr.b1.voisinage.004', 'fr.b1.voisinage.005'],
} as const;
