/* Regenerates data/verbes-ir-familles-rows.gen.ts, the recorded read behind a2.10.l2.
 *
 * a2.10.l2 authors NO infinitive: all twelve verbs already exist in Postgres.
 *
 *     pnpm tsx scripts/_a210l2_manifest.ts
 */
import './env.ts';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { Pool } from 'pg';
import { itemLiteral, unknownPopulatedColumns } from './manifest-item.ts';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, 'data/verbes-ir-familles-rows.gen.ts');

/** verb -> the row this lesson imports, in learner order: the six shedders, then
 *  the five that take -ER endings, then courir.
 *
 *  Chosen the way a2.01, a2.09 and a2.10.l1 chose: a home in `verbes` or
 *  `verbes-essentiels` where one exists, a respelling present, NO `gender`, and a
 *  `flashcard` drill, because all twelve are released into the hub.
 *
 *  `partir` deliberately takes fr.sons.verbes-essentiels.040 and not
 *  fr.a2.verbes.014, even though the latter is in this lesson's own theme: .014
 *  respells `pahr-TEER` and the other seven partir rows all say `par-TEER`, so
 *  .014 is the minority variant. Invariants §9 says a variant is not a violation,
 *  so it is left alone rather than repaired — and not displayed either. */
const VERBS: [string, string][] = [
  ['partir', 'fr.sons.verbes-essentiels.040'],
  ['sortir', 'fr.sons.verbes-essentiels.041'],
  ['dormir', 'fr.sons.verbes-essentiels.039'],
  ['servir', 'fr.a2.courses.080'],
  ['sentir', 'fr.sons.verbes-essentiels.074'],
  ['mentir', 'fr.sons.verbes-essentiels.204'],
  ['ouvrir', 'fr.sons.verbes-essentiels.034'],
  ['offrir', 'fr.sons.verbes-essentiels.053'],
  ['couvrir', 'fr.sons.verbes-essentiels.157'],
  ['découvrir', 'fr.sons.verbes-essentiels.158'],
  ['souffrir', 'fr.b1.verbes.054'],
  ['courir', 'fr.sons.verbes-essentiels.045'],
];

/** Sentences this lesson teaches FROM rather than teaching.
 *
 *  Both are a2.10.l1's own PLURAL rows, reused rather than twinned, because the
 *  pair that proves the infinitive ending predicts nothing has to put two plurals
 *  side by side — one that inserts -iss- and one that restores a consonant:
 *
 *    fr.a2.verbes.202  Les voitures ralentissent ici.   -tir, takes the -iss-
 *    fr.a2.verbes.476  Elles sentent le café.           -tir, restores a t
 *    fr.a2.verbes.198  Ils guérissent vite.             -rir, takes the -iss-
 *    fr.a2.verbes.478  Ils courent vite.                -rir, restores nothing
 *
 *  Reusing l1's rows is the point: these are the exact sentences the learner met
 *  one lesson ago, so the contradiction is with their own memory rather than with
 *  a fresh example invented to make it. */
const REUSED_SENTENCES: string[] = ['fr.a2.verbes.202', 'fr.a2.verbes.198'];

type Row = Record<string, unknown> & { id: string; fr: string; gender: string | null; status: string };

async function main() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 1 });
  const c = await pool.connect();
  const ids = [...VERBS.map((t) => t[1]), ...REUSED_SENTENCES];
  const r = await c.query<Row>('select * from content_items where id = any($1)', [ids]);
  const by = new Map(r.rows.map((x) => [x.id, x]));

  const missing = ids.filter((i) => !by.has(i));
  if (missing.length) { console.error('MISSING FROM POSTGRES:', missing.join(', ')); process.exit(1); }
  const unpublished = r.rows.filter((x) => x.status !== 'published');
  if (unpublished.length) { console.error('NOT PUBLISHED:', unpublished.map((x) => x.id).join(', ')); process.exit(1); }
  const unknown = [...new Set(r.rows.flatMap((x) => unknownPopulatedColumns(x as Record<string, unknown>)))];
  if (unknown.length) { console.error(`!! unmapped populated column(s): ${unknown.join(', ')} — see scripts/manifest-item.ts`); process.exit(1); }

  for (const [verb, id] of VERBS) {
    const x = by.get(id)!;
    if (x.fr !== verb) { console.error(`!! ${id} fr is ${JSON.stringify(x.fr)}, expected ${JSON.stringify(verb)}`); process.exit(1); }
    if (x.gender) { console.error(`!! ${id} "${verb}" carries a gender. An infinitive is not a noun.`); process.exit(1); }
    if (!String(x.drills).includes('flashcard')) { console.error(`!! ${id} "${verb}" has no flashcard drill and is released to the hub`); process.exit(1); }
  }

  const stamp = new Date().toISOString().slice(0, 10);
  const body = `// GENERATED by scripts/_a210l2_manifest.ts on ${stamp}. Do not edit by hand.
//
// A recorded read of the ${ids.length} rows a2.10.l2 imports rather than authors.
// Verified field by field by author-verbes-ir-familles-batch.ts before it opens a
// transaction, and CARRIED into seed.json by the merge, because \`verbes\` and
// \`verbes-essentiels\` are both outside the seed cut.
//
// Regenerate with: pnpm tsx scripts/_a210l2_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The ${VERBS.length} infinitives, in learner order. */
export const IMPORTED_VERB_ROWS: Item[] = [
${VERBS.map(([, id]) => itemLiteral(by.get(id)!)).join('\n')}
];

/** The published sentences this lesson teaches from rather than teaching. */
export const IMPORTED_SENTENCE_ROWS: Item[] = [
${REUSED_SENTENCES.map((id) => itemLiteral(by.get(id)!)).join('\n')}
];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
${VERBS.map(([v, id]) => `  [${JSON.stringify(v)}, ${JSON.stringify(id)}],`).join('\n')}
];
`;
  writeFileSync(OUT, body, 'utf8');
  console.log(`  wrote ${OUT}`);
  for (const [verb, id] of VERBS) {
    const x = by.get(id)!;
    console.log(`    ${verb.padEnd(11)} ${id.padEnd(34)} respell=${(x.respell as string | null) ?? '-'}  drills=${String(x.drills)}`);
  }
  c.release(); await pool.end();
}
main().catch((e) => { console.error(e); process.exit(1); });
