/* Rewires bilan-lesson.ts from v1 (integration lesson) to v2 (exam-shaped).
 *
 *   node scripts/_bilan_v2.mjs
 *
 * Six sections go, the ten hand-written mixed rounds are replaced by fifteen
 * generated by-unit rounds, the acts are rebuilt around what survives, and the
 * error triggers stop pointing at sections that no longer exist.
 *
 * The cut is only safe BECAUSE the rounds are by-unit: s10-bank, s21-flash and
 * s22-review were the only screens 87 items lived on, and a by-unit round names
 * its two units' six contributions in its own stems. Verified: 87 of 87.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const p = 'scripts/data/bilan-lesson.ts';
let t = readFileSync(p, 'utf8');
const before = t.length;

/* ── 1. Import the generated rounds ─────────────────────────────────────── */
t = t.replace(
  "import { AUTHORED_ITEMS, BAND_STATS, CANDO_CLAUSES, COVERED_UNITS } from './bilan-corpus.ts';",
  "import { AUTHORED_ITEMS, BAND_STATS, CANDO_CLAUSES, COVERED_UNITS } from './bilan-corpus.ts';\nimport { BILAN_ROUNDS } from './bilan-rounds.ts';",
);

/* ── 2. Cut six sections ────────────────────────────────────────────────────
 *
 * Each section literal runs from its `{\n    type:` line to the matching `},`
 * at the same indent. Located by id and sliced out whole. */
const CUT = ['s08-mixed', 's10-bank', 's11-oneturn', 's19-reading', 's21-flash', 's22-review'];
for (const id of CUT) {
  const marker = `    id: '${id}',`;
  const at = t.indexOf(marker);
  if (at === -1) { console.error(`  ! section ${id} not found`); continue; }
  // Walk back to the opening `  {` of this section literal.
  const start = t.lastIndexOf('\n  {', at);
  // Walk forward to the closing `\n  },` that ends it.
  const end = t.indexOf('\n  },', at);
  if (start === -1 || end === -1) { console.error(`  ! could not bound ${id}`); continue; }
  t = t.slice(0, start) + t.slice(end + '\n  },'.length);
  console.log(`  cut ${id}`);
}

/* ── 3. Replace the ten hand-written rounds with the fifteen generated ───── */
{
  const open = t.indexOf('    rounds: [');
  const close = t.indexOf('\n    ],\n  },\n\n  {\n    type: \'roundup\'');
  if (open === -1 || close === -1) { console.error('  ! could not bound the rounds array'); process.exit(1); }
  t = t.slice(0, open)
    + '    // FIFTEEN BY-UNIT ROUNDS, generated in bilan-rounds.ts from the selection.\n'
    + '    // Hand-written rounds drift from the coverage rule the moment the corpus\n'
    + '    // moves. These cannot: a round can only ask about rows the selector chose.\n'
    + '    //\n'
    + '    // They are also what keeps the 87 review rows REACHABLE after v2 cut the\n'
    + '    // vocab, flashcard and review sections. Each round names its two units\'\n'
    + '    // six contributions, so the exam is the screen. 87 of 87, checked.\n'
    + '    rounds: BILAN_ROUNDS,'
    + t.slice(close + '\n    ],'.length);
  console.log('  replaced 10 hand-written rounds with 15 generated');
}

/* ── 4. Rebuild the acts around what survives ───────────────────────────── */
{
  const open = t.indexOf('const ACTS: LessonAct[] = [');
  const close = t.indexOf('\n];', open);
  if (open === -1 || close === -1) { console.error('  ! could not bound ACTS'); process.exit(1); }
  const acts = `const ACTS: LessonAct[] = [
  {
    id: 'act1',
    title: 'What you have, and the one thing you do not',
    sections: ['s01-scene', 's02-goals', 's03-lost', 's04-kit', 's05-repeat'],
    milestone: 'You have the thirteen phrases nobody taught you.',
    estScreens: 28,
    restPoints: ['s01-scene/after-break', 's04-kit/halfway'],
  },
  {
    id: 'act2',
    title: 'Recognise it, whoever says it',
    sections: ['s06-listen', 's07-sort', 's09-check'],
    milestone: 'You can hear two lessons arriving in one sentence.',
    estScreens: 20,
    restPoints: ['s07-sort/halfway'],
  },
  {
    id: 'act3',
    title: 'Produce one turn',
    sections: ['s12-drill', 's13-speak', 's14-dictation', 's15-errors'],
    milestone: 'You can build an answer that needs more than one morning of work.',
    estScreens: 24,
    restPoints: ['s12-drill/halfway', 's13-speak/halfway'],
  },
  {
    id: 'act4',
    title: 'Under pressure',
    sections: ['s16-trap-articles', 's17-trap-shapes', 's18-fast'],
    milestone: 'Sixteen questions at speed, and the words were never the difficulty.',
    estScreens: 22,
    restPoints: ['s16-trap-articles/halfway', 's17-trap-shapes/halfway'],
  },
  {
    id: 'act5',
    title: 'Hold a long exchange',
    sections: ['s20-scenario'],
    milestone: 'Eight turns, four changes of subject, and you stayed in it.',
    estScreens: 18,
    restPoints: ['s20-scenario/halfway'],
  },
  {
    id: 'act6',
    title: 'The exam',
    sections: ['s23-progress', 's24-quiz', 's25-roundup'],
    milestone: 'A1 complete.',
    estScreens: 82,
    restPoints: ['s24-quiz/after-r3', 's24-quiz/after-r6', 's24-quiz/after-r9', 's24-quiz/after-r12'],
  },
];`;
  t = t.slice(0, open) + acts + t.slice(close + '\n];'.length);
  console.log('  rebuilt 6 acts around 19 surviving sections');
}

/* ── 5. Error triggers stop naming sections that no longer exist ────────── */
const DEAD_REF = { 's08-mixed': 's07-sort', 's11-oneturn': 's12-drill', 's19-reading': 's20-scenario', 's10-bank': 's09-check', 's21-flash': 's22-review', 's22-review': 's18-fast' };
for (const [dead, live] of Object.entries(DEAD_REF)) {
  t = t.split(`'${dead}'`).join(`'${live}'`);
}
// The quiz round ids changed, so detectOn entries naming old rounds go too.
t = t.replace(/'s24-quiz\/r\d+-[a-z-]+'/g, "'s24-quiz'");
console.log('  repointed error triggers off cut sections and renamed rounds');

/* ── 6. Version, intro and the progress card ────────────────────────────── */
t = t.replace(/^  version: 1,$/m, `  // v1 shipped as an integration lesson: 25 sections, 88 scored moments, and it
  // was verified on a device. Seeing it there, the product owner's judgement was
  // that a band capstone should feel like an exam across lessons 1 to 29.
  //
  // v2 keeps act 1, because twenty-nine lessons teach production and none teaches
  // repair, and this is the band's only remaining slot. Everything after it is
  // assessment. Six sections are cut and the ten hand-written mixed rounds become
  // fifteen generated by-unit rounds.
  //
  // The two halves of that are NOT independent. Cutting s10-bank, s21-flash and
  // s22-review removes the only screens 87 of the 101 items lived on, and every
  // itemId must be on a screen. A by-unit round names its own two units' six
  // contributions, so the exam becomes the screen: 87 of 87, checked. A
  // mixed-topic exam cannot do that, which is why reverting the rounds while
  // keeping the cut goes red on reachability.
  version: 2,`);

writeFileSync(p, t);
console.log(`\n  bilan-lesson.ts rewired: ${before} -> ${t.length} bytes`);
