// TEF Canada blanc-03 — shared constants and the paper plan.
//
// ── The paper plan ──────────────────────────────────────────────────────────
//
// GENERATED by `scripts/plan-paper.ts 3`, approved as
// `exam-blueprints/PLAN-tef-blanc-03.md`, and pasted here as the ledger the
// planner reads back when it draws papers 4 and 5.
//
// A comment rather than data on purpose: nothing at runtime needs it, but
// `plan-paper.ts` scans this header for `TEF-\d+` to know what is spent. Do not
// reformat the ids out of it.
//
//   CO-A   TEF-185 · TEF-227 · TEF-228 · TEF-229
//   CO-B   TEF-150 · TEF-154 · TEF-167 · TEF-188
//   CO-C   TEF-123 · TEF-155
//   CO-D   TEF-50
//   CO-E   TEF-14
//   CO-F   TEF-43
//   CO-G   TEF-230 · TEF-117 · TEF-203 · TEF-131 · TEF-92 · TEF-234 · TEF-129 · TEF-239
//          TEF-143 · TEF-104 · TEF-237 · TEF-141 · TEF-244 · TEF-151 · TEF-116 · TEF-67
//          TEF-160
//   CE-A   TEF-175 · TEF-183 · TEF-186 · TEF-211 · TEF-225 · TEF-238 · TEF-240
//   CE-BC (no topic: gap-fill is written to the grammar point, per TOPICS)
//   CE-DE  TEF-193 · TEF-218
//   CE-F   TEF-21 · TEF-26
//   CE-G   TEF-47
//   EE-A   TEF-111
//   EE-B   TEF-39
//   EO-A   TEF-195
//   EO-B   TEF-251
//
// 46 of the bank's 255 situations, none of them twice, and none shared with
// blanc-01 or blanc-02. `scripts/plan-paper.test.ts` asserts both, against every
// other paper's ledger rather than a hardcoded one.
//
// ── Integrity ───────────────────────────────────────────────────────────────
//
// Every proper noun in the finished stimuli is invented (STANDARD-common §6.1),
// and none of the earlier papers' names are reused: a candidate sitting all
// three should not meet Sainte-Ambre or Nervaux again. This paper's places are
// Aubercy, Grandvaux, Pierrefonte, Mesnil-Doré and Valcourt. Every figure is
// either invented and attributed to an invented source, or is a plain fact of
// the document itself. No real institution, business or person appears.
import { NOTES_CLOSED, NOTES_OPEN, taskIdFor, paperIdFor, FORMAT, FORMAT_VERSION, uniq } from '../tef/common.ts';

export { NOTES_CLOSED, NOTES_OPEN, FORMAT, FORMAT_VERSION, uniq };

export const VARIANT = 'blanc-03';
export const PAPER_ID = paperIdFor(VARIANT, 3);
export const taskId = taskIdFor(VARIANT);

/**
 * Where a miss in this block routes back to for review.
 *
 * GENERATED by `scripts/tef/pick-items.ts 3` from the published corpus. Every
 * entry was filled at the block's own band; the script reports any theme that
 * could not rather than padding it out.
 */
export const ITEMS = {
  animauxDomestiques: ['fr.a2.animaux-domestiques.001', 'fr.a2.animaux-domestiques.002', 'fr.a2.animaux-domestiques.003', 'fr.a2.animaux-domestiques.004', 'fr.a2.animaux-domestiques.005'],
  appareils: ['fr.a2.appareils.001', 'fr.a2.appareils.002', 'fr.a2.appareils.003', 'fr.a2.appareils.004', 'fr.a2.appareils.005'],
  argentQuotidien: ['fr.b1.argent-quotidien.001', 'fr.b1.argent-quotidien.002', 'fr.b1.argent-quotidien.003', 'fr.b1.argent-quotidien.004', 'fr.b1.argent-quotidien.005'],
  auRestaurant: ['fr.a2.au-restaurant.001', 'fr.a2.au-restaurant.002', 'fr.a2.au-restaurant.003', 'fr.a2.au-restaurant.004', 'fr.a2.au-restaurant.005'],
  collegues: ['fr.a2.collegues.001', 'fr.a2.collegues.002', 'fr.a2.collegues.003', 'fr.a2.collegues.004', 'fr.a2.collegues.005'],
  communaute: ['fr.a2.communaute.001', 'fr.a2.communaute.002', 'fr.a2.communaute.003', 'fr.a2.communaute.004', 'fr.a2.communaute.005'],
  corps: ['fr.a2.corps.001', 'fr.a2.corps.002', 'fr.a2.corps.003', 'fr.a2.corps.004', 'fr.a2.corps.005'],
  courses: ['fr.a2.courses.001', 'fr.a2.courses.002', 'fr.a2.courses.003', 'fr.a2.courses.004', 'fr.a2.courses.005'],
  cuisine: ['fr.a2.cuisine.001', 'fr.a2.cuisine.002', 'fr.a2.cuisine.003', 'fr.a2.cuisine.004', 'fr.a2.cuisine.005'],
  deplacements: ['fr.a2.deplacements.001', 'fr.a2.deplacements.002', 'fr.a2.deplacements.003', 'fr.a2.deplacements.004', 'fr.a2.deplacements.005'],
  droit: ['fr.b1.droit.001', 'fr.b1.droit.002', 'fr.b1.droit.003', 'fr.b1.droit.004', 'fr.b1.droit.005'],
  // `ecole` and `la-ville` carry NOTHING above A2, so the generator fell back to
  // the whole theme and said so. Routing a B2/C1 miss to A1 vocabulary sends a
  // learner somewhere the item never tested, so the two blocks that needed them
  // route to a neighbouring theme that exists at the right band instead:
  // CO-F (orientation apres le lycee) -> examens-et-diplomes, CO-C (amenagement
  // cyclable) -> questions-sociales. Both are B2.
  examensEtDiplomes: ['fr.b2.examens-et-diplomes.001', 'fr.b2.examens-et-diplomes.004', 'fr.b2.examens-et-diplomes.005', 'fr.b2.examens-et-diplomes.006', 'fr.b2.examens-et-diplomes.007'],
  ecologie: ['fr.b1.ecologie.001', 'fr.b1.ecologie.002', 'fr.b1.ecologie.003', 'fr.b1.ecologie.004', 'fr.b1.ecologie.005'],
  entraide: ['fr.a2.entraide.001', 'fr.a2.entraide.002', 'fr.a2.entraide.003', 'fr.a2.entraide.004', 'fr.a2.entraide.005'],
  evenementsFamiliaux: ['fr.a2.evenements-familiaux.001', 'fr.a2.evenements-familiaux.002', 'fr.a2.evenements-familiaux.003', 'fr.a2.evenements-familiaux.004', 'fr.a2.evenements-familiaux.005'],
  gouvernement: ['fr.a2.gouvernement.001', 'fr.a2.gouvernement.002', 'fr.a2.gouvernement.003', 'fr.a2.gouvernement.004', 'fr.a2.gouvernement.005'],
  hebergement: ['fr.a2.hebergement.001', 'fr.a2.hebergement.002', 'fr.a2.hebergement.003', 'fr.a2.hebergement.004', 'fr.a2.hebergement.005'],
  questionsSociales: ['fr.b2.questions-sociales.001', 'fr.b2.questions-sociales.002', 'fr.b2.questions-sociales.003', 'fr.b2.questions-sociales.004', 'fr.b2.questions-sociales.005'],
  lesFetes: ['fr.a2.les-fetes.001', 'fr.a2.les-fetes.002', 'fr.a2.les-fetes.003', 'fr.a2.les-fetes.004', 'fr.a2.les-fetes.005'],
  maison: ['fr.a2.maison.001', 'fr.a2.maison.002', 'fr.a2.maison.003', 'fr.a2.maison.004', 'fr.a2.maison.005'],
  marche: ['fr.a2.marche.001', 'fr.a2.marche.002', 'fr.a2.marche.003', 'fr.a2.marche.004', 'fr.a2.marche.005'],
  meteo: ['fr.a2.meteo.001', 'fr.a2.meteo.002', 'fr.a2.meteo.003', 'fr.a2.meteo.004', 'fr.a2.meteo.005'],
  metiers: ['fr.b1.metiers.001', 'fr.b1.metiers.002', 'fr.b1.metiers.003', 'fr.b1.metiers.004', 'fr.b1.metiers.005'],
  musees: ['fr.b1.musees.001', 'fr.b1.musees.002', 'fr.b1.musees.003', 'fr.b1.musees.004', 'fr.b1.musees.005'],
  objets: ['fr.a2.objets.001', 'fr.a2.objets.002', 'fr.a2.objets.003', 'fr.a2.objets.004', 'fr.a2.objets.005'],
  reseauxSociaux: ['fr.b1.reseaux-sociaux.001', 'fr.b1.reseaux-sociaux.002', 'fr.b1.reseaux-sociaux.003', 'fr.b1.reseaux-sociaux.004', 'fr.b1.reseaux-sociaux.005'],
  soins: ['fr.b1.soins.001', 'fr.b1.soins.002', 'fr.b1.soins.003', 'fr.b1.soins.004', 'fr.b1.soins.005'],
  sportsEtLoisirs: ['fr.a2.sports-et-loisirs.001', 'fr.a2.sports-et-loisirs.002', 'fr.a2.sports-et-loisirs.003', 'fr.a2.sports-et-loisirs.004', 'fr.a2.sports-et-loisirs.005'],
  systemeDeSante: ['fr.b1.systeme-de-sante.001', 'fr.b1.systeme-de-sante.006', 'fr.b1.systeme-de-sante.007', 'fr.b1.systeme-de-sante.009', 'fr.b1.systeme-de-sante.012'],
  tourisme: ['fr.a2.tourisme.001', 'fr.a2.tourisme.002', 'fr.a2.tourisme.003', 'fr.a2.tourisme.004', 'fr.a2.tourisme.005'],
  transportsQuotidiens: ['fr.a2.transports-quotidiens.001', 'fr.a2.transports-quotidiens.002', 'fr.a2.transports-quotidiens.003', 'fr.a2.transports-quotidiens.004', 'fr.a2.transports-quotidiens.005'],
  universite: ['fr.b1.universite.001', 'fr.b1.universite.002', 'fr.b1.universite.003', 'fr.b1.universite.004', 'fr.b1.universite.005'],
  vetements: ['fr.a2.vetements.001', 'fr.a2.vetements.002', 'fr.a2.vetements.003', 'fr.a2.vetements.004', 'fr.a2.vetements.005'],
} as const;
