// TCF Canada blanc-04 — shared constants and the paper plan.
//
// ── The paper plan ──────────────────────────────────────────────────────────
//
// TOPICS-tcf-canada.md rule 1: no topic is reused across TCF papers. The ids
// below are what scripts/tcf/plan-paper.ts emitted for this paper and what it
// reads back to know what paper 5 must avoid, so this ledger is DERIVED
// rather than re-typed. Generated by scripts/tcf/scaffold-paper.ts.
//
// The full layout, including which document carries how many questions, is in
// exam-blueprints/PLAN-tcf-blanc-04.md. Re-run the planner to regenerate it.
//
//   CO
//       TCF-85 · TCF-88 · TCF-90 · TCF-127 · TCF-129 · TCF-131 · TCF-134 · TCF-136
//       TCF-138 · TCF-184 · TCF-189 · TCF-193 · TCF-244 · TCF-245 · TCF-259 · TCF-260
//       TCF-208 · TCF-210 · TCF-212 · TCF-214 · TCF-228 · TCF-230 · TCF-254 · TCF-235
//   CE
//       TCF-84 · TCF-86 · TCF-87 · TCF-124 · TCF-126 · TCF-128 · TCF-130 · TCF-133
//       TCF-135 · TCF-177 · TCF-179 · TCF-182 · TCF-185 · TCF-187 · TCF-190 · TCF-194
//       TCF-207 · TCF-211 · TCF-213 · TCF-215 · TCF-219 · TCF-221 · TCF-72
//   EE  TCF-249 (T1) · TCF-171 (T2) · TCF-217 (T3)
//   EO  TCF-264 (T1) · TCF-262 (T2) · TCF-54 (T3)
//
// ── The ramp is the instrument ──────────────────────────────────────────────
//
// 39 questions per comprehension épreuve, A1 to C2, in order: 3/6/10/10/7/3.
// Order is CONTENT here in a way it is not on TEF — item 4 is A2 because it is
// item 4 — so nothing may reorder a section, and scripts/tcf/paper-rules.ts
// refuses a paper whose ramp goes backwards even when the counts balance.
//
// ── Integrity ───────────────────────────────────────────────────────────────
//
// Every proper noun below is invented (STANDARD-common §6.1). Every figure is
// either invented and attributed to an invented source, or a plain fact of the
// document itself. No real institution, business or person appears anywhere.

export const FORMAT = 'tcf_canada' as const;
export const VARIANT = 'blanc-04';
export const FORMAT_VERSION = 'tcf-canada-2026.01';
export const PAPER_ID = `paper.${FORMAT}.${VARIANT}.4`;

export const taskId = (taskType: string, seq: string) =>
  `exam.${FORMAT}.${VARIANT}.${taskType}.${seq}`;

/** Carried by every closed task. STANDARD-common §7, plus the scoring
 *  disclaimer. CO and CE use SEPARATE NCLC tables on this format. */
export const NOTES_CLOSED = [
  'Épreuve blanche rédigée par Ealch d’après le format publié. Ce n’est pas un sujet officiel et aucun extrait ne provient d’un sujet réel.',
  'Le barème brut vers échelle est une estimation experte, pas une équivalence officielle. Les seuils NCLC proviennent de la grille IRCC.',
];

export const NOTES_OPEN = [
  'Épreuve blanche rédigée par Ealch d’après le format publié. Ce n’est pas un sujet officiel.',
  'La grille de correction est notre propre construction : le centre d’examen ne publie pas le libellé de ses descripteurs.',
  'La correction est assistée par IA et s’appuie sur cette grille et sur cette réponse modèle. Le résultat est une estimation d’entraînement, jamais un score équivalent.',
];

export const uniq = (...groups: readonly (readonly string[])[]) => [...new Set(groups.flat())];

/** Corpus items this paper routes misses back to, by theme and BAND.
 *
 *  Generated by scripts/tcf/pick-items.ts — do not hand-edit, re-run it.
 *  Keyed by band because a TCF document sits at exactly one, and remediation
 *  must land at or below the failure rather than above it. */
export const ITEMS = {
  amis: {
    a1: ['fr.a1.amis.001', 'fr.a1.amis.002', 'fr.a1.amis.003', 'fr.a1.amis.004', 'fr.a1.amis.005', 'fr.a1.amis.006'],
  },
  appareils: {
    a2: ['fr.a2.appareils.001', 'fr.a2.appareils.002', 'fr.a2.appareils.003', 'fr.a2.appareils.004', 'fr.a2.appareils.005', 'fr.a2.appareils.006'],
  },
  communaute: {
    b1: ['fr.b1.communaute.001', 'fr.b1.communaute.002', 'fr.b1.communaute.003', 'fr.b1.communaute.004', 'fr.b1.communaute.005', 'fr.b1.communaute.006'],
  },
  cuisine: {
    a1: ['fr.a1.cuisine.001', 'fr.a1.cuisine.002', 'fr.a1.cuisine.003', 'fr.a1.cuisine.004', 'fr.a1.cuisine.005', 'fr.a1.cuisine.006'],
  },
  decouvertes: {
    c2: ['fr.c1.decouvertes.001', 'fr.c1.decouvertes.002', 'fr.c1.decouvertes.003', 'fr.c1.decouvertes.004', 'fr.c1.decouvertes.005'],
  },
  douaneEtImmigration: {
    a2: ['fr.a2.douane-et-immigration.006', 'fr.a2.douane-et-immigration.009', 'fr.a2.douane-et-immigration.010', 'fr.a2.douane-et-immigration.011', 'fr.a2.douane-et-immigration.014', 'fr.a2.douane-et-immigration.015'],
  },
  droit: {
    b1: ['fr.b1.droit.001', 'fr.b1.droit.002', 'fr.b1.droit.003', 'fr.b1.droit.004', 'fr.b1.droit.005', 'fr.b1.droit.006'],
    b2: ['fr.b2.droit.001', 'fr.b2.droit.002', 'fr.b2.droit.003', 'fr.b2.droit.004', 'fr.b2.droit.005', 'fr.b2.droit.006'],
  },
  ecole: {
    a2: ['fr.a2.ecole.001', 'fr.a2.ecole.002', 'fr.a2.ecole.003', 'fr.a2.ecole.004', 'fr.a2.ecole.005', 'fr.a2.ecole.006'],
  },
  ethique: {
    c1: ['fr.c1.ethique.001', 'fr.c1.ethique.002', 'fr.c1.ethique.003', 'fr.c1.ethique.004', 'fr.c1.ethique.005', 'fr.c1.ethique.006'],
  },
  examensEtDiplomes: {
    a2: ['fr.a2.examens-et-diplomes.001', 'fr.a2.examens-et-diplomes.002', 'fr.a2.examens-et-diplomes.003', 'fr.a2.examens-et-diplomes.004', 'fr.a2.examens-et-diplomes.005', 'fr.a2.examens-et-diplomes.006'],
  },
  famille: {
    a1: ['fr.a1.famille.001', 'fr.a1.famille.002', 'fr.a1.famille.003', 'fr.a1.famille.004', 'fr.a1.famille.005', 'fr.a1.famille.006'],
  },
  hebergement: {
    a2: ['fr.a2.hebergement.001', 'fr.a2.hebergement.002', 'fr.a2.hebergement.003', 'fr.a2.hebergement.004', 'fr.a2.hebergement.005', 'fr.a2.hebergement.006'],
    b2: ['fr.b2.hebergement.001', 'fr.b2.hebergement.002', 'fr.b2.hebergement.003', 'fr.b2.hebergement.004', 'fr.b2.hebergement.005', 'fr.b2.hebergement.006'],
  },
  meteo: {
    a1: ['fr.a1.meteo.001', 'fr.a1.meteo.002', 'fr.a1.meteo.003', 'fr.a1.meteo.004', 'fr.a1.meteo.005', 'fr.a1.meteo.006'],
  },
  methodeScientifique: {
    c2: ['fr.c1.methode-scientifique.001', 'fr.c1.methode-scientifique.002', 'fr.c1.methode-scientifique.003', 'fr.c1.methode-scientifique.004', 'fr.c1.methode-scientifique.005', 'fr.c1.methode-scientifique.006'],
  },
  metiers: {
    b1: ['fr.b1.metiers.001', 'fr.b1.metiers.002', 'fr.b1.metiers.003', 'fr.b1.metiers.004', 'fr.b1.metiers.005', 'fr.b1.metiers.006'],
  },
  musees: {
    b1: ['fr.b1.musees.001', 'fr.b1.musees.002', 'fr.b1.musees.003', 'fr.b1.musees.004', 'fr.b1.musees.005', 'fr.b1.musees.006'],
    b2: ['fr.b2.musees.001', 'fr.b2.musees.002', 'fr.b2.musees.003', 'fr.b2.musees.004', 'fr.b2.musees.005', 'fr.b2.musees.006'],
  },
  musique: {
    b1: ['fr.b1.musique.001', 'fr.b1.musique.002', 'fr.b1.musique.003', 'fr.b1.musique.004', 'fr.b1.musique.005', 'fr.b1.musique.006'],
  },
  objets: {
    a1: ['fr.a1.objets.001', 'fr.a1.objets.002', 'fr.a1.objets.003', 'fr.a1.objets.004', 'fr.a1.objets.005', 'fr.a1.objets.006'],
    a2: ['fr.a2.objets.001', 'fr.a2.objets.002', 'fr.a2.objets.003', 'fr.a2.objets.004', 'fr.a2.objets.005', 'fr.a2.objets.006'],
  },
  philosophie: {
    c1: ['fr.c1.philosophie.001', 'fr.c1.philosophie.002', 'fr.c1.philosophie.003', 'fr.c1.philosophie.004', 'fr.c1.philosophie.005', 'fr.c1.philosophie.006'],
  },
  presentationPersonnelle: {
    a1: ['fr.a1.presentation-personnelle.001', 'fr.a1.presentation-personnelle.002', 'fr.a1.presentation-personnelle.003', 'fr.a1.presentation-personnelle.004', 'fr.a1.presentation-personnelle.005', 'fr.a1.presentation-personnelle.006'],
  },
  quebecEtFrancophonie: {
    b1: ['fr.b1.quebec-et-francophonie.006', 'fr.b1.quebec-et-francophonie.009', 'fr.b1.quebec-et-francophonie.010', 'fr.b1.quebec-et-francophonie.011', 'fr.b1.quebec-et-francophonie.012', 'fr.b1.quebec-et-francophonie.015'],
    b2: ['fr.b2.quebec-et-francophonie.003', 'fr.b2.quebec-et-francophonie.006', 'fr.b2.quebec-et-francophonie.007', 'fr.b2.quebec-et-francophonie.008', 'fr.b2.quebec-et-francophonie.009', 'fr.b2.quebec-et-francophonie.010'],
  },
  rechercheEmploi: {
    b2: ['fr.b2.recherche-emploi.001', 'fr.b2.recherche-emploi.009', 'fr.b2.recherche-emploi.011', 'fr.b2.recherche-emploi.018', 'fr.b2.recherche-emploi.019', 'fr.b2.recherche-emploi.027'],
  },
  reseauxSociaux: {
    b1: ['fr.b1.reseaux-sociaux.001', 'fr.b1.reseaux-sociaux.002', 'fr.b1.reseaux-sociaux.003', 'fr.b1.reseaux-sociaux.004', 'fr.b1.reseaux-sociaux.005', 'fr.b1.reseaux-sociaux.006'],
  },
  rpVoyage: {
    a2: ['fr.a2.rp-voyage.001', 'fr.a2.rp-voyage.002', 'fr.a2.rp-voyage.003', 'fr.a2.rp-voyage.004', 'fr.a2.rp-voyage.005', 'fr.a2.rp-voyage.006'],
    b1: ['fr.b1.rp-voyage.001', 'fr.b1.rp-voyage.002', 'fr.b1.rp-voyage.003', 'fr.b1.rp-voyage.004', 'fr.b1.rp-voyage.005', 'fr.b1.rp-voyage.006'],
  },
  soins: {
    b2: ['fr.b2.soins.001', 'fr.b2.soins.002', 'fr.b2.soins.003', 'fr.b2.soins.004', 'fr.b2.soins.005', 'fr.b2.soins.006'],
  },
  sportsEtLoisirs: {
    a2: ['fr.a2.sports-et-loisirs.001', 'fr.a2.sports-et-loisirs.002', 'fr.a2.sports-et-loisirs.003', 'fr.a2.sports-et-loisirs.004', 'fr.a2.sports-et-loisirs.005', 'fr.a2.sports-et-loisirs.006'],
    b1: ['fr.b1.sports-et-loisirs.001', 'fr.b1.sports-et-loisirs.002', 'fr.b1.sports-et-loisirs.003', 'fr.b1.sports-et-loisirs.004', 'fr.b1.sports-et-loisirs.005', 'fr.b1.sports-et-loisirs.006'],
  },
  systemeDeSante: {
    a2: ['fr.a2.systeme-de-sante.001', 'fr.a2.systeme-de-sante.002', 'fr.a2.systeme-de-sante.003', 'fr.a2.systeme-de-sante.004', 'fr.a2.systeme-de-sante.005', 'fr.a2.systeme-de-sante.006'],
    b1: ['fr.b1.systeme-de-sante.001', 'fr.b1.systeme-de-sante.006', 'fr.b1.systeme-de-sante.007', 'fr.b1.systeme-de-sante.009', 'fr.b1.systeme-de-sante.012', 'fr.b1.systeme-de-sante.016'],
  },
  traditions: {
    b2: ['fr.b2.traditions.001', 'fr.b2.traditions.002', 'fr.b2.traditions.003', 'fr.b2.traditions.004', 'fr.b2.traditions.005', 'fr.b2.traditions.006'],
  },
  transportsQuotidiens: {
    a2: ['fr.a2.transports-quotidiens.001', 'fr.a2.transports-quotidiens.002', 'fr.a2.transports-quotidiens.003', 'fr.a2.transports-quotidiens.004', 'fr.a2.transports-quotidiens.005', 'fr.a2.transports-quotidiens.006'],
  },
  valeurs: {
    b2: ['fr.b2.valeurs.001', 'fr.b2.valeurs.002', 'fr.b2.valeurs.003', 'fr.b2.valeurs.004', 'fr.b2.valeurs.005', 'fr.b2.valeurs.006'],
  },
  vetements: {
    b1: ['fr.b1.vetements.001', 'fr.b1.vetements.002', 'fr.b1.vetements.003', 'fr.b1.vetements.004', 'fr.b1.vetements.005', 'fr.b1.vetements.006'],
  },
  voisinage: {
    b1: ['fr.b1.voisinage.001', 'fr.b1.voisinage.002', 'fr.b1.voisinage.003', 'fr.b1.voisinage.004', 'fr.b1.voisinage.005', 'fr.b1.voisinage.006'],
  },
} as const;
