// TCF Canada blanc-02 — shared constants and the paper plan.
//
// ── The paper plan ───────────────────────────────────────────────
//
// TOPICS-tcf-canada.md rule 1: no topic is reused across TCF papers. The ids
// below are what scripts/tcf/plan-paper.ts emitted for this paper and what it
// reads back to know what paper 3 must avoid, so this ledger is DERIVED rather
// than re-typed. TEF's blanc-01 typed its ledger by hand and both its figures
// were wrong, which made paper 2 look buildable when it was not.
//
// Papers 2 to 5 were planned in ONE run for the same reason. `spent()` reads
// AUTHORED papers, and none of 3, 4 or 5 exists yet, so planning them
// separately returns four identical papers that each look internally correct.
//
// The full layout, including which document carries how many questions, is in
// exam-blueprints/PLAN-tcf-blanc-02.md. Re-run the planner to regenerate it.
//
//   CO
//       TCF-08 · TCF-74 · TCF-77 · TCF-99 · TCF-101 · TCF-104 · TCF-106 · TCF-109
//       TCF-111 · TCF-149 · TCF-151 · TCF-153 · TCF-155 · TCF-157 · TCF-159 · TCF-161
//       TCF-49 · TCF-50 · TCF-52 · TCF-198 · TCF-63 · TCF-66 · TCF-220 · TCF-71
//   CE
//       TCF-73 · TCF-75 · TCF-76 · TCF-95 · TCF-97 · TCF-100 · TCF-102 · TCF-105
//       TCF-108 · TCF-35 · TCF-144 · TCF-146 · TCF-150 · TCF-152 · TCF-154 · TCF-156
//       TCF-47 · TCF-48 · TCF-51 · TCF-53 · TCF-59 · TCF-60 · TCF-68
//   EE  TCF-164 (T1) · TCF-148 (T2) · TCF-197 (T3)
//   EO  TCF-186 (T1) · TCF-178 (T2) · TCF-166 (T3)
//
// ── The ramp is the instrument ───────────────────────────────────────
//
// 39 questions per comprehension épreuve, A1 to C2, in order: 3/6/10/10/7/3.
// Order is CONTENT here in a way it is not on TEF — item 4 is A2 because it is
// item 4 — so nothing may reorder a section, and scripts/tcf/paper-rules.ts
// refuses a paper whose ramp goes backwards even when the counts balance.
//
// ── Integrity ──────────────────────────────────────────────────
//
// Every proper noun below is invented (STANDARD-common §6.1). Every figure is
// either invented and attributed to an invented source, or a plain fact of the
// document itself. No real institution, business or person appears anywhere.

export const FORMAT = 'tcf_canada' as const;
export const VARIANT = 'blanc-02';
export const FORMAT_VERSION = 'tcf-canada-2026.01';
export const PAPER_ID = `paper.${FORMAT}.${VARIANT}.2`;

export const taskId = (taskType: string, seq: string) =>
  `exam.${FORMAT}.${VARIANT}.${taskType}.${seq}`;

/** Carried by every closed task. STANDARD-common §7, plus the scoring
 *  disclaimer. CO and CE use SEPARATE NCLC tables on this format. */
export const NOTES_CLOSED = [
  'Épreuve blanche rédigée par Ealch d’après le format publié. Ce n’est pas un sujet officiel et aucun extrait ne provient d’un sujet réel.',
  'Le barème brut vers échelle est une estimation experte, pas une équivalence officielle. Les seuils NCLC proviennent de la grille IRCC.',
];

export const NOTES_OPEN = [
  'Épreuve blanche rédigée par Ealch d’après le format publié. Ce n’est pas un sujet officiel.',
  'La grille de correction est notre propre construction : le centre d’examen ne publie pas le libellé de ses descripteurs.',
  'La correction est assistée par IA et s’appuie sur cette grille et sur cette réponse modèle. Le résultat est une estimation d’entraînement, jamais un score équivalent.',
];

export const uniq = (...groups: readonly (readonly string[])[]) => [...new Set(groups.flat())];

/** Corpus items this paper routes misses back to, by theme and BAND.
 *
 *  Generated by scripts/tcf/pick-items.ts — do not hand-edit, re-run it.
 *  Keyed by band because a TCF document sits at exactly one, and remediation
 *  must land at or below the failure rather than above it. */
export const ITEMS = {
  affaires: {
    b1: ['fr.b1.affaires.001', 'fr.b1.affaires.002', 'fr.b1.affaires.003', 'fr.b1.affaires.004', 'fr.b1.affaires.005', 'fr.b1.affaires.006'],
  },
  argotClassique: {
    c1: ['fr.c1.argot-classique.001', 'fr.c1.argot-classique.002', 'fr.c1.argot-classique.003', 'fr.c1.argot-classique.004', 'fr.c1.argot-classique.005', 'fr.c1.argot-classique.006'],
    c2: ['fr.c1.argot-classique.001', 'fr.c1.argot-classique.002', 'fr.c1.argot-classique.003', 'fr.c1.argot-classique.004', 'fr.c1.argot-classique.005', 'fr.c1.argot-classique.006'],
  },
  bureau: {
    b1: ['fr.b1.bureau.001', 'fr.b1.bureau.002', 'fr.b1.bureau.003', 'fr.b1.bureau.004', 'fr.b1.bureau.005', 'fr.b1.bureau.006'],
  },
  cafe: {
    a1: ['fr.a1.cafe.001', 'fr.a1.cafe.002', 'fr.a1.cafe.003', 'fr.a1.cafe.004', 'fr.a1.cafe.005', 'fr.a1.cafe.006'],
  },
  collegues: {
    a2: ['fr.a2.collegues.001', 'fr.a2.collegues.002', 'fr.a2.collegues.003', 'fr.a2.collegues.004', 'fr.a2.collegues.005', 'fr.a2.collegues.006'],
    b1: ['fr.b1.collegues.001', 'fr.b1.collegues.002', 'fr.b1.collegues.003', 'fr.b1.collegues.004', 'fr.b1.collegues.005', 'fr.b1.collegues.006'],
  },
  communaute: {
    a2: ['fr.a2.communaute.001', 'fr.a2.communaute.002', 'fr.a2.communaute.003', 'fr.a2.communaute.004', 'fr.a2.communaute.005', 'fr.a2.communaute.006'],
    b1: ['fr.b1.communaute.001', 'fr.b1.communaute.002', 'fr.b1.communaute.003', 'fr.b1.communaute.004', 'fr.b1.communaute.005', 'fr.b1.communaute.006'],
  },
  conflitsReconciliation: {
    b1: ['fr.b1.conflits-reconciliation.001', 'fr.b1.conflits-reconciliation.002', 'fr.b1.conflits-reconciliation.003', 'fr.b1.conflits-reconciliation.004', 'fr.b1.conflits-reconciliation.005', 'fr.b1.conflits-reconciliation.006'],
  },
  courses: {
    a2: ['fr.a2.courses.001', 'fr.a2.courses.002', 'fr.a2.courses.003', 'fr.a2.courses.004', 'fr.a2.courses.005', 'fr.a2.courses.006'],
  },
  douaneEtImmigration: {
    b1: ['fr.b1.douane-et-immigration.006', 'fr.b1.douane-et-immigration.010', 'fr.b1.douane-et-immigration.016', 'fr.b1.douane-et-immigration.017', 'fr.b1.douane-et-immigration.023', 'fr.b1.douane-et-immigration.026'],
  },
  droit: {
    b2: ['fr.b2.droit.001', 'fr.b2.droit.002', 'fr.b2.droit.003', 'fr.b2.droit.004', 'fr.b2.droit.005', 'fr.b2.droit.006'],
  },
  ecologie: {
    b2: ['fr.b2.ecologie.001', 'fr.b2.ecologie.002', 'fr.b2.ecologie.003', 'fr.b2.ecologie.004', 'fr.b2.ecologie.005', 'fr.b2.ecologie.006'],
  },
  economie: {
    b2: ['fr.b2.economie.001', 'fr.b2.economie.002', 'fr.b2.economie.003', 'fr.b2.economie.004', 'fr.b2.economie.005', 'fr.b2.economie.006'],
  },
  entraide: {
    b1: ['fr.b1.entraide.001', 'fr.b1.entraide.002', 'fr.b1.entraide.003', 'fr.b1.entraide.004', 'fr.b1.entraide.005', 'fr.b1.entraide.006'],
  },
  ethique: {
    c1: ['fr.c1.ethique.001', 'fr.c1.ethique.002', 'fr.c1.ethique.003', 'fr.c1.ethique.004', 'fr.c1.ethique.005', 'fr.c1.ethique.006'],
  },
  hebergement: {
    a2: ['fr.a2.hebergement.001', 'fr.a2.hebergement.002', 'fr.a2.hebergement.003', 'fr.a2.hebergement.004', 'fr.a2.hebergement.005', 'fr.a2.hebergement.006'],
  },
  heureEtDate: {
    a1: ['fr.a1.heure-et-date.001', 'fr.a1.heure-et-date.002', 'fr.a1.heure-et-date.003', 'fr.a1.heure-et-date.004', 'fr.a1.heure-et-date.005', 'fr.a1.heure-et-date.006'],
  },
  internet: {
    a2: ['fr.a2.internet.001', 'fr.a2.internet.002', 'fr.a2.internet.003', 'fr.a2.internet.004', 'fr.a2.internet.005', 'fr.a2.internet.006'],
    b1: ['fr.b1.internet.001', 'fr.b1.internet.002', 'fr.b1.internet.003', 'fr.b1.internet.004', 'fr.b1.internet.005', 'fr.b1.internet.006'],
  },
  lesFetes: {
    a2: ['fr.a2.les-fetes.001', 'fr.a2.les-fetes.002', 'fr.a2.les-fetes.003', 'fr.a2.les-fetes.004', 'fr.a2.les-fetes.005', 'fr.a2.les-fetes.006'],
  },
  maison: {
    a2: ['fr.a2.maison.001', 'fr.a2.maison.002', 'fr.a2.maison.003', 'fr.a2.maison.004', 'fr.a2.maison.005', 'fr.a2.maison.006'],
  },
  marche: {
    a1: ['fr.a1.marche.001', 'fr.a1.marche.002', 'fr.a1.marche.003', 'fr.a1.marche.004', 'fr.a1.marche.005', 'fr.a1.marche.006'],
  },
  methodeScientifique: {
    c1: ['fr.c1.methode-scientifique.001', 'fr.c1.methode-scientifique.002', 'fr.c1.methode-scientifique.003', 'fr.c1.methode-scientifique.004', 'fr.c1.methode-scientifique.005', 'fr.c1.methode-scientifique.006'],
    c2: ['fr.c1.methode-scientifique.001', 'fr.c1.methode-scientifique.002', 'fr.c1.methode-scientifique.003', 'fr.c1.methode-scientifique.004', 'fr.c1.methode-scientifique.005', 'fr.c1.methode-scientifique.006'],
  },
  musees: {
    b1: ['fr.b1.musees.001', 'fr.b1.musees.002', 'fr.b1.musees.003', 'fr.b1.musees.004', 'fr.b1.musees.005', 'fr.b1.musees.006'],
  },
  objets: {
    a2: ['fr.a2.objets.001', 'fr.a2.objets.002', 'fr.a2.objets.003', 'fr.a2.objets.004', 'fr.a2.objets.005', 'fr.a2.objets.006'],
  },
  philosophie: {
    c1: ['fr.c1.philosophie.001', 'fr.c1.philosophie.002', 'fr.c1.philosophie.003', 'fr.c1.philosophie.004', 'fr.c1.philosophie.005', 'fr.c1.philosophie.006'],
  },
  presentationPersonnelle: {
    a1: ['fr.a1.presentation-personnelle.001', 'fr.a1.presentation-personnelle.002', 'fr.a1.presentation-personnelle.003', 'fr.a1.presentation-personnelle.004', 'fr.a1.presentation-personnelle.005', 'fr.a1.presentation-personnelle.006'],
  },
  questionsSociales: {
    b1: ['fr.b1.questions-sociales.001', 'fr.b1.questions-sociales.002', 'fr.b1.questions-sociales.003', 'fr.b1.questions-sociales.004', 'fr.b1.questions-sociales.005', 'fr.b1.questions-sociales.006'],
    b2: ['fr.b2.questions-sociales.001', 'fr.b2.questions-sociales.002', 'fr.b2.questions-sociales.003', 'fr.b2.questions-sociales.004', 'fr.b2.questions-sociales.005', 'fr.b2.questions-sociales.006'],
  },
  rechercheEmploi: {
    b1: ['fr.b1.recherche-emploi.001', 'fr.b1.recherche-emploi.004', 'fr.b1.recherche-emploi.006', 'fr.b1.recherche-emploi.007', 'fr.b1.recherche-emploi.009', 'fr.b1.recherche-emploi.010'],
    b2: ['fr.b2.recherche-emploi.001', 'fr.b2.recherche-emploi.009', 'fr.b2.recherche-emploi.011', 'fr.b2.recherche-emploi.018', 'fr.b2.recherche-emploi.019', 'fr.b2.recherche-emploi.027'],
  },
  reseauxSociaux: {
    b2: ['fr.b2.reseaux-sociaux.001', 'fr.b2.reseaux-sociaux.002', 'fr.b2.reseaux-sociaux.003', 'fr.b2.reseaux-sociaux.004', 'fr.b2.reseaux-sociaux.005', 'fr.b2.reseaux-sociaux.006'],
  },
  salutations: {
    a1: ['fr.a1.salutations.001', 'fr.a1.salutations.002', 'fr.a1.salutations.003', 'fr.a1.salutations.004', 'fr.a1.salutations.005', 'fr.a1.salutations.006'],
  },
  soins: {
    b1: ['fr.b1.soins.001', 'fr.b1.soins.002', 'fr.b1.soins.003', 'fr.b1.soins.004', 'fr.b1.soins.005', 'fr.b1.soins.006'],
  },
  sportsEtLoisirs: {
    a2: ['fr.a2.sports-et-loisirs.001', 'fr.a2.sports-et-loisirs.002', 'fr.a2.sports-et-loisirs.003', 'fr.a2.sports-et-loisirs.004', 'fr.a2.sports-et-loisirs.005', 'fr.a2.sports-et-loisirs.006'],
  },
  systemeDeSante: {
    a2: ['fr.a2.systeme-de-sante.001', 'fr.a2.systeme-de-sante.002', 'fr.a2.systeme-de-sante.003', 'fr.a2.systeme-de-sante.004', 'fr.a2.systeme-de-sante.005', 'fr.a2.systeme-de-sante.006'],
    b1: ['fr.b1.systeme-de-sante.001', 'fr.b1.systeme-de-sante.006', 'fr.b1.systeme-de-sante.007', 'fr.b1.systeme-de-sante.009', 'fr.b1.systeme-de-sante.012', 'fr.b1.systeme-de-sante.016'],
  },
  tourisme: {
    b2: ['fr.b2.tourisme.001', 'fr.b2.tourisme.002', 'fr.b2.tourisme.003', 'fr.b2.tourisme.004', 'fr.b2.tourisme.005', 'fr.b2.tourisme.006'],
  },
  transportsQuotidiens: {
    a1: ['fr.a1.transports-quotidiens.001', 'fr.a1.transports-quotidiens.002', 'fr.a1.transports-quotidiens.003', 'fr.a1.transports-quotidiens.004', 'fr.a1.transports-quotidiens.005', 'fr.a1.transports-quotidiens.006'],
  },
  voisinage: {
    a2: ['fr.a2.voisinage.001', 'fr.a2.voisinage.002', 'fr.a2.voisinage.003', 'fr.a2.voisinage.004', 'fr.a2.voisinage.005', 'fr.a2.voisinage.006'],
  },
} as const;

/* The picker reported, and it is not a defect:
 *
 *   2 routing(s) fell back down the ramp
 *     argot-classique: wanted C2, routed C1
 *     methode-scientifique: wanted C2, routed C1
 *
 * There are no published C2 corpus items at all, on any theme. A candidate
 * who misses the last three questions is sent to the hardest material that
 * exists, which is the honest answer and not a satisfying one. blanc-01 does
 * the same on `philosophie`. */
