// The dev build's exam content: TEF Canada Examen 1, before it is published.
//
// ── What changed, and why ───────────────────────────────────────────────────
//
// This file used to hold a hand-written four-épreuve mock with one question per
// section, built in E2 so the runner had something to render before any real
// paper existed. That paper now exists (E7), so the mock is gone and this
// loads the real one instead.
//
// ── Why the real paper is here at all ───────────────────────────────────────
//
// paper.tef_canada.blanc-01.1 lands `in_review`. `content:publish` will not
// carry it and no device can reach it through the normal path, which is Gate H
// working as intended: no human has reviewed a word of it yet. But E7 also has
// to be SAT END TO END ON DEVICE before it can be called done, and a paper
// nobody can open cannot be sat.
//
// So the dev build loads it directly, exactly as it loaded the mock. The JSON
// is a module generated by `pnpm tsx scripts/tef-blanc01/emit-dev-paper.ts` in
// ealch-admin and must never be edited here: the source of truth is
// scripts/tef-blanc01/, where the paper's own test suite can see it.
//
// ── The fence ───────────────────────────────────────────────────────────────
//
// `__DEV__` keeps this out of every release build's CONTENT. It does not keep
// the JSON out of the release BUNDLE — a fenced import still ships its bytes —
// so this is 121 KiB of unreviewed content riding along until E10. That is a
// known cost, recorded in the phase notes, and it ends when the paper is
// published for real.
//
// DELETE THIS FILE AND devExamPaper.ts once E10 publishes blanc-01.
import type { ExamPaper, ExamTask } from './schema';
// Relative AND with the extension, like progress.logic.ts's schema import:
// this is a RUNTIME import, and node --test resolves it as ESM where the
// extension is not optional. The type-only import above is stripped and does
// not need one.
import { DEV_PAPER } from './devExamPaper.ts';

const DATA = DEV_PAPER as unknown as { paper: ExamPaper; tasks: ExamTask[] };

/** The dev build's papers, or nothing outside a dev build. */
export function devExamPapers(isDev: boolean): ExamPaper[] {
  return isDev ? [DATA.paper] : [];
}

/** The dev build's tasks, or nothing outside a dev build. */
export function devExamTasks(isDev: boolean): ExamTask[] {
  return isDev ? DATA.tasks : [];
}
