// The back-compat gate: the corpus we ACTUALLY ship must validate, always.
//
// This test loads the real, committed seed.json — not a fixture, not a trimmed
// copy. That is the entire point. Every other test in schema.test.ts measures the
// validators against content written to satisfy them; this one measures them
// against the content already on people's phones.
//
// It exists because the schema is being extended while the corpus stands still.
// A tightened validator (dropping `c2`, requiring a new field, narrowing an id
// regex) does not fail loudly — it fails at publish, or worse, it silently makes
// the bundled seed unshippable and a fresh offline install renders nothing. This
// test turns that class of mistake into a red light on the commit that causes it,
// which is the only moment it is cheap to fix.
//
// If this test goes red: do not edit the seed to suit the schema. The seed is
// what shipped. Either the schema change is wrong, or it needs a real data
// migration through ealch-admin's publish pipeline first.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { deepStrictEqual, ok } from 'node:assert';
import { test } from 'node:test';
import { formatIssues, validateCorpus } from './schema.ts';

const here = dirname(fileURLToPath(import.meta.url));
const seed = JSON.parse(readFileSync(resolve(here, 'seed.json'), 'utf8')) as unknown;

test('the real, committed seed.json validates against the current schema', () => {
  const issues = validateCorpus(seed);
  deepStrictEqual(
    issues,
    [],
    `The shipped seed.json no longer validates:\n${formatIssues(issues)}\n\n` +
      'A schema change has outpaced the corpus. Do not edit seed.json to fit the schema — ' +
      'it is generated by ealch-admin/scripts/publish-content.ts and mirrors the database.'
  );
});

test('the seed is a real corpus, not an empty one that would validate trivially', () => {
  // Without this, deleting every row from seed.json would make the test above
  // pass, which is the opposite of what it is for.
  const c = seed as { units?: unknown[]; lessons?: unknown[]; items?: unknown[] };
  ok(Array.isArray(c.units) && c.units.length > 0, 'seed has units');
  ok(Array.isArray(c.lessons) && c.lessons.length > 0, 'seed has lessons');
  ok(Array.isArray(c.items) && c.items.length > 0, 'seed has items');
});
