// GENERATED by scripts/_a203_manifest.ts on 2026-08-13. Do not edit by hand.
//
// A recorded read of the 23 rows a2.03 imports rather than authors, out of
// 6 themes, plus 13 read and refused.
//
// THE GENDER CHECK IS THE POINT OF THIS FILE. The brief said every `orange` row
// carries gender and that importing one would move a1.03's printed figures.
// fr.sons.couleurs.009 and fr.sons.couleurs.011 both carry gender NULL, and the
// generator refuses any carried row that does not.
//
// TWO ROWS ARE CARRIED WITHOUT A RESPELLING AND THIS BUILD SUPPLIES ONE FOR EACH.
// fr.a2.description-personnes-objets.003 and .004 are the only published evidence
// of sportif and sportive in 27,600 rows and neither had one.
//
// Regenerate with: pnpm tsx scripts/_a203_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 21 naming forms this lesson displays: the four pattern heads, the -eux
 *  family, the one -if headword the theme holds, and the invariable colours. */
export const IMPORTED_NAMING_ROWS: Item[] = [
  { id: "fr.sons.adjectifs-essentiels.001", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "grand", en: "big, tall", ipa: "/ɡʁɑ̃/", respell: "GRAHⁿ", notes: "Feminine: grande. Opposite: petit. Un grand arbre, une grande maison.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.muettes.047", kind: "word", level: "sons", theme: "muettes", fr: "grande", en: "big, tall (feminine)", ipa: "/ɡʁɑ̃d/", respell: "GRAHⁿD", notes: "The E stays silent. The D wakes up.", tags: ["e-switch","gender-audible","nasal"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.adjectifs-essentiels.037", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "sérieux", en: "serious", ipa: "/seʁjø/", respell: "say-RYUH", notes: "Feminine: sérieuse. Opposite: drôle. Un travail sérieux.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.emotions.001", kind: "word", level: "a1", theme: "emotions", fr: "heureux", en: "happy", ipa: "/ø.ʁø/", respell: "uh-RUH", notes: "Feminine: heureuse.", tags: ["adjective","feeling"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.muettes.053", kind: "word", level: "sons", theme: "muettes", fr: "heureuse", en: "happy (feminine)", ipa: "/œ.ʁøz/", respell: "eu-REUZ", tags: ["e-switch","gender-audible","h-muet"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.adjectifs-essentiels.266", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "joyeux", en: "joyful, cheerful", ipa: "ʒwajø", respell: "zhwah-YUH", notes: "Feminine: joyeuse.", tags: ["personnalité","émotion"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.sons.adjectifs-essentiels.096", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "curieux", en: "curious", ipa: "kyʁjø", respell: "kü-RYUH", notes: "Feminine: curieuse. Un enfant curieux, a curious child. Can also mean odd.", tags: ["adjective","personality"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.234", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "généreux", en: "generous", ipa: "ʒeneʁø", respell: "zhay-nay-RUH", notes: "Feminine: généreuse.", tags: ["personnalité"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.sons.adjectifs-essentiels.052", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "dangereux", en: "dangerous", ipa: "/dɑ̃ʒʁø/", respell: "dahn-zhuh-RUH", notes: "Feminine: dangereuse. Opposite: sûr. Une route dangereuse.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.118", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "nombreux", en: "numerous, many", ipa: "nɔ̃bʁø", respell: "nohn-BRUH", notes: "Feminine: nombreuse. De nombreux amis, many friends.", tags: ["adjective"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.261", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "impulsif", en: "impulsive", ipa: "ɛ̃pylsif", respell: "an-pewl-SEEF", notes: "Feminine: impulsive.", tags: ["personnalité"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.sons.adjectifs-essentiels.256", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "naïf", en: "naive", ipa: "naif", respell: "nah-EEF", notes: "Feminine: naïve.", tags: ["personnalité"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.sons.couleurs.011", kind: "word", level: "sons", theme: "couleurs", fr: "marron", en: "brown", ipa: "/ma.ʁɔ̃/", respell: "mah-ROHⁿ", notes: "Invariable: des chaussures marron. Named after the chestnut. For hair, French uses brun instead.", tags: ["couleurs","adjectif","invariable"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.couleurs.009", kind: "word", level: "sons", theme: "couleurs", fr: "orange", en: "orange", ipa: "/ɔʁɑ̃ʒ/", respell: "oh-RAHⁿZH", notes: "Invariable as a color: des sacs orange, no extra ending. Named after the fruit, une orange.", tags: ["couleurs","adjectif","invariable"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.couleurs.030", kind: "word", level: "sons", theme: "couleurs", fr: "kaki", en: "khaki", ipa: "kaki", respell: "kah-KEE", notes: "Invariable, never adds an ending. Un pantalon kaki, khaki pants.", tags: ["color"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.couleurs.032", kind: "word", level: "sons", theme: "couleurs", fr: "crème", en: "cream", ipa: "kʁɛm", respell: "KREHM", notes: "Invariable as a color. Des rideaux crème, cream curtains.", tags: ["color"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.couleurs.026", kind: "word", level: "sons", theme: "couleurs", fr: "bleu marine", en: "navy blue", ipa: "blø maʁin", respell: "bluh mah-REEN", notes: "Invariable, never adds an ending. Un pull bleu marine, a navy sweater.", tags: ["color"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.couleurs.019", kind: "word", level: "sons", theme: "couleurs", fr: "bleu clair", en: "light blue", ipa: "/blø klɛʁ/", respell: "BLUH KLEHR", notes: "Compound colors never agree: une chemise bleu clair, des chemises bleu clair.", tags: ["couleurs","phrase","nuance"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.couleurs.022", kind: "word", level: "sons", theme: "couleurs", fr: "vert foncé", en: "dark green", ipa: "/vɛʁ fɔ̃.se/", respell: "VEHR fohn-SAY", notes: "Invariable as a compound color: une veste vert foncé.", tags: ["couleurs","phrase","nuance"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.consonnes.127", kind: "word", level: "sons", theme: "consonnes", fr: "vert", en: "green", ipa: "/vɛʁ/", respell: "VEHR", tags: ["final-consonant","silent-final","r"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.muettes.049", kind: "word", level: "sons", theme: "muettes", fr: "verte", en: "green (feminine)", ipa: "/vɛʁt/", respell: "VEHRT", tags: ["e-switch","gender-audible"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
];

/** The 2 published sentences that carry sportif and sportive. Neither had a
 *  respelling and this build supplies both. */
export const IMPORTED_EVIDENCE_ROWS: Item[] = [
  { id: "fr.a2.description-personnes-objets.003", kind: "sentence", level: "a2", theme: "description-personnes-objets", fr: "Les jumeaux sont sportifs.", en: "The twin boys are athletic.", ipa: "le ʒy.mo sɔ̃ spɔʁ.tif", notes: "“sportif” takes a simple s in the masculine plural, “sportifs”.", tags: ["accord-nombre"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.description-personnes-objets.004", kind: "sentence", level: "a2", theme: "description-personnes-objets", fr: "Les jumelles sont sportives.", en: "The twin girls are athletic.", ipa: "le ʒy.mɛl sɔ̃ spɔʁ.tiv", notes: "“sportif” changes f to v before adding the feminine e, giving “sportive”.", tags: ["accord-genre"], drills: ["dictation"], audioRef: null, version: 1 },
];

/** The 13 rows read and refused. READ ONLY: never carried, never released,
 *  never in itemIds, and named on no screen. */
export const READ_ONLY_ROWS: Item[] = [
  { id: "fr.a1.description-personnes-objets.001", kind: "sentence", level: "a1", theme: "description-personnes-objets", fr: "Il est grand.", en: "He is tall.", ipa: "il ɛ ɡʁɑ̃", notes: "The final “d” in “grand” stays silent when nothing follows it.", tags: ["silent-letter"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.description-personnes-objets.076", kind: "sentence", level: "a1", theme: "description-personnes-objets", fr: "Il est grand.", en: "He is tall.", tags: [], drills: ["sentence"], audioRef: null, version: 1 },
  { id: "fr.a1.description-personnes-objets.003", kind: "sentence", level: "a1", theme: "description-personnes-objets", fr: "Ils sont grands.", en: "They (m.) are tall.", ipa: "il sɔ̃ ɡʁɑ̃", notes: "The plural “grands” still sounds like singular “grand”, the s stays silent.", tags: ["accord-nombre"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.metiers.273", kind: "sentence", level: "a1", theme: "metiers", fr: "Elle est grande.", en: "She is tall.", ipa: "/ɛ lɛ ɡʁɑ̃d/", respell: "el eh GRAHⁿD", notes: "Here the agreement IS audible: the e wakes the d. Compare fatiguée, where it stays silent.", tags: ["etre","description","adjective","agreement","nasal"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.268", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "Il est heureux avec elle.", en: "He is happy with her.", notes: "{\"tiles\":[{\"w\":\"Il est heureux\",\"t\":\"he is happy\"},{\"w\":\"avec elle.\",\"t\":\"with her\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.271", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "Elles sont heureuses de leur voyage.", en: "They are happy about their trip.", notes: "{\"tiles\":[{\"w\":\"Elles sont heureuses\",\"t\":\"they are happy\"},{\"w\":\"de leur voyage.\",\"t\":\"about their trip\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.couleurs.269", kind: "sentence", level: "a1", theme: "couleurs", fr: "Mes sacs sont marron.", en: "My bags are brown.", ipa: "/me sak sɔ̃ ma.ʁɔ̃/", notes: "No s either. Writing marrons here would be the one error a French reader always notices.", tags: ["couleurs","accord","accord-nombre"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.couleurs.013", kind: "word", level: "sons", theme: "couleurs", fr: "turquoise", en: "turquoise", ipa: "/tyʁ.kwaz/", respell: "tür-KWAHZ", notes: "Invariable: des robes turquoise. Say 'tur-kwahz' with the tight French u.", tags: ["couleurs","adjectif","invariable"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.094", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "courageux", en: "brave", ipa: "kuʁaʒø", respell: "koo-rah-ZHUH", notes: "Feminine: courageuse. Un pompier courageux, a brave firefighter.", tags: ["adjective","personality"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.muettes.027", kind: "word", level: "sons", theme: "muettes", fr: "actif", en: "active", ipa: "/ak.tif/", respell: "ak-TEEF", tags: ["careful","careful-f"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.adjectifs-essentiels.314", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "bel", en: "beautiful (before a vowel)", ipa: "/bɛl/", respell: "BEL", notes: "Beau becomes bel in front of a word starting with a vowel sound: un bel homme, un bel arbre. It sounds exactly like the feminine belle and it is used with the un kind of thing.", tags: ["adjective","elision"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.315", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "vieil", en: "old (before a vowel)", ipa: "/vjɛj/", respell: "VYEY", notes: "Vieux becomes vieil in front of a word starting with a vowel sound: un vieil ami, un vieil immeuble. It sounds exactly like the feminine vieille and it is used with the un kind of thing.", tags: ["adjective","elision"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.312", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "vieille", en: "old (feminine)", ipa: "/vjɛj/", respell: "VYEY", notes: "The feminine of vieux, and it is a different word rather than an added ending: vieille, never vieuxe. Ma grand-mère est vieille. Before a vowel the masculine is vieil.", tags: ["adjective","accord-genre"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** naming form -> id, in learner order. The only place this pairing is written. */
export const NAMING_ROW_IDS: [string, string][] = [
  ["grand", "fr.sons.adjectifs-essentiels.001"],
  ["grande", "fr.sons.muettes.047"],
  ["sérieux", "fr.sons.adjectifs-essentiels.037"],
  ["heureux", "fr.a1.emotions.001"],
  ["heureuse", "fr.sons.muettes.053"],
  ["joyeux", "fr.sons.adjectifs-essentiels.266"],
  ["curieux", "fr.sons.adjectifs-essentiels.096"],
  ["généreux", "fr.sons.adjectifs-essentiels.234"],
  ["dangereux", "fr.sons.adjectifs-essentiels.052"],
  ["nombreux", "fr.sons.adjectifs-essentiels.118"],
  ["impulsif", "fr.sons.adjectifs-essentiels.261"],
  ["naïf", "fr.sons.adjectifs-essentiels.256"],
  ["marron", "fr.sons.couleurs.011"],
  ["orange", "fr.sons.couleurs.009"],
  ["kaki", "fr.sons.couleurs.030"],
  ["crème", "fr.sons.couleurs.032"],
  ["bleu marine", "fr.sons.couleurs.026"],
  ["bleu clair", "fr.sons.couleurs.019"],
  ["vert foncé", "fr.sons.couleurs.022"],
  ["vert", "fr.sons.consonnes.127"],
  ["verte", "fr.sons.muettes.049"],
];

/** evidence sentence -> id. */
export const EVIDENCE_ROW_IDS: [string, string][] = [
  ["Les jumeaux sont sportifs.", "fr.a2.description-personnes-objets.003"],
  ["Les jumelles sont sportives.", "fr.a2.description-personnes-objets.004"],
];

/** And the refused pairing, kept apart so nothing can iterate both by accident. */
export const READ_ONLY_ROW_IDS: [string, string][] = [
  ["Il est grand.", "fr.a1.description-personnes-objets.001"],
  ["Il est grand.", "fr.a1.description-personnes-objets.076"],
  ["Ils sont grands.", "fr.a1.description-personnes-objets.003"],
  ["Elle est grande.", "fr.a1.metiers.273"],
  ["Il est heureux avec elle.", "fr.a1.adjectifs-essentiels.268"],
  ["Elles sont heureuses de leur voyage.", "fr.a1.adjectifs-essentiels.271"],
  ["Mes sacs sont marron.", "fr.a1.couleurs.269"],
  ["turquoise", "fr.sons.couleurs.013"],
  ["courageux", "fr.sons.adjectifs-essentiels.094"],
  ["actif", "fr.sons.muettes.027"],
  ["bel", "fr.sons.adjectifs-essentiels.314"],
  ["vieil", "fr.sons.adjectifs-essentiels.315"],
  ["vieille", "fr.sons.adjectifs-essentiels.312"],
];

/** Every id this lesson may put in `itemIds`. The refused rows are deliberately
 *  absent and the batch asserts that absence. */
export const IMPORTABLE_IDS: string[] = [
  "fr.sons.adjectifs-essentiels.001",
  "fr.sons.muettes.047",
  "fr.sons.adjectifs-essentiels.037",
  "fr.a1.emotions.001",
  "fr.sons.muettes.053",
  "fr.sons.adjectifs-essentiels.266",
  "fr.sons.adjectifs-essentiels.096",
  "fr.sons.adjectifs-essentiels.234",
  "fr.sons.adjectifs-essentiels.052",
  "fr.sons.adjectifs-essentiels.118",
  "fr.sons.adjectifs-essentiels.261",
  "fr.sons.adjectifs-essentiels.256",
  "fr.sons.couleurs.011",
  "fr.sons.couleurs.009",
  "fr.sons.couleurs.030",
  "fr.sons.couleurs.032",
  "fr.sons.couleurs.026",
  "fr.sons.couleurs.019",
  "fr.sons.couleurs.022",
  "fr.sons.consonnes.127",
  "fr.sons.muettes.049",
  "fr.a2.description-personnes-objets.003",
  "fr.a2.description-personnes-objets.004",
];

/** Every id the merge writes into the seed. Identical to IMPORTABLE_IDS here:
 *  unlike a2.15, this build repairs nothing it does not also display. */
export const CARRIED_IDS: string[] = [
  "fr.sons.adjectifs-essentiels.001",
  "fr.sons.muettes.047",
  "fr.sons.adjectifs-essentiels.037",
  "fr.a1.emotions.001",
  "fr.sons.muettes.053",
  "fr.sons.adjectifs-essentiels.266",
  "fr.sons.adjectifs-essentiels.096",
  "fr.sons.adjectifs-essentiels.234",
  "fr.sons.adjectifs-essentiels.052",
  "fr.sons.adjectifs-essentiels.118",
  "fr.sons.adjectifs-essentiels.261",
  "fr.sons.adjectifs-essentiels.256",
  "fr.sons.couleurs.011",
  "fr.sons.couleurs.009",
  "fr.sons.couleurs.030",
  "fr.sons.couleurs.032",
  "fr.sons.couleurs.026",
  "fr.sons.couleurs.019",
  "fr.sons.couleurs.022",
  "fr.sons.consonnes.127",
  "fr.sons.muettes.049",
  "fr.a2.description-personnes-objets.003",
  "fr.a2.description-personnes-objets.004",
];

/** The themes the imported rows came out of. */
export const SOURCE_THEMES: string[] = ["adjectifs-essentiels","consonnes","couleurs","description-personnes-objets","emotions","muettes"];

/** The family sizes in the home theme, re-measured on the day this manifest was
 *  generated, excluding this build's own rows. Corpus header item 8: the -eux
 *  family is large and the -if family is one row wide, and the lesson's shape
 *  follows that rather than pretending they are equal. */
export const FAMILY_MEASURED = { eux: 25, if: 1, date: "2026-08-13" };
