// GENERATED by scripts/_a217_manifest.ts on 2026-08-14. Do not edit by hand.
//
// A recorded read of the 28 rows a2.17 imports rather than authors, out of
// 5 themes, plus 12 read and refused.
//
// NOT ONE OF THE TWENTY-TWO ADVERBS IS AUTHORED. `adverbes-essentiels` holds 325
// published rows and every adverb this lesson teaches is in it. What is authored
// is the other half of the derivation: four ADJECTIVES that do not exist at any
// status in any theme, two of which are the middle step of the chain.
//
// AND FOR `sérieux` ALL THREE CELLS OF THE CHAIN ARE SOMEBODY ELSE'S DATA, in
// two themes by different authors, with a2.03's own `sérieuse` in the middle.
//
// Regenerate with: pnpm tsx scripts/_a217_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 20 headwords that already exist. `lente` and `douce` are deliberately
 *  absent: they are the two middle steps the corpus does not hold, and the
 *  corpus file authors them. */
export const IMPORTED_NAMING_ROWS: Item[] = [
  { id: "fr.sons.adjectifs-essentiels.021", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "lent", en: "slow", ipa: "/lɑ̃/", respell: "LAHN", notes: "Feminine: lente. Opposite: rapide. Un bus lent.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adverbes-essentiels.001", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "lentement", en: "slowly", ipa: "lɑ̃t.mɑ̃", respell: "lahnt-MAHN", notes: "lent + -ment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.033", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "doux", en: "soft, gentle", ipa: "/du/", respell: "DOO", notes: "Feminine: douce. Opposite: dur. Une couverture douce.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adverbes-essentiels.003", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "doucement", en: "gently, softly", ipa: "dus.mɑ̃", respell: "doos-MAHN", notes: "doux, douce + -ment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.037", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "sérieux", en: "serious", ipa: "/seʁjø/", respell: "say-RYUH", notes: "Feminine: sérieuse. Opposite: drôle. Un travail sérieux.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.adjectifs-essentiels.019", kind: "word", level: "a2", theme: "adjectifs-essentiels", fr: "sérieuse", en: "serious (feminine)", ipa: "/se.ʁjøz/", respell: "say-RYUHZ", notes: "The x has become se. Say it and you will hear the buzz on the end.", tags: ["adjectifs-essentiels","accord"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.adverbes-essentiels.021", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "sérieusement", en: "seriously", ipa: "se.ʁjøz.mɑ̃", respell: "say-ryuhz-MAHN", notes: "sérieux, sérieuse + -ment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.020", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "rapide", en: "fast, quick", ipa: "/ʁapid/", respell: "rah-PEED", notes: "Same form for both genders. Opposite: lent. Un train rapide.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adverbes-essentiels.002", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "rapidement", en: "quickly", ipa: "ʁa.pid.mɑ̃", respell: "ra-peed-MAHN", notes: "rapide + -ment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.018", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "facile", en: "easy", ipa: "/fasil/", respell: "fah-SEEL", notes: "Same form for both genders. Opposite: difficile. C'est facile!", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adverbes-essentiels.004", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "facilement", en: "easily", ipa: "fa.sil.mɑ̃", respell: "fa-seel-MAHN", notes: "facile + -ment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.mots-essentiels.045", kind: "word", level: "sons", theme: "mots-essentiels", fr: "bien", en: "well, good", ipa: "/bjɛ̃/", respell: "BYAN", notes: "Nasal ending, like 'byan'. Ça va bien: it is going well.", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.mots-essentiels.046", kind: "word", level: "sons", theme: "mots-essentiels", fr: "mal", en: "badly", ipa: "/mal/", respell: "MAL", notes: "Sounds like 'mal'. Opposite of bien. Pas mal: not bad.", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.mots-essentiels.064", kind: "word", level: "sons", theme: "mots-essentiels", fr: "vite", en: "fast, quickly", ipa: "/vit/", respell: "VEET", notes: "Sounds like 'veet'. Vite, vite!: quick, quick!", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.003", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "bon", en: "good", ipa: "/bɔ̃/", respell: "BOHⁿ", notes: "Feminine: bonne. Opposite: mauvais. Un bon film, une bonne idée.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.004", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "mauvais", en: "bad", ipa: "/mɔvɛ/", respell: "moh-VEH", notes: "Feminine: mauvaise. Opposite: bon. Un mauvais jour.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.mots-essentiels.056", kind: "word", level: "sons", theme: "mots-essentiels", fr: "souvent", en: "often", ipa: "/suvɑ̃/", respell: "soo-VAHN", notes: "Silent t, like 'soo-vahn'.", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.mots-essentiels.054", kind: "word", level: "sons", theme: "mots-essentiels", fr: "toujours", en: "always", ipa: "/tuʒuʁ/", respell: "too-ZHOOR", notes: "Silent final s, like 'too-zhoor'. Can also mean 'still' in context.", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adverbes-essentiels.018", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "évidemment", en: "obviously", ipa: "e.vi.da.mɑ̃", respell: "ay-vee-da-MAHN", notes: "évident; -emment is pronounced like -amment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adverbes-essentiels.045", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "constamment", en: "constantly", ipa: "kɔ̃s.ta.mɑ̃", respell: "kohns-ta-MAHN", notes: "constant + -amment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The 8 published sentences. Two are a2.03's own rows and six put an adverb
 *  after a conjugated verb, every one of them already respelled the house way. */
export const IMPORTED_EVIDENCE_ROWS: Item[] = [
  { id: "fr.a2.adjectifs-essentiels.005", kind: "sentence", level: "a2", theme: "adjectifs-essentiels", fr: "Il est sérieux.", en: "He is serious.", ipa: "/il ɛ se.ʁjø/", respell: "eel eh say-RYUH", notes: "Ends in x. Remember that, because it decides two of the next three.", tags: ["accord","accord-eux"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.adjectifs-essentiels.006", kind: "sentence", level: "a2", theme: "adjectifs-essentiels", fr: "Elle est sérieuse.", en: "She is serious.", ipa: "/ɛl ɛ se.ʁjøz/", respell: "el eh say-RYUHZ", notes: "The x becomes se, and the ending gains a buzz you can hear across a room.", tags: ["accord","accord-eux","accord-genre"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.nasales.001", kind: "sentence", level: "sons", theme: "nasales", fr: "Maman chante souvent.", en: "Mom often sings.", ipa: "ma.mɑ̃ ʃɑ̃t su.vɑ̃", respell: "ma-MAHⁿ SHAHⁿT soo-VAHⁿ", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.a2.verbes.477", kind: "sentence", level: "a2", theme: "verbes", fr: "Il court vite.", en: "He runs fast.", ipa: "/il kuʁ vit/", respell: "eel koor VEET", notes: "courir ends in -rir and takes no -iss-. guérir ends in -rir and takes one.", tags: ["ir-verb","courir","singular"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.189", kind: "sentence", level: "a2", theme: "verbes", fr: "Il réussit toujours.", en: "He always succeeds.", ipa: "/il ʁe.y.si tu.ʒuʁ/", respell: "eel ray-ü-see too-ZHOOR", tags: ["ir-verb","pair","singular"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.nasales.014", kind: "sentence", level: "sons", theme: "nasales", fr: "Le vent souffle doucement.", en: "The wind blows gently.", ipa: "lə vɑ̃ sufl dus.mɑ̃", respell: "LUH VAHⁿ SOOFL doos-MAHⁿ", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.nasales.078", kind: "sentence", level: "sons", theme: "nasales", fr: "Son nom sonne bien.", en: "His name sounds nice.", ipa: "sɔ̃ nɔ̃ sɔn bjɛ̃", respell: "SOHⁿ NOHⁿ SON BYEHⁿ", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.nasales.013", kind: "sentence", level: "sons", theme: "nasales", fr: "L'enfant mange trop lentement.", en: "The child eats too slowly.", ipa: "lɑ̃.fɑ̃ mɑ̃ʒ tʁo lɑ̃t.mɑ̃", respell: "lahⁿ-FAHⁿ MAHⁿZH TROH lahⁿt-MAHⁿ", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
];

/** The 12 rows read and refused. READ ONLY: never carried, never released,
 *  never in itemIds, and named on no screen. */
export const READ_ONLY_ROWS: Item[] = [
  { id: "fr.sons.voyelles.174", kind: "word", level: "sons", theme: "voyelles", fr: "le mieux", en: "the best (thing)", ipa: "mjø", respell: "myuh", gender: "m", example: {"en":"She does her best every day.","fr":"Elle fait de son mieux chaque jour."}, tags: ["voyelle-eu-ferme"], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.a1.adverbes-essentiels.055", kind: "sentence", level: "a1", theme: "adverbes-essentiels", fr: "Franchement, ce film m'a beaucoup déçu.", en: "Frankly, this film disappointed me a lot.", ipa: "fʁɑ̃ʃ.mɑ̃ sə film ma bo.ku de.sy", tags: ["grammaire"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.rythme.180", kind: "sentence", level: "sons", theme: "rythme", fr: "Elle chante, très bien.", en: "She sings, very well.", ipa: "ɛl ʃɑ̃t | tʁɛ bjɛ̃", respell: "[ehl SHAHⁿT | treh BYAⁿ]", tags: ["syll-4","short","falling","grouped","tappable","minimal-pair","pair-180"], drills: ["sentence","review","dictation","voiceflash"], audioRef: null, version: 6 },
  { id: "fr.sons.rythme.181", kind: "sentence", level: "sons", theme: "rythme", fr: "Elle chante très bien.", en: "She sings very well.", ipa: "ɛl ʃɑ̃t tʁɛ bjɛ̃", respell: "[ehl shahⁿt treh BYAⁿ]", tags: ["syll-4","short","falling","tappable","minimal-pair","pair-180"], drills: ["sentence","review","dictation","voiceflash"], audioRef: null, version: 6 },
  { id: "fr.sons.alphabet.385", kind: "sentence", level: "sons", theme: "alphabet", fr: "Notez bien chaque lettre.", en: "Write down each letter carefully.", ipa: "nɔ.te bjɛ̃ ʃak lɛtʁ", respell: "no-TAY BYEHⁿ SHAK LEHTR", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.adverbes-essentiels.014", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "parfaitement", en: "perfectly", ipa: "paʁ.fɛt.mɑ̃", respell: "par-feht-MAHN", notes: "parfait + -ment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adverbes-essentiels.015", kind: "word", level: "sons", theme: "adverbes-essentiels", fr: "certainement", en: "certainly", ipa: "sɛʁ.tɛn.mɑ̃", respell: "sehr-tehn-MAHN", notes: "certain, certaine + -ment", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.047", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "parfait", en: "perfect", ipa: "/paʁfɛ/", respell: "par-FEH", notes: "Feminine: parfaite. C'est parfait! (That's perfect!)", tags: ["adjective"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.dictee.166", kind: "word", level: "a1", theme: "dictee", fr: "lentement", en: "slowly", ipa: "lɑ̃t.mɑ̃", respell: "lahnt-MAHN", example: {"en":"The teacher speaks slowly for the dictation.","fr":"La maîtresse parle lentement pour la dictée."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.a1.dictee.167", kind: "word", level: "a1", theme: "dictee", fr: "rapidement", en: "quickly", ipa: "ʁa.pid.mɑ̃", example: {"en":"He writes too quickly.","fr":"Il écrit trop rapidement."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.a1.temps-et-frequence.120", kind: "word", level: "a1", theme: "temps-et-frequence", fr: "souvent", en: "often", tags: [], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.sons.voyelles.761", kind: "word", level: "sons", theme: "voyelles", fr: "bien", en: "the nasal glide [jɛ̃] : the next lesson", tags: ["deck","dk6-458"], drills: ["flashcard","review"], audioRef: null, version: 1, cardType: "grammar", prompt: "« ien » : which sound?" },
];

/** word -> id, in learner order. The only place this pairing is written. */
export const NAMING_ROW_IDS: [string, string][] = [
  ["lent", "fr.sons.adjectifs-essentiels.021"],
  ["lentement", "fr.sons.adverbes-essentiels.001"],
  ["doux", "fr.sons.adjectifs-essentiels.033"],
  ["doucement", "fr.sons.adverbes-essentiels.003"],
  ["sérieux", "fr.sons.adjectifs-essentiels.037"],
  ["sérieuse", "fr.a2.adjectifs-essentiels.019"],
  ["sérieusement", "fr.sons.adverbes-essentiels.021"],
  ["rapide", "fr.sons.adjectifs-essentiels.020"],
  ["rapidement", "fr.sons.adverbes-essentiels.002"],
  ["facile", "fr.sons.adjectifs-essentiels.018"],
  ["facilement", "fr.sons.adverbes-essentiels.004"],
  ["bien", "fr.sons.mots-essentiels.045"],
  ["mal", "fr.sons.mots-essentiels.046"],
  ["vite", "fr.sons.mots-essentiels.064"],
  ["bon", "fr.sons.adjectifs-essentiels.003"],
  ["mauvais", "fr.sons.adjectifs-essentiels.004"],
  ["souvent", "fr.sons.mots-essentiels.056"],
  ["toujours", "fr.sons.mots-essentiels.054"],
  ["évidemment", "fr.sons.adverbes-essentiels.018"],
  ["constamment", "fr.sons.adverbes-essentiels.045"],
];

/** evidence sentence -> id. */
export const EVIDENCE_ROW_IDS: [string, string][] = [
  ["Il est sérieux.", "fr.a2.adjectifs-essentiels.005"],
  ["Elle est sérieuse.", "fr.a2.adjectifs-essentiels.006"],
  ["Maman chante souvent.", "fr.sons.nasales.001"],
  ["Il court vite.", "fr.a2.verbes.477"],
  ["Il réussit toujours.", "fr.a2.verbes.189"],
  ["Le vent souffle doucement.", "fr.sons.nasales.014"],
  ["Son nom sonne bien.", "fr.sons.nasales.078"],
  ["L'enfant mange trop lentement.", "fr.sons.nasales.013"],
];

/** And the refused pairing, kept apart so nothing can iterate both by accident. */
export const READ_ONLY_ROW_IDS: [string, string][] = [
  ["le mieux", "fr.sons.voyelles.174"],
  ["Franchement, ce film m'a beaucoup déçu.", "fr.a1.adverbes-essentiels.055"],
  ["Elle chante, très bien.", "fr.sons.rythme.180"],
  ["Elle chante très bien.", "fr.sons.rythme.181"],
  ["Notez bien chaque lettre.", "fr.sons.alphabet.385"],
  ["parfaitement", "fr.sons.adverbes-essentiels.014"],
  ["certainement", "fr.sons.adverbes-essentiels.015"],
  ["parfait", "fr.sons.adjectifs-essentiels.047"],
  ["lentement", "fr.a1.dictee.166"],
  ["rapidement", "fr.a1.dictee.167"],
  ["souvent", "fr.a1.temps-et-frequence.120"],
  ["bien", "fr.sons.voyelles.761"],
];

/** Every id this lesson may put in `itemIds`. */
export const IMPORTABLE_IDS: string[] = [
  "fr.sons.adjectifs-essentiels.021",
  "fr.sons.adverbes-essentiels.001",
  "fr.sons.adjectifs-essentiels.033",
  "fr.sons.adverbes-essentiels.003",
  "fr.sons.adjectifs-essentiels.037",
  "fr.a2.adjectifs-essentiels.019",
  "fr.sons.adverbes-essentiels.021",
  "fr.sons.adjectifs-essentiels.020",
  "fr.sons.adverbes-essentiels.002",
  "fr.sons.adjectifs-essentiels.018",
  "fr.sons.adverbes-essentiels.004",
  "fr.sons.mots-essentiels.045",
  "fr.sons.mots-essentiels.046",
  "fr.sons.mots-essentiels.064",
  "fr.sons.adjectifs-essentiels.003",
  "fr.sons.adjectifs-essentiels.004",
  "fr.sons.mots-essentiels.056",
  "fr.sons.mots-essentiels.054",
  "fr.sons.adverbes-essentiels.018",
  "fr.sons.adverbes-essentiels.045",
  "fr.a2.adjectifs-essentiels.005",
  "fr.a2.adjectifs-essentiels.006",
  "fr.sons.nasales.001",
  "fr.a2.verbes.477",
  "fr.a2.verbes.189",
  "fr.sons.nasales.014",
  "fr.sons.nasales.078",
  "fr.sons.nasales.013",
];

/** Every id the merge writes into the seed. Identical to IMPORTABLE_IDS: this
 *  build repairs nothing it does not also display. The seed is a CUT and
 *  `adverbes-essentiels` is outside SEED_CUT.themes, so most of these are not
 *  in it today and a merge that did not carry them would render blank cards. */
export const CARRIED_IDS: string[] = [
  "fr.sons.adjectifs-essentiels.021",
  "fr.sons.adverbes-essentiels.001",
  "fr.sons.adjectifs-essentiels.033",
  "fr.sons.adverbes-essentiels.003",
  "fr.sons.adjectifs-essentiels.037",
  "fr.a2.adjectifs-essentiels.019",
  "fr.sons.adverbes-essentiels.021",
  "fr.sons.adjectifs-essentiels.020",
  "fr.sons.adverbes-essentiels.002",
  "fr.sons.adjectifs-essentiels.018",
  "fr.sons.adverbes-essentiels.004",
  "fr.sons.mots-essentiels.045",
  "fr.sons.mots-essentiels.046",
  "fr.sons.mots-essentiels.064",
  "fr.sons.adjectifs-essentiels.003",
  "fr.sons.adjectifs-essentiels.004",
  "fr.sons.mots-essentiels.056",
  "fr.sons.mots-essentiels.054",
  "fr.sons.adverbes-essentiels.018",
  "fr.sons.adverbes-essentiels.045",
  "fr.a2.adjectifs-essentiels.005",
  "fr.a2.adjectifs-essentiels.006",
  "fr.sons.nasales.001",
  "fr.a2.verbes.477",
  "fr.a2.verbes.189",
  "fr.sons.nasales.014",
  "fr.sons.nasales.078",
  "fr.sons.nasales.013",
];

/** The themes the imported rows came out of. */
export const SOURCE_THEMES: string[] = ["adjectifs-essentiels","adverbes-essentiels","mots-essentiels","nasales","verbes"];

/** The block, and the row count in it on the day this manifest was generated.
 *  A NEW namespace, so the count is 0 and anything at all inside it is somebody
 *  else's. Ledger §10: the maximum is useless and the COUNT is the only signal. */
export const BLOCK_MEASURED = { rows: 0, insideBlock: 0, themeRows: 325, date: "2026-08-14" };

/** The measurement the lesson rests on, re-taken here so it cannot go stale in a
 *  comment: the same word respelled two ways in one database, with the SENTENCE
 *  half right and the HEADWORD half wrong. */
export const TWO_WAYS_EVIDENCE: { word: string; headword: string; stored: string; sentence: string; published: string }[] = [
  { word: "lentement", headword: "fr.sons.adverbes-essentiels.001", stored: "lahnt-MAHN", sentence: "fr.sons.nasales.013", published: "lahⁿ-FAHⁿ MAHⁿZH TROH lahⁿt-MAHⁿ" },
  { word: "doucement", headword: "fr.sons.adverbes-essentiels.003", stored: "doos-MAHN", sentence: "fr.sons.nasales.014", published: "LUH VAHⁿ SOOFL doos-MAHⁿ" },
  { word: "bien", headword: "fr.sons.mots-essentiels.045", stored: "BYAN", sentence: "fr.sons.nasales.078", published: "SOHⁿ NOHⁿ SON BYEHⁿ" },
];
