// GENERATED by scripts/_a202_manifest.ts on 2026-08-12. Do not edit by hand.
//
// A recorded read of the 6 verb rows a2.02 imports rather than authors, the
// 1 it reads and does not import, and the 4 published sentences it teaches
// FROM. Two consumers need the whole row and not just the id:
//
//   author-aller-venir-batch.ts verifies every field against Postgres before it
//   opens a transaction, so a stale manifest cannot put the lesson ahead of rows
//   nobody has looked at.
//
//   merge-aller-venir-into-seed.ts CARRIES them into seed.json. The seed is a
//   CUT, so without the carry the verb cards and the cross-lesson screen would
//   draw empty.
//
// THE READ-ONLY ROW IS NOT CARRIED AND NOT RELEASED. a2.10 settled the rule: a
// verb a lesson does not teach is a display string, not a row in the hub.
//
// THE FOUR SENTENCES ARE a2.10.l1's AND a2.10.l2's, ON THIS LESSON'S FRAME WORD.
// Both of those builds chose `tôt` deliberately so a later lesson could hold
// their pairs beside its own. This is that lesson.
//
// Regenerate with: pnpm tsx scripts/_a202_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 6 infinitives this lesson teaches, in learner order. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.003", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "aller", en: "to go", ipa: "/ale/", respell: "ah-LAY", notes: "irregular · je vais, tu vas, il va, nous allons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.010", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "venir", en: "to come", ipa: "/vəniʁ/", respell: "vuh-NEER", notes: "irregular · je viens, nous venons, ils viennent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.052", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "tenir", en: "to hold", ipa: "/təniʁ/", respell: "tuh-NEER", notes: "irregular · je tiens, conjugates like venir", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.084", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "revenir", en: "to come back", ipa: "/ʁəvəniʁ/", respell: "ruh-vuh-NEER", notes: "irregular · je reviens, like venir", tags: ["irregular","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.083", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "devenir", en: "to become", ipa: "/dəvəniʁ/", respell: "duh-vuh-NEER", notes: "irregular · je deviens, tu deviens, like venir", tags: ["irregular","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.examens-et-diplomes.038", kind: "word", level: "a2", theme: "examens-et-diplomes", fr: "obtenir", en: "to obtain", ipa: "ɔb.tə.niʁ", respell: "ohb-tuh-NEER", example: {"en":"He wants to obtain his diploma this year.","fr":"Il veut obtenir son diplôme cette année."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
];

/** The 1 it reads and does not import. READ ONLY: never carried, never
 *  released, never in itemIds, and named on no screen. */
export const READ_ONLY_VERB_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.218", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "appartenir", en: "to belong", ipa: "/apaʁtəniʁ/", respell: "ah-par-tuh-NEER", notes: "Irregular; like tenir, used with à.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The published sentences this lesson teaches from rather than teaching. */
export const IMPORTED_SENTENCE_ROWS: Item[] = [
  { id: "fr.a2.verbes.183", kind: "sentence", level: "a2", theme: "verbes", fr: "Il finit tôt.", en: "He finishes early.", ipa: "/il fi.ni to/", respell: "eel fee-nee TOH", notes: "The -t is silent. This is the half of the pair the ear can settle against the plural.", tags: ["ir-verb","paradigm","singular"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.186", kind: "sentence", level: "a2", theme: "verbes", fr: "Ils finissent tôt.", en: "They finish early.", ipa: "/il fi.nis to/", respell: "eel fee-nees TOH", notes: "One sound more than Il finit tôt, at the very end of the verb, and nothing else.", tags: ["ir-verb","paradigm","plural"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.463", kind: "sentence", level: "a2", theme: "verbes", fr: "Il part tôt.", en: "He leaves early.", ipa: "/il paʁ to/", respell: "eel par TOH", notes: "Put this beside Il finit tôt from the last lesson. Both stop dead.", tags: ["ir-verb","shed","singular"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.464", kind: "sentence", level: "a2", theme: "verbes", fr: "Ils partent tôt.", en: "They leave early.", ipa: "/il paʁt to/", respell: "eel part TOH", notes: "One consonant more than Il part tôt, at the very end. That T is the whole difference.", tags: ["ir-verb","shed","plural"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["aller", "fr.sons.verbes-essentiels.003"],
  ["venir", "fr.sons.verbes-essentiels.010"],
  ["tenir", "fr.sons.verbes-essentiels.052"],
  ["revenir", "fr.sons.verbes-essentiels.084"],
  ["devenir", "fr.sons.verbes-essentiels.083"],
  ["obtenir", "fr.a2.examens-et-diplomes.038"],
];

/** And the read-only pairing, kept apart so nothing can iterate both by accident. */
export const READ_ONLY_ROW_IDS: [string, string][] = [
  ["appartenir", "fr.sons.verbes-essentiels.218"],
];
