// GENERATED by scripts/_a216_manifest.ts on 2026-08-13. Do not edit by hand.
//
// A recorded read of the 12 rows a2.16 imports rather than authors, out of
// 3 themes, plus 12 read and refused.
//
// THE POINT OF THIS FILE IS THAT EIGHT OF THE NINE FORMS ALREADY EXISTED. The
// brief said `bel`, `nouvel` and `vieil` were all likely absent and that this
// lesson would author its three headline forms. `bel` is
// fr.sons.adjectifs-essentiels.314 and `vieil` is .315, both published, both
// respelled, both in the home theme. Only `nouvel` is absent.
//
// FOUR ROWS ARE CARRIED WITHOUT A RESPELLING AND THIS BUILD SUPPLIES ONE FOR
// EACH. They are the only published rows in the corpus holding a third form in
// a frame short enough to teach with, and none of them could be said aloud.
//
// Regenerate with: pnpm tsx scripts/_a216_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 8 forms that already exist as headwords. `nouvel` is deliberately
 *  absent: it is the one form the corpus does not hold and the corpus file
 *  authors it. */
export const IMPORTED_NAMING_ROWS: Item[] = [
  { id: "fr.sons.adjectifs-essentiels.005", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "beau", en: "beautiful, handsome", ipa: "/bo/", respell: "BOH", notes: "Feminine: belle. Becomes bel before a vowel: un bel homme.", tags: ["adjective"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.007", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "nouveau", en: "new", ipa: "/nuvo/", respell: "noo-VOH", notes: "Feminine: nouvelle. Becomes nouvel before a vowel: un nouvel ami. Opposite: vieux.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.008", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "vieux", en: "old", ipa: "/vjø/", respell: "VYUH", notes: "Feminine: vieille. Becomes vieil before a vowel: un vieil homme. Opposites: nouveau, jeune.", tags: ["adjective","opposites"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.314", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "bel", en: "beautiful (before a vowel)", ipa: "/bɛl/", respell: "BEL", notes: "Beau becomes bel in front of a word starting with a vowel sound: un bel homme, un bel arbre. It sounds exactly like the feminine belle and it is used with the un kind of thing.", tags: ["adjective","elision"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.adjectifs-essentiels.315", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "vieil", en: "old (before a vowel)", ipa: "/vjɛj/", respell: "VYEY", notes: "Vieux becomes vieil in front of a word starting with a vowel sound: un vieil ami, un vieil immeuble. It sounds exactly like the feminine vieille and it is used with the un kind of thing.", tags: ["adjective","elision"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.consonnes.138", kind: "word", level: "sons", theme: "consonnes", fr: "belle", en: "beautiful", ipa: "/bɛl/", respell: "BEL", tags: ["doubled"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.adjectifs-essentiels.312", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "vieille", en: "old (feminine)", ipa: "/vjɛj/", respell: "VYEY", notes: "The feminine of vieux, and it is a different word rather than an added ending: vieille, never vieuxe. Ma grand-mère est vieille. Before a vowel the masculine is vieil.", tags: ["adjective","accord-genre"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.rencontres.095", kind: "word", level: "a1", theme: "rencontres", fr: "nouvelle", en: "new (feminine)", ipa: "nu.vɛl", respell: "noo-VELL", example: {"en":"Here is my new address.","fr":"Voici ma nouvelle adresse."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
];

/** The 4 published sentences that hold a third form in the `C'est un ___`
 *  frame. None had a respelling and this build supplies all four. */
export const IMPORTED_EVIDENCE_ROWS: Item[] = [
  { id: "fr.a1.adjectifs-essentiels.204", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "C'est un bel arbre.", en: "It's a beautiful tree.", notes: "{\"tiles\":[{\"w\":\"C'est un\",\"t\":\"it's a\"},{\"w\":\"bel\",\"t\":\"beautiful\"},{\"w\":\"arbre.\",\"t\":\"tree\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.038", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "C'est un nouvel ami.", en: "He's a new friend.", ipa: "sɛ.tœ̃ nu.vɛl a.mi", notes: "'Nouvel' replaces 'nouveau' before a vowel-starting masculine noun.", tags: ["grammaire"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.214", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "C'est un vieil immeuble.", en: "It's an old building.", notes: "{\"tiles\":[{\"w\":\"C'est un\",\"t\":\"it's an\"},{\"w\":\"vieil\",\"t\":\"old\"},{\"w\":\"immeuble.\",\"t\":\"building\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.026", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "C'est un bel homme.", en: "He is a handsome man.", ipa: "sɛ.tœ̃ bɛl ɔm", notes: "'Bel' replaces 'beau' before a masculine noun starting with a vowel.", tags: ["grammaire"], drills: ["dictation"], audioRef: null, version: 1 },
];

/** The 12 rows read and refused. READ ONLY: never carried, never released,
 *  never in itemIds, and named on no screen. */
export const READ_ONLY_ROWS: Item[] = [
  { id: "fr.sons.masterclass.034", kind: "sentence", level: "sons", theme: "masterclass", fr: "C'est un très bel appartement.", en: "It is a very nice flat.", ipa: "/sɛ.t‿œ̃ tʁɛ bɛ.l‿a.paʁ.tə.mɑ̃/", respell: "seh-t‿uhⁿ treh beh-l‿a-par-tuh-MAHⁿ", notes: "beau became bel before the vowel. French changed the word rather than allow the gap.", tags: ["elision","liaison","muettes","nasales","join","liaison-l","liaison-t"], drills: ["sentence","review","flashcard","voiceflash","dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.048", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "C'est un vieil arbre magnifique.", en: "It's a magnificent old tree.", ipa: "sɛ.tœ̃ vjɛj aʁbʁ ma.ɲi.fik", notes: "'Vieil' is used before the vowel-starting 'arbre'.", tags: ["grammaire"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.209", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "C'est un nouvel hôtel.", en: "It's a new hotel.", notes: "{\"tiles\":[{\"w\":\"C'est un\",\"t\":\"it's a\"},{\"w\":\"nouvel\",\"t\":\"new\"},{\"w\":\"hôtel.\",\"t\":\"hotel\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.025", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "C'est un beau jardin.", en: "It's a beautiful garden.", ipa: "sɛ.tœ̃ bo ʒaʁ.dɛ̃", notes: "'Beau' precedes the noun 'jardin'.", tags: ["grammaire"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.043", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "C'est un vieux château.", en: "It's an old castle.", ipa: "sɛ.tœ̃ vjø ʃa.to", notes: "'Vieux' precedes the noun 'château'.", tags: ["grammaire"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.202", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "Ce sont de beaux tableaux.", en: "These are beautiful paintings.", notes: "{\"tiles\":[{\"w\":\"Ce sont\",\"t\":\"these are\"},{\"w\":\"de beaux\",\"t\":\"beautiful\"},{\"w\":\"tableaux.\",\"t\":\"paintings\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.adjectifs-essentiels.212", kind: "sentence", level: "a1", theme: "adjectifs-essentiels", fr: "Ce sont de vieux amis.", en: "They are old friends.", notes: "{\"tiles\":[{\"w\":\"Ce sont\",\"t\":\"they are\"},{\"w\":\"de vieux\",\"t\":\"old\"},{\"w\":\"amis.\",\"t\":\"friends\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.sons.liaisons.168", kind: "phrase", level: "sons", theme: "liaisons", fr: "un homme", en: "a man", ipa: "œ̃.n‿ɔm", respell: "uhⁿ-n‿OM", notes: "H muet is not there as far as the ear is concerned, so the N links straight across it.", tags: ["liaison-n","liaison-obligatoire","after-determiner","h-muet","word-level"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.rp-maison.001", kind: "word", level: "a1", theme: "rp-maison", fr: "un appartement", en: "an apartment", ipa: "a.paʁ.tə.mɑ̃", respell: "ah-par-tuh-MAHN", gender: "m", notes: "", tags: ["genre"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.la-ville.002", kind: "word", level: "a1", theme: "la-ville", fr: "l'immeuble", en: "the apartment building", ipa: "/limœbl/", respell: "lee-MUHBL", gender: "m", notes: "A multi-storey residential or office building.", tags: ["ville","lieux"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.rencontres.073", kind: "word", level: "a1", theme: "rencontres", fr: "un ami", en: "a friend (male)", ipa: "œ̃.n‿a.mi", respell: "uh-nah-MEE", gender: "m", example: {"en":"He's a friend of my brother.","fr":"C'est un ami de mon frère."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  { id: "fr.sons.elision.012", kind: "word", level: "sons", theme: "elision", fr: "l'homme", en: "the man", ipa: "/lɔm/", respell: "LOM", gender: "m", notes: "H muet. The article shrinks and the word starts on the O.", tags: ["le","h-muet"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
];

/** form -> id, in learner order. The only place this pairing is written. */
export const NAMING_ROW_IDS: [string, string][] = [
  ["beau", "fr.sons.adjectifs-essentiels.005"],
  ["nouveau", "fr.sons.adjectifs-essentiels.007"],
  ["vieux", "fr.sons.adjectifs-essentiels.008"],
  ["bel", "fr.sons.adjectifs-essentiels.314"],
  ["vieil", "fr.sons.adjectifs-essentiels.315"],
  ["belle", "fr.sons.consonnes.138"],
  ["vieille", "fr.sons.adjectifs-essentiels.312"],
  ["nouvelle", "fr.a1.rencontres.095"],
];

/** evidence sentence -> id. */
export const EVIDENCE_ROW_IDS: [string, string][] = [
  ["C'est un bel arbre.", "fr.a1.adjectifs-essentiels.204"],
  ["C'est un nouvel ami.", "fr.a1.adjectifs-essentiels.038"],
  ["C'est un vieil immeuble.", "fr.a1.adjectifs-essentiels.214"],
  ["C'est un bel homme.", "fr.a1.adjectifs-essentiels.026"],
];

/** And the refused pairing, kept apart so nothing can iterate both by accident. */
export const READ_ONLY_ROW_IDS: [string, string][] = [
  ["C'est un très bel appartement.", "fr.sons.masterclass.034"],
  ["C'est un vieil arbre magnifique.", "fr.a1.adjectifs-essentiels.048"],
  ["C'est un nouvel hôtel.", "fr.a1.adjectifs-essentiels.209"],
  ["C'est un beau jardin.", "fr.a1.adjectifs-essentiels.025"],
  ["C'est un vieux château.", "fr.a1.adjectifs-essentiels.043"],
  ["Ce sont de beaux tableaux.", "fr.a1.adjectifs-essentiels.202"],
  ["Ce sont de vieux amis.", "fr.a1.adjectifs-essentiels.212"],
  ["un homme", "fr.sons.liaisons.168"],
  ["un appartement", "fr.a1.rp-maison.001"],
  ["l'immeuble", "fr.a1.la-ville.002"],
  ["un ami", "fr.a1.rencontres.073"],
  ["l'homme", "fr.sons.elision.012"],
];

/** Every id this lesson may put in `itemIds`. */
export const IMPORTABLE_IDS: string[] = [
  "fr.sons.adjectifs-essentiels.005",
  "fr.sons.adjectifs-essentiels.007",
  "fr.sons.adjectifs-essentiels.008",
  "fr.sons.adjectifs-essentiels.314",
  "fr.sons.adjectifs-essentiels.315",
  "fr.sons.consonnes.138",
  "fr.sons.adjectifs-essentiels.312",
  "fr.a1.rencontres.095",
  "fr.a1.adjectifs-essentiels.204",
  "fr.a1.adjectifs-essentiels.038",
  "fr.a1.adjectifs-essentiels.214",
  "fr.a1.adjectifs-essentiels.026",
];

/** Every id the merge writes into the seed. Identical to IMPORTABLE_IDS: this
 *  build repairs nothing it does not also display. TWO OF THE TWELVE ARE NOT IN
 *  THE SEED TODAY — fr.a1.adjectifs-essentiels.038 and fr.a1.rencontres.095 —
 *  so a merge that did not carry them would render two empty cards. */
export const CARRIED_IDS: string[] = [
  "fr.sons.adjectifs-essentiels.005",
  "fr.sons.adjectifs-essentiels.007",
  "fr.sons.adjectifs-essentiels.008",
  "fr.sons.adjectifs-essentiels.314",
  "fr.sons.adjectifs-essentiels.315",
  "fr.sons.consonnes.138",
  "fr.sons.adjectifs-essentiels.312",
  "fr.a1.rencontres.095",
  "fr.a1.adjectifs-essentiels.204",
  "fr.a1.adjectifs-essentiels.038",
  "fr.a1.adjectifs-essentiels.214",
  "fr.a1.adjectifs-essentiels.026",
];

/** The themes the imported rows came out of. */
export const SOURCE_THEMES: string[] = ["adjectifs-essentiels","consonnes","rencontres"];

/** The block, and the row count in it on the day this manifest was generated.
 *  Ledger §10: the maximum is useless and the COUNT is the only signal. */
export const BLOCK_MEASURED = { rows: 33, insideBlock: 0, date: "2026-08-13" };

/** The measurement the lesson rests on, re-taken here so it cannot go stale in
 *  a comment: the short form and the feminine carry the same respelling and the
 *  same IPA, in rows written by different authors in different themes. */
export const ONE_SOUND_EVIDENCE: { pair: string; respell: string; ipa: string }[] = [
  { pair: "bel / belle", respell: "BEL", ipa: "/bɛl/" },
  { pair: "vieil / vieille", respell: "VYEY", ipa: "/vjɛj/" },
];
