// GENERATED by scripts/_a212_manifest.ts on 2026-08-12. Do not edit by hand.
//
// A recorded read of the 3 naming forms and 23 expressions a2.12 imports rather
// than authors, and the 3 rows it reads and refuses. Two consumers need
// the whole row rather than the id:
//
//   author-faire-dire-lire-batch.ts verifies every field against Postgres before
//   it opens a transaction, so a stale manifest cannot put the lesson ahead of
//   rows nobody has looked at.
//
//   merge-faire-dire-lire-into-seed.ts CARRIES them into seed.json. The seed is
//   a CUT — meteo shows 26 rows against 336 in Postgres — so without the carry
//   most of this lesson's thirty expression cards would draw empty.
//
// THE READ-ONLY ROWS ARE NOT CARRIED AND NOT RELEASED. a2.10 settled the rule: a
// row a lesson does not teach is a display string at most, never a row in the hub.
//
// Regenerate with: pnpm tsx scripts/_a212_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 3 naming forms this lesson teaches, in learner order. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.004", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "faire", en: "to do, to make", ipa: "/fɛʁ/", respell: "FEHR", notes: "irregular · je fais, nous faisons, ils font", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.005", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "dire", en: "to say, to tell", ipa: "/diʁ/", respell: "DEER", notes: "irregular · je dis, vous dites, ils disent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.dictee.091", kind: "word", level: "a1", theme: "dictee", fr: "lire", en: "to read", ipa: "liʁ", respell: "LEER", example: {"en":"We are going to read the sentence out loud.","fr":"Nous allons lire la phrase à voix haute."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
];

/** The 23 expressions this lesson imports, grouped by the English verb
 *  French does not use. */
export const IMPORTED_EXPRESSION_ROWS: Item[] = [
  { id: "fr.a2.courses.018", kind: "phrase", level: "a2", theme: "courses", fr: "faire les courses", en: "to do the grocery shopping", ipa: "/fɛʁ le kuʁs/", respell: "FEHR lay KOORS", tags: ["shopping"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.routines.030", kind: "phrase", level: "a1", theme: "routines", fr: "faire le ménage", en: "to do the housework", respell: "FEHR luh may-NAHZH", tags: ["phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.routines.031", kind: "phrase", level: "a1", theme: "routines", fr: "faire la vaisselle", en: "to do the dishes", respell: "FEHR lah veh-SEHL", tags: ["phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.routines.032", kind: "phrase", level: "a1", theme: "routines", fr: "faire la lessive", en: "to do the laundry", respell: "FEHR lah leh-SEEV", tags: ["phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.ecole.106", kind: "phrase", level: "a1", theme: "ecole", fr: "faire ses devoirs", en: "to do your homework", ipa: "fɛʁ se dəvwaʁ", respell: "FEHR SAY duh-VWAHR", notes: "Ses changes with the person: je fais mes devoirs.", tags: ["school","routine"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.maison.122", kind: "phrase", level: "a1", theme: "maison", fr: "faire le lit", en: "to make the bed", ipa: "/fɛʁ lə li/", respell: "fehr luh LEE", tags: ["phrase","chore","bedroom"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.b1.voisinage.062", kind: "phrase", level: "b1", theme: "voisinage", fr: "faire du bruit", en: "to make noise", ipa: "/fɛʁ dy bʁɥi/", respell: "fair dü BRWEE", example: {"en":"Avoid making noise after 10pm.","fr":"Évitez de faire du bruit après 22 heures."}, tags: [], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.b2.rp-achats.004", kind: "phrase", level: "b2", theme: "rp-achats", fr: "faire un effort", en: "to make an effort, to meet halfway", ipa: "fɛʁ œ̃.n‿e.fɔʁ", notes: "", tags: ["expression"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.b1.bien-etre.035", kind: "phrase", level: "b1", theme: "bien-etre", fr: "faire du sport", en: "to exercise", ipa: "/fɛʁ dy spɔʁ/", respell: "FEHR dü SPOHR", example: {"en":"I exercise three times a week.","fr":"Je fais du sport trois fois par semaine."}, tags: [], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.a1.sports-et-loisirs.109", kind: "phrase", level: "a1", theme: "sports-et-loisirs", fr: "faire du vélo", en: "to ride a bike", ipa: "/fɛʁ dy ve.lo/", respell: "fair dü vay-LOH", tags: ["phrase","verb","sport"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.sports-et-loisirs.074", kind: "phrase", level: "a1", theme: "sports-et-loisirs", fr: "faire du ski", en: "to go skiing", ipa: "/fɛʁ dy ski/", respell: "FEHR DÜ SKEE", notes: "Du before masculine nouns, de la before feminine ones.", tags: ["verb","expression"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.sports-et-loisirs.073", kind: "phrase", level: "a1", theme: "sports-et-loisirs", fr: "faire de la natation", en: "to go swimming", ipa: "/fɛʁ də la natasjɔ̃/", respell: "FEHR DUH LAH na-ta-SYOHN", notes: "Faire de for activities you practice, jouer à only for games.", tags: ["verb","expression"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.animaux-domestiques.123", kind: "phrase", level: "a1", theme: "animaux-domestiques", fr: "faire une promenade", en: "to go for a walk", ipa: "/fɛʁ yn pʁɔmnad/", respell: "fair ün prohm-NAHD", tags: ["phrase","verb","care"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.meteo.027", kind: "phrase", level: "a1", theme: "meteo", fr: "il fait beau", en: "the weather is nice", ipa: "il fɛ bo", respell: "EEL FEH BOH", notes: "Weather uses il fait plus an adjective.", tags: ["weather","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.meteo.029", kind: "phrase", level: "a1", theme: "meteo", fr: "il fait chaud", en: "it is hot", ipa: "il fɛ ʃo", respell: "EEL FEH SHOH", tags: ["weather","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.meteo.028", kind: "phrase", level: "a1", theme: "meteo", fr: "il fait froid", en: "it is cold", ipa: "il fɛ fʁwa", respell: "EEL FEH FRWAH", tags: ["weather","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.meteo.039", kind: "word", level: "a1", theme: "meteo", fr: "il fait frais", en: "it is cool, it is chilly", ipa: "/il fɛ fʁɛ/", respell: "EEL FEH FREH", gender: "m", notes: "Between mild and cold. Frais also describes fresh food.", tags: ["weather","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.meteo.037", kind: "word", level: "a1", theme: "meteo", fr: "il fait mauvais", en: "the weather is bad", ipa: "/il fɛ mo.vɛ/", respell: "EEL FEH moh-VEH", gender: "m", notes: "The opposite of il fait beau. Weather phrases use il fait plus an adjective.", tags: ["weather","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.famille.136", kind: "phrase", level: "a1", theme: "famille", fr: "faire la cuisine", en: "to cook", ipa: "fɛʁ la kɥi.zin", example: {"en":"My father likes to cook on Sundays.","fr":"Mon père aime faire la cuisine le dimanche."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.b1.tourisme.039", kind: "phrase", level: "b1", theme: "tourisme", fr: "faire la queue", en: "to queue up / to wait in line", ipa: "/fɛʁ la kø/", respell: "fair la KUH", example: {"en":"You have to wait in line for almost an hour.","fr":"Il faut faire la queue pendant presque une heure."}, tags: [], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.a1.amis.026", kind: "phrase", level: "a1", theme: "amis", fr: "faire la fête", en: "to party", ipa: "/fɛʁ la fɛt/", respell: "FEHR LAH FEHT", notes: "Literally to make the party.", tags: ["amis","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.routines.043", kind: "word", level: "a1", theme: "routines", fr: "faire la sieste", en: "to take a nap", ipa: "fɛʁ la sjɛst", respell: "FEHR la SYEST", notes: "Uses faire: je fais la sieste après le déjeuner.", tags: ["routine","rest","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.dictee.122", kind: "phrase", level: "a1", theme: "dictee", fr: "faire attention", en: "to pay attention", ipa: "fɛʁ a.tɑ̃.sjɔ̃", example: {"en":"Pay attention to the accents.","fr":"Fais attention aux accents."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
];

/** The 3 rows read and refused. READ ONLY: never carried, never released,
 *  never in itemIds, and named on no screen. */
export const READ_ONLY_ROWS: Item[] = [
  { id: "fr.a1.dictee.090", kind: "word", level: "a1", theme: "dictee", fr: "écrire", en: "to write", ipa: "e.kʁiʁ", respell: "ay-KREER", example: {"en":"You must write your name at the top of the page.","fr":"Il faut écrire son nom en haut de la page."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.a1.routines.050", kind: "word", level: "a1", theme: "routines", fr: "faire son lit", en: "to make one's bed", ipa: "fɛʁ sɔ̃ li", respell: "FEHR sohn LEE", notes: "Son changes with the subject: je fais mon lit, tu fais ton lit.", tags: ["routine","chores","morning"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.b1.courses.023", kind: "phrase", level: "b1", theme: "courses", fr: "faire la queue", en: "to stand in line, queue", ipa: "/fɛʁ la kø/", respell: "fair lah kuh", example: {"en":"We had to stand in line for twenty minutes at the checkout.","fr":"On a dû faire la queue vingt minutes à la caisse."}, tags: [], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["faire", "fr.sons.verbes-essentiels.004"],
  ["dire", "fr.sons.verbes-essentiels.005"],
  ["lire", "fr.a1.dictee.091"],
];

/** group -> expression -> id, in the order the tapTable renders the groups. */
export const EXPRESSION_ROW_IDS: [string, string, string][] = [
  ["do", "faire les courses", "fr.a2.courses.018"],
  ["do", "faire le ménage", "fr.a1.routines.030"],
  ["do", "faire la vaisselle", "fr.a1.routines.031"],
  ["do", "faire la lessive", "fr.a1.routines.032"],
  ["do", "faire ses devoirs", "fr.a1.ecole.106"],
  ["make", "faire le lit", "fr.a1.maison.122"],
  ["make", "faire du bruit", "fr.b1.voisinage.062"],
  ["make", "faire un effort", "fr.b2.rp-achats.004"],
  ["go", "faire du sport", "fr.b1.bien-etre.035"],
  ["go", "faire du vélo", "fr.a1.sports-et-loisirs.109"],
  ["go", "faire du ski", "fr.a1.sports-et-loisirs.074"],
  ["go", "faire de la natation", "fr.a1.sports-et-loisirs.073"],
  ["take", "faire une promenade", "fr.a1.animaux-domestiques.123"],
  ["be", "il fait beau", "fr.a1.meteo.027"],
  ["be", "il fait chaud", "fr.a1.meteo.029"],
  ["be", "il fait froid", "fr.a1.meteo.028"],
  ["be", "il fait frais", "fr.a1.meteo.039"],
  ["be", "il fait mauvais", "fr.a1.meteo.037"],
  ["own", "faire la cuisine", "fr.a1.famille.136"],
  ["own", "faire la queue", "fr.b1.tourisme.039"],
  ["own", "faire la fête", "fr.a1.amis.026"],
  ["own", "faire la sieste", "fr.a1.routines.043"],
  ["own", "faire attention", "fr.a1.dictee.122"],
];

/** And the read-only pairing, kept apart so nothing can iterate both by accident. */
export const READ_ONLY_ROW_IDS: [string, string][] = [
  ["écrire", "fr.a1.dictee.090"],
  ["faire son lit", "fr.a1.routines.050"],
  ["faire la queue", "fr.b1.courses.023"],
];
