// A RECORDED READ OF POSTGRES. Generated by scripts/_a219_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 17 rows imported out of 6 themes.
// 9 rows read and refused; see READ_NOT_IMPORTED in the corpus file.
// 0 respellings repaired, 4 supplied.
// 6 rows found broken and left alone; 6 of them still are.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   the published negatives   13 sentences put ne...pas round aller with an
//                             infinitive behind it, and 0 of them carry a respelling
//     fr.a1.expressions-utiles.220           NO RESPELLING
//     fr.a2.negation-et-restriction.107      NO RESPELLING
//     fr.a2.negation-et-restriction.108      NO RESPELLING
//     fr.a2.negation-et-restriction.109      NO RESPELLING
//     fr.a2.negation-et-restriction.148      NO RESPELLING
//     fr.a2.negation-et-restriction.152      NO RESPELLING
//     fr.a2.negation-et-restriction.157      NO RESPELLING
//     fr.a2.negation-et-restriction.158      NO RESPELLING
//     fr.a2.negation-et-restriction.159      NO RESPELLING
//     fr.a2.negation-et-restriction.161      NO RESPELLING
//     fr.a2.negation-et-restriction.164      NO RESPELLING
//     fr.a2.negation-et-restriction.166      NO RESPELLING
//     fr.b1.projets-et-futur.012             NO RESPELLING
//
//   aller + infinitive        721 published sentences, 10 with a respelling
//                             a2.13 §1: evidence is not cards, and the pool was 10 not 721
//
//   the one-word future       206 published sentences already hold one
//                             (the corpus file records 206)
//
//   a2.02's paradigm, still six consecutive published rows in one frame:
//     fr.a2.verbes.261  Je vais au parc.       zhuh veh oh PARK
//     fr.a2.verbes.262  Tu vas au parc.        tü vah oh PARK
//     fr.a2.verbes.263  Il va au parc.         eel vah oh PARK
//     fr.a2.verbes.264  Nous allons au parc.   noo za-lohⁿ oh PARK
//     fr.a2.verbes.265  Vous allez au parc.    voo za-lay oh PARK
//     fr.a2.verbes.266  Ils vont au parc.      eel vohⁿ oh PARK
//
// THE BLOCK: fr.a2.verbes held 374 rows before this build and holds
// 374 now. Rows inside fr.a2.verbes.501..fr.a2.verbes.540 that this
// build does not own: none.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const FUTUR_PROCHE_ROWS: Record<string, Item> = {
  'fr.a2.negation-et-restriction.107':   { id: "fr.a2.negation-et-restriction.107", kind: "sentence", level: "a2", theme: "negation-et-restriction", fr: "Je ne vais pas sortir ce soir.", en: "I am not going to go out tonight.", notes: "In futur proche, ne and pas wrap around the conjugated verb aller, right before the infinitive.", tags: ["negation","ne-pas","futur-proche","word-order"], drills: ["flashcard","sentence","dictation"], audioRef: null, version: 1 },
  'fr.a2.negation-et-restriction.152':   { id: "fr.a2.negation-et-restriction.152", kind: "sentence", level: "a2", theme: "negation-et-restriction", fr: "Ils ne vont pas venir à la fête.", en: "They aren't going to come to the party.", ipa: "/il nə vɔ̃ pa və.niʁ a la fɛt/", notes: "Vont is easy to confuse with on or ont by sound, so check the subject ils carefully.", tags: ["homophone"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.negation-et-restriction.158':   { id: "fr.a2.negation-et-restriction.158", kind: "sentence", level: "a2", theme: "negation-et-restriction", fr: "Je ne vais pas manger de viande ce soir.", en: "I'm not going to eat meat tonight.", ipa: "/ʒə nə vɛ pa mɑ̃.ʒe də vjɑ̃d sə swaʁ/", notes: "After the negation, de la viande shortens to de viande, losing the article.", tags: ["orthographe"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.negation-et-restriction.164':   { id: "fr.a2.negation-et-restriction.164", kind: "sentence", level: "a2", theme: "negation-et-restriction", fr: "Elle ne va pas finir le rapport ce soir.", en: "She isn't going to finish the report tonight.", ipa: "/ɛl nə va pa fi.niʁ lə ʁa.pɔʁ sə swaʁ/", notes: "Rapport doubles its p in spelling though it is pronounced as a single consonant.", tags: ["orthographe"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.prepositions-essentielles.130':   { id: "fr.a2.prepositions-essentielles.130", kind: "sentence", level: "a2", theme: "prepositions-essentielles", fr: "Je vais à Paris.", en: "I am going to Paris.", ipa: "/ʒə vɛ a pa.ʁi/", respell: "zhuh veh a pa-REE", notes: "A city has no article to fold with, so à goes straight on. Twelve letters.", tags: ["prepositions","lieu","ville"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  'fr.a2.prepositions-essentielles.172':   { id: "fr.a2.prepositions-essentielles.172", kind: "sentence", level: "a2", theme: "prepositions-essentielles", fr: "Je pars dans dix minutes.", en: "I am leaving in ten minutes.", ipa: "/ʒə paʁ dɑ̃ di mi.nyt/", respell: "zhuh PAR dAHⁿ dee mee-NÜT", notes: "A present tense about something that has not happened, which is correct French and not a shortcut. The other way to say it is the next lesson.", tags: ["prepositions","temps","dans"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.a2.prepositions-essentielles.184':   { id: "fr.a2.prepositions-essentielles.184", kind: "phrase", level: "a2", theme: "prepositions-essentielles", fr: "dans dix minutes", en: "in ten minutes", ipa: "/dɑ̃ di mi.nyt/", respell: "dAHⁿ dee mee-NÜT", notes: "Fourteen letters. A point ahead, and the present tense goes in front of it.", tags: ["prepositions","temps"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  'fr.a2.verbes.031':   { id: "fr.a2.verbes.031", kind: "word", level: "a2", theme: "verbes", fr: "travailler", en: "to work", ipa: "tʁa.va.je", respell: "trah-vah-YAY", example: {"en":"I work in a hospital.","fr":"Je travaille dans un hôpital."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.a2.verbes.261':   { id: "fr.a2.verbes.261", kind: "sentence", level: "a2", theme: "verbes", fr: "Je vais au parc.", en: "I go to the park.", ipa: "/ʒə vɛ o paʁk/", respell: "zhuh veh oh PARK", notes: "vais, and there is no all- in it anywhere. This is the form to stop looking for a reason for.", tags: ["irregular","aller","paradigm","singular"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.a2.verbes.266':   { id: "fr.a2.verbes.266", kind: "sentence", level: "a2", theme: "verbes", fr: "Ils vont au parc.", en: "They go to the park.", ipa: "/il vɔ̃ o paʁk/", respell: "eel vohⁿ oh PARK", notes: "vont, and the all- is gone again. Four cells from v-, two from all-, and no rule joins them.", tags: ["irregular","aller","paradigm","plural","nasal"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.a2.verbes.347':   { id: "fr.a2.verbes.347", kind: "sentence", level: "a2", theme: "verbes", fr: "Je peux payer.", en: "I can pay.", ipa: "/ʒə pø pe.je/", respell: "zhuh PUH pay-YAY", notes: "The same -x ending as veux, on the same kind of stem. Two verbs, one new letter between them.", tags: ["modal","pouvoir","paradigm","singular"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.sons.consonnes.098':   { id: "fr.sons.consonnes.098", kind: "word", level: "sons", theme: "consonnes", fr: "partir", en: "to leave", ipa: "/paʁ.tiʁ/", respell: "par-TEER", tags: ["r","r-medial","r-final"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  'fr.sons.muettes.037':   { id: "fr.sons.muettes.037", kind: "word", level: "sons", theme: "muettes", fr: "manger", en: "to eat", ipa: "/mɑ̃.ʒe/", respell: "mahⁿ-ZHAY", tags: ["er-ending","silent-r","infinitive","nasal"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.sons.verbes-essentiels.003':   { id: "fr.sons.verbes-essentiels.003", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "aller", en: "to go", ipa: "/ale/", respell: "ah-LAY", notes: "irregular · je vais, tu vas, il va, nous allons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.010':   { id: "fr.sons.verbes-essentiels.010", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "venir", en: "to come", ipa: "/vəniʁ/", respell: "vuh-NEER", notes: "irregular · je viens, nous venons, ils viennent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.041':   { id: "fr.sons.verbes-essentiels.041", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "sortir", en: "to go out", ipa: "/sɔʁtiʁ/", respell: "sor-TEER", notes: "irregular · je sors, nous sortons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.059':   { id: "fr.sons.verbes-essentiels.059", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "payer", en: "to pay", ipa: "/peje/", respell: "pay-YAY", notes: "spelling change · je paie, nous payons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
};

/** What the database said, so a guard can compare a supplied value against the
 *  READ rather than against a second copy of the same string. a2.14 §5. An
 *  empty string is a row that had no respelling at all. */
export const STORED_RESPELL: Record<string, string> = {
  'fr.a2.negation-et-restriction.107': "",
  'fr.a2.negation-et-restriction.152': "",
  'fr.a2.negation-et-restriction.158': "",
  'fr.a2.negation-et-restriction.164': "",
  'fr.a2.prepositions-essentielles.130': "zhuh veh a pa-REE",
  'fr.a2.prepositions-essentielles.172': "zhuh PAR dAHⁿ dee mee-NÜT",
  'fr.a2.prepositions-essentielles.184': "dAHⁿ dee mee-NÜT",
  'fr.a2.verbes.031': "trah-vah-YAY",
  'fr.a2.verbes.261': "zhuh veh oh PARK",
  'fr.a2.verbes.266': "eel vohⁿ oh PARK",
  'fr.a2.verbes.347': "zhuh PUH pay-YAY",
  'fr.sons.consonnes.098': "par-TEER",
  'fr.sons.muettes.037': "mahⁿ-ZHAY",
  'fr.sons.verbes-essentiels.003': "ah-LAY",
  'fr.sons.verbes-essentiels.010': "vuh-NEER",
  'fr.sons.verbes-essentiels.041': "sor-TEER",
  'fr.sons.verbes-essentiels.059': "pay-YAY",
};

/** Re-measured on every regeneration. A figure the lesson prints comes from
 *  here rather than from a constant somebody typed. */
export const MEASURED = {
  publishedNegatives: 13,
  publishedNegativesRespelled: 0,
  allerPlusInfinitive: 721,
  allerPlusInfinitiveRespelled: 10,
  oneWordFutureRows: 206,
  blockCountAtRead: 374,
} as const;
