// a1.26's IMPORTED manifest: a RECORDED READ of Postgres taken by
// scripts/_maison_manifest.ts. NOTHING BELOW WAS RETYPED.
//
//     pnpm tsx scripts/_maison_manifest.ts > scripts/data/maison-imported.ts
//
// The batch compares every field against the live database before writing and
// dies if this manifest has drifted, because a stale manifest puts the seed
// ahead of rows nobody has looked at.
//
// ── Why nothing is carried into the seed ──────────────────────────────────
//
// `maison` IS in SEED_CUT.themes. 363 rows published in Postgres, 363 already
// in seed.json, measured both ways. So unlike a1.13 (couleurs) and a1.22
// (pays-et-nationalites), which are OUTSIDE the cut and had to carry every row
// they named, this merge carries NOTHING. It writes three authored rows, the
// respelling repairs, and the lesson.
//
// ── The respellings below are the values the rows hold TODAY ──────────────
//
// Forty-two of them are broken and are repaired by RESPELL_REPAIRS in
// maison-corpus.ts rather than corrected here, because the batch compares this
// manifest field by field against the database and a corrected value would read
// as drift and stop the run.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export type ImportedRow = Item;

/* GENERATED by scripts/_maison_manifest.ts. Do not hand-edit. */
export const IMPORTED: ImportedRow[] = [

  // ── the 57 words and phrases this lesson names ──
  {
    id: "fr.a1.maison.001", kind: "word", level: "a1", theme: "maison", fr: "la maison", en: "the house", ipa: "/mɛ.zɔ̃/", respell: "lah meh-ZOHN", gender: "f", tags: ["noun","home"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.002", kind: "word", level: "a1", theme: "maison", fr: "la chambre", en: "the bedroom", respell: "lah SHAHNBR", gender: "f", tags: ["noun","home","rooms"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.003", kind: "word", level: "a1", theme: "maison", fr: "le salon", en: "the living room", respell: "luh sah-LOHN", gender: "m", tags: ["noun","home","rooms"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.010", kind: "word", level: "a1", theme: "maison", fr: "la salle de bain", en: "the bathroom", ipa: "/sal də bɛ̃/", gender: "f", tags: ["home","rooms"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.011", kind: "word", level: "a1", theme: "maison", fr: "les toilettes", en: "the toilet", ipa: "/twalɛt/", respell: "lay twah-LEHT", gender: "f", notes: "Always plural in French.", tags: ["home","rooms"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.038", kind: "word", level: "a1", theme: "maison", fr: "la salle à manger", en: "the dining room", gender: "f", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.104", kind: "word", level: "a1", theme: "maison", fr: "la cuisine", en: "the kitchen", ipa: "/la kɥi.zin/", respell: "lah kwee-ZEEN", gender: "f", tags: ["noun","room","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.040", kind: "word", level: "a1", theme: "maison", fr: "la cave", en: "the cellar", respell: "lah KAHV", gender: "f", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.052", kind: "word", level: "a1", theme: "maison", fr: "le grenier", en: "the attic", ipa: "lə ɡʁə.nje", respell: "luh gruh-NYAY", gender: "m", notes: "The space under the roof, often used for storage.", tags: ["maison","pieces","rangement"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.097", kind: "word", level: "a1", theme: "maison", fr: "le couloir", en: "the hallway", ipa: "/lə ku.lwaʁ/", respell: "luh koo-LWAHR", gender: "m", notes: "The corridor inside a home or building.", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.018", kind: "word", level: "a1", theme: "maison", fr: "le jardin", en: "the garden", ipa: "/ʒaʁdɛ̃/", respell: "luh zhahr-DAN", gender: "m", tags: ["home","outdoors"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.039", kind: "word", level: "a1", theme: "maison", fr: "le balcon", en: "the balcony", respell: "luh bahl-KOHN", gender: "m", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.077", kind: "word", level: "a1", theme: "maison", fr: "l'appartement", en: "the apartment", ipa: "/la.paʁ.tə.mɑ̃/", respell: "lah-par-tuh-MAHN", gender: "m", notes: "Often shortened to un appart in speech.", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.076", kind: "word", level: "a1", theme: "maison", fr: "le studio", en: "the studio apartment", ipa: "/lə sty.djo/", respell: "luh stü-DYOH", gender: "m", notes: "A one-room apartment.", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.023", kind: "word", level: "a1", theme: "maison", fr: "le garage", en: "the garage", ipa: "/ɡaʁaʒ/", respell: "luh gah-RAHZH", gender: "m", tags: ["home"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.012", kind: "word", level: "a1", theme: "maison", fr: "la porte", en: "the door", ipa: "/pɔʁt/", respell: "lah PORT", gender: "f", tags: ["home"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.013", kind: "word", level: "a1", theme: "maison", fr: "la fenêtre", en: "the window", ipa: "/fənɛtʁ/", respell: "lah fuh-NEHTR", gender: "f", tags: ["home"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.019", kind: "word", level: "a1", theme: "maison", fr: "l'escalier", en: "the staircase", ipa: "/ɛskalje/", respell: "leh-skah-LYAY", gender: "m", tags: ["home"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.020", kind: "word", level: "a1", theme: "maison", fr: "le mur", en: "the wall", ipa: "/myʁ/", respell: "luh MÜR", gender: "m", tags: ["home"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.033", kind: "word", level: "a1", theme: "maison", fr: "le plafond", en: "the ceiling", respell: "luh plah-FOHN", gender: "m", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.034", kind: "word", level: "a1", theme: "maison", fr: "le sol", en: "the floor", respell: "luh SOL", gender: "m", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.014", kind: "word", level: "a1", theme: "maison", fr: "le lit", en: "the bed", ipa: "/li/", respell: "luh LEE", gender: "m", tags: ["home","furniture"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.015", kind: "word", level: "a1", theme: "maison", fr: "la table", en: "the table", ipa: "/tabl/", respell: "lah TAHBL", gender: "f", tags: ["home","furniture"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.016", kind: "word", level: "a1", theme: "maison", fr: "la chaise", en: "the chair", ipa: "/ʃɛz/", respell: "lah SHEHZ", gender: "f", tags: ["home","furniture"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.017", kind: "word", level: "a1", theme: "maison", fr: "le canapé", en: "the sofa", ipa: "/kanape/", respell: "luh kah-nah-PAY", gender: "m", tags: ["home","furniture"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.041", kind: "word", level: "a1", theme: "maison", fr: "le fauteuil", en: "the armchair", ipa: "lə fo.tœj", respell: "luh foh-TUHY", gender: "m", notes: "A comfortable chair with arms, usually in the living room.", tags: ["maison","furniture","salon"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.025", kind: "word", level: "a1", theme: "maison", fr: "la lampe", en: "the lamp", ipa: "/lɑ̃p/", respell: "lah LAHNP", gender: "f", tags: ["home","furniture"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.026", kind: "word", level: "a1", theme: "maison", fr: "l'armoire", en: "the wardrobe", ipa: "/aʁmwaʁ/", respell: "lahr-MWAHR", gender: "f", tags: ["home","furniture"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.027", kind: "word", level: "a1", theme: "maison", fr: "le tapis", en: "the rug", ipa: "/tapi/", respell: "luh tah-PEE", gender: "m", tags: ["home","furniture"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.028", kind: "word", level: "a1", theme: "maison", fr: "l'étagère", en: "the shelf", respell: "lay-tah-ZHEHR", gender: "f", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.029", kind: "word", level: "a1", theme: "maison", fr: "le rideau", en: "the curtain", respell: "luh ree-DOH", gender: "m", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.086", kind: "word", level: "a1", theme: "maison", fr: "le placard", en: "the cupboard, the closet", ipa: "/lə pla.kaʁ/", respell: "luh plah-KAR", gender: "m", notes: "A built-in cupboard or closet.", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.030", kind: "word", level: "a1", theme: "maison", fr: "la couverture", en: "the blanket", respell: "lah koo-vehr-TÜR", gender: "f", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.032", kind: "word", level: "a1", theme: "maison", fr: "l'oreiller", en: "the pillow", respell: "loh-ray-YAY", gender: "m", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.035", kind: "word", level: "a1", theme: "maison", fr: "la douche", en: "the shower", respell: "lah DOOSH", gender: "f", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.036", kind: "word", level: "a1", theme: "maison", fr: "la baignoire", en: "the bathtub", respell: "lah beh-NYWAHR", gender: "f", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.037", kind: "word", level: "a1", theme: "maison", fr: "le lavabo", en: "the washbasin", respell: "luh lah-vah-BOH", gender: "m", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.105", kind: "word", level: "a1", theme: "maison", fr: "le frigo", en: "the fridge", ipa: "/lə fʁi.go/", respell: "luh free-GOH", gender: "m", tags: ["noun","appliance","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.106", kind: "word", level: "a1", theme: "maison", fr: "le four", en: "the oven", ipa: "/lə fuʁ/", respell: "luh FOOR", gender: "m", tags: ["noun","appliance","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.107", kind: "word", level: "a1", theme: "maison", fr: "le micro-ondes", en: "the microwave", ipa: "/lə mi.kʁo.ɔ̃d/", respell: "luh mee-kroh-OHND", gender: "m", tags: ["noun","appliance","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.108", kind: "word", level: "a1", theme: "maison", fr: "la cuisinière", en: "the stove", ipa: "/la kɥi.zi.njɛʁ/", respell: "lah kwee-zee-NYEHR", gender: "f", tags: ["noun","appliance","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.109", kind: "word", level: "a1", theme: "maison", fr: "le lave-vaisselle", en: "the dishwasher", ipa: "/lə lav.vɛ.sɛl/", respell: "luh lahv-veh-SELL", gender: "m", tags: ["noun","appliance","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.110", kind: "word", level: "a1", theme: "maison", fr: "la machine à laver", en: "the washing machine", ipa: "/la ma.ʃin a la.ve/", respell: "lah mah-SHEEN ah lah-VAY", gender: "f", tags: ["noun","appliance","laundry"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.111", kind: "word", level: "a1", theme: "maison", fr: "le sèche-linge", en: "the clothes dryer", ipa: "/lə sɛʃ.lɛ̃ʒ/", respell: "luh sesh-LIHNZH", gender: "m", tags: ["noun","appliance","laundry"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.113", kind: "word", level: "a1", theme: "maison", fr: "la fourchette", en: "the fork", ipa: "/la fuʁ.ʃɛt/", respell: "lah foor-SHET", gender: "f", tags: ["noun","tableware","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.114", kind: "word", level: "a1", theme: "maison", fr: "le couteau", en: "the knife", ipa: "/lə ku.to/", respell: "luh koo-TOH", gender: "m", tags: ["noun","tableware","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.115", kind: "word", level: "a1", theme: "maison", fr: "la cuillère", en: "the spoon", ipa: "/la kɥi.jɛʁ/", respell: "lah kwee-YEHR", gender: "f", tags: ["noun","tableware","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.116", kind: "word", level: "a1", theme: "maison", fr: "l'assiette", en: "the plate", ipa: "/la.sjɛt/", respell: "lah-SYET", gender: "f", tags: ["noun","tableware","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.117", kind: "word", level: "a1", theme: "maison", fr: "le verre", en: "the glass", ipa: "/lə vɛʁ/", respell: "luh VEHR", gender: "m", tags: ["noun","tableware","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.022", kind: "word", level: "a1", theme: "maison", fr: "la clé", en: "the key", ipa: "/kle/", respell: "lah KLAY", gender: "f", tags: ["home","objects"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.048", kind: "word", level: "a1", theme: "maison", fr: "la poubelle", en: "the trash can", ipa: "la pu.bɛl", respell: "la poo-BEL", gender: "f", notes: "Named after Monsieur Poubelle, the official who introduced it in Paris.", tags: ["maison","objects","cuisine"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.100", kind: "word", level: "a1", theme: "maison", fr: "l'ampoule", en: "the light bulb", ipa: "/lɑ̃.pul/", respell: "lahn-POOL", gender: "f", notes: "Changer une ampoule: to change a light bulb.", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.070", kind: "word", level: "a1", theme: "maison", fr: "le balai", en: "the broom", ipa: "/lə ba.lɛ/", respell: "luh bah-LEH", gender: "m", notes: "Passer le balai: to sweep.", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.069", kind: "word", level: "a1", theme: "maison", fr: "le seau", en: "the bucket", ipa: "/lə so/", respell: "luh SOH", gender: "m", notes: "Un seau d'eau: a bucket of water.", tags: ["noun"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.121", kind: "phrase", level: "a1", theme: "maison", fr: "faire la vaisselle", en: "to do the dishes", ipa: "/fɛʁ la vɛ.sɛl/", respell: "fehr lah veh-SELL", tags: ["phrase","chore","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.122", kind: "phrase", level: "a1", theme: "maison", fr: "faire le lit", en: "to make the bed", ipa: "/fɛʁ lə li/", respell: "fehr luh LEE", tags: ["phrase","chore","bedroom"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.maison.123", kind: "phrase", level: "a1", theme: "maison", fr: "mettre la table", en: "to set the table", ipa: "/mɛtʁ la tabl/", respell: "MET-ruh lah TABL", tags: ["phrase","chore","kitchen"], drills: ["flashcard","voiceflash","review"], version: 1, cardType: "vocab",
  },

  // ── the 12 published sentences it shows ──
  {
    id: "fr.a1.maison.005", kind: "sentence", level: "a1", theme: "maison", fr: "Il y a une table dans le salon.", en: "There is a table in the living room.", notes: "« salon » is masculine, so it takes « le ».", tags: ["home","articles"], drills: ["flashcard"], version: 1, cardType: "gapfill",
  },
  {
    id: "fr.a1.maison.124", kind: "sentence", level: "a1", theme: "maison", fr: "La cuisine est à côté du salon.", en: "The kitchen is next to the living room.", ipa: "/la kɥi.zin ɛ.t‿a ko.te dy sa.lɔ̃/", notes: "\"à\" (preposition, with accent) must not be confused with \"a\" (verb avoir), even though both sound the same.", tags: ["homophone"], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.maison.125", kind: "sentence", level: "a1", theme: "maison", fr: "Il y a un grand lit dans la chambre.", en: "There is a big bed in the bedroom.", ipa: "/il i a œ̃ ɡʁɑ̃ li dɑ̃ la ʃɑ̃bʁ/", notes: "The final \"d\" of \"grand\" and the final \"t\" of \"lit\" are both silent.", tags: ["silent-letter"], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.maison.129", kind: "sentence", level: "a1", theme: "maison", fr: "Le salon a deux fenêtres et une porte.", en: "The living room has two windows and one door.", ipa: "/lə sa.lɔ̃ a dø fə.nɛtʁ e yn pɔʁt/", notes: "\"et\" (and) sounds exactly like \"est\" (is), so context alone tells you which spelling to use.", tags: ["homophone"], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.maison.131", kind: "sentence", level: "a1", theme: "maison", fr: "Les rideaux sont bleus dans le salon.", en: "The curtains are blue in the living room.", ipa: "/le ʁi.do sɔ̃ blø dɑ̃ lə sa.lɔ̃/", notes: "The final \"x\" of \"rideaux\" and the final \"s\" of \"bleus\" are both silent plural markers.", tags: ["silent-letter"], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.maison.134", kind: "sentence", level: "a1", theme: "maison", fr: "La salle de bain est au bout du couloir.", en: "The bathroom is at the end of the hallway.", ipa: "/la sal də bɛ̃ ɛ.t‿o bu dy ku.lwaʁ/", notes: "\"bain\" is one single nasal sound, not \"ba\" plus a separate \"n\".", tags: ["nasal"], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.maison.137", kind: "sentence", level: "a1", theme: "maison", fr: "Le chat dort sur le grand lit blanc.", en: "The cat sleeps on the big white bed.", ipa: "/lə ʃa dɔʁ syʁ lə ɡʁɑ̃ li blɑ̃/", notes: "The final consonants of \"grand\" and \"blanc\" are silent unless a liaison occurs.", tags: ["silent-letter"], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.maison.141", kind: "sentence", level: "a1", theme: "maison", fr: "Il y a un canapé dans le salon.", en: "There is a sofa in the living room.", notes: "{\"tiles\":[{\"w\":\"Il y a\",\"t\":\"there is\"},{\"w\":\"un canapé\",\"t\":\"a sofa\"},{\"w\":\"dans le salon.\",\"t\":\"in the living room\"}]}", tags: [], drills: ["sentence","flashcard","review"], version: 1,
  },
  {
    id: "fr.a1.maison.144", kind: "sentence", level: "a1", theme: "maison", fr: "Nous avons deux chambres et une salle de bains.", en: "We have two bedrooms and a bathroom.", notes: "{\"tiles\":[{\"w\":\"Nous avons\",\"t\":\"we have\"},{\"w\":\"deux chambres\",\"t\":\"two bedrooms\"},{\"w\":\"et une salle de bains.\",\"t\":\"and a bathroom\"}]}", tags: [], drills: ["sentence","flashcard","review"], version: 1,
  },
  {
    id: "fr.a1.maison.145", kind: "sentence", level: "a1", theme: "maison", fr: "Le frigo est vide.", en: "The fridge is empty.", notes: "{\"tiles\":[{\"w\":\"Le frigo\",\"t\":\"the fridge\"},{\"w\":\"est\",\"t\":\"is\"},{\"w\":\"vide.\",\"t\":\"empty\"}]}", tags: [], drills: ["sentence","flashcard","review"], version: 1,
  },
  {
    id: "fr.a1.maison.152", kind: "sentence", level: "a1", theme: "maison", fr: "Le lit est près de la fenêtre.", en: "The bed is close to the window.", notes: "{\"tiles\":[{\"w\":\"Le lit\",\"t\":\"the bed\"},{\"w\":\"est près\",\"t\":\"is close\"},{\"w\":\"de la fenêtre.\",\"t\":\"to the window\"}]}", tags: [], drills: ["sentence","flashcard","review"], version: 1,
  },
  {
    id: "fr.a1.maison.155", kind: "sentence", level: "a1", theme: "maison", fr: "La salle de bains est au premier étage.", en: "The bathroom is on the first floor.", notes: "{\"tiles\":[{\"w\":\"La salle de bains\",\"t\":\"the bathroom\"},{\"w\":\"est\",\"t\":\"is\"},{\"w\":\"au premier étage.\",\"t\":\"on the first floor\"}]}", tags: [], drills: ["sentence","flashcard","review"], version: 1,
  },
];

/** Every imported id, in manifest order. */
export const IMPORTED_IDS: string[] = IMPORTED.map((r) => r.id);
