// GENERATED by scripts/_a213_manifest.ts on 2026-08-13. Do not edit by hand.
//
// A recorded read of the 20 rows a2.13 imports rather than authors, out of
// 11 themes, plus the 6 it reads and refuses and the 1 it deliberately
// does not release.
//
// NOT ONE INFINITIVE IN THIS LESSON IS AUTHORED. The Owns is that a modal lets a
// learner use a verb nobody taught them, so the corpus demonstrates the same
// claim the missions make.
//
// Two consumers need the whole row rather than the id:
//
//   author-modaux-batch.ts verifies every field against Postgres before it opens
//   a transaction, so a stale manifest cannot put the lesson ahead of rows nobody
//   has looked at.
//
//   merge-modaux-into-seed.ts CARRIES them into seed.json. The seed is a CUT, and
//   jardinage, argent-quotidien and rp-achats sit outside SEED_CUT.themes, so
//   without the carry the situation cards would draw empty on a device.
//
// THE REFUSED ROWS ARE NOT CARRIED AND NOT RELEASED. a2.10 settled the rule: a
// row a lesson does not teach is a display string at most, never a row in the hub.
//
// THE UNSEEN ROW IS NOT CARRIED EITHER, AND FOR A DIFFERENT REASON. `arroser` is
// the verb the generalisation mission hands the learner cold. The moment the
// lesson gives them a card for it, the lesson has taught it and the claim being
// tested is gone. It is here so the batch can check the respelling the mission
// prints against the database, and for nothing else.
//
// Regenerate with: pnpm tsx scripts/_a213_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 3 naming forms this lesson teaches, in learner order. All three share
 *  one theme, which a2.12's three did not. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.007", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "vouloir", en: "to want", ipa: "/vulwaʁ/", respell: "voo-LWAR", notes: "irregular · je veux, il veut, ils veulent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.006", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "pouvoir", en: "to be able to, can", ipa: "/puvwaʁ/", respell: "poo-VWAR", notes: "irregular · je peux, il peut, ils peuvent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.008", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "devoir", en: "to have to, must", ipa: "/dəvwaʁ/", respell: "duh-VWAR", notes: "irregular · je dois, il doit, nous devons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The 10 infinitives that follow a modal here. Every one imported. */
export const IMPORTED_INFINITIVE_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.059", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "payer", en: "to pay", ipa: "/peje/", respell: "pay-YAY", notes: "spelling change · je paie, nous payons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.rp-achats.019", kind: "word", level: "a2", theme: "rp-achats", fr: "commander", en: "to order", ipa: "/kɔ.mɑ̃.de/", respell: "koh-mahn-DAY", tags: ["verb","shopping"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.transports-quotidiens.046", kind: "word", level: "a1", theme: "transports-quotidiens", fr: "attendre", en: "to wait", ipa: "/a.tɑ̃dʁ/", respell: "ah-TAHN-druh", tags: ["verb","movement"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.courses.063", kind: "word", level: "a2", theme: "courses", fr: "choisir", en: "to choose", ipa: "/ʃwa.ziʁ/", respell: "shwa-ZEER", tags: ["verb","shopping"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.rp-repas.014", kind: "word", level: "a1", theme: "rp-repas", fr: "boire", en: "to drink", ipa: "/bwaʁ/", respell: "BWAHR", tags: ["verb","drink"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.argent-quotidien.061", kind: "word", level: "a1", theme: "argent-quotidien", fr: "acheter", en: "to buy", ipa: "/aʃ.te/", respell: "ahsh-TAY", tags: ["verb","shopping","money"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.amis.024", kind: "word", level: "a1", theme: "amis", fr: "aider", en: "to help", ipa: "/ɛ.de/", respell: "eh-DAY", notes: "Verb, regular er group.", tags: ["amis","verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.rp-achats.004", kind: "word", level: "a1", theme: "rp-achats", fr: "chercher", en: "to look for", ipa: "ʃɛʁ.ʃe", respell: "share-SHAY", notes: "", tags: ["verbe"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.routines.107", kind: "word", level: "a1", theme: "routines", fr: "conduire", en: "to drive", ipa: "/kɔ̃dɥiʁ/", respell: "kohn-DWEER", tags: ["verb","transport"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.transports-quotidiens.047", kind: "word", level: "a1", theme: "transports-quotidiens", fr: "arriver", en: "to arrive", ipa: "/a.ʁi.ve/", respell: "ah-ree-VAY", tags: ["verb","movement"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The 5 modal frames that already existed whole AND respelled, out of the
 *  628 that hold the shape and the 12 that carry a respelling. */
export const IMPORTED_SENTENCE_ROWS: Item[] = [
  { id: "fr.a2.verbes-essentiels.041", kind: "sentence", level: "a2", theme: "verbes-essentiels", fr: "Elle veut devenir médecin.", en: "She wants to become a doctor.", ipa: "/ɛl vø dəvniʁ medsɛ̃/", respell: "ell vuh duhv-NEER med-SAN", notes: "Conjugates like venir: je deviens, nous devenons.", tags: ["verbe","travail"], drills: ["flashcard","voiceflash","sentence","dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.verbes-essentiels.033", kind: "sentence", level: "a1", theme: "verbes-essentiels", fr: "Tu peux ouvrir la fenêtre, s'il te plaît ?", en: "Can you open the window, please?", ipa: "/ty pø uvʁiʁ la fənɛtʁ sil tə plɛ/", respell: "tew puh oov-REER lah fuh-NET seel tuh play", tags: ["verbe","modal"], drills: ["flashcard","voiceflash","sentence","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes-essentiels.040", kind: "sentence", level: "a2", theme: "verbes-essentiels", fr: "Nous devons partir avant midi.", en: "We must leave before noon.", ipa: "/nu dəvɔ̃ paʁtiʁ avɑ̃ midi/", respell: "noo duh-VOHN par-TEER ah-VAHN mee-DEE", tags: ["verbe","modal"], drills: ["flashcard","voiceflash","sentence","dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.cafe.173", kind: "sentence", level: "a1", theme: "cafe", fr: "Il faut réserver.", en: "You have to book.", ipa: "/il fo ʁe.zɛʁ.ve/", respell: "eel foh ray-zehr-VAY", notes: "il faut is how French says one has to. It never has a subject you could point at.", tags: ["pronoun","il","impersonal"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.liaisons.220", kind: "sentence", level: "sons", theme: "liaisons", fr: "Il faut aller plus vite.", en: "We need to go faster (casual).", ipa: "il fo a.le ply vit", respell: "EEL FOH a-LAY PLÜ VEET", notes: "faut aller is a classic optional link. Leave it and you sound normal.", tags: ["liaison-facultative","register-courant","pair-faut-aller"], drills: ["sentence","review"], audioRef: null, version: 1 },
];

/** The register pair. NEITHER ROW HAS A RESPELLING in the database; this build
 *  adds one to each, and the batch is the only place that happens. */
export const IMPORTED_REGISTER_ROWS: Item[] = [
  { id: "fr.a1.verbes-du-quotidien.035", kind: "sentence", level: "a1", theme: "verbes-du-quotidien", fr: "Je veux un café, s'il vous plaît.", en: "I want a coffee, please.", ipa: "ʒə vø.n‿œ̃ ka.fe, sil vu plɛ", notes: "“veux” ends in x, not the s one might expect.", tags: ["orthographe"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.cafe.051", kind: "sentence", level: "a1", theme: "cafe", fr: "Je voudrais un café, s'il vous plaît.", en: "I'd like a coffee, please.", notes: "{\"tiles\":[{\"w\":\"Je voudrais\",\"t\":\"I'd like\"},{\"w\":\"un café,\",\"t\":\"a coffee,\"},{\"w\":\"s'il vous plaît.\",\"t\":\"please\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
];

/** The 6 rows read and refused. READ ONLY: never carried, never released,
 *  never in itemIds, and named on no screen. */
export const READ_ONLY_ROWS: Item[] = [
  { id: "fr.a2.verbes-essentiels.013", kind: "sentence", level: "a2", theme: "verbes-essentiels", fr: "Je dois étudier pour mon examen demain.", en: "I have to study for my exam tomorrow.", ipa: "/ʒə dwa etydje puʁ mɔ̃n ɛgzamɛ̃ dəmɛ̃/", respell: "zhuh dwah ay-tew-DYAY poor mohn eg-zah-MAN duh-MAN", tags: ["verbe","ecole"], drills: ["flashcard","voiceflash","sentence","dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.voyelles.311", kind: "sentence", level: "sons", theme: "voyelles", fr: "Vous devez arriver au bureau avant neuf heures.", en: "You must arrive at the office before nine o'clock.", ipa: "vu də.ve a.ʁi.ve o by.ʁo a.vɑ̃ nœ.v‿œʁ", respell: "VOO duh-VAY a-ree-VAY OH bü-ROH a-VAHⁿ neu-v‿EUR", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, skill: "PE", register: "courant" },
  { id: "fr.a1.verbes-essentiels.079", kind: "sentence", level: "a1", theme: "verbes-essentiels", fr: "Nous voulons réserver une table pour deux.", en: "We want to book a table for two.", ipa: "nu vu.lɔ̃ ʁe.zɛʁ.ve yn tabl puʁ dø", notes: "The stem changes from \"veu\" to \"voul\" in the nous form.", tags: ["conjugaison"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes-du-quotidien.073", kind: "sentence", level: "a2", theme: "verbes-du-quotidien", fr: "Nous voudrions réserver une table pour deux.", en: "We would like to book a table for two.", notes: "{\"tiles\":[{\"w\":\"Nous voudrions\",\"t\":\"we would like\"},{\"w\":\"réserver\",\"t\":\"to book\"},{\"w\":\"une table pour deux.\",\"t\":\"a table for two\"}]}", tags: [], drills: ["sentence"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.009", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "savoir", en: "to know (a fact)", ipa: "/savwaʁ/", respell: "sah-VWAR", notes: "irregular · je sais, nous savons, ils savent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.088", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "nager", en: "to swim", ipa: "/naʒe/", respell: "nah-ZHAY", notes: "spelling change · nous nageons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The unseen verb. NOT AN IMPORT. Never in itemIds, never in a deck, never a
 *  term. Present so the batch can check what the mission prints. */
export const UNSEEN_VERB_ROW: Item[] = [
  { id: "fr.a1.jardinage.108", kind: "word", level: "a1", theme: "jardinage", fr: "arroser", en: "to water", ipa: "/a.ʁo.ze/", respell: "ah-roh-ZAY", tags: ["verb","gardening","action"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["vouloir", "fr.sons.verbes-essentiels.007"],
  ["pouvoir", "fr.sons.verbes-essentiels.006"],
  ["devoir", "fr.sons.verbes-essentiels.008"],
];

/** infinitive -> id, in the order the lesson meets them. */
export const INFINITIVE_ROW_IDS: [string, string][] = [
  ["payer", "fr.sons.verbes-essentiels.059"],
  ["commander", "fr.a2.rp-achats.019"],
  ["attendre", "fr.a1.transports-quotidiens.046"],
  ["choisir", "fr.a2.courses.063"],
  ["boire", "fr.a1.rp-repas.014"],
  ["acheter", "fr.a1.argent-quotidien.061"],
  ["aider", "fr.a1.amis.024"],
  ["chercher", "fr.a1.rp-achats.004"],
  ["conduire", "fr.a1.routines.107"],
  ["arriver", "fr.a1.transports-quotidiens.047"],
];

/** sentence -> id. */
export const SENTENCE_ROW_IDS: [string, string][] = [
  ["Elle veut devenir médecin.", "fr.a2.verbes-essentiels.041"],
  ["Tu peux ouvrir la fenêtre, s'il te plaît ?", "fr.a1.verbes-essentiels.033"],
  ["Nous devons partir avant midi.", "fr.a2.verbes-essentiels.040"],
  ["Il faut réserver.", "fr.a1.cafe.173"],
  ["Il faut aller plus vite.", "fr.sons.liaisons.220"],
];

/** register half -> id. */
export const REGISTER_ROW_IDS: [string, string][] = [
  ["Je veux un café, s'il vous plaît.", "fr.a1.verbes-du-quotidien.035"],
  ["Je voudrais un café, s'il vous plaît.", "fr.a1.cafe.051"],
];

/** And the refused pairing, kept apart so nothing can iterate both by accident. */
export const READ_ONLY_ROW_IDS: [string, string][] = [
  ["Je dois étudier pour mon examen demain.", "fr.a2.verbes-essentiels.013"],
  ["Vous devez arriver au bureau avant neuf heures.", "fr.sons.voyelles.311"],
  ["Nous voulons réserver une table pour deux.", "fr.a1.verbes-essentiels.079"],
  ["Nous voudrions réserver une table pour deux.", "fr.a2.verbes-du-quotidien.073"],
  ["savoir", "fr.sons.verbes-essentiels.009"],
  ["nager", "fr.sons.verbes-essentiels.088"],
];

/** Every id this lesson may put in `itemIds`. The unseen verb and the refused
 *  rows are deliberately absent, and the batch asserts that absence. */
export const IMPORTABLE_IDS: string[] = [
  "fr.sons.verbes-essentiels.007",
  "fr.sons.verbes-essentiels.006",
  "fr.sons.verbes-essentiels.008",
  "fr.sons.verbes-essentiels.059",
  "fr.a2.rp-achats.019",
  "fr.a1.transports-quotidiens.046",
  "fr.a2.courses.063",
  "fr.a1.rp-repas.014",
  "fr.a1.argent-quotidien.061",
  "fr.a1.amis.024",
  "fr.a1.rp-achats.004",
  "fr.a1.routines.107",
  "fr.a1.transports-quotidiens.047",
  "fr.a2.verbes-essentiels.041",
  "fr.a1.verbes-essentiels.033",
  "fr.a2.verbes-essentiels.040",
  "fr.a1.cafe.173",
  "fr.sons.liaisons.220",
  "fr.a1.verbes-du-quotidien.035",
  "fr.a1.cafe.051",
];

/** The themes these rows came out of. */
export const SOURCE_THEMES: string[] = ["amis","argent-quotidien","cafe","courses","liaisons","routines","rp-achats","rp-repas","transports-quotidiens","verbes-du-quotidien","verbes-essentiels"];
