// a1.18's IMPORTED and REUSED manifests: a RECORDED READ of Postgres taken on
// 2026-08-07 by scripts/_negation_manifest.ts, so the merge can write these rows
// into seed.json without a connection.
//
// NOTHING BELOW WAS RETYPED. Regenerate with:
//
//     pnpm tsx scripts/_negation_manifest.ts > scripts/data/_negation-manifest.gen.txt
//
// The batch compares every field against the live database before writing and
// dies if the manifest has drifted, because a stale manifest puts the seed ahead
// of rows nobody has looked at. Only the `why` lines on REUSED are written by
// hand; every other character is generated.
//
// ── Why eighteen rows have to be CARRIED ───────────────────────────────────
//
// `negation-et-restriction` IS NOT IN SEED_CUT.themes. It holds 604 published
// rows in Postgres and 0 in the seed, which is a VISIBILITY fact and not an
// emptiness one: exactly the situation a1.13 met with `couleurs` (322 published,
// 0 in the seed) and a1.10 met with `meteo`. Every row this lesson borrows from
// that theme, and from adjectifs-essentiels, rp-identite, expressions-utiles,
// mots-essentiels and the rest, is absent from the seed today and renders as an
// empty card unless the merge carries it.
//
// A MERGE THAT LEFT THE SEED UNCHANGED FOR THESE ROWS WOULD BE THE BUG.
//
// Split as the seed reported it, not as anyone guessed:
//
//     IMPORTED  18   published in Postgres, ABSENT from the seed
//     REUSED     6   published in Postgres, ALREADY in the seed, untouched
//
// ── The one row this lesson repairs ────────────────────────────────────────
//
// `fr.sons.mots-essentiels.043` is reproduced below with the BROKEN respelling
// it carries today (NOHN). It is repaired to NOHⁿ by RESPELL_REPAIRS in
// negation-corpus.ts rather than tidied here, because the batch compares this
// manifest field by field against the database and a corrected value would read
// as drift and stop the run.
//
// Its own `notes` field already says "Nasal vowel, do not pronounce a hard n at
// the end", which is exactly what NOHN instructs an English reader to do. The
// card has been contradicting itself since it was written.
//
// ── What is NOT here, and why ──────────────────────────────────────────────
//
// `pas` as a headword. The only published row is fr.sons.noms-essentiels.179
// « le pas », a masculine noun meaning "the step" and a homograph of this
// lesson's particle. Importing it would put a card reading "the step" into a
// negation deck. `pas` is displayed here as a respelling and taught as half of
// a wrap, never as a word with a meaning of its own.
//
// `jamais`, `rien` and `personne`. All three exist as headwords (jamais in
// three themes, rien in two, personne in three) and all three belong to
// constructions this lesson's canDo excludes. See NOT_REPAIRED in
// negation-corpus.ts for the respelling conflicts they carry, which are
// reported and deliberately not fixed.
//
// The 25 rows of this lesson's own theme slice that are outside its canDo,
// including the three imperatives at .018, .019 and .020. Enumerated in the
// header of negation-corpus.ts.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export type ImportedRow = Item;

// generated by scripts/_negation_manifest.ts, do not edit by hand
// 24 rows: 18 IMPORTED (absent from the seed), 6 REUSED (already in it)

export const IMPORTED: ImportedRow[] = [
  // Ce chien n'est pas méchant. A clean être predicate with no article in it at all, which is the wrap on its own.
  {
    id: "fr.a1.adjectifs-essentiels.187", kind: "sentence", level: "a1", theme: "adjectifs-essentiels",
    fr: "Ce chien n'est pas méchant.", en: "This dog is not mean.",
    ipa: "sə ʃjɛ̃ nɛ pa me.ʃɑ̃",
    notes: "'Méchant' follows 'n'est pas' describing the dog.",
    tags: ["grammaire"], drills: ["dictation"], version: 1,
  },
  // c'est pas donné. The dropped ne, published, and the only a1 attestation of it anywhere.
  {
    id: "fr.a1.argot-du-quotidien.042", kind: "phrase", level: "a1", theme: "argot-du-quotidien",
    fr: "c'est pas donné", en: "it's not cheap",
    ipa: "/sɛ pa dɔ.ne/",
    respell: "SEH PA do-NAY",
    notes: "Familier for c'est cher, it is pricey. Literally: it is not given away.",
    tags: ["argot"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  // Nous n'avons pas de fruits frais. The collapse on nous, which the authored pairs do not cover.
  {
    id: "fr.a1.douane-et-immigration.188", kind: "sentence", level: "a1", theme: "douane-et-immigration",
    fr: "Nous n'avons pas de fruits frais.", en: "We do not have any fresh fruit.",
    ipa: "nu na.vɔ̃ pa də fʁɥi fʁɛ",
    notes: "\"frais\" ends in a silent s, homophone trap with \"frai\".",
    tags: [], drills: ["dictation"], version: 1,
  },
  // Bien sûr que non, ce n'est pas grave. non answering, and ne inside the sentence, three words apart.
  {
    id: "fr.a1.expressions-frequentes.029", kind: "sentence", level: "a1", theme: "expressions-frequentes",
    fr: "Bien sûr que non, ce n'est pas grave.", en: "Of course not, it's not a big deal.",
    ipa: "bjɛ̃ syʁ kə nɔ̃, sə nɛ pa gʁav",
    notes: "“Grave” ends in a silent final “e” that does not change its pronunciation.",
    tags: ["silent-letter"], drills: ["dictation"], version: 1,
  },
  // Je n'aime pas le café. Moi non plus. Carries the le survival AND the reply, which is the whole of act 5's second half.
  {
    id: "fr.a1.expressions-utiles.095", kind: "sentence", level: "a1", theme: "expressions-utiles",
    fr: "Je n'aime pas le café. Moi non plus.", en: "I don't like coffee. Me neither.",
    ipa: "ʒə nɛm pa lə ka.fe mwa nɔ̃ ply",
    notes: "\"Non plus\" pairs with a negative statement; it never follows a positive one.",
    tags: ["fixed-expression"], drills: ["dictation"], version: 1,
  },
  // Il n'est pas triste, au contraire il est très content. The negative and its positive answer in one line.
  {
    id: "fr.a1.mots-de-liaison.025", kind: "sentence", level: "a1", theme: "mots-de-liaison",
    fr: "Il n'est pas triste, au contraire il est très content.", en: "He's not sad, on the contrary he's very happy.",
    ipa: "il nɛ pa tʁist o kɔ̃.tʁɛʁ i.lɛ tʁɛ kɔ̃.tɑ̃",
    notes: "\"Au contraire\" oppose totalement deux idées, plus fort que \"par contre\".",
    tags: ["grammaire"], drills: ["dictation"], version: 1,
  },
  // Je ne parle pas allemand. Reading only: parler is a2.01 and this lesson never asks for it.
  {
    id: "fr.a1.negation-et-restriction.002", kind: "sentence", level: "a1", theme: "negation-et-restriction",
    fr: "Je ne parle pas allemand.", en: "I do not speak German.",
    tags: ["negation","ne-pas"], drills: ["flashcard","sentence"], version: 1,
  },
  // Nous n'habitons pas à Lyon. Reading only. The wrap on a plural person with no article anywhere.
  {
    id: "fr.a1.negation-et-restriction.006", kind: "sentence", level: "a1", theme: "negation-et-restriction",
    fr: "Nous n'habitons pas à Lyon.", en: "We do not live in Lyon.",
    notes: "Ne becomes n' before a vowel sound.",
    tags: ["negation","ne-pas","elision"], drills: ["flashcard","sentence","dictation"], version: 1,
  },
  // Je n'ai pas de stylo. The cleanest row in this lesson's own theme slice and one of only two in its canDo.
  {
    id: "fr.a1.negation-et-restriction.021", kind: "sentence", level: "a1", theme: "negation-et-restriction",
    fr: "Je n'ai pas de stylo.", en: "I don't have a pen.",
    ipa: "/ʒə nɛ pa də sti.lo/",
    notes: "The elided n' before ai must be written even though it almost disappears in fast speech.",
    tags: ["elision"], drills: ["dictation"], version: 1,
  },
  // Elle ne mange pas de viande. Reading only, and it shows the collapse working on a verb outside avoir.
  {
    id: "fr.a1.negation-et-restriction.022", kind: "sentence", level: "a1", theme: "negation-et-restriction",
    fr: "Elle ne mange pas de viande.", en: "She doesn't eat meat.",
    ipa: "/ɛl nə mɑ̃ʒ pa də vjɑ̃d/",
    notes: "The ne before mange is barely audible but still required in writing.",
    tags: ["silent-letter"], drills: ["dictation"], version: 1,
  },
  // Nous n'avons pas faim. The other one. No article, so nothing collapses, which a1.07 taught on je.
  {
    id: "fr.a1.negation-et-restriction.023", kind: "sentence", level: "a1", theme: "negation-et-restriction",
    fr: "Nous n'avons pas faim.", en: "We are not hungry.",
    ipa: "/nu na.vɔ̃ pa fɛ̃/",
    notes: "Faim ends in a nasal vowel sound with no audible consonant, so listen for the nasal quality rather than a final letter.",
    tags: ["nasal"], drills: ["dictation"], version: 1,
  },
  // Il n'aime pas le café. The same le survival on a third person, in this lesson's own theme.
  {
    id: "fr.a1.negation-et-restriction.025", kind: "sentence", level: "a1", theme: "negation-et-restriction",
    fr: "Il n'aime pas le café.", en: "He doesn't like coffee.",
    ipa: "/il nɛm pa lə ka.fe/",
    notes: "N'aime elides ne before the vowel of aime, so remember the apostrophe when writing.",
    tags: ["elision"], drills: ["dictation"], version: 1,
  },
  // Je n'ai pas d'enfants. de becoming d' in front of a vowel, attested rather than authored.
  {
    id: "fr.a1.presentation-personnelle.049", kind: "sentence", level: "a1", theme: "presentation-personnelle",
    fr: "Je n'ai pas d'enfants.", en: "I do not have any children.",
    ipa: "ʒə ne pa dɑ̃.fɑ̃",
    notes: "“de” elides to “d'” before the vowel in this negative sentence.",
    tags: ["elision"], drills: ["dictation"], version: 1,
  },
  // Je ne suis pas espagnol, je suis portugais. The je form of être negated, which returns 35 rows in total and 5 at a1.
  {
    id: "fr.a1.rp-identite.027", kind: "sentence", level: "a1", theme: "rp-identite",
    fr: "Je ne suis pas espagnol, je suis portugais.", en: "I'm not Spanish, I'm Portuguese.",
    notes: "négation ne...pas + correction",
    tags: ["nationalité","malentendu"], drills: ["dictation"], version: 1,
  },
  // Non, je ne suis pas mariée, je suis fiancée. Carries non AND ne in one sentence, which is the pair learners merge.
  {
    id: "fr.a1.rp-identite.057", kind: "sentence", level: "a1", theme: "rp-identite",
    fr: "Non, je ne suis pas mariée, je suis fiancée.", en: "No, I'm not married, I'm engaged.",
    notes: "accord féminin : mariée, fiancée",
    tags: ["malentendu","famille"], drills: ["dictation"], version: 1,
  },
  // Non, ce n'est pas mon mari, c'est mon frère. ce n'est pas with a possessive after it, so no article moves.
  {
    id: "fr.a1.rp-identite.058", kind: "sentence", level: "a1", theme: "rp-identite",
    fr: "Non, ce n'est pas mon mari, c'est mon frère.", en: "No, that's not my husband, that's my brother.",
    notes: "ce n'est pas / c'est, correction",
    tags: ["malentendu","famille"], drills: ["dictation"], version: 1,
  },
  // non, and this lesson REPAIRS its respelling from NOHN to NOHⁿ. The word learners merge with ne.
  {
    id: "fr.sons.mots-essentiels.043", kind: "word", level: "sons", theme: "mots-essentiels",
    fr: "non", en: "no",
    ipa: "/nɔ̃/",
    respell: "NOHN",
    notes: "Nasal vowel, do not pronounce a hard n at the end.",
    tags: ["adverb"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  // ne, the particle itself, already published with the respelling this lesson agrees with.
  {
    id: "fr.sons.voyelles.182", kind: "word", level: "sons", theme: "voyelles",
    fr: "ne", en: "not",
    ipa: "nə",
    respell: "nuh",
    tags: ["schwa"], drills: ["voiceflash","review"], version: 1,
  },
];

export const REUSED: { id: string; fr: string; en: string; why: string }[] = [
  { id: "fr.a1.au-restaurant.189", fr: "Je ne mange pas de viande.", en: "I don't eat meat.",
    why: "Je ne mange pas de viande. The same, and the one the brief quotes." },
  { id: "fr.a1.cuisine.264", fr: "Je ne mange pas de pain.", en: "I do not eat bread.",
    why: "Je ne mange pas de pain. a1.29's partitive row, in the seed, and reading exposure here." },
  { id: "fr.a1.famille.234", fr: "Je n'ai pas faim.", en: "I am not hungry.",
    why: "Je n'ai pas faim. a1.07 authored it and teaches it. Named here as the bridge, and NOT re-authored." },
  { id: "fr.a1.famille.246", fr: "Je n'ai pas de frère.", en: "I do not have a brother.",
    why: "Je n'ai pas de frère. a1.07's row. This lesson authors its own positive/negative PAIR rather than reusing it alone." },
  { id: "fr.a1.jours-et-mois.022", fr: "Ce n'est pas lundi, c'est mardi.", en: "It's not Monday, it's Tuesday.",
    why: "Ce n'est pas lundi, c'est mardi. ce n'est pas already in the seed, from a1.09." },
  { id: "fr.a1.objets.153", fr: "Elle n'a pas de portable.", en: "She does not have a cell phone.",
    why: "Elle n'a pas de portable. a1.11's row, the collapse on elle." },
];
