// a1.23's IMPORTED and REUSED manifests: a RECORDED READ of Postgres taken on
// 2026-08-07 by scripts/_nourriture_imported_gen.ts, so the merge can write
// these rows into seed.json without a connection.
//
// NOTHING BELOW WAS RETYPED. Regenerate with:
//
//     pnpm tsx scripts/_nourriture_imported_gen.ts
//
// The batch compares every field against the live database before writing and
// dies if the manifest has drifted, because a stale manifest puts the seed ahead
// of rows nobody has looked at.
//
// ── Why the import is only eight rows ──────────────────────────────────────
//
// a1.22 had to carry FORTY, because `pays-et-nationalites` sits outside
// SEED_CUT.themes and every row it named was absent from the seed. This lesson
// is the opposite case and it is worth stating plainly, because the reflex
// after reading a1.22's manifest is to assume a large carry.
//
// Both of a1.23's themes are INSIDE the cut:
//
//     cuisine   425 published / 425 in the seed
//     marche    343 published / 343 in the seed
//
// So 52 of the 60 food cards are already in the binary and need nothing. Only
// these eight are outside:
//
//     7 from `au-restaurant`   346 published / 10 in the seed
//     1 from `mots-essentiels` outside the cut entirely
//
// The ten `au-restaurant` rows already in the seed are there because a1.29
// names nine of them: publish pulls lesson-referenced items into the cut even
// when their theme is not listed. That is the same mechanism carrying these
// seven, and it is why naming a row is enough and copying it into `cuisine`
// would be wrong.
//
// ── Nineteen sentences are REUSED, not imported ────────────────────────────
//
// The whole aimer/manger contrast is built from rows that are ALREADY in the
// seed, by authors who were not teaching this. That is the strongest evidence
// the lesson has: the contrast is a property of French as this corpus records
// it, not a pattern invented to justify a lesson. See REUSED below.
//
// ── The imported respellings are reproduced AS THEY ARE ────────────────────
//
// `luh VAN` (le vin) and `sahnd-WEETCH` are below with the values they carry
// today. They are repaired by RESPELL_REPAIRS in nourriture-corpus.ts rather
// than tidied here, because the batch compares this manifest field by field
// against the database and a corrected value would read as drift and stop the
// run. Same reasoning as pays-imported.ts.
//
// ── One imported row has no `cardType` ─────────────────────────────────────
//
// `fr.a1.mots-essentiels.004` (le chocolat) carries no `card_type` in Postgres
// where the other seven carry `vocab`. Imported exactly as stored rather than
// normalised: it is another author's row, the field is optional in the schema,
// and inventing a value here would be a silent edit that the batch's own drift
// check could never catch.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export type ImportedRow = Item;

/* GENERATED by scripts/_nourriture_imported_gen.ts. Do not hand-edit. */
export const IMPORTED: ImportedRow[] = [

  // ── drinks the cuisine theme does not hold (2) ──
  {
    id: "fr.a1.au-restaurant.007", kind: "word", level: "a1", theme: "au-restaurant", fr: "le vin", en: "the wine", ipa: "/lə vɛ̃/", respell: "luh VAN", gender: "m", tags: ["restaurant", "boisson"], drills: ["flashcard", "voiceflash"], version: 1, cardType: "vocab", notes: "Vin rouge, vin blanc, vin rosé.",
  },
  {
    id: "fr.a1.au-restaurant.008", kind: "word", level: "a1", theme: "au-restaurant", fr: "la bière", en: "the beer", ipa: "/la bjɛʁ/", respell: "lah BYEHR", gender: "f", tags: ["restaurant", "boisson"], drills: ["flashcard", "voiceflash"], version: 1, cardType: "vocab", notes: "Une pression is a draft beer.",
  },

  // ── the coffee and tea the whole contrast is built on (2) ──
  //
  // `le café` is served rather than fr.a1.cafe.009 « un café » because the
  // contrast in act 3 needs the DEFINITE article on the card: « J'aime le café »
  // against « Je bois du café ». An indefinite headword would put a third
  // article on a screen whose entire job is to hold two apart.
  {
    id: "fr.a1.au-restaurant.081", kind: "word", level: "a1", theme: "au-restaurant", fr: "le café", en: "the coffee", ipa: "/ka.fe/", respell: "luh kah-FAY", gender: "m", tags: ["noun", "drink"], drills: ["flashcard", "voiceflash", "review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.au-restaurant.082", kind: "word", level: "a1", theme: "au-restaurant", fr: "le thé", en: "the tea", ipa: "/te/", respell: "luh TAY", gender: "m", tags: ["noun", "drink"], drills: ["flashcard", "voiceflash", "review"], version: 1, cardType: "vocab",
  },

  // ── three foods with no cuisine row at all (3) ──
  {
    id: "fr.a1.au-restaurant.069", kind: "word", level: "a1", theme: "au-restaurant", fr: "les frites", en: "the fries", ipa: "/fʁit/", respell: "lay FREET", gender: "f", tags: ["noun", "food"], drills: ["flashcard", "voiceflash", "review"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.au-restaurant.077", kind: "word", level: "a1", theme: "au-restaurant", fr: "le fruit", en: "the fruit", ipa: "/fʁɥi/", respell: "luh FRWEE", gender: "m", tags: ["noun", "food"], drills: ["flashcard", "voiceflash", "review"], version: 1, cardType: "vocab",
  },
  // Served rather than fr.a1.cuisine.013 « un œuf » for the same reason as
  // `le café`: this lesson's headword shape is definite, and l'œuf also earns
  // its place in the l' group, where the elided article hides the gender.
  {
    id: "fr.a1.au-restaurant.088", kind: "word", level: "a1", theme: "au-restaurant", fr: "l'œuf", en: "the egg", ipa: "/œf/", respell: "LUF", gender: "m", tags: ["noun", "food"], drills: ["flashcard", "voiceflash", "review"], version: 1, cardType: "vocab",
  },

  // ── chocolate, which exists nowhere near the food themes (1) ──
  {
    id: "fr.a1.mots-essentiels.004", kind: "word", level: "a1", theme: "mots-essentiels", fr: "le chocolat", en: "the chocolate", ipa: "/ʃɔkɔla/", respell: "shoh-koh-LAH", gender: "m", tags: ["food"], drills: ["flashcard", "voiceflash"], version: 1, notes: "Final 't' is silent.",
  },
];

export const IMPORTED_IDS: string[] = IMPORTED.map((i) => i.id);

/** Published, ALREADY in the seed, and displayed unchanged. The `why` lines are
 *  the only hand-written characters in this file. */
export const REUSED: { id: string; fr: string; en: string; why: string }[] = [

  // ── THE PAIR. One noun, two verbs, two articles, two authors, two themes ──
  {
    id: 'fr.a1.cafe.149', fr: "J'aime le café.", en: 'I like coffee.',
    why: 'THE LIKE COLUMN OF THE WHOLE LESSON. Written by whoever built the cafe theme, with no thought of a '
      + 'contrast, which is exactly what makes it evidence rather than illustration.',
  },
  {
    id: 'fr.a1.cuisine.268', fr: 'Je bois du café.', en: 'I drink coffee.',
    why: 'THE EAT COLUMN, on the same noun, from a1.29\'s partitive block. Borrowed for the contrast screen '
      + 'and deliberately NOT released to spaced repetition, because a1.29 owns it.',
  },

  // ── the negation pair, which neither upstream lesson could show ──
  {
    id: 'fr.a1.cafe.150', fr: "Je n'aime pas le café.", en: 'I do not like coffee.',
    why: 'le SURVIVES the negative after aimer. a1.18 taught ne...pas and a1.29 taught the collapse to de, and '
      + 'neither could show this, because neither had both columns.',
  },
  {
    id: 'fr.a1.cuisine.264', fr: 'Je ne mange pas de pain.', en: 'I do not eat bread.',
    why: 'and du COLLAPSES to de after manger. The two rows side by side are the deeper half of the lesson. '
      + 'a1.29\'s row, borrowed and not re-released.',
  },

  // ── the like column, widened past one verb and one person ──
  {
    id: 'fr.a1.cuisine.192', fr: 'Les enfants aiment les pâtes au fromage.', en: 'The children like pasta with cheese.',
    why: 'aimer in the plural, with a plural-only food, still taking the definite article.',
  },
  {
    id: 'fr.a1.cuisine.257', fr: 'Il aime les plats épicés.', en: 'He likes spicy dishes.',
    why: 'third person, and les rather than le, so the rule is not read as a first-person habit.',
  },
  {
    id: 'fr.a1.cuisine.258', fr: 'Je préfère les légumes frais aux légumes surgelés.', en: 'I prefer fresh vegetables to frozen vegetables.',
    why: 'préférer behaving exactly like aimer, which is what makes this a class of verbs rather than one word.',
  },
  {
    id: 'fr.a1.marche.118', fr: 'Les enfants aiment les fraises sucrées.', en: 'The children love sweet strawberries.',
    why: 'the same shape from the OTHER theme this unit now declares, which is part of why marche was bound in.',
  },
  {
    id: 'fr.a1.marche.159', fr: 'Je préfère les légumes bio.', en: 'I prefer organic vegetables.',
    why: 'préférer again, in marche.',
  },
  {
    id: 'fr.a1.questions.077', fr: 'Est-ce que tu préfères le thé ou le café ?', en: 'Do you prefer tea or coffee?',
    why: 'the like column inside a question, using a1.19\'s est-ce que. The reading passage needs one question '
      + 'that is not this lesson\'s own invention.',
  },
  {
    id: 'fr.sons.liaisons.139', fr: 'Nous aimons le café.', en: 'We love coffee.',
    why: 'first person plural, and a sons-track row, so the evidence is not all from one band.',
  },
  {
    id: 'fr.sons.voyelles.424', fr: 'Elle préfère le thé léger.', en: 'She prefers weak tea.',
    why: 'préférer with thé, the other drink the contrast screen uses.',
  },

  // ── the eat column, across persons and both verbs ──
  {
    id: 'fr.a1.cuisine.007', fr: 'Je mange du pain.', en: 'I eat bread.',
    why: 'the plainest possible eat-column row, and the one the scene ends on.',
  },
  {
    id: 'fr.a1.cuisine.004', fr: 'Je bois du café le matin.', en: 'I drink coffee in the morning.',
    why: 'boire with a time phrase, so the partitive is seen inside an ordinary sentence rather than a frame.',
  },
  {
    id: 'fr.a1.cuisine.189', fr: 'Nous mangeons du pain frais chaque matin.', en: 'We eat fresh bread every morning.',
    why: 'first person plural, and an adjective agreeing behind the partitive.',
  },
  {
    id: 'fr.a1.cuisine.205', fr: 'Vous mangez du poulet rôti ce soir.', en: 'You are eating roast chicken tonight.',
    why: 'second person plural. Between this and the rows above, manger is seen in four of its six persons '
      + 'without this lesson conjugating anything, which is a2.02\'s job.',
  },
  {
    id: 'fr.a1.cuisine.209', fr: 'Ils mangent des légumes verts chaque soir.', en: 'They eat green vegetables every evening.',
    why: 'des with a plural food, the third shape of the partitive, third person plural.',
  },
  {
    id: 'fr.a1.routines.161', fr: 'Nous mangeons du pain avec du beurre.', en: 'We eat bread with butter.',
    why: 'TWO partitives in one sentence, on two different foods, which is what an ordinary meal sentence '
      + 'actually looks like.',
  },
  {
    id: 'fr.sons.liaisons.122', fr: 'On mange des œufs et du pain le matin.', en: 'We eat eggs and bread in the morning.',
    why: 'des and du in one sentence, with the liaison on « des œufs » that sons.10 already teaches.',
  },
];

export const REUSED_IDS: string[] = REUSED.map((r) => r.id);

/** Everything this lesson names that lives outside its own two themes, imported
 *  or reused. The merge reports this so the carry is never silent. */
export const ALL_BORROWED_IDS: string[] = [...IMPORTED_IDS, ...REUSED_IDS];
