// A RECORDED READ OF POSTGRES. Generated by scripts/_a220_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 39 rows imported out of 12 themes.
// 7 rows read and refused; see READ_NOT_IMPORTED in the corpus file.
// 1 respelling repaired, 0 supplied.
// 7 rows found broken and left alone; 7 of them still are.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   THE SPLIT              0 REGULAR past forms exist as headwords.
//                          28 of this lesson's thirty-three exist as bare rows.
//                          4 of those are glossed AS a past form, and
//                          0 of THOSE carry a respelling.
//                          That last figure is the whole argument: a bare past
//                          form reaches a card the learner cannot say. Settled by
//                          a2.05, agreed here. Corpus file §1.
//
//   the evidence           1435 published sentences put one of the thirty-three
//                          behind a first word. The eight commonest:
//     été           286
//     pris          174
//     dû            132
//     fait          109
//     reçu           90
//     eu             78
//     mis            61
//     ouvert         58
//
//   a2.13 §1               2 of them are CARDS: a1 or a2, respelled, in a
//                          sentence. Evidence is not cards, and the pool this
//                          lesson could import from was 2, not 1435.
//     fr.a2.au-restaurant.061                « C'est fait maison ? »
//     fr.a2.expressions-argot.003            « c'est mort »
//
//   the two derived-only   refait: 2 occurrences, naming form absent
//                          aperçu: 0 occurrences, naming form absent
//                          Both are named on the reference sheet as members of a
//                          group they were never taught in, and refait is one of
//                          the two forms the exam asks for cold.
//
// THE BLOCK: fr.a2.verbes held 439 rows before this build and holds
// 439 now. Rows inside fr.a2.verbes.591..fr.a2.verbes.650 that this
// build does not own: none.
// a2.05's block fr.a2.verbes.541..fr.a2.verbes.590 holds 36 rows, which is
// exactly what that lesson applied. Neither side re-authored the other's.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const PARTICIPES_ROWS: Record<string, Item> = {
  'fr.a1.cuisine.042':   { id: "fr.a1.cuisine.042", kind: "word", level: "a1", theme: "cuisine", fr: "boire", en: "to drink", respell: "BWAHR", tags: ["verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.dictee.091':   { id: "fr.a1.dictee.091", kind: "word", level: "a1", theme: "dictee", fr: "lire", en: "to read", ipa: "liʁ", respell: "LEER", example: {"en":"We are going to read the sentence out loud.","fr":"Nous allons lire la phrase à voix haute."}, tags: [], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  'fr.a1.emotions.034':   { id: "fr.a1.emotions.034", kind: "phrase", level: "a1", theme: "emotions", fr: "mort de rire", en: "dying of laughter", ipa: "mɔʁ də ʁiʁ", respell: "MOR duh REER", notes: "Origin of the French texting abbreviation MDR, the equivalent of LOL.", tags: ["emotions","idioms"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.meteo.062':   { id: "fr.a1.meteo.062", kind: "word", level: "a1", theme: "meteo", fr: "couvert", en: "overcast", ipa: "/kuvɛʁ/", respell: "koo-VEHR", notes: "Literally covered; le ciel est couvert means the sky is grey.", tags: ["weather","adjective"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.107':   { id: "fr.a1.routines.107", kind: "word", level: "a1", theme: "routines", fr: "conduire", en: "to drive", ipa: "/kɔ̃dɥiʁ/", respell: "kohⁿ-DWEER", tags: ["verb","transport"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a2.courses.070':   { id: "fr.a2.courses.070", kind: "word", level: "a2", theme: "courses", fr: "ouvert", en: "open", ipa: "/u.vɛʁ/", respell: "oo-VEHR", tags: ["adjective","shopping"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a2.disciplines.051':   { id: "fr.a2.disciplines.051", kind: "word", level: "a2", theme: "disciplines", fr: "apprendre", en: "to learn", ipa: "a.pʁɑ̃dʁ", respell: "a-PRAHⁿDR", example: {"en":"I've been learning French for a year.","fr":"J'apprends le français depuis un an."}, tags: [], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  'fr.a2.examens-et-diplomes.045':   { id: "fr.a2.examens-et-diplomes.045", kind: "word", level: "a2", theme: "examens-et-diplomes", fr: "écrit", en: "written", ipa: "e.kʁi", respell: "ay-KREE", example: {"en":"The written exam lasts two hours.","fr":"L'examen écrit dure deux heures."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.a2.verbes.423':   { id: "fr.a2.verbes.423", kind: "word", level: "a2", theme: "verbes", fr: "remettre", en: "to put back, to hand in", ipa: "/ʁəmɛtʁ/", respell: "ruh-MEHTR", notes: "irregular · takes every ending mettre takes", tags: ["irregular","verb","family"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.b1.verbes.054':   { id: "fr.b1.verbes.054", kind: "word", level: "b1", theme: "verbes", fr: "souffrir", en: "to suffer", ipa: "su.fʁiʁ", respell: "soo-FREER", example: {"en":"He has been suffering from back pain for several weeks.","fr":"Il souffre de maux de dos depuis plusieurs semaines."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.sons.adjectifs-essentiels.082':   { id: "fr.sons.adjectifs-essentiels.082", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "cru", en: "raw", ipa: "kʁy", respell: "KRÜ", notes: "Feminine: crue, same sound. Des carottes crues, raw carrots.", tags: ["adjective","food"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.adjectifs-essentiels.161':   { id: "fr.sons.adjectifs-essentiels.161", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "mort", en: "dead", ipa: "/mɔʁ/", respell: "MOR", notes: "Feminine: morte.", tags: ["adjective"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.consonnes.110':   { id: "fr.sons.consonnes.110", kind: "word", level: "sons", theme: "consonnes", fr: "écrire", en: "to write", ipa: "/e.kʁiʁ/", respell: "ay-KREER", tags: ["r","r-cluster","r-final","c-hard"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.sons.verbes-essentiels.001':   { id: "fr.sons.verbes-essentiels.001", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "être", en: "to be", ipa: "/ɛtʁ/", respell: "ETR", notes: "irregular · je suis, tu es, il est, nous sommes", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.002':   { id: "fr.sons.verbes-essentiels.002", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "avoir", en: "to have", ipa: "/avwaʁ/", respell: "ah-VWAR", notes: "irregular · j'ai, tu as, il a, nous avons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.004':   { id: "fr.sons.verbes-essentiels.004", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "faire", en: "to do, to make", ipa: "/fɛʁ/", respell: "FEHR", notes: "irregular · je fais, nous faisons, ils font", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.005':   { id: "fr.sons.verbes-essentiels.005", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "dire", en: "to say, to tell", ipa: "/diʁ/", respell: "DEER", notes: "irregular · je dis, vous dites, ils disent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.006':   { id: "fr.sons.verbes-essentiels.006", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "pouvoir", en: "to be able to, can", ipa: "/puvwaʁ/", respell: "poo-VWAR", notes: "irregular · je peux, il peut, ils peuvent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.007':   { id: "fr.sons.verbes-essentiels.007", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "vouloir", en: "to want", ipa: "/vulwaʁ/", respell: "voo-LWAR", notes: "irregular · je veux, il veut, ils veulent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.008':   { id: "fr.sons.verbes-essentiels.008", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "devoir", en: "to have to, must", ipa: "/dəvwaʁ/", respell: "duh-VWAR", notes: "irregular · je dois, il doit, nous devons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.009':   { id: "fr.sons.verbes-essentiels.009", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "savoir", en: "to know (a fact)", ipa: "/savwaʁ/", respell: "sah-VWAR", notes: "irregular · je sais, nous savons, ils savent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.010':   { id: "fr.sons.verbes-essentiels.010", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "venir", en: "to come", ipa: "/vəniʁ/", respell: "vuh-NEER", notes: "irregular · je viens, nous venons, ils viennent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.011':   { id: "fr.sons.verbes-essentiels.011", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "voir", en: "to see", ipa: "/vwaʁ/", respell: "VWAR", notes: "irregular · je vois, nous voyons, ils voient", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.012':   { id: "fr.sons.verbes-essentiels.012", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "prendre", en: "to take", ipa: "/pʁɑ̃dʁ/", respell: "PRAHⁿDR", notes: "irregular · je prends, nous prenons, ils prennent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.014':   { id: "fr.sons.verbes-essentiels.014", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "mettre", en: "to put", ipa: "/mɛtʁ/", respell: "METR", notes: "irregular · je mets, nous mettons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.030':   { id: "fr.sons.verbes-essentiels.030", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "comprendre", en: "to understand", ipa: "/kɔ̃pʁɑ̃dʁ/", respell: "kohⁿ-PRAHⁿDR", notes: "irregular · conjugates like prendre", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.034':   { id: "fr.sons.verbes-essentiels.034", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "ouvrir", en: "to open", ipa: "/uvʁiʁ/", respell: "oo-VREER", notes: "irregular · conjugates like an -er verb: j'ouvre", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.045':   { id: "fr.sons.verbes-essentiels.045", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "courir", en: "to run", ipa: "/kuʁiʁ/", respell: "koo-REER", notes: "irregular · je cours, nous courons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.047':   { id: "fr.sons.verbes-essentiels.047", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "recevoir", en: "to receive", ipa: "/ʁəsəvwaʁ/", respell: "ruh-suh-VWAR", notes: "irregular · je reçois, nous recevons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.048':   { id: "fr.sons.verbes-essentiels.048", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "connaître", en: "to know (people, places)", ipa: "/kɔnɛtʁ/", respell: "koh-NEHTR", notes: "irregular · je connais, nous connaissons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.049':   { id: "fr.sons.verbes-essentiels.049", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "croire", en: "to believe", ipa: "/kʁwaʁ/", respell: "KRWAR", notes: "irregular · je crois, nous croyons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.052':   { id: "fr.sons.verbes-essentiels.052", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "tenir", en: "to hold", ipa: "/təniʁ/", respell: "tuh-NEER", notes: "irregular · je tiens, conjugates like venir", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.053':   { id: "fr.sons.verbes-essentiels.053", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "offrir", en: "to offer, to give (a gift)", ipa: "/ɔfʁiʁ/", respell: "oh-FREER", notes: "irregular · conjugates like an -er verb: j'offre", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.081':   { id: "fr.sons.verbes-essentiels.081", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "naître", en: "to be born", ipa: "/nɛtʁ/", respell: "NEHTR", notes: "irregular · je suis né, I was born", tags: ["irregular","re-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.082':   { id: "fr.sons.verbes-essentiels.082", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "mourir", en: "to die", ipa: "/muʁiʁ/", respell: "moo-REER", notes: "irregular · je meurs, nous mourons", tags: ["irregular","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.100':   { id: "fr.sons.verbes-essentiels.100", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "s'asseoir", en: "to sit down", ipa: "/saswaʁ/", respell: "sah-SWAHR", notes: "irregular reflexive · je m'assois, asseyez-vous", tags: ["irregular","reflexive"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.118':   { id: "fr.sons.verbes-essentiels.118", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "construire", en: "to build", ipa: "/kɔ̃stʁɥiʁ/", respell: "kohn-STRWEER", notes: "irregular · je construis, nous construisons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.157':   { id: "fr.sons.verbes-essentiels.157", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "couvrir", en: "to cover", ipa: "/kuvʁiʁ/", respell: "koo-VREER", notes: "Irregular: conjugates like ouvrir, je couvre.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.191':   { id: "fr.sons.verbes-essentiels.191", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "promettre", en: "to promise", ipa: "/pʁɔmɛtʁ/", respell: "proh-MEHTR", notes: "Irregular; conjugates like mettre.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
};

/** What the database said, so a guard can compare a supplied value against the
 *  READ rather than against a second copy of the same string. a2.14 §5. An
 *  empty string is a row that had no respelling at all. */
export const STORED_RESPELL: Record<string, string> = {
  'fr.a1.cuisine.042': "BWAHR",
  'fr.a1.dictee.091': "LEER",
  'fr.a1.emotions.034': "MOR duh REER",
  'fr.a1.meteo.062': "koo-VEHR",
  'fr.a1.routines.107': "kohⁿ-DWEER",
  'fr.a2.courses.070': "oo-VEHR",
  'fr.a2.disciplines.051': "a-PRAHⁿDR",
  'fr.a2.examens-et-diplomes.045': "ay-KREE",
  'fr.a2.verbes.423': "ruh-MEHTR",
  'fr.b1.verbes.054': "soo-FREER",
  'fr.sons.adjectifs-essentiels.082': "KRÜ",
  'fr.sons.adjectifs-essentiels.161': "MOR",
  'fr.sons.consonnes.110': "ay-KREER",
  'fr.sons.verbes-essentiels.001': "ETR",
  'fr.sons.verbes-essentiels.002': "ah-VWAR",
  'fr.sons.verbes-essentiels.004': "FEHR",
  'fr.sons.verbes-essentiels.005': "DEER",
  'fr.sons.verbes-essentiels.006': "poo-VWAR",
  'fr.sons.verbes-essentiels.007': "voo-LWAR",
  'fr.sons.verbes-essentiels.008': "duh-VWAR",
  'fr.sons.verbes-essentiels.009': "sah-VWAR",
  'fr.sons.verbes-essentiels.010': "vuh-NEER",
  'fr.sons.verbes-essentiels.011': "VWAR",
  'fr.sons.verbes-essentiels.012': "PRAHⁿDR",
  'fr.sons.verbes-essentiels.014': "METR",
  'fr.sons.verbes-essentiels.030': "kohⁿ-PRAHⁿDR",
  'fr.sons.verbes-essentiels.034': "oo-VREER",
  'fr.sons.verbes-essentiels.045': "koo-REER",
  'fr.sons.verbes-essentiels.047': "ruh-suh-VWAR",
  'fr.sons.verbes-essentiels.048': "koh-NEHTR",
  'fr.sons.verbes-essentiels.049': "KRWAR",
  'fr.sons.verbes-essentiels.052': "tuh-NEER",
  'fr.sons.verbes-essentiels.053': "oh-FREER",
  'fr.sons.verbes-essentiels.081': "NEHTR",
  'fr.sons.verbes-essentiels.082': "moo-REER",
  'fr.sons.verbes-essentiels.100': "sah-SWAHR",
  'fr.sons.verbes-essentiels.118': "kohn-STRWEER",
  'fr.sons.verbes-essentiels.157': "koo-VREER",
  'fr.sons.verbes-essentiels.191': "proh-MEHTR",
};

/** How many published sentences put each of the thirty-three behind a first
 *  word. The figures the lesson prints come from here rather than from a
 *  constant somebody typed. */
export const EVIDENCE: Record<string, number> = {
  "pris": 174,
  "mis": 61,
  "appris": 49,
  "compris": 29,
  "remis": 12,
  "promis": 18,
  "assis": 3,
  "dit": 55,
  "écrit": 24,
  "conduit": 2,
  "construit": 7,
  "vu": 56,
  "lu": 16,
  "bu": 8,
  "su": 8,
  "pu": 31,
  "voulu": 5,
  "dû": 132,
  "connu": 8,
  "venu": 14,
  "tenu": 12,
  "reçu": 90,
  "couru": 23,
  "cru": 3,
  "ouvert": 58,
  "offert": 28,
  "couvert": 7,
  "souffert": 2,
  "fait": 109,
  "été": 286,
  "eu": 78,
  "né": 25,
  "mort": 2,
};

/** Re-measured on every regeneration. */
export const MEASURED = {
  bareRegularPastForms: 0,
  lookalikeRows: 28,
  glossedAsPastForm: 4,
  glossedAndRespelled: 0,
  evidenceTotal: 1435,
  evidenceCards: 2,
  refaitOccurrences: 2,
  apercuOccurrences: 0,
  a205BlockRows: 36,
  blockCountAtRead: 439,
} as const;
