// A RECORDED READ OF POSTGRES. Generated by scripts/_a221_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 22 rows imported out of 5 themes; 9 of them declared absent from the seed.
// 7 rows read and refused; see READ_NOT_IMPORTED in the corpus file.
// 2 respellings repaired, 0 supplied.
// 7 rows found broken and left alone; 7 of them still are.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   THE SPLIT              0 agreed cells exist as headwords, out of 60
//                          cells across 15 verbs. « mort » is published as an
//                          ordinary describing word and is imported for that
//                          reason; every other cell is absent. Settled by a2.05,
//                          agreed by a2.20, inherited here.
//
//   THE TRANSITIVE SPLIT   the largest judgement call in the lesson, and the
//                          figures it rests on:
//     sortir      avoir=  1   être= 24
//     monter      avoir=  4   être=  9
//     descendre   avoir=  0   être=  5
//     passer      avoir= 45   être= 26
//     rentrer     avoir=  0   être= 13
//     retourner   avoir=  0   être=  8
//                          3 of the six have ZERO published uses with avoir, so
//                          the brief's "group of six" is a group of two. Shown
//                          receptively on sortir and passer; the rule is B1's.
//
//   THE PARADIGM           466 published sentences put être in front of one of
//                          the cells. 4 of them are a1/a2 cards with a respelling
//                          and 0 of THOSE show a second word with an ending
//                          on it, which is why the whole paradigm is authored.
//                          fr.a1.rp-recits-temps holds 487 published rows and
//                          is laid out as a person walk.
//     fr.a2.expressions-argot.003          « c'est mort »
//     fr.a2.expressions-argot.021          « c'est parti »
//     fr.a2.verbes.620                     « Il est venu hier. »
//     fr.a2.verbes.621                     « Il est né ici. »
//
//   THE FOUR CELLS         all four spellings of allé are already published with
//                          être in front of them, which the opening deck claims:
//     allé          19
//     allée         11
//     allés         23
//     allées         1
//
// THE BLOCK: fr.a2.verbes held 482 rows before this build and holds
// 482 now. Rows inside fr.a2.verbes.651..fr.a2.verbes.720 that this
// build does not own: none.
// a2.20's block holds 43 rows and a2.05's holds 36, which is exactly
// what each of those lessons applied.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const ETRE_IMPORT_ROWS: Record<string, Item> = {
  'fr.a1.transports-quotidiens.044':   { id: "fr.a1.transports-quotidiens.044", kind: "word", level: "a1", theme: "transports-quotidiens", fr: "monter", en: "to get on", ipa: "/mɔ̃.te/", respell: "mohn-TAY", tags: ["verb","movement"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.transports-quotidiens.045':   { id: "fr.a1.transports-quotidiens.045", kind: "word", level: "a1", theme: "transports-quotidiens", fr: "descendre", en: "to get off", ipa: "/de.sɑ̃dʁ/", respell: "day-SAHⁿDR", tags: ["verb","movement"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a2.maison.022':   { id: "fr.a2.maison.022", kind: "phrase", level: "a2", theme: "maison", fr: "sortir la poubelle", en: "to take out the trash", ipa: "/sɔʁ.tiʁ la pu.bɛl/", respell: "sor-TEER lah poo-BELL", tags: ["phrase","chore","household"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a2.verbes.013':   { id: "fr.a2.verbes.013", kind: "word", level: "a2", theme: "verbes", fr: "arriver", en: "to arrive", ipa: "a.ʁi.ve", respell: "ah-ree-VAY", example: {"en":"The train arrives at noon.","fr":"Le train arrive à midi."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.a2.verbes.016':   { id: "fr.a2.verbes.016", kind: "word", level: "a2", theme: "verbes", fr: "rentrer", en: "to go home", ipa: "ʁɑ̃.tʁe", respell: "rahⁿ-TRAY", example: {"en":"She goes home after work.","fr":"Elle rentre à la maison après le travail."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.sons.adjectifs-essentiels.161':   { id: "fr.sons.adjectifs-essentiels.161", kind: "word", level: "sons", theme: "adjectifs-essentiels", fr: "mort", en: "dead", ipa: "/mɔʁ/", respell: "MOR", notes: "Feminine: morte.", tags: ["adjective"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.001':   { id: "fr.sons.verbes-essentiels.001", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "être", en: "to be", ipa: "/ɛtʁ/", respell: "ETR", notes: "irregular · je suis, tu es, il est, nous sommes", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.002':   { id: "fr.sons.verbes-essentiels.002", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "avoir", en: "to have", ipa: "/avwaʁ/", respell: "ah-VWAR", notes: "irregular · j'ai, tu as, il a, nous avons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.003':   { id: "fr.sons.verbes-essentiels.003", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "aller", en: "to go", ipa: "/ale/", respell: "ah-LAY", notes: "irregular · je vais, tu vas, il va, nous allons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.010':   { id: "fr.sons.verbes-essentiels.010", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "venir", en: "to come", ipa: "/vəniʁ/", respell: "vuh-NEER", notes: "irregular · je viens, nous venons, ils viennent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.017':   { id: "fr.sons.verbes-essentiels.017", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "passer", en: "to pass, to spend (time)", ipa: "/pase/", respell: "pah-SAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.021':   { id: "fr.sons.verbes-essentiels.021", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "rester", en: "to stay", ipa: "/ʁɛste/", respell: "res-TAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.040':   { id: "fr.sons.verbes-essentiels.040", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "partir", en: "to leave, to depart", ipa: "/paʁtiʁ/", respell: "par-TEER", notes: "irregular · je pars, nous partons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.041':   { id: "fr.sons.verbes-essentiels.041", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "sortir", en: "to go out", ipa: "/sɔʁtiʁ/", respell: "sor-TEER", notes: "irregular · je sors, nous sortons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.043':   { id: "fr.sons.verbes-essentiels.043", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "entrer", en: "to enter, to go in", ipa: "/ɑ̃tʁe/", respell: "ahⁿ-TRAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.044':   { id: "fr.sons.verbes-essentiels.044", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "tomber", en: "to fall", ipa: "/tɔ̃be/", respell: "tohn-BAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.081':   { id: "fr.sons.verbes-essentiels.081", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "naître", en: "to be born", ipa: "/nɛtʁ/", respell: "NEHTR", notes: "irregular · je suis né, I was born", tags: ["irregular","re-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.082':   { id: "fr.sons.verbes-essentiels.082", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "mourir", en: "to die", ipa: "/muʁiʁ/", respell: "moo-REER", notes: "irregular · je meurs, nous mourons", tags: ["irregular","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.083':   { id: "fr.sons.verbes-essentiels.083", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "devenir", en: "to become", ipa: "/dəvəniʁ/", respell: "duh-vuh-NEER", notes: "irregular · je deviens, tu deviens, like venir", tags: ["irregular","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.084':   { id: "fr.sons.verbes-essentiels.084", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "revenir", en: "to come back", ipa: "/ʁəvəniʁ/", respell: "ruh-vuh-NEER", notes: "irregular · je reviens, like venir", tags: ["irregular","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.085':   { id: "fr.sons.verbes-essentiels.085", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "retourner", en: "to go back", ipa: "/ʁətuʁne/", respell: "ruh-toor-NAY", notes: "regular er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.086':   { id: "fr.sons.verbes-essentiels.086", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "repartir", en: "to leave again", ipa: "/ʁəpaʁtiʁ/", respell: "ruh-par-TEER", notes: "irregular · je repars, like partir", tags: ["irregular","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
};

/** What the database said, so a guard can compare a repaired value against the
 *  READ rather than against a second copy of the same string. a2.14 §5. */
export const STORED_RESPELL: Record<string, string> = {
  'fr.a1.transports-quotidiens.044': "mohn-TAY",
  'fr.a1.transports-quotidiens.045': "day-SAHⁿDR",
  'fr.a2.maison.022': "sor-TEER lah poo-BELL",
  'fr.a2.verbes.013': "ah-ree-VAY",
  'fr.a2.verbes.016': "rahⁿ-TRAY",
  'fr.sons.adjectifs-essentiels.161': "MOR",
  'fr.sons.verbes-essentiels.001': "ETR",
  'fr.sons.verbes-essentiels.002': "ah-VWAR",
  'fr.sons.verbes-essentiels.003': "ah-LAY",
  'fr.sons.verbes-essentiels.010': "vuh-NEER",
  'fr.sons.verbes-essentiels.017': "pah-SAY",
  'fr.sons.verbes-essentiels.021': "res-TAY",
  'fr.sons.verbes-essentiels.040': "par-TEER",
  'fr.sons.verbes-essentiels.041': "sor-TEER",
  'fr.sons.verbes-essentiels.043': "ahⁿ-TRAY",
  'fr.sons.verbes-essentiels.044': "tohn-BAY",
  'fr.sons.verbes-essentiels.081': "NEHTR",
  'fr.sons.verbes-essentiels.082': "moo-REER",
  'fr.sons.verbes-essentiels.083': "duh-vuh-NEER",
  'fr.sons.verbes-essentiels.084': "ruh-vuh-NEER",
  'fr.sons.verbes-essentiels.085': "ruh-toor-NAY",
  'fr.sons.verbes-essentiels.086': "ruh-par-TEER",
};

/** The transitive split, verb by verb, re-measured on every regeneration. */
export const TRANSITIVE_MEASURED: Record<string, { avoir: number; etre: number }> = {
  "sortir": { avoir: 1, etre: 24 },
  "monter": { avoir: 4, etre: 9 },
  "descendre": { avoir: 0, etre: 5 },
  "passer": { avoir: 45, etre: 26 },
  "rentrer": { avoir: 0, etre: 13 },
  "retourner": { avoir: 0, etre: 8 },
};

/** Published sentences putting être in front of each cell of aller. */
export const CELL_EVIDENCE: Record<string, number> = {
  "allé": 19,
  "allée": 11,
  "allés": 23,
  "allées": 1,
};

/** Re-measured on every regeneration. */
export const MEASURED = {
  agreedCellsAsHeadwords: 0,
  agreedCellsChecked: 60,
  paradigmEvidence: 466,
  paradigmEvidenceCards: 4,
  paradigmCardsShowingAnEnding: 0,
  recitsTempsRows: 487,
  transitiveZeroCount: 3,
  a220BlockRows: 43,
  a205BlockRows: 36,
  blockCountAtRead: 482,
} as const;
