// A RECORDED READ OF POSTGRES. Generated by scripts/_a205_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 23 rows imported out of 10 themes.
// 7 rows read and refused; see READ_NOT_IMPORTED in the corpus file.
// 1 respelling repaired, 4 supplied.
// 5 rows found broken and left alone; 5 of them still are.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   THE LEDGER DECISION    0 regular past forms exist as headwords.
//                          24 bare rows LOOK like past forms and every one is a
//                          word in its own right (fermé and ouvert are adjectives,
//                          été is the season, vu is a preposition).
//                          A past form is not a corpus item. Neither this lesson
//                          nor a2.20 authors one. Corpus file §1.
//
//   the published negatives 90 sentences put ne...pas round a form of avoir with
//                          a past form behind it, and 1 of them carry a respelling
//     fr.sons.masterclass.021                [eel na pa mahⁿ-ZHAY]
//
//   avoir + a past form    2843 published sentences, 19 with a respelling
//                          a2.13 §1: evidence is not cards, and the pool was 19 not 2843
//
//   a short adverb in the gap  177 published sentences, 3 with a respelling
//                          (a2.17 §10 measured 82 with a shorter adverb list)
//
//   the preceding object   81 published rows DO agree a past form after avoir, and
//                          every one is « que j'ai achetée » or « je l'ai aidée ».
//                          That is a2.06 at seq 21 and the guard here is scoped to
//                          this lesson's own surfaces rather than to the corpus.
//
//   -ER naming form after avoir  0. a2.01 kept the evidence clean and it
//                          still is, corpus-wide and not only in its own rows.
//   a2.01's own rows       25 at fr.a2.verbes.101..140, all simple present.
//
// THE BLOCK: fr.a2.verbes held 403 rows before this build and holds
// 403 now. Rows inside fr.a2.verbes.541..fr.a2.verbes.590 that this
// build does not own: none.
// Rows inside a2.20's reservation fr.a2.verbes.591..fr.a2.verbes.650: none.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const PASSE_COMPOSE_ROWS: Record<string, Item> = {
  'fr.a2.negation-et-restriction.113':   { id: "fr.a2.negation-et-restriction.113", kind: "sentence", level: "a2", theme: "negation-et-restriction", fr: "Elle n'a pas répondu à mon message.", en: "She didn't reply to my message.", ipa: "/ɛl na pa ʁe.pɔ̃.dy a mɔ̃ me.saʒ/", notes: "Répondu à uses the preposition à, easily confused with the verb form a in this same sentence.", tags: ["homophone"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.negation-et-restriction.114':   { id: "fr.a2.negation-et-restriction.114", kind: "sentence", level: "a2", theme: "negation-et-restriction", fr: "Nous n'avons pas visité le musée samedi.", en: "We didn't visit the museum on Saturday.", ipa: "/nu na.vɔ̃ pa vi.zi.te lə my.ze sam.di/", notes: "The negation wraps around avons, not around visité, so pas comes before the past participle.", tags: ["orthographe"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.negation-et-restriction.117':   { id: "fr.a2.negation-et-restriction.117", kind: "sentence", level: "a2", theme: "negation-et-restriction", fr: "Ils n'ont pas payé la facture ce mois-ci.", en: "They didn't pay the bill this month.", ipa: "/il nɔ̃ pa pe.je la fak.tyʁ sə mwa.si/", notes: "Ont sounds exactly like on, so context alone tells you which spelling to use here.", tags: ["homophone"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.negation-et-restriction.142':   { id: "fr.a2.negation-et-restriction.142", kind: "sentence", level: "a2", theme: "negation-et-restriction", fr: "Il n'a pas travaillé la semaine dernière.", en: "He didn't work last week.", ipa: "/il na pa tʁa.va.je la sə.mɛn dɛʁ.njɛʁ/", notes: "Travaillé ends in a silent é sound spelled with the participle ending rather than an accented e alone.", tags: ["e-muet"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.prepositions-essentielles.174':   { id: "fr.a2.prepositions-essentielles.174", kind: "sentence", level: "a2", theme: "prepositions-essentielles", fr: "J'ai commencé il y a trois jours.", en: "I started three days ago.", ipa: "/ʒe kɔ.mɑ̃.se il i a tʁwa ʒuʁ/", respell: "zhay ko-mahⁿ-SAY eel ee ah trwah ZHOOR", notes: "THE ONE RECEPTIVE ROW. It holds a passé composé, which is a2.05 and two lessons away, and it is shown once and asked for nowhere: no dictée, no drill, no quiz question.", tags: ["prepositions","temps","il-y-a","receptive"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.a2.prepositions-essentielles.186':   { id: "fr.a2.prepositions-essentielles.186", kind: "phrase", level: "a2", theme: "prepositions-essentielles", fr: "il y a trois jours", en: "three days ago", ipa: "/il i a tʁwa ʒuʁ/", respell: "EEL EE AH trwah ZHOOR", notes: "Fourteen letters and NO DICTATION DRILL, because the dictée is a production surface and this phrase needs a tense the learner does not have.", tags: ["prepositions","temps"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.a2.verbes.020':   { id: "fr.a2.verbes.020", kind: "word", level: "a2", theme: "verbes", fr: "répondre", en: "to answer", ipa: "ʁe.pɔ̃dʁ", respell: "ray-POHⁿDR", example: {"en":"You must answer before Friday.","fr":"Vous devez répondre avant vendredi."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.a2.verbes.027':   { id: "fr.a2.verbes.027", kind: "word", level: "a2", theme: "verbes", fr: "vendre", en: "to sell", ipa: "vɑ̃dʁ", respell: "VAHⁿDR", example: {"en":"The store sells cheap furniture.","fr":"Le magasin vend des meubles pas chers."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.a2.verbes.031':   { id: "fr.a2.verbes.031", kind: "word", level: "a2", theme: "verbes", fr: "travailler", en: "to work", ipa: "tʁa.va.je", respell: "trah-vah-YAY", example: {"en":"I work in a hospital.","fr":"Je travaille dans un hôpital."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.a2.verbes.527':   { id: "fr.a2.verbes.527", kind: "sentence", level: "a2", theme: "verbes", fr: "Je vais manger avec des amis.", en: "I am going to eat with friends.", ipa: "/ʒə vɛ mɑ̃.ʒe a.vɛk de.za.mi/", respell: "zhuh veh mahⁿ-ZHAY ah-VEK day-za-MEE", notes: "A plan with something after the naming form, which nothing about the rule minds.", tags: ["verbes","futur-proche"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.sons.alphabet.402':   { id: "fr.sons.alphabet.402", kind: "sentence", level: "sons", theme: "alphabet", fr: "J'ai mal entendu la deuxième lettre.", en: "I misheard the second letter.", ipa: "ʒe mal ɑ̃.tɑ̃.dy la dø.zjɛm lɛtʁ", respell: "ZHAY MAL ahⁿ-tahⁿ-DÜ LA deu-ZYEHM LEHTR", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  'fr.sons.jours-et-mois.025':   { id: "fr.sons.jours-et-mois.025", kind: "word", level: "sons", theme: "jours-et-mois", fr: "hier", en: "yesterday", ipa: "/jɛʁ/", respell: "YEHR", notes: "One syllable: 'yair'. The h is silent, as always in French.", tags: ["jours-et-mois","adverbe"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.jours-et-mois.027':   { id: "fr.sons.jours-et-mois.027", kind: "word", level: "sons", theme: "jours-et-mois", fr: "avant-hier", en: "the day before yesterday", ipa: "/a.vɑ̃.tjɛʁ/", respell: "ah-vahn-TYEHR", notes: "Literally 'before yesterday'. The t links into hier: 'ah-vahn-tyair'.", tags: ["jours-et-mois","adverbe"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.masterclass.021':   { id: "fr.sons.masterclass.021", kind: "sentence", level: "sons", theme: "masterclass", fr: "Il n'a pas mangé.", en: "He has not eaten.", ipa: "/il na pa mɑ̃.ʒe/", respell: "eel na pa mahⁿ-ZHAY", notes: "Remove one word and the Z disappears with it. The elision is untouched: it never depended on encore.", tags: ["elision","muettes","nasales","blocked","no-liaison"], drills: ["sentence","review","flashcard","voiceflash","dictation"], audioRef: null, version: 1 },
  'fr.sons.mots-essentiels.045':   { id: "fr.sons.mots-essentiels.045", kind: "word", level: "sons", theme: "mots-essentiels", fr: "bien", en: "well, good", ipa: "/bjɛ̃/", respell: "BYEHⁿ", notes: "Nasal ending, like 'byan'. Ça va bien: it is going well.", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.mots-essentiels.053':   { id: "fr.sons.mots-essentiels.053", kind: "word", level: "sons", theme: "mots-essentiels", fr: "déjà", en: "already", ipa: "/deʒa/", respell: "day-ZHAH", notes: "Sounds like 'day-zha', as in déjà vu.", tags: ["adverb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.muettes.037':   { id: "fr.sons.muettes.037", kind: "word", level: "sons", theme: "muettes", fr: "manger", en: "to eat", ipa: "/mɑ̃.ʒe/", respell: "mahⁿ-ZHAY", tags: ["er-ending","silent-r","infinitive","nasal"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.sons.verbes-essentiels.002':   { id: "fr.sons.verbes-essentiels.002", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "avoir", en: "to have", ipa: "/avwaʁ/", respell: "ah-VWAR", notes: "irregular · j'ai, tu as, il a, nous avons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.015':   { id: "fr.sons.verbes-essentiels.015", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "parler", en: "to speak, to talk", ipa: "/paʁle/", respell: "par-LAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.037':   { id: "fr.sons.verbes-essentiels.037", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "finir", en: "to finish", ipa: "/finiʁ/", respell: "fee-NEER", notes: "regular -ir verb · je finis, nous finissons", tags: ["ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.038':   { id: "fr.sons.verbes-essentiels.038", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "choisir", en: "to choose", ipa: "/ʃwaziʁ/", respell: "shwah-ZEER", notes: "regular -ir verb · je choisis, nous choisissons", tags: ["ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.voyelles.355':   { id: "fr.sons.voyelles.355", kind: "sentence", level: "sons", theme: "voyelles", fr: "Son style d'écriture a beaucoup changé cette année.", en: "Her writing style has changed a lot this year.", ipa: "sɔ̃ stil de.kʁi.tyʁ a bo.ku ʃɑ̃.ʒe sɛt a.ne", respell: "SOHⁿ STEEL day-kree-TÜR A boh-KOO shahⁿ-ZHAY SEHT a-NAY", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, skill: "PE", register: "courant" },
  'fr.sons.voyelles.445':   { id: "fr.sons.voyelles.445", kind: "sentence", level: "sons", theme: "voyelles", fr: "J'ai laissé mon téléphone sous le canapé.", en: "I left my phone under the couch.", ipa: "ʒe lɛ.se mɔ̃ te.le.fɔn su lə ka.na.pe", respell: "ZHAY leh-SAY MOHⁿ tay-lay-FON SOO LUH ka-na-PAY", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
};

/** What the database said, so a guard can compare a supplied value against the
 *  READ rather than against a second copy of the same string. a2.14 §5. An
 *  empty string is a row that had no respelling at all. */
export const STORED_RESPELL: Record<string, string> = {
  'fr.a2.negation-et-restriction.113': "",
  'fr.a2.negation-et-restriction.114': "",
  'fr.a2.negation-et-restriction.117': "",
  'fr.a2.negation-et-restriction.142': "",
  'fr.a2.prepositions-essentielles.174': "zhay ko-mahⁿ-SAY eel ee ah trwah ZHOOR",
  'fr.a2.prepositions-essentielles.186': "EEL EE AH trwah ZHOOR",
  'fr.a2.verbes.020': "ray-POHⁿDR",
  'fr.a2.verbes.027': "VAHⁿDR",
  'fr.a2.verbes.031': "trah-vah-YAY",
  'fr.a2.verbes.527': "zhuh veh mahⁿ-ZHAY ah-VEK day-za-MEE",
  'fr.sons.alphabet.402': "ZHAY MAL ahⁿ-tahⁿ-DÜ LA deu-ZYEHM LEHTR",
  'fr.sons.jours-et-mois.025': "YEHR",
  'fr.sons.jours-et-mois.027': "ah-vahn-TYEHR",
  'fr.sons.masterclass.021': "eel na pa mahⁿ-ZHAY",
  'fr.sons.mots-essentiels.045': "BYEHⁿ",
  'fr.sons.mots-essentiels.053': "day-ZHAH",
  'fr.sons.muettes.037': "mahⁿ-ZHAY",
  'fr.sons.verbes-essentiels.002': "ah-VWAR",
  'fr.sons.verbes-essentiels.015': "par-LAY",
  'fr.sons.verbes-essentiels.037': "fee-NEER",
  'fr.sons.verbes-essentiels.038': "shwah-ZEER",
  'fr.sons.voyelles.355': "SOHⁿ STEEL day-kree-TÜR A boh-KOO shahⁿ-ZHAY SEHT a-NAY",
  'fr.sons.voyelles.445': "ZHAY leh-SAY MOHⁿ tay-lay-FON SOO LUH ka-na-PAY",
};

/** Re-measured on every regeneration. A figure the lesson prints comes from
 *  here rather than from a constant somebody typed. */
export const MEASURED = {
  bareRegularPastForms: 0,
  pastFormLookalikes: 24,
  publishedNegatives: 90,
  publishedNegativesRespelled: 1,
  avoirPlusPastForm: 2843,
  avoirPlusPastFormRespelled: 19,
  adverbInGap: 177,
  adverbInGapRespelled: 3,
  precedingObjectAgreements: 81,
  infinitiveAfterAvoir: 0,
  a201Rows: 25,
  blockCountAtRead: 403,
} as const;
