// a1.22's IMPORTED and REUSED manifests: a RECORDED READ of Postgres taken on
// 2026-08-07 by scripts/_pays_manifest.ts, so the merge can write these rows
// into seed.json without a connection.
//
// NOTHING BELOW WAS RETYPED. Regenerate with:
//
//     pnpm tsx scripts/_pays_manifest.ts > scripts/data/_pays-manifest.gen.txt
//
// The batch compares every field against the live database before writing and
// dies if the manifest has drifted, because a stale manifest puts the seed ahead
// of rows nobody has looked at. Only the `why` lines on REUSED are written by
// hand; every other character is generated.
//
// ── Why the import is forty rows ───────────────────────────────────────────
//
// `pays-et-nationalites` is NOT in SEED_CUT.themes, so all 326 of its published
// rows are outside seed.json today and every one this lesson names has to be
// carried or it renders as an empty card. That is a1.13's situation with
// `couleurs`, which is also outside the cut and now holds 48 seed rows for
// exactly this reason.
//
// THE BRIEF SAYS THE OPPOSITE and it is the second most consequential of its
// errors: "a merge that leaves the seed unchanged for these rows is behaving
// correctly". Being outside the cut explains why the rows are ABSENT today; it
// is not a licence for the merge to leave them absent.
//
//     IMPORTED  40   published in Postgres, ABSENT from the seed
//     REUSED     4   published in Postgres, ALREADY in the seed, untouched
//
// ── Two conventions in one theme, visible below ────────────────────────────
//
// Rows .001 to .080 were authored as country/nationality PAIRS with English
// tags (`country`, `nationality`), an explicit `gender` on both halves, and a
// `notes` line naming the preposition. Rows .086 to .197 are a later pass in a
// different hand: French tags (`pays`, `nationalite`), `gender` usually null on
// the nationality, no notes, and a U+203F tie in the IPA.
//
// `l'Iran` (.172) and `iranien` (.173) are the only rows this lesson takes from
// the second block, and the difference is why `iranien` carries no gender and
// so does not join a1.03's measured ending population while `italien` does.
//
// ── The ten broken respellings are reproduced AS THEY ARE ──────────────────
//
// `frahn-SEH`, `kah-nah-DYAN`, `LAH FRAHNSS` and seven more are below with the
// values they carry today. They are repaired by RESPELL_REPAIRS in
// pays-corpus.ts rather than tidied here, because the batch compares this
// manifest field by field against the database and a corrected value would read
// as drift and stop the run.
//
// ── Three imported rows carry French `notes` ───────────────────────────────
//
// .254, .255 and .288 have dictée hints written in French ("La liaison 'est_un'
// sonne comme 'ɛtɛ̃'"), which is against the house rule that instruction and
// context are English. They are another author's rows and `notes` is read by no
// component in the app, so nothing of it reaches a screen. Imported unchanged
// and reported rather than rewritten.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export type ImportedRow = Item;

/* GENERATED by scripts/_pays_manifest.ts. Do not hand-edit. */
export const IMPORTED: ImportedRow[] = [

  // ── the twelve countries, each paired with its nationality by id (24) ──
  {
    id: "fr.a1.pays-et-nationalites.001", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "la France", en: "France", ipa: "la fʁɑ̃s", respell: "LAH FRAHNSS", gender: "f", notes: "en France (in or to France).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.002", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "français", en: "French", ipa: "fʁɑ̃sɛ", respell: "frahn-SEH", gender: "m", notes: "Feminine: française. Nationality adjectives are lowercase in French.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.003", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "le Canada", en: "Canada", ipa: "lə kanada", respell: "LUH kah-nah-DAH", gender: "m", notes: "au Canada (in or to Canada).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.004", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "canadien", en: "Canadian", ipa: "kanadjɛ̃", respell: "kah-nah-DYAN", gender: "m", notes: "Feminine: canadienne.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.007", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "la Belgique", en: "Belgium", ipa: "la bɛlʒik", respell: "LAH behl-ZHEEK", gender: "f", notes: "en Belgique (in or to Belgium).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.008", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "belge", en: "Belgian", ipa: "bɛlʒ", respell: "BEHLZH", gender: "m", notes: "Same form for masculine and feminine: belge.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.011", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "les États-Unis", en: "the United States", ipa: "lezetazyni", respell: "LAY zay-tah-zü-NEE", gender: "m", notes: "aux États-Unis (in or to the United States). Always plural.", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.012", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "américain", en: "American", ipa: "ameʁikɛ̃", respell: "ah-may-ree-KAN", gender: "m", notes: "Feminine: américaine.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.021", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "le Sénégal", en: "Senegal", ipa: "lə seneɡal", respell: "LUH say-nay-GAHL", gender: "m", notes: "au Sénégal (in or to Senegal).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.022", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "sénégalais", en: "Senegalese", ipa: "seneɡalɛ", respell: "say-nay-gah-LEH", gender: "m", notes: "Feminine: sénégalaise.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.041", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "l'Allemagne", en: "Germany", ipa: "lalmaɲ", respell: "lahl-MAHNY", gender: "f", notes: "en Allemagne (in or to Germany).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.042", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "allemand", en: "German", ipa: "almɑ̃", respell: "ahl-MAHN", gender: "m", notes: "Feminine: allemande.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.043", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "l'Espagne", en: "Spain", ipa: "lɛspaɲ", respell: "lehs-PAHNY", gender: "f", notes: "en Espagne (in or to Spain).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.044", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "espagnol", en: "Spanish", ipa: "ɛspaɲɔl", respell: "ehs-pah-NYOL", gender: "m", notes: "Feminine: espagnole.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.045", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "l'Italie", en: "Italy", ipa: "litali", respell: "lee-tah-LEE", gender: "f", notes: "en Italie (in or to Italy).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.046", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "italien", en: "Italian", ipa: "italjɛ̃", respell: "ee-tah-LYAN", gender: "m", notes: "Feminine: italienne.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.047", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "le Portugal", en: "Portugal", ipa: "lə pɔʁtyɡal", respell: "LUH por-tü-GAHL", gender: "m", notes: "au Portugal (in or to Portugal).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.048", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "portugais", en: "Portuguese", ipa: "pɔʁtyɡɛ", respell: "por-tü-GEH", gender: "m", notes: "Feminine: portugaise.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.051", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "le Japon", en: "Japan", ipa: "lə ʒapɔ̃", respell: "LUH zhah-POHN", gender: "m", notes: "au Japon (in or to Japan).", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.052", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "japonais", en: "Japanese", ipa: "ʒapɔnɛ", respell: "zhah-po-NEH", gender: "m", notes: "Feminine: japonaise.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.057", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "le Mexique", en: "Mexico", ipa: "lə mɛksik", respell: "LUH mehk-SEEK", gender: "m", notes: "au Mexique (in or to Mexico). Masculine even though it ends in e.", tags: ["country"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.058", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "mexicain", en: "Mexican", ipa: "mɛksikɛ̃", respell: "mehk-see-KAN", gender: "m", notes: "Feminine: mexicaine.", tags: ["nationality"], drills: ["flashcard","voiceflash"], version: 1, cardType: "vocab",
  },
  {
    id: "fr.a1.pays-et-nationalites.172", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "l'Iran", en: "Iran", ipa: "l‿i.ʁɑ̃", respell: "lee-RAHN", gender: "m", tags: ["pays"], drills: ["flashcard","review"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.173", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "iranien", en: "Iranian", ipa: "i.ʁa.njɛ̃", respell: "ee-ra-nee-AHN", tags: ["nationalite"], drills: ["voiceflash","review"], version: 1,
  },

  // ── three of the six grid cells, already published in the same frame (2) ──
  {
    id: "fr.a1.presentation-personnelle.028", kind: "sentence", level: "a1", theme: "presentation-personnelle", fr: "Je viens du Canada.", en: "I come from Canada.", ipa: "ʒə vjɛ̃ dy ka.na.da", notes: "“du” is used before a masculine country like “le Canada”.", tags: ["grammaire"], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.presentation-personnelle.029", kind: "sentence", level: "a1", theme: "presentation-personnelle", fr: "Je viens de France.", en: "I come from France.", ipa: "ʒə vjɛ̃ də fʁɑ̃s", notes: "“de” alone is used before a feminine country like “la France”, not “du”.", tags: ["grammaire"], drills: ["dictation"], version: 1,
  },

  // ── coming from, in the first person, on four more countries (3) ──
  {
    id: "fr.a1.pays-et-nationalites.204", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Je viens du Sénégal.", en: "I come from Senegal.", ipa: "ʒə vjɛ̃ dy se.ne.gal", tags: [], drills: ["sentence","review"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.216", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Je viens du Mexique.", en: "I come from Mexico.", ipa: "ʒə vjɛ̃ dy mɛk.sik", tags: [], drills: ["sentence","review"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.225", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Je viens d'Espagne.", en: "I come from Spain.", ipa: "ʒə vjɛ̃ dɛs.paɲ", tags: [], drills: ["sentence","review"], version: 1,
  },

  // ── coming from in the third person: READING EXPOSURE ONLY, never produced (3) ──
  {
    id: "fr.a1.pays-et-nationalites.218", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Il vient du Japon.", en: "He comes from Japan.", ipa: "il vjɛ̃ dy ʒa.pɔ̃", tags: [], drills: ["sentence","review"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.226", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Elle vient d'Italie.", en: "She comes from Italy.", ipa: "ɛl vjɛ̃ di.ta.li", tags: [], drills: ["sentence","review"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.233", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Il vient des États-Unis.", en: "He comes from the United States.", ipa: "il vjɛ̃ de.ze.ta.zy.ni", tags: [], drills: ["sentence","review"], version: 1,
  },

  // ── the nationality after être, and the agreement the corpus already carries (4) ──
  {
    id: "fr.a1.presentation-personnelle.012", kind: "sentence", level: "a1", theme: "presentation-personnelle", fr: "Il est français.", en: "He is French.", ipa: "i.l‿ɛ fʁɑ̃.sɛ", notes: "“français” keeps a cedilla under the c to keep the soft s sound.", tags: ["accent"], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.198", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Je suis canadien.", en: "I am Canadian.", ipa: "ʒə sɥi ka.na.djɛ̃", tags: [], drills: ["sentence","review"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.199", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Elle est française.", en: "She is French.", ipa: "ɛl ɛ fʁɑ̃.sɛz", tags: [], drills: ["sentence","review"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.081", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Elle est canadienne, mais elle habite en France.", en: "She is Canadian, but she lives in France.", ipa: "ɛ.l‿ɛ ka.na.djɛn mɛ.z‿ɛl a.bit ɑ̃ fʁɑ̃s", notes: "Nationality adjectives like “canadienne” take a lowercase letter in French.", tags: ["orthographe"], drills: ["dictation"], version: 1,
  },

  // ── the countries as subjects, so the article is seen doing ordinary work (4) ──
  {
    id: "fr.a1.pays-et-nationalites.254", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "La France est un pays d'Europe.", en: "France is a country in Europe.", ipa: "la fʁɑ̃s ɛ.t‿ɛ̃ pe.i dø.ʁɔp", notes: "La liaison 'est_un' sonne comme 'ɛtɛ̃', facile d'oublier le t de liaison à l'écrit.", tags: [], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.255", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Le Canada est un grand pays.", en: "Canada is a big country.", ipa: "lə ka.na.da ɛ.t‿ɛ̃ gʁɑ̃ pe.i", notes: "'Grand' se termine par un d muet, ne pas ajouter de lettre en trop.", tags: [], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.288", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "Les États-Unis sont grands.", en: "The United States are big.", ipa: "le.ze.ta.zy.ni sɔ̃ gʁɑ̃", notes: "'États-Unis' prend un trait d'union et deux majuscules.", tags: [], drills: ["dictation"], version: 1,
  },
  {
    id: "fr.a1.pays-et-nationalites.235", kind: "sentence", level: "a1", theme: "pays-et-nationalites", fr: "J'habite au Canada depuis deux ans.", en: "I have been living in Canada for two years.", ipa: "ʒa.bit o ka.na.da də.pɥi dø.z‿ɑ̃", tags: [], drills: ["sentence","review"], version: 1,
  },
];

export const REUSED: { id: string; fr: string; en: string; why: string }[] = [

  // ── three of the six grid cells, already published in the same frame (1) ──
  {
    id: "fr.a1.deplacements.011",
    fr: "Je vais au Canada.",
    en: "I am going to Canada.",
    why: 'The masculine going-to cell of the grid, ALREADY IN THE SEED. The one cell of six a learner may '
      + 'already have met, and the reason this lesson borrows three of its six rather than authoring all six.',
  },

  // ── the nationality after être, and the agreement the corpus already carries (1) ──
  {
    id: "fr.a1.metiers.264",
    fr: "Je suis français.",
    en: "I am French. (said by a man)",
    why: 'a1.06 taught that nothing goes in front of a nationality after être, and the metiers theme carries '
      + 'the parallel rule for jobs at fr.a1.metiers.016. This row is that rule surviving in ordinary French, '
      + 'in the seed, written by nobody teaching it.',
  },

  // ── aux plus a plural country, whole, with its liaison (1) ──
  {
    id: "fr.sons.liaisons.059",
    fr: "Mon frère travaille aux États-Unis.",
    en: "My brother works in the United States.",
    why: '« aux États-Unis » in the wild, and the liaison lesson already owns it. Kept as a whole phrase '
      + 'because a clip of `aux` alone teaches nothing: the whole word is /o.ze.ta.zy.ni/.',
  },

  // ── française, the one nationality respelling in the corpus that is already right (1) ──
  {
    id: "fr.sons.muettes.051",
    fr: "française",
    en: "French (feminine)",
    why: 'THE ONE TRANSCRIPTION IN THIS AREA OF THE CORPUS THAT WAS ALREADY RIGHT: frahⁿ-SEHZ, in the sons '
      + 'track, where every nasal is closed correctly. It is imported rather than authored so the feminine '
      + 'half of the ear pair is the corpus\'s own row, and it is the evidence for the systematic finding in '
      + 'the header of pays-corpus.ts.',
  },
];
