// GENERATED by scripts/_a215_manifest.ts on 2026-08-13. Do not edit by hand.
//
// A recorded read of the 12 rows a2.15 imports rather than authors, out of
// 5 themes, plus 1 repaired and carried without being imported and
// 13 read and refused.
//
// a2.15 IS THE FIRST A2 BUILD TO AUTHOR AN INFINITIVE. `battre`, `combattre` and
// `remettre` do not exist at any status in any theme, and `battre` is in the unit
// title. Five builds in a row before this one authored none.
//
// THE REFUSALS ARE THE INTERESTING HALF. The four best respelled prendre
// sentences in the corpus are all a2.27's, the best apprennent sentence carries
// U+203F, and all three published battre sentences hold U+0153.
//
// Regenerate with: pnpm tsx scripts/_a215_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 8 naming forms this lesson displays. Six are the three heads and the
 *  compounds they buy; `vendre` is a2.11's and the trap contrasts against it. */
export const IMPORTED_NAMING_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.012", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "prendre", en: "to take", ipa: "/pʁɑ̃dʁ/", respell: "PRAHNDR", notes: "irregular · je prends, nous prenons, ils prennent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.disciplines.051", kind: "word", level: "a2", theme: "disciplines", fr: "apprendre", en: "to learn", ipa: "a.pʁɑ̃dʁ", respell: "a-PRAHNDR", example: {"en":"I've been learning French for a year.","fr":"J'apprends le français depuis un an."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.sons.verbes-essentiels.030", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "comprendre", en: "to understand", ipa: "/kɔ̃pʁɑ̃dʁ/", respell: "kohn-PRAHNDR", notes: "irregular · conjugates like prendre", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.225", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "surprendre", en: "to surprise", ipa: "/syʁpʁɑ̃dʁ/", respell: "sür-PRAHNDR", notes: "Irregular; conjugates like prendre.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.014", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "mettre", en: "to put", ipa: "/mɛtʁ/", respell: "METR", notes: "irregular · je mets, nous mettons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.196", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "permettre", en: "to allow", ipa: "/pɛʁmɛtʁ/", respell: "pehr-MEHTR", notes: "Irregular; conjugates like mettre.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.191", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "promettre", en: "to promise", ipa: "/pʁɔmɛtʁ/", respell: "proh-MEHTR", notes: "Irregular; conjugates like mettre.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.verbes.027", kind: "word", level: "a2", theme: "verbes", fr: "vendre", en: "to sell", ipa: "vɑ̃dʁ", respell: "VAHⁿDR", example: {"en":"The store sells cheap furniture.","fr":"Le magasin vend des meubles pas chers."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
];

/** The 4 published sentences that survived every refusal. */
export const IMPORTED_EVIDENCE_ROWS: Item[] = [
  { id: "fr.sons.nasales.027", kind: "sentence", level: "sons", theme: "nasales", fr: "J'apprends le français depuis le printemps.", en: "I have been learning French since spring.", ipa: "ʒa.pʁɑ̃ lə fʁɑ̃.sɛ də.pɥi lə pʁɛ̃.tɑ̃", respell: "zha-PRAHⁿ LUH frahⁿ-SEH duh-PÜEE LUH prehⁿ-TAHⁿ", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.nasales.020", kind: "sentence", level: "sons", theme: "nasales", fr: "Maman prend toujours son temps.", en: "Mom always takes her time.", ipa: "ma.mɑ̃ pʁɑ̃ tu.ʒuʁ sɔ̃ tɑ̃", respell: "ma-MAHⁿ PRAHⁿ too-ZHOOR SOHⁿ TAHⁿ", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.voyelles.448", kind: "sentence", level: "sons", theme: "voyelles", fr: "Elle met sa veste et ferme la porte.", en: "She puts on her jacket and closes the door.", ipa: "ɛl mɛ sa vɛst e fɛʁm la pɔʁt", respell: "EHL MEH SA VEHST AY FEHRM LA PORT", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.voyelles.386", kind: "sentence", level: "sons", theme: "voyelles", fr: "Tu mets du beurre sur tout, toujours.", en: "You put butter on everything, always.", ipa: "ty mɛ dy bœʁ syʁ tu tu.ʒuʁ", respell: "TÜ MEH DÜ BEUR SÜR TOO too-ZHOOR", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
];

/** REPAIRED AND CARRIED, NEVER IMPORTED. Named on no screen and in no itemId. */
export const REPAIR_ONLY_ROWS: Item[] = [
  { id: "fr.a1.transports-quotidiens.041", kind: "word", level: "a1", theme: "transports-quotidiens", fr: "prendre", en: "to take", ipa: "/pʁɑ̃dʁ/", respell: "PRAHN-druh", tags: ["verb","movement"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The 13 rows read and refused. READ ONLY: never carried, never released,
 *  never in itemIds, and named on no screen. */
export const READ_ONLY_ROWS: Item[] = [
  { id: "fr.sons.nasales.143", kind: "sentence", level: "sons", theme: "nasales", fr: "On prend le train ensemble.", en: "We're taking the train together.", ipa: "ɔ̃ pʁɑ̃ lə tʁɛ̃ ɑ̃.sɑ̃bl", respell: "OHⁿ PRAHⁿ LUH TREHⁿ ahⁿ-SAHⁿBL", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.voyelles.407", kind: "sentence", level: "sons", theme: "voyelles", fr: "Tu prends le bus ou tu marches sous la pluie?", en: "Do you take the bus or walk in the rain?", ipa: "ty pʁɑ̃ lə bys u ty maʁʃ su la plɥi", respell: "TÜ PRAHⁿ LUH BÜS OO TÜ MARSH SOO LA PLÜEE", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.a1.verbes-essentiels.020", kind: "sentence", level: "a1", theme: "verbes-essentiels", fr: "Nous prenons le métro tous les jours.", en: "We take the subway every day.", ipa: "/nu pʁənɔ̃ lə metʁo tu le ʒuʁ/", respell: "noo pruh-NOHN luh may-TROH too lay zhoor", notes: "Irregular verb: je prends, nous prenons, ils prennent.", tags: ["verbe","deplacement"], drills: ["flashcard","voiceflash","sentence","dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.voyelles.434", kind: "sentence", level: "sons", theme: "voyelles", fr: "Tu prends le vélo ou l'auto ?", en: "Are you taking the bike or the car?", ipa: "ty pʁɑ̃ lə ve.lo u lo.to", respell: "TÜ PRAHⁿ LUH vay-LOH OO loh-TOH", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.masterclass.043", kind: "sentence", level: "sons", theme: "masterclass", fr: "Après le dîner, on prend un verre d'eau.", en: "After dinner, we have a glass of water.", ipa: "/a.pʁɛ lə di.ne | ɔ̃ pʁɑ̃.t‿œ̃ vɛʁ do/", respell: "a-preh luh dee-NAY | ohⁿ prahⁿ-t‿uhⁿ vehr DOH", notes: "The S of après is next to a consonant and stays down. One word later a D wakes as a T.", tags: ["rythme","elision","liaison","muettes","nasales","pipeline","liaison-t","devoicing","all-five"], drills: ["sentence","review","flashcard","voiceflash","dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.nasales.038", kind: "sentence", level: "sons", theme: "nasales", fr: "Les enfants apprennent une chanson en classe.", en: "The children are learning a song in class.", ipa: "lez‿ɑ̃.fɑ̃ a.pʁɛn yn ʃɑ̃.sɔ̃ ɑ̃ klɑs", respell: "lay-z‿ahⁿ-FAHⁿ a-PREHN ÜN shahⁿ-SOHⁿ AHⁿ KLAHS", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.a1.verbes-essentiels.035", kind: "sentence", level: "a1", theme: "verbes-essentiels", fr: "Je comprends mieux maintenant.", en: "I understand better now.", ipa: "/ʒə kɔ̃pʁɑ̃ mjø mɛ̃tnɑ̃/", respell: "zhuh kohn-PRAHN myuh mant-NAHN", tags: ["verbe"], drills: ["flashcard","voiceflash","sentence","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.mots-essentiels.009", kind: "sentence", level: "a2", theme: "mots-essentiels", fr: "Prends ton parapluie.", en: "Take your umbrella.", ipa: "/pʁɑ̃ tɔ̃ paʁaplɥi/", respell: "prahn tohn pah-rah-PLWEE", tags: ["daily-life"], drills: ["flashcard","voiceflash","dictation","sentence"], audioRef: null, version: 1 },
  { id: "fr.a2.mots-essentiels.008", kind: "sentence", level: "a2", theme: "mots-essentiels", fr: "Mets ton manteau.", en: "Put on your coat.", ipa: "/mɛ tɔ̃ mɑ̃to/", respell: "meh tohn mahn-TOH", tags: ["daily-life"], drills: ["flashcard","voiceflash","dictation","sentence"], audioRef: null, version: 1 },
  { id: "fr.b1.cuisine.009", kind: "sentence", level: "b1", theme: "cuisine", fr: "Elle bat les œufs avant de les incorporer à la pâte.", en: "She beats the eggs before mixing them into the batter.", notes: "Don't confuse the preposition \"à\" (with a grave accent) and the verb form \"a\" (has).", tags: ["homophone"], drills: ["sentence","dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.voyelles.020", kind: "sentence", level: "sons", theme: "voyelles", fr: "Mon cœur bat vite après le jeu.", en: "My heart beats fast after the game.", ipa: "/mɔ̃ kœʁ ba vit a.pʁɛ lə ʒø/", notes: "Cœur uses the open œu sound while jeu uses the closed eu sound, even though both come from the same two letters reversed.", tags: ["orthographe"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.noms-essentiels.256", kind: "sentence", level: "a1", theme: "noms-essentiels", fr: "Le cœur bat plus vite après la course.", en: "The heart beats faster after the run.", notes: "{\"tiles\":[{\"w\":\"Le cœur\",\"t\":\"the heart\"},{\"w\":\"bat plus vite\",\"t\":\"beats faster\"},{\"w\":\"après la course.\",\"t\":\"after the run\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.cuisine.166", kind: "phrase", level: "a1", theme: "cuisine", fr: "battre les œufs", en: "to beat the eggs", ipa: "batʁ le zø", respell: "BATR LAY ZUH", notes: "Liaison makes les œufs sound like lay zuh, and the plural fs is silent.", tags: ["verb","cooking","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** naming form -> id, in learner order. The only place this pairing is written. */
export const NAMING_ROW_IDS: [string, string][] = [
  ["prendre", "fr.sons.verbes-essentiels.012"],
  ["apprendre", "fr.a2.disciplines.051"],
  ["comprendre", "fr.sons.verbes-essentiels.030"],
  ["surprendre", "fr.sons.verbes-essentiels.225"],
  ["mettre", "fr.sons.verbes-essentiels.014"],
  ["permettre", "fr.sons.verbes-essentiels.196"],
  ["promettre", "fr.sons.verbes-essentiels.191"],
  ["vendre", "fr.a2.verbes.027"],
];

/** evidence sentence -> id. */
export const EVIDENCE_ROW_IDS: [string, string][] = [
  ["J'apprends le français depuis le printemps.", "fr.sons.nasales.027"],
  ["Maman prend toujours son temps.", "fr.sons.nasales.020"],
  ["Elle met sa veste et ferme la porte.", "fr.sons.voyelles.448"],
  ["Tu mets du beurre sur tout, toujours.", "fr.sons.voyelles.386"],
];

/** And the refused pairing, kept apart so nothing can iterate both by accident. */
export const READ_ONLY_ROW_IDS: [string, string][] = [
  ["On prend le train ensemble.", "fr.sons.nasales.143"],
  ["Tu prends le bus ou tu marches sous la pluie?", "fr.sons.voyelles.407"],
  ["Nous prenons le métro tous les jours.", "fr.a1.verbes-essentiels.020"],
  ["Tu prends le vélo ou l'auto ?", "fr.sons.voyelles.434"],
  ["Après le dîner, on prend un verre d'eau.", "fr.sons.masterclass.043"],
  ["Les enfants apprennent une chanson en classe.", "fr.sons.nasales.038"],
  ["Je comprends mieux maintenant.", "fr.a1.verbes-essentiels.035"],
  ["Prends ton parapluie.", "fr.a2.mots-essentiels.009"],
  ["Mets ton manteau.", "fr.a2.mots-essentiels.008"],
  ["Elle bat les œufs avant de les incorporer à la pâte.", "fr.b1.cuisine.009"],
  ["Mon cœur bat vite après le jeu.", "fr.sons.voyelles.020"],
  ["Le cœur bat plus vite après la course.", "fr.a1.noms-essentiels.256"],
  ["battre les œufs", "fr.a1.cuisine.166"],
];

/** Every id this lesson may put in `itemIds`. The refused rows and the
 *  repair-only row are deliberately absent, and the batch asserts that absence. */
export const IMPORTABLE_IDS: string[] = [
  "fr.sons.verbes-essentiels.012",
  "fr.a2.disciplines.051",
  "fr.sons.verbes-essentiels.030",
  "fr.sons.verbes-essentiels.225",
  "fr.sons.verbes-essentiels.014",
  "fr.sons.verbes-essentiels.196",
  "fr.sons.verbes-essentiels.191",
  "fr.a2.verbes.027",
  "fr.sons.nasales.027",
  "fr.sons.nasales.020",
  "fr.sons.voyelles.448",
  "fr.sons.voyelles.386",
];

/** Every id the merge writes into the seed: the importable ones plus the row
 *  this build repairs without displaying. */
export const CARRIED_IDS: string[] = [
  "fr.sons.verbes-essentiels.012",
  "fr.a2.disciplines.051",
  "fr.sons.verbes-essentiels.030",
  "fr.sons.verbes-essentiels.225",
  "fr.sons.verbes-essentiels.014",
  "fr.sons.verbes-essentiels.196",
  "fr.sons.verbes-essentiels.191",
  "fr.a2.verbes.027",
  "fr.sons.nasales.027",
  "fr.sons.nasales.020",
  "fr.sons.voyelles.448",
  "fr.sons.voyelles.386",
  "fr.a1.transports-quotidiens.041",
];

/** The themes the imported rows came out of. */
export const SOURCE_THEMES: string[] = ["disciplines","nasales","verbes","verbes-essentiels","voyelles"];
/** And the themes the merge writes into, which is one wider. */
export const CARRIED_THEMES: string[] = ["disciplines","nasales","transports-quotidiens","verbes","verbes-essentiels","voyelles"];

/** The evidence count, re-measured on the day this manifest was generated. */
export const EVIDENCE_MEASURED = { prendreCells: 234, mettreCells: 80, battreCells: 0, date: "2026-08-13" };
