// A RECORDED READ OF POSTGRES. Generated by scripts/_a218_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 12 rows imported out of 5 themes.
// 15 rows read and refused; see READ_NOT_IMPORTED in the corpus file.
// 5 respellings repaired, 1 supplied.
// 7 rows found broken and left alone; 7 of them still are.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   il y a          217 published rows
//                   130 of them "there is"
//                   33 a number and a duration, 24 of those with nothing after it
//                   the counterexample still reads as quoted
//
//   depuis          31 of 560 sentences sit beside an avoir past
//   pendant         97 of 447 do
//                   ratio 3.92x, and the build refuses anything under 2x
//
//   evidence against cards (a2.13 §1), published sentences:
//     en        2178 sentences,  58 carry a respelling
//     dans      1506 sentences,  42 carry a respelling
//     depuis     560 sentences,  15 carry a respelling
//     pendant    447 sentences,  11 carry a respelling
//     il y a     202 sentences,   4 carry a respelling
//
//   THE QUADRUPLE, still four consecutive published cards:
//     fr.sons.jours-et-mois.080  dans une heure     DAHⁿ ZÜN UHR
//     fr.sons.jours-et-mois.081  il y a une heure   EEL EE AH ÜN UHR
//     fr.sons.jours-et-mois.082  depuis une heure   duh-PWEE ZÜN UHR
//     fr.sons.jours-et-mois.083  pendant une heure  pahⁿ-DAHⁿ TÜN UHR
//
// THE BLOCK: fr.a2.prepositions-essentielles held 153 rows before this
// build and holds 182 now. Rows inside fr.a2.prepositions-essentielles.169..fr.a2.prepositions-essentielles.208 that
// this build does not own: none.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const PREPOSITIONS_TEMPS_ROWS: Record<string, Item> = {
  'fr.a1.prepositions-essentielles.093':   { id: "fr.a1.prepositions-essentielles.093", kind: "sentence", level: "a1", theme: "prepositions-essentielles", fr: "Il pleut pendant la nuit.", en: "It rains during the night.", respell: "eel PLEU pahⁿ-DAHⁿ LA NÜEE", notes: "{\"tiles\":[{\"w\":\"Il pleut\",\"t\":\"it rains\"},{\"w\":\"pendant la nuit.\",\"t\":\"during the night\"}]}", tags: [], drills: ["flashcard","voiceflash","sentence","review"], audioRef: null, version: 1 },
  'fr.sons.jours-et-mois.080':   { id: "fr.sons.jours-et-mois.080", kind: "phrase", level: "sons", theme: "jours-et-mois", fr: "dans une heure", en: "in an hour", ipa: "/dɑ̃.zyn.œʁ/", respell: "DAHⁿ ZÜN UHR", notes: "Dans plus a duration points to the future: an hour from now.", tags: ["time","expressions"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.jours-et-mois.081':   { id: "fr.sons.jours-et-mois.081", kind: "phrase", level: "sons", theme: "jours-et-mois", fr: "il y a une heure", en: "an hour ago", ipa: "/i.li.a.yn.œʁ/", respell: "EEL EE AH ÜN UHR", notes: "Il y a plus a duration points to the past: an hour back.", tags: ["time","expressions"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.jours-et-mois.082':   { id: "fr.sons.jours-et-mois.082", kind: "phrase", level: "sons", theme: "jours-et-mois", fr: "depuis une heure", en: "for an hour, since an hour ago", ipa: "/də.pɥi.zyn.œʁ/", respell: "duh-PWEE ZÜN UHR", notes: "Depuis marks something that started in the past and is still going.", tags: ["time","expressions"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.jours-et-mois.083':   { id: "fr.sons.jours-et-mois.083", kind: "phrase", level: "sons", theme: "jours-et-mois", fr: "pendant une heure", en: "for an hour, during an hour", ipa: "/pɑ̃.dɑ̃.tyn.œʁ/", respell: "pahⁿ-DAHⁿ TÜN UHR", notes: "Pendant marks a finished duration: it lasted an hour.", tags: ["time","expressions"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.mots-essentiels.013':   { id: "fr.sons.mots-essentiels.013", kind: "word", level: "sons", theme: "mots-essentiels", fr: "dans", en: "in, inside", ipa: "/dɑ̃/", respell: "DAHⁿ", notes: "Nasal vowel, silent s. Sounds like 'dahn'.", tags: ["preposition"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.mots-essentiels.027':   { id: "fr.sons.mots-essentiels.027", kind: "word", level: "sons", theme: "mots-essentiels", fr: "depuis", en: "since, for (time)", ipa: "/dəpɥi/", respell: "duh-PWEE", notes: "Silent s. Depuis lundi: since Monday.", tags: ["preposition"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.mots-essentiels.028':   { id: "fr.sons.mots-essentiels.028", kind: "word", level: "sons", theme: "mots-essentiels", fr: "pendant", en: "during", ipa: "/pɑ̃dɑ̃/", respell: "pahⁿ-DAHⁿ", notes: "Two nasal vowels, silent t. Pendant la nuit: during the night.", tags: ["preposition"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.mots-essentiels.088':   { id: "fr.sons.mots-essentiels.088", kind: "word", level: "sons", theme: "mots-essentiels", fr: "en", en: "some, of it", ipa: "/ɑ̃/", respell: "AHⁿ", notes: "replaces de + noun: j'en veux", tags: ["pronoun"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.nasales.030':   { id: "fr.sons.nasales.030", kind: "sentence", level: "sons", theme: "nasales", fr: "Elle danse pendant toute la chanson.", en: "She dances during the whole song.", ipa: "ɛl dɑ̃s pɑ̃.dɑ̃ tut la ʃɑ̃.sɔ̃", respell: "EHL DAHⁿS pahⁿ-DAHⁿ TOOT LA shahⁿ-SOHⁿ", tags: [], drills: ["flashcard","voiceflash","sentence","review"], audioRef: null, version: 1, register: "courant" },
  'fr.sons.nasales.039':   { id: "fr.sons.nasales.039", kind: "sentence", level: "sons", theme: "nasales", fr: "Pendant l'hiver, il fait franchement froid ici.", en: "During winter, it is frankly cold here.", ipa: "pɑ̃.dɑ̃ li.vɛʁ il fɛ fʁɑ̃ʃ.mɑ̃ fʁwa i.si", respell: "pahⁿ-DAHⁿ lee-VEHR EEL FEH frahⁿsh-MAHⁿ FRWA ee-SEE", tags: [], drills: ["flashcard","voiceflash","sentence","review"], audioRef: null, version: 1, register: "courant" },
  'fr.sons.questions.040':   { id: "fr.sons.questions.040", kind: "phrase", level: "sons", theme: "questions", fr: "depuis quand ?", en: "since when?", ipa: "/dəpɥi kɑ̃/", respell: "duh-PWEE KAHⁿ", notes: "asks about a starting point in time", tags: ["question-phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
};

/** What the database said, so a guard can compare a repair against the read
 *  rather than against a second copy of the same string. An empty string is a
 *  row that had no respelling at all and gets one from RESPELL_ADDITIONS. */
export const STORED_RESPELL: Record<string, string> = {
  'fr.a1.prepositions-essentielles.093': "eel PLEU pahⁿ-DAHⁿ LA NÜEE",
  'fr.sons.jours-et-mois.080': "DAHⁿ ZÜN UHR",
  'fr.sons.jours-et-mois.081': "EEL EE AH ÜN UHR",
  'fr.sons.jours-et-mois.082': "duh-PWEE ZÜN UHR",
  'fr.sons.jours-et-mois.083': "pahⁿ-DAHⁿ TÜN UHR",
  'fr.sons.mots-essentiels.013': "DAHⁿ",
  'fr.sons.mots-essentiels.027': "duh-PWEE",
  'fr.sons.mots-essentiels.028': "pahⁿ-DAHⁿ",
  'fr.sons.mots-essentiels.088': "AHⁿ",
  'fr.sons.nasales.030': "EHL DAHⁿS pahⁿ-DAHⁿ TOOT LA shahⁿ-SOHⁿ",
  'fr.sons.nasales.039': "pahⁿ-DAHⁿ lee-VEHR EEL FEH frahⁿsh-MAHⁿ FRWA ee-SEE",
  'fr.sons.questions.040': "duh-PWEE KAHⁿ",
};

/** Re-measured on every regeneration. A figure the lesson prints comes from
 *  here rather than from a constant somebody typed. */
export const MEASURED = {
  ilYaRows: 217,
  ilYaExistence: 130,
  ilYaAgo: 33,
  ilYaAgoBare: 24,
  depuisSentences: 560,
  depuisWithACompound: 31,
  pendantSentences: 447,
  pendantWithACompound: 97,
  depuisSentencesWithARespelling: 15,
  blockCountAtRead: 182,
} as const;
