// GENERATED by scripts/_prepositions_manifest.ts. DO NOT EDIT BY HAND.
//
// A recorded read of Postgres for every row a1.21 imports, so
// merge-prepositions-into-seed.ts can carry them into seed.json without a
// connection. Regenerate with:
//
//     pnpm tsx scripts/_prepositions_manifest.ts
//
// author-prepositions-batch.ts compares every field below against the live
// database before writing and dies if this file has drifted, because a stale
// manifest puts the seed ahead of rows nobody has looked at.
//
// `prepositions-essentielles` holds 407 published rows and ZERO in seed.json,
// because the theme is not in SEED_CUT.themes. Every row this lesson names has
// to be carried by the merge or it renders as an empty card. The brief says the
// opposite; see the header of merge-prepositions-into-seed.ts.
//
// Rows: 49
import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const IMPORTED_ROWS: Item[] = [
  {
    "id": "fr.a1.maison.124",
    "kind": "sentence",
    "level": "a1",
    "theme": "maison",
    "fr": "La cuisine est à côté du salon.",
    "en": "The kitchen is next to the living room.",
    "ipa": "/la kɥi.zin ɛ.t‿a ko.te dy sa.lɔ̃/",
    "notes": "\"à\" (preposition, with accent) must not be confused with \"a\" (verb avoir), even though both sound the same.",
    "tags": [
      "homophone"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.mots-essentiels.116",
    "kind": "sentence",
    "level": "a1",
    "theme": "mots-essentiels",
    "fr": "La voiture est garée devant la maison.",
    "en": "The car is parked in front of the house.",
    "ipa": "la vwa.tyʁ ɛ ga.ʁe də.vɑ̃ la mɛ.zɔ̃",
    "tags": [
      "grammaire"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.mots-essentiels.117",
    "kind": "sentence",
    "level": "a1",
    "theme": "mots-essentiels",
    "fr": "Le jardin se trouve derrière la maison.",
    "en": "The garden is behind the house.",
    "ipa": "lə ʒaʁ.dɛ̃ sə tʁuv dɛ.ʁjɛʁ la mɛ.zɔ̃",
    "tags": [
      "grammaire"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.objets.122",
    "kind": "sentence",
    "level": "a1",
    "theme": "objets",
    "fr": "Le stylo est à côté du cahier.",
    "en": "The pen is next to the notebook.",
    "ipa": "/lə sti.lo ɛ a ko.te dy ka.je/",
    "notes": "The \"à\" in \"à côté\" sounds identical to \"a\", so the accent depends on grammar, not sound.",
    "tags": [
      "homophone"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.001",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le chat dort sous la table.",
    "en": "The cat is sleeping under the table.",
    "notes": "sous = under, opposite of sur (on).",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.002",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Les clés sont sur le bureau.",
    "en": "The keys are on the desk.",
    "notes": "sur = on top of a surface.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.005",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le pain est dans le sac.",
    "en": "The bread is in the bag.",
    "notes": "dans = à l'intérieur d'un espace fermé.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.009",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "La pharmacie est en face de la boulangerie.",
    "en": "The pharmacy is across from the bakery.",
    "notes": "en face de = du côté opposé.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.010",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le café est à côté de la banque.",
    "en": "The café is next to the bank.",
    "notes": "à côté de = juste à proximité immédiate.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.017",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le livre est sur l'étagère.",
    "en": "The book is on the shelf.",
    "notes": "sur + surface horizontale, ici l'étagère.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.018",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Mon sac est sous le lit.",
    "en": "My bag is under the bed.",
    "notes": "sous + objet placé plus bas.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.020",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Nous habitons près de la gare.",
    "en": "We live near the station.",
    "notes": "près de = à faible distance, opposé de loin de.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.021",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le supermarché est loin de chez moi.",
    "en": "The supermarket is far from my house.",
    "notes": "loin de = à grande distance.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.023",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Je vais chez le médecin demain.",
    "en": "I am going to the doctor's tomorrow.",
    "notes": "chez + profession, ici le médecin.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.028",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Mon vélo est derrière la maison.",
    "en": "My bike is behind the house.",
    "notes": "derrière + bâtiment.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.034",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le chien attend devant la porte.",
    "en": "The dog waits in front of the door.",
    "notes": "devant + porte, position fixe.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.039",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Mon école est entre la boulangerie et la pharmacie.",
    "en": "My school is between the bakery and the pharmacy.",
    "notes": "entre + deux repères géographiques.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.054",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Mon chat dort sous le canapé.",
    "en": "My cat sleeps under the sofa.",
    "notes": "sous + meuble bas.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.057",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le chien dort à côté du feu.",
    "en": "The dog sleeps next to the fire.",
    "notes": "à côté du = à côté de + le, contraction obligatoire.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.067",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Il range les jouets dans la boîte.",
    "en": "He puts the toys away in the box.",
    "notes": "dans + contenant.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.068",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "La boulangerie est au coin de la rue.",
    "en": "The bakery is at the corner of the street.",
    "notes": "au coin de = à l'angle de.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.073",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Nous restons chez nous ce week-end.",
    "en": "We are staying home this weekend.",
    "notes": "chez nous = à notre domicile.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.078",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le nid est dans l'arbre.",
    "en": "The nest is in the tree.",
    "notes": "dans + arbre, intérieur du feuillage.",
    "tags": [
      "prepositions",
      "lieu"
    ],
    "drills": [
      "dictation"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.082",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Les clés sont dans mon sac.",
    "en": "The keys are in my bag.",
    "notes": "{\"tiles\":[{\"w\":\"Les clés sont\",\"t\":\"the keys are\"},{\"w\":\"dans mon sac.\",\"t\":\"in my bag\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.083",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le chat dort sur le canapé.",
    "en": "The cat sleeps on the couch.",
    "notes": "{\"tiles\":[{\"w\":\"Le chat dort\",\"t\":\"the cat sleeps\"},{\"w\":\"sur le canapé.\",\"t\":\"on the couch\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.084",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le ballon est sous la table.",
    "en": "The ball is under the table.",
    "notes": "{\"tiles\":[{\"w\":\"Le ballon est\",\"t\":\"the ball is\"},{\"w\":\"sous la table.\",\"t\":\"under the table\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.090",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le magasin est entre la banque et la poste.",
    "en": "The shop is between the bank and the post office.",
    "notes": "{\"tiles\":[{\"w\":\"Le magasin est\",\"t\":\"the shop is\"},{\"w\":\"entre la banque\",\"t\":\"between the bank\"},{\"w\":\"et la poste.\",\"t\":\"and the post office\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.092",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le jardin est derrière la maison.",
    "en": "The garden is behind the house.",
    "notes": "{\"tiles\":[{\"w\":\"Le jardin est\",\"t\":\"the garden is\"},{\"w\":\"derrière la maison.\",\"t\":\"behind the house\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.096",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "La pharmacie est à côté de l'école.",
    "en": "The pharmacy is next to the school.",
    "notes": "{\"tiles\":[{\"w\":\"La pharmacie est\",\"t\":\"the pharmacy is\"},{\"w\":\"à côté de\",\"t\":\"next to\"},{\"w\":\"l'école.\",\"t\":\"the school\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.097",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le café est en face de la gare.",
    "en": "The cafe is across from the station.",
    "notes": "{\"tiles\":[{\"w\":\"Le café est\",\"t\":\"the cafe is\"},{\"w\":\"en face de\",\"t\":\"across from\"},{\"w\":\"la gare.\",\"t\":\"the station\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.098",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Je vais au marché le samedi.",
    "en": "I go to the market on Saturdays.",
    "notes": "{\"tiles\":[{\"w\":\"Je vais\",\"t\":\"I go\"},{\"w\":\"au marché\",\"t\":\"to the market\"},{\"w\":\"le samedi.\",\"t\":\"on Saturdays\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.099",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Les enfants jouent aux cartes.",
    "en": "The children are playing cards.",
    "notes": "{\"tiles\":[{\"w\":\"Les enfants jouent\",\"t\":\"the children play\"},{\"w\":\"aux cartes.\",\"t\":\"cards\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.100",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Il revient du travail à six heures.",
    "en": "He comes back from work at six o'clock.",
    "notes": "{\"tiles\":[{\"w\":\"Il revient\",\"t\":\"he comes back\"},{\"w\":\"du travail\",\"t\":\"from work\"},{\"w\":\"à six heures.\",\"t\":\"at six o'clock\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.104",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "L'hôtel est loin de la plage.",
    "en": "The hotel is far from the beach.",
    "notes": "{\"tiles\":[{\"w\":\"L'hôtel est\",\"t\":\"the hotel is\"},{\"w\":\"loin de\",\"t\":\"far from\"},{\"w\":\"la plage.\",\"t\":\"the beach\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.105",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "La boulangerie est près de chez moi.",
    "en": "The bakery is near my house.",
    "notes": "{\"tiles\":[{\"w\":\"La boulangerie est\",\"t\":\"the bakery is\"},{\"w\":\"près de\",\"t\":\"near\"},{\"w\":\"chez moi.\",\"t\":\"my house\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.112",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le professeur écrit sur le tableau.",
    "en": "The teacher writes on the board.",
    "notes": "{\"tiles\":[{\"w\":\"Le professeur écrit\",\"t\":\"the teacher writes\"},{\"w\":\"sur le tableau.\",\"t\":\"on the board\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.113",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Mon frère travaille à la banque.",
    "en": "My brother works at the bank.",
    "notes": "{\"tiles\":[{\"w\":\"Mon frère travaille\",\"t\":\"my brother works\"},{\"w\":\"à la banque.\",\"t\":\"at the bank\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.116",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Le chien reste devant la porte.",
    "en": "The dog stays in front of the door.",
    "notes": "{\"tiles\":[{\"w\":\"Le chien reste\",\"t\":\"the dog stays\"},{\"w\":\"devant la porte.\",\"t\":\"in front of the door\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.a1.prepositions-essentielles.118",
    "kind": "sentence",
    "level": "a1",
    "theme": "prepositions-essentielles",
    "fr": "Elle habite au troisième étage.",
    "en": "She lives on the third floor.",
    "notes": "{\"tiles\":[{\"w\":\"Elle habite\",\"t\":\"she lives\"},{\"w\":\"au troisième étage.\",\"t\":\"on the third floor\"}]}",
    "tags": [],
    "drills": [
      "sentence",
      "flashcard",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.accents.034",
    "kind": "word",
    "level": "sons",
    "theme": "accents",
    "fr": "à",
    "en": "to, at",
    "ipa": "/a/",
    "respell": "AH",
    "notes": "Identical sound to a. The mark is doing grammar, not sound.",
    "tags": [
      "minimal-pair",
      "pair-a",
      "grave-other"
    ],
    "drills": [
      "flashcard",
      "voiceflash",
      "review"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.mots-essentiels.013",
    "kind": "word",
    "level": "sons",
    "theme": "mots-essentiels",
    "fr": "dans",
    "en": "in, inside",
    "ipa": "/dɑ̃/",
    "respell": "DAHⁿ",
    "notes": "Nasal vowel, silent s. Sounds like 'dahn'.",
    "tags": [
      "preposition"
    ],
    "drills": [
      "flashcard",
      "voiceflash"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.mots-essentiels.014",
    "kind": "word",
    "level": "sons",
    "theme": "mots-essentiels",
    "fr": "sur",
    "en": "on, on top of",
    "ipa": "/syʁ/",
    "respell": "SÜR",
    "notes": "The u is the tight French 'u', lips rounded. Sur la table: on the table.",
    "tags": [
      "preposition"
    ],
    "drills": [
      "flashcard",
      "voiceflash"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.mots-essentiels.015",
    "kind": "word",
    "level": "sons",
    "theme": "mots-essentiels",
    "fr": "sous",
    "en": "under",
    "ipa": "/su/",
    "respell": "SOO",
    "notes": "Sounds like 'soo', silent s at the end. Opposite of sur.",
    "tags": [
      "preposition"
    ],
    "drills": [
      "flashcard",
      "voiceflash"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.mots-essentiels.020",
    "kind": "word",
    "level": "sons",
    "theme": "mots-essentiels",
    "fr": "entre",
    "en": "between",
    "ipa": "/ɑ̃tʁ/",
    "respell": "AHⁿ-truh",
    "notes": "Nasal start, like 'ahntr'. Entre nous: between us.",
    "tags": [
      "preposition"
    ],
    "drills": [
      "flashcard",
      "voiceflash"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.mots-essentiels.021",
    "kind": "word",
    "level": "sons",
    "theme": "mots-essentiels",
    "fr": "devant",
    "en": "in front of",
    "ipa": "/dəvɑ̃/",
    "respell": "duh-VAHⁿ",
    "notes": "Silent t. Sounds like 'duh-vahn'.",
    "tags": [
      "preposition"
    ],
    "drills": [
      "flashcard",
      "voiceflash"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.mots-essentiels.022",
    "kind": "word",
    "level": "sons",
    "theme": "mots-essentiels",
    "fr": "derrière",
    "en": "behind",
    "ipa": "/dɛʁjɛʁ/",
    "respell": "deh-RYEHR",
    "notes": "Sounds like 'deh-ryehr'. Opposite of devant.",
    "tags": [
      "preposition"
    ],
    "drills": [
      "flashcard",
      "voiceflash"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.mots-essentiels.030",
    "kind": "word",
    "level": "sons",
    "theme": "mots-essentiels",
    "fr": "près de",
    "en": "near, close to",
    "ipa": "/pʁɛ də/",
    "respell": "PREH DUH",
    "notes": "Silent s in près. Près de la gare: near the station.",
    "tags": [
      "preposition"
    ],
    "drills": [
      "flashcard",
      "voiceflash"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.mots-essentiels.031",
    "kind": "word",
    "level": "sons",
    "theme": "mots-essentiels",
    "fr": "loin de",
    "en": "far from",
    "ipa": "/lwɛ̃ də/",
    "respell": "LWAHⁿ DUH",
    "notes": "Loin sounds like 'lwan' with a nasal ending. Opposite of près de.",
    "tags": [
      "preposition"
    ],
    "drills": [
      "flashcard",
      "voiceflash"
    ],
    "version": 1
  },
  {
    "id": "fr.sons.muettes.009",
    "kind": "word",
    "level": "sons",
    "theme": "muettes",
    "fr": "chez",
    "en": "at the home of",
    "ipa": "/ʃe/",
    "respell": "SHAY",
    "tags": [
      "silent-final",
      "silent-z"
    ],
    "drills": [
      "flashcard",
      "voiceflash",
      "review"
    ],
    "version": 1
  }
] as Item[];

export const IMPORTED_ROW_IDS: string[] = IMPORTED_ROWS.map((r) => r.id);
