// A RECORDED READ OF POSTGRES. Generated by scripts/_a204_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 37 rows imported out of 18 themes.
// 12 rows read and refused; see READ_NOT_IMPORTED in the corpus file.
// 9 respellings repaired, 0 supplied.
// 7 rows found broken and left alone; 7 of them still are.
//
// THE MEASUREMENT, RE-RUN ON EVERY REGENERATION:
//   283 published rows hold `chez`
//   20 of them carry a respelling and can reach a card
//   0 of them put it in front of a place
//
// THE BLOCK: fr.a2.prepositions-essentielles held 127 rows before this
// build and holds 127 now. Rows inside fr.a2.prepositions-essentielles.129..fr.a2.prepositions-essentielles.168 that
// this build does not own: none.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const PREPOSITIONS_LIEU_ROWS: Record<string, Item> = {
  'fr.a1.amis.011':   { id: "fr.a1.amis.011", kind: "word", level: "a1", theme: "amis", fr: "le copain", en: "the friend (male, casual)", ipa: "/lə kɔ.pɛ̃/", respell: "LUH koh-PAN", gender: "m", notes: "Informal; can also mean boyfriend with mon.", tags: ["amis","noun"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.amis.030':   { id: "fr.a1.amis.030", kind: "phrase", level: "a1", theme: "amis", fr: "Bienvenue chez moi", en: "Welcome to my place", ipa: "/bjɛ̃.və.ny ʃe mwa/", respell: "byan-vuh-NÜ SHAY MWAH", tags: ["amis","phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.amis.059':   { id: "fr.a1.amis.059", kind: "phrase", level: "a1", theme: "amis", fr: "passer chez quelqu'un", en: "to drop by someone's place", ipa: "pa.se ʃe kɛl.kœ̃", respell: "pah-SAY SHAY kehl-KUHN", notes: "Chez means at the home of.", tags: ["friendship","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.animaux-domestiques.108':   { id: "fr.a1.animaux-domestiques.108", kind: "word", level: "a1", theme: "animaux-domestiques", fr: "le vétérinaire", en: "the vet", ipa: "/lə veteʁinɛʁ/", respell: "luh vay-tay-ree-NAIR", gender: "m", tags: ["noun","health","pet"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.animaux-domestiques.130':   { id: "fr.a1.animaux-domestiques.130", kind: "phrase", level: "a1", theme: "animaux-domestiques", fr: "aller chez le vétérinaire", en: "to go to the vet", ipa: "/ale ʃe lə veteʁinɛʁ/", respell: "ah-LAY shay luh vay-tay-ree-NAIR", tags: ["phrase","verb","health"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.au-restaurant.001':   { id: "fr.a1.au-restaurant.001", kind: "word", level: "a1", theme: "au-restaurant", fr: "le restaurant", en: "the restaurant", ipa: "/lə ʁɛstoʁɑ̃/", respell: "luh rehs-toh-RAHN", gender: "m", notes: "Often shortened to le resto in everyday speech.", tags: ["restaurant"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.deplacements.003':   { id: "fr.a1.deplacements.003", kind: "word", level: "a1", theme: "deplacements", fr: "la gare", en: "the train station", ipa: "ɡaʁ", respell: "lah GAHR", gender: "f", tags: ["transport","noun","places"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.famille.025':   { id: "fr.a1.famille.025", kind: "word", level: "a1", theme: "famille", fr: "la tante", en: "the aunt", ipa: "/la tɑ̃t/", respell: "LAH TAHⁿT", gender: "f", tags: ["famille","noun","extended"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.famille.124':   { id: "fr.a1.famille.124", kind: "phrase", level: "a1", theme: "famille", fr: "dormir chez", en: "to sleep at someone's place", ipa: "dɔʁ.miʁ ʃe", respell: "dor-MEER shay", example: {"en":"I'm sleeping at my grandparents' place this weekend.","fr":"Je dors chez mes grands-parents ce week-end."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  'fr.a1.famille.125':   { id: "fr.a1.famille.125", kind: "phrase", level: "a1", theme: "famille", fr: "rester chez", en: "to stay at someone's place", ipa: "ʁɛs.te ʃe", respell: "rehs-TAY shay", example: {"en":"He stays at his uncle's during the vacation.","fr":"Il reste chez son oncle pendant les vacances."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  'fr.a1.famille.126':   { id: "fr.a1.famille.126", kind: "phrase", level: "a1", theme: "famille", fr: "venir chez", en: "to come to someone's place", ipa: "və.niʁ ʃe", respell: "vuh-NEER shay", example: {"en":"Come to our place on Sunday!","fr":"Viens chez nous dimanche !"}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  'fr.a1.la-ville.012':   { id: "fr.a1.la-ville.012", kind: "word", level: "a1", theme: "la-ville", fr: "l'hôpital", en: "the hospital", ipa: "/lopital/", respell: "loh-pee-TAL", gender: "m", notes: "The h is silent, so le becomes l apostrophe.", tags: ["ville","lieux"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.la-ville.103':   { id: "fr.a1.la-ville.103", kind: "word", level: "a1", theme: "la-ville", fr: "la banque", en: "the bank", ipa: "/bɑ̃k/", respell: "BAHNK", gender: "f", tags: ["noun","building","money"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.la-ville.105':   { id: "fr.a1.la-ville.105", kind: "word", level: "a1", theme: "la-ville", fr: "la pharmacie", en: "the pharmacy", ipa: "/faʁ.ma.si/", respell: "far-mah-SEE", gender: "f", tags: ["noun","building","health"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.marche.006':   { id: "fr.a1.marche.006", kind: "word", level: "a1", theme: "marche", fr: "le marché", en: "the market", ipa: "/lə maʁ.ʃe/", respell: "luh mar-SHAY", gender: "m", tags: ["noun","market","place"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.pays-et-nationalites.001':   { id: "fr.a1.pays-et-nationalites.001", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "la France", en: "France", ipa: "la fʁɑ̃s", respell: "LAH FRAHⁿSS", gender: "f", notes: "en France (in or to France).", tags: ["country"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.pays-et-nationalites.011':   { id: "fr.a1.pays-et-nationalites.011", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "les États-Unis", en: "the United States", ipa: "lezetazyni", respell: "LAY zay-tah-zü-NEE", gender: "m", notes: "aux États-Unis (in or to the United States). Always plural.", tags: ["country"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.pays-et-nationalites.051':   { id: "fr.a1.pays-et-nationalites.051", kind: "word", level: "a1", theme: "pays-et-nationalites", fr: "le Japon", en: "Japan", ipa: "lə ʒapɔ̃", respell: "LUH zhah-POHⁿ", gender: "m", notes: "au Japon (in or to Japan).", tags: ["country"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.pronoms-essentiels.075':   { id: "fr.a1.pronoms-essentiels.075", kind: "phrase", level: "a1", theme: "pronoms-essentiels", fr: "chez toi", en: "at your place", ipa: "/ʃe twa/", respell: "shay twah", tags: ["pronoun","stressed","toi"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.a1.routines.063':   { id: "fr.a1.routines.063", kind: "phrase", level: "a1", theme: "routines", fr: "aller à l'école", en: "to go to school", ipa: "/a.le a le.kɔl/", respell: "ah-LAY ah lay-KOHL", notes: "Les enfants vont à l'école: the children go to school.", tags: ["phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.064':   { id: "fr.a1.routines.064", kind: "phrase", level: "a1", theme: "routines", fr: "aller au marché", en: "to go to the market", ipa: "/a.le o maʁ.ʃe/", respell: "ah-LAY oh mar-SHAY", notes: "Many French families go every weekend.", tags: ["phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.067':   { id: "fr.a1.routines.067", kind: "phrase", level: "a1", theme: "routines", fr: "rentrer à la maison", en: "to go home", ipa: "/ʁɑ̃.tʁe a la mɛ.zɔ̃/", respell: "rahn-TRAY ah lah meh-ZOHN", notes: "Je rentre à la maison à six heures.", tags: ["phrase"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.verbes-essentiels.026':   { id: "fr.a1.verbes-essentiels.026", kind: "sentence", level: "a1", theme: "verbes-essentiels", fr: "Elle reste chez elle ce week-end.", en: "She is staying home this weekend.", ipa: "/ɛl ʁɛst ʃez ɛl sə wikɛnd/", respell: "ell rest shay ell suh week-end", tags: ["verbe","maison"], drills: ["flashcard","voiceflash","sentence","dictation"], audioRef: null, version: 1 },
  'fr.a2.courses.024':   { id: "fr.a2.courses.024", kind: "word", level: "a2", theme: "courses", fr: "la boulangerie", en: "the bakery", respell: "lah boo-lahnzh-REE", gender: "f", tags: ["noun"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a2.pronoms-essentiels.055':   { id: "fr.a2.pronoms-essentiels.055", kind: "phrase", level: "a2", theme: "pronoms-essentiels", fr: "chez nous", en: "at our place", ipa: "/ʃe nu/", respell: "shay noo", tags: ["pronoun","stressed","nous"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.a2.systeme-de-sante.001':   { id: "fr.a2.systeme-de-sante.001", kind: "word", level: "a2", theme: "systeme-de-sante", fr: "le médecin", en: "the doctor", ipa: "med.sɛ̃", respell: "mayd-SAN", gender: "m", example: {"en":"The doctor examined me quickly.","fr":"Le médecin m'a examiné rapidement."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.a2.systeme-de-sante.042':   { id: "fr.a2.systeme-de-sante.042", kind: "word", level: "a2", theme: "systeme-de-sante", fr: "le dentiste", en: "the dentist", ipa: "dɑ̃.tist", respell: "dahn-TEEST", gender: "m", example: {"en":"I have a dentist appointment on Friday.","fr":"J'ai un rendez-vous chez le dentiste vendredi."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  'fr.a2.verbes.261':   { id: "fr.a2.verbes.261", kind: "sentence", level: "a2", theme: "verbes", fr: "Je vais au parc.", en: "I go to the park.", ipa: "/ʒə vɛ o paʁk/", respell: "zhuh veh oh PARK", notes: "vais, and there is no all- in it anywhere. This is the form to stop looking for a reason for.", tags: ["irregular","aller","paradigm","singular"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.a2.verbes.285':   { id: "fr.a2.verbes.285", kind: "sentence", level: "a2", theme: "verbes", fr: "Je viens de Paris.", en: "I am from Paris.", ipa: "/ʒə vjɛ̃ də pa.ʁi/", respell: "zhuh vyaⁿ duh pa-REE", notes: "Word for word the same as Je viens de manger until the fourth word. A place after de is where you are from.", tags: ["venir-de","origin","trap","nasal"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  'fr.sons.elision.029':   { id: "fr.sons.elision.029", kind: "word", level: "sons", theme: "elision", fr: "de Paris", en: "from Paris", ipa: "/də pa.ʁi/", respell: "duh pa-REE", tags: ["de","consonant-initial","no-elision"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.sons.elision.062':   { id: "fr.sons.elision.062", kind: "sentence", level: "sons", theme: "elision", fr: "J'habite à Lyon.", en: "I live in Lyon.", ipa: "/ʒa.bit a ljɔ̃/", respell: "zha-beet a LYOHⁿ", tags: ["je","h-muet","sentence","nasal"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  'fr.sons.muettes.004':   { id: "fr.sons.muettes.004", kind: "word", level: "sons", theme: "muettes", fr: "Paris", en: "Paris", ipa: "/pa.ʁi/", respell: "pa-REE", notes: "No S, ever, including in the city.", tags: ["silent-final","silent-s","proper-noun"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  'fr.sons.muettes.009':   { id: "fr.sons.muettes.009", kind: "word", level: "sons", theme: "muettes", fr: "chez", en: "at the home of", ipa: "/ʃe/", respell: "SHAY", tags: ["silent-final","silent-z"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.sons.muettes.038':   { id: "fr.sons.muettes.038", kind: "word", level: "sons", theme: "muettes", fr: "boulanger", en: "baker", ipa: "/bu.lɑ̃.ʒe/", respell: "boo-lahⁿ-ZHAY", gender: "m", notes: "A job noun in -er. Same ending as the infinitives, same silence.", tags: ["er-ending","silent-r","nasal"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  'fr.sons.nasales.029':   { id: "fr.sons.nasales.029", kind: "sentence", level: "sons", theme: "nasales", fr: "Mon grand frère travaille en France.", en: "My big brother works in France.", ipa: "mɔ̃ ɡʁɑ̃ fʁɛʁ tʁa.vaj ɑ̃ fʁɑ̃s", respell: "MOHⁿ GRAHⁿ FREHR tra-VAY AHⁿ FRAHⁿS", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  'fr.sons.nasales.157':   { id: "fr.sons.nasales.157", kind: "sentence", level: "sons", theme: "nasales", fr: "Vincent invite ses copains chez lui.", en: "Vincent invites his friends to his place.", ipa: "vɛ̃.sɑ̃ ɛ̃.vit se kɔ.pɛ̃ ʃe lɥi", respell: "vehⁿ-SAHⁿ ehⁿ-VEET SAY ko-PEHⁿ SHAY LÜEE", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  'fr.sons.voyelles.449':   { id: "fr.sons.voyelles.449", kind: "sentence", level: "sons", theme: "voyelles", fr: "Nous mangeons des crêpes sucrées chez ma grand-mère.", en: "We eat sweet crepes at my grandmother's.", ipa: "nu mɑ̃.ʒɔ̃ de kʁɛp sy.kʁe ʃe ma gʁɑ̃.mɛʁ", respell: "NOO mahⁿ-ZHOHⁿ DAY KREHP sü-KRAY SHAY MA grahⁿ-MEHR", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
};

/** What the database said, so a guard can compare a repair against the read
 *  rather than against a second copy of the same string. */
export const STORED_RESPELL: Record<string, string> = {
  'fr.a1.amis.011': "LUH koh-PAN",
  'fr.a1.amis.030': "byan-vuh-NÜ SHAY MWAH",
  'fr.a1.amis.059': "pah-SAY SHAY kehl-KUHN",
  'fr.a1.animaux-domestiques.108': "luh vay-tay-ree-NAIR",
  'fr.a1.animaux-domestiques.130': "ah-LAY shay luh vay-tay-ree-NAIR",
  'fr.a1.au-restaurant.001': "luh rehs-toh-RAHN",
  'fr.a1.deplacements.003': "lah GAHR",
  'fr.a1.famille.025': "LAH TAHⁿT",
  'fr.a1.famille.124': "dor-MEER shay",
  'fr.a1.famille.125': "rehs-TAY shay",
  'fr.a1.famille.126': "vuh-NEER shay",
  'fr.a1.la-ville.012': "loh-pee-TAL",
  'fr.a1.la-ville.103': "BAHNK",
  'fr.a1.la-ville.105': "far-mah-SEE",
  'fr.a1.marche.006': "luh mar-SHAY",
  'fr.a1.pays-et-nationalites.001': "LAH FRAHⁿSS",
  'fr.a1.pays-et-nationalites.011': "LAY zay-tah-zü-NEE",
  'fr.a1.pays-et-nationalites.051': "LUH zhah-POHⁿ",
  'fr.a1.pronoms-essentiels.075': "shay twah",
  'fr.a1.routines.063': "ah-LAY ah lay-KOHL",
  'fr.a1.routines.064': "ah-LAY oh mar-SHAY",
  'fr.a1.routines.067': "rahn-TRAY ah lah meh-ZOHN",
  'fr.a1.verbes-essentiels.026': "ell rest shay ell suh week-end",
  'fr.a2.courses.024': "lah boo-lahnzh-REE",
  'fr.a2.pronoms-essentiels.055': "shay noo",
  'fr.a2.systeme-de-sante.001': "mayd-SAN",
  'fr.a2.systeme-de-sante.042': "dahn-TEEST",
  'fr.a2.verbes.261': "zhuh veh oh PARK",
  'fr.a2.verbes.285': "zhuh vyaⁿ duh pa-REE",
  'fr.sons.elision.029': "duh pa-REE",
  'fr.sons.elision.062': "zha-beet a LYOHⁿ",
  'fr.sons.muettes.004': "pa-REE",
  'fr.sons.muettes.009': "SHAY",
  'fr.sons.muettes.038': "boo-lahⁿ-ZHAY",
  'fr.sons.nasales.029': "MOHⁿ GRAHⁿ FREHR tra-VAY AHⁿ FRAHⁿS",
  'fr.sons.nasales.157': "vehⁿ-SAHⁿ ehⁿ-VEET SAY ko-PEHⁿ SHAY LÜEE",
  'fr.sons.voyelles.449': "NOO mahⁿ-ZHOHⁿ DAY KREHP sü-KRAY SHAY MA grahⁿ-MEHR",
};

/** Re-measured on every regeneration. */
export const MEASURED = {
  chezRows: 283,
  chezCardReady: 20,
  chezBeforeAPlace: 0,
  blockCountAtRead: 127,
} as const;
