// A RECORDED READ OF POSTGRES. Generated by scripts/_a206_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 9 rows imported: 7 headwords out of 5 themes,
// plus 2 published sentences from this lesson's own theme.
// 8 respellings repaired. 0 supplied.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   THE FRAME CELLS. The corpus file's §3 claim is that the bare frame does not
//   exist, which is stronger than the brief's substring counts and is what the
//   generator refuses on. Both figures, 2026-08-15:
//
//     Je le vois.            exact   0   as a substring   2
//     Je la vois.            exact   0   as a substring   1
//     Je les vois.           exact   0   as a substring   0
//     Tu le connais.         exact   0   as a substring   0
//     Je ne le vois pas.     exact   0   as a substring   0
//     Je l'aime.             exact   0   as a substring   2
//     Je l'ai vu.            exact   0   as a substring   3
//     Je l'ai vue.           exact   0   as a substring   0
//     Je les achète.         exact   0   as a substring   0
//     Je la connais.         exact   0   as a substring   1
//
//   THE THEME. 486 published rows, 486 of them not this build's.
//   0 pre-existing duplicate fr groups, computed article-stripped the way
//   flashhub-coverage computes it. A clean sheet, and this build keeps it clean.
//
//   THE DIVERGENT RESPELLINGS, every published row for each word:
//
//     connaître
//       koh-NEHTR        2   fr.a1.famille.151 fr.sons.verbes-essentiels.048
//       kon-NETR         1   fr.a2.communaute.050
//     inviter
//       aⁿ-vee-TAY       1   fr.a1.amis.019
//       an-vee-TAY       4   fr.a1.evenements-familiaux.058 fr.a1.famille.094 fr.a1.les-fetes.083 fr.a2.communaute.054
//       ehn-vee-TAY      1   fr.a1.rp-famille.048
//     manger
//       mahn-ZHAY        2   fr.a1.cuisine.041 fr.a1.rp-repas.013
//       mahⁿ-ZHAY        2   fr.a1.routines.185 fr.sons.muettes.037
//     acheter
//       ahsh-TAY         4   fr.a1.argent-quotidien.061 fr.a2.courses.020 fr.a2.economie.034 fr.a2.verbes.026
//       ash-TAY          2   fr.a1.rp-achats.013 fr.sons.consonnes.019

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const PRONOMS_DIRECT_IMPORT_ROWS: Item[] = [
  { id: "fr.a1.amis.019", kind: "word", level: "a1", theme: "amis", fr: "inviter", en: "to invite", ipa: "/ɛ̃.vi.te/", respell: "aⁿ-vee-TAY", notes: "Verb, regular er group.", tags: ["amis","verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.pronoms-essentiels.087", kind: "sentence", level: "a1", theme: "pronoms-essentiels", fr: "Je la vois tous les jours.", en: "I see her every day.", ipa: "/ʒə la vwa tu le ʒuʁ/", notes: "The object pronoun 'la' has no accent, unlike the adverb 'là', though both sound the same.", tags: ["homophone"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.pronoms-essentiels.096", kind: "sentence", level: "a1", theme: "pronoms-essentiels", fr: "Je le vois chaque semaine.", en: "I see him every week.", ipa: "/ʒə lə vwa ʃak sə.mɛn/", notes: "Three weak schwa sounds in a row, je, le, se, can trick the ear into hearing fewer syllables than exist.", tags: ["e-muet"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.routines.185", kind: "word", level: "a1", theme: "routines", fr: "manger", en: "to eat", ipa: "/mɑ̃ʒe/", respell: "mahⁿ-ZHAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.courses.020", kind: "word", level: "a2", theme: "courses", fr: "acheter", en: "to buy", respell: "ahsh-TAY", tags: ["verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.011", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "voir", en: "to see", ipa: "/vwaʁ/", respell: "VWAR", notes: "irregular · je vois, nous voyons, ils voient", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.016", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "aimer", en: "to like, to love", ipa: "/eme/", respell: "eh-MAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.024", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "regarder", en: "to watch, to look at", ipa: "/ʁəɡaʁde/", respell: "ruh-gar-DAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.048", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "connaître", en: "to know (people, places)", ipa: "/kɔnɛtʁ/", respell: "koh-NEHTR", notes: "irregular · je connais, nous connaissons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** What Postgres held for each repair target when this was generated. The batch
 *  compares it against RESPELL_REPAIRS and refuses on a mismatch, so a repair
 *  table that has drifted from the database cannot silently repair nothing. */
export const STORED_RESPELL: Record<string, string> = {
  "fr.a2.communaute.050": "kon-NETR",
  "fr.a1.famille.094": "an-vee-TAY",
  "fr.a1.evenements-familiaux.058": "an-vee-TAY",
  "fr.a1.les-fetes.083": "an-vee-TAY",
  "fr.a2.communaute.054": "an-vee-TAY",
  "fr.a1.rp-famille.048": "ehn-vee-TAY",
  "fr.a1.cuisine.041": "mahn-ZHAY",
  "fr.a1.rp-repas.013": "mahn-ZHAY"
};

/** Whole-sentence counts for each authored frame, excluding this build's rows. */
export const FRAME_EXACT: Record<string, number> = {
  "Je le vois.": 0,
  "Je la vois.": 0,
  "Je les vois.": 0,
  "Tu le connais.": 0,
  "Je ne le vois pas.": 0,
  "Je l'aime.": 0,
  "Je l'ai vu.": 0,
  "Je l'ai vue.": 0,
  "Je les achète.": 0,
  "Je la connais.": 0
};
/** The same frames counted as substrings, which is what the brief's probe did. */
export const FRAME_SUBSTRING: Record<string, number> = {
  "Je le vois.": 2,
  "Je la vois.": 1,
  "Je les vois.": 0,
  "Tu le connais.": 0,
  "Je ne le vois pas.": 0,
  "Je l'aime.": 2,
  "Je l'ai vu.": 3,
  "Je l'ai vue.": 0,
  "Je les achète.": 0,
  "Je la connais.": 1
};

/** Every published respelling for the four words that diverge. */
export const RESPELL_POPULATION: Record<string, Record<string, string[]>> = {
  "connaître": {
    "koh-NEHTR": [
      "fr.a1.famille.151",
      "fr.sons.verbes-essentiels.048"
    ],
    "kon-NETR": [
      "fr.a2.communaute.050"
    ]
  },
  "inviter": {
    "aⁿ-vee-TAY": [
      "fr.a1.amis.019"
    ],
    "an-vee-TAY": [
      "fr.a1.evenements-familiaux.058",
      "fr.a1.famille.094",
      "fr.a1.les-fetes.083",
      "fr.a2.communaute.054"
    ],
    "ehn-vee-TAY": [
      "fr.a1.rp-famille.048"
    ]
  },
  "manger": {
    "mahn-ZHAY": [
      "fr.a1.cuisine.041",
      "fr.a1.rp-repas.013"
    ],
    "mahⁿ-ZHAY": [
      "fr.a1.routines.185",
      "fr.sons.muettes.037"
    ]
  },
  "acheter": {
    "ahsh-TAY": [
      "fr.a1.argent-quotidien.061",
      "fr.a2.courses.020",
      "fr.a2.economie.034",
      "fr.a2.verbes.026"
    ],
    "ash-TAY": [
      "fr.a1.rp-achats.013",
      "fr.sons.consonnes.019"
    ]
  }
};

export const MEASURED_AT = 'read from Postgres by scripts/_a206_manifest.ts';
export const MEASURED_ROWS = {
  imported: 9,
  headwords: 7,
  sentences: 2,
  themeRowsBefore: 486,
  themeDuplicateGroups: 0,
  repairs: 8,
  framesMeasured: 10,
  framesPresentAsWholeSentence: 0,
} as const;
