// A RECORDED READ OF POSTGRES. Generated by scripts/_a223_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 20 rows imported out of 5 themes.
// 8 rows read and refused; see READ_NOT_IMPORTED in the corpus file.
// 0 respellings repaired, 0 supplied. This build repairs nothing.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   THE FRAME VERB'S CELLS, published sentences per cell, excluding this
//   lesson's own rows. ALL THIRTEEN WERE ZERO on 2026-08-15, which is why the
//   whole paradigm, the whole negative and the whole exception are authored:
//
//     je me suis lavé                0
//     tu t'es lavé                   0
//     il s'est lavé                  0
//     nous nous sommes lavés         0
//     vous vous êtes lavés           0
//     ils se sont lavés              0
//     elle s'est lavée               0
//     elles se sont lavées           0
//     ils se sont levés              0
//     vous vous êtes levés           0
//     elle s'est lavé les mains      0
//     ne me suis pas                 0
//     ne se sont pas                 0
//
//   AND THE CONSTRUCTION ITSELF IS EVERYWHERE. That pair of figures is the
//   Owns: the shape is common and the verb has never been built:
//
//     s'est                        224
//     se sont                      104
//     nous nous sommes              46
//     me suis                       38
//     vous vous êtes                 0
//     elle s'est                    51
//
//   THE ASYMMETRY. The avoir sentence that causes the error is published and
//   the être sentence that corrects it is not:
//
//     j'ai lavé la voiture           2
//     je me suis lavé                0
//
//   THE EXCEPTION.  3 published rows still show a feminine subject with an
//     unagreed second word (« Elle s'est cassé le bras »). Corpus §6: that is
//     why the exception is named receptively rather than left out.
//
//   THE BLOCKS.  fr.a2.verbes holds 559 rows other than this build's.
//     a2.21's fr.a2.verbes.651..fr.a2.verbes.720 holds 46.
//     a2.22's fr.a2.verbes.721..fr.a2.verbes.790 holds 31.
//     Rows inside fr.a2.verbes.791..fr.a2.verbes.860 that this build does not own: none.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const PRONOMINAUX_PASSE_IMPORT_ROWS: Record<string, Item> = {
  'fr.a1.corps.209':   { id: "fr.a1.corps.209", kind: "sentence", level: "a1", theme: "corps", fr: "Je me lave les mains avant de manger.", en: "I wash my hands before eating.", ipa: "ʒə mə lav le mɛ̃ a.vɑ̃ də mɑ̃.ʒe", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, skill: "PE", register: "courant", verbCheck: {"tense":"présent","number":"s","person":"1","infinitive":"se laver"} },
  'fr.a1.cuisine.183':   { id: "fr.a1.cuisine.183", kind: "word", level: "a1", theme: "cuisine", fr: "laver", en: "to wash", ipa: "/la.ve/", respell: "lah-VAY", tags: ["verb","kitchen"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.001':   { id: "fr.a1.routines.001", kind: "phrase", level: "a1", theme: "routines", fr: "se lever", en: "to get up", respell: "suh luh-VAY", tags: ["verbs","reflexive","daily-routine"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.010':   { id: "fr.a1.routines.010", kind: "word", level: "a1", theme: "routines", fr: "se réveiller", en: "to wake up", ipa: "/sə ʁeveje/", respell: "suh ray-veh-YAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.011':   { id: "fr.a1.routines.011", kind: "word", level: "a1", theme: "routines", fr: "se doucher", en: "to take a shower", ipa: "/sə duʃe/", respell: "suh doo-SHAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.012':   { id: "fr.a1.routines.012", kind: "word", level: "a1", theme: "routines", fr: "s'habiller", en: "to get dressed", ipa: "/sabije/", respell: "sah-bee-YAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.019':   { id: "fr.a1.routines.019", kind: "phrase", level: "a1", theme: "routines", fr: "se brosser les dents", en: "to brush one's teeth", ipa: "/sə bʁɔse le dɑ̃/", respell: "suh bro-SAY lay DAHⁿ", tags: ["daily","hygiene"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.020':   { id: "fr.a1.routines.020", kind: "word", level: "a1", theme: "routines", fr: "se coucher", en: "to go to bed", ipa: "/sə kuʃe/", respell: "suh koo-SHAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.028':   { id: "fr.a1.routines.028", kind: "word", level: "a1", theme: "routines", fr: "se laver", en: "to wash up", respell: "suh lah-VAY", tags: ["verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.034':   { id: "fr.a1.routines.034", kind: "word", level: "a1", theme: "routines", fr: "se reposer", en: "to rest", respell: "suh ruh-poh-ZAY", tags: ["verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.087':   { id: "fr.a1.routines.087", kind: "word", level: "a1", theme: "routines", fr: "se dépêcher", en: "to hurry", ipa: "/sə de.pɛ.ʃe/", respell: "suh day-peh-SHAY", notes: "Dépêche-toi! Hurry up!", tags: ["verb","reflexive"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.rp-recits-temps.066':   { id: "fr.a1.rp-recits-temps.066", kind: "sentence", level: "a1", theme: "rp-recits-temps", fr: "Ce matin, j'ai lavé la voiture.", en: "This morning, I washed the car.", notes: "passé composé avec avoir", tags: ["maison"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a1.rp-recits-temps.180':   { id: "fr.a1.rp-recits-temps.180", kind: "sentence", level: "a1", theme: "rp-recits-temps", fr: "Le lendemain matin, elle s'est levée à cinq heures.", en: "The next morning, she got up at five o'clock.", ipa: "lə lɑ̃d.mɛ̃ ma.tɛ̃ ɛl sɛ lə.ve a sɛ̃k œʁ", notes: "Levée agrees with the feminine subject elle in this reflexive verb.", tags: ["accord-genre"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a1.rp-recits-temps.199':   { id: "fr.a1.rp-recits-temps.199", kind: "sentence", level: "a1", theme: "rp-recits-temps", fr: "Ce matin, nous nous sommes levés très tôt pour partir.", en: "This morning, we got up very early to leave.", ipa: "sə ma.tɛ̃ nu nu sɔm lə.ve tʁɛ to puʁ paʁ.tiʁ", notes: "Levés takes an s to agree with the plural subject nous.", tags: ["accord-nombre"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.corps.001':   { id: "fr.a2.corps.001", kind: "sentence", level: "a2", theme: "corps", fr: "Elle s'est cassé le bras en tombant du vélo.", en: "She broke her arm falling off her bike.", notes: "{\"tiles\":[{\"w\":\"Elle s'est cassé\",\"t\":\"she broke\"},{\"w\":\"le bras\",\"t\":\"her arm\"},{\"w\":\"en tombant\",\"t\":\"falling\"},{\"w\":\"du vélo.\",\"t\":\"off her bike\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  'fr.a2.routines.032':   { id: "fr.a2.routines.032", kind: "sentence", level: "a2", theme: "routines", fr: "Ce matin, je me suis levé tôt pour aller courir.", en: "This morning, I got up early to go running.", ipa: "/sə matɛ̃ ʒə mə sɥi ləve to puʁ ale kuʁiʁ/", notes: "The past participle 'levé' agrees with the reflexive subject, so a female speaker would need to add an e.", tags: ["accord"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.routines.039':   { id: "fr.a2.routines.039", kind: "sentence", level: "a2", theme: "routines", fr: "Ils se sont couchés très tard hier soir.", en: "They went to bed very late last night.", ipa: "/il sə sɔ̃ kuʃe tʁɛ taʁ jɛʁ swaʁ/", notes: "'Couchés' takes a plural s to agree with the plural reflexive subject ils.", tags: ["accord"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a2.routines.049':   { id: "fr.a2.routines.049", kind: "sentence", level: "a2", theme: "routines", fr: "Ce matin, je me suis réveillé tôt, puis j'ai pris une douche.", en: "This morning, I woke up early, then I took a shower.", notes: "{\"tiles\":[{\"w\":\"Ce matin,\",\"t\":\"this morning\"},{\"w\":\"je me suis réveillé tôt,\",\"t\":\"i woke up early\"},{\"w\":\"puis j'ai pris une douche.\",\"t\":\"then i took a shower\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  'fr.sons.verbes-essentiels.001':   { id: "fr.sons.verbes-essentiels.001", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "être", en: "to be", ipa: "/ɛtʁ/", respell: "ETR", notes: "irregular · je suis, tu es, il est, nous sommes", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.sons.verbes-essentiels.002':   { id: "fr.sons.verbes-essentiels.002", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "avoir", en: "to have", ipa: "/avwaʁ/", respell: "ah-VWAR", notes: "irregular · j'ai, tu as, il a, nous avons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
};

/** What each imported row's respelling said on the day of the read, so a repair
 *  or a drift is visible without another database call. */
export const STORED_RESPELL: Record<string, string | null> = {
  'fr.a1.corps.209': null,
  'fr.a1.cuisine.183': "lah-VAY",
  'fr.a1.routines.001': "suh luh-VAY",
  'fr.a1.routines.010': "suh ray-veh-YAY",
  'fr.a1.routines.011': "suh doo-SHAY",
  'fr.a1.routines.012': "sah-bee-YAY",
  'fr.a1.routines.019': "suh bro-SAY lay DAHⁿ",
  'fr.a1.routines.020': "suh koo-SHAY",
  'fr.a1.routines.028': "suh lah-VAY",
  'fr.a1.routines.034': "suh ruh-poh-ZAY",
  'fr.a1.routines.087': "suh day-peh-SHAY",
  'fr.a1.rp-recits-temps.066': null,
  'fr.a1.rp-recits-temps.180': null,
  'fr.a1.rp-recits-temps.199': null,
  'fr.a2.corps.001': null,
  'fr.a2.routines.032': null,
  'fr.a2.routines.039': null,
  'fr.a2.routines.049': null,
  'fr.sons.verbes-essentiels.001': "ETR",
  'fr.sons.verbes-essentiels.002': "ah-VWAR",
};

/** Published sentences per cell of the frame verb, excluding this build's own
 *  rows. Corpus §5 claims every one of these is zero. */
export const CELL_EVIDENCE: Record<string, number> = {
  "je me suis lavé": 0,
  "tu t'es lavé": 0,
  "il s'est lavé": 0,
  "nous nous sommes lavés": 0,
  "vous vous êtes lavés": 0,
  "ils se sont lavés": 0,
  "elle s'est lavée": 0,
  "elles se sont lavées": 0,
  "ils se sont levés": 0,
  "vous vous êtes levés": 0,
  "elle s'est lavé les mains": 0,
  "ne me suis pas": 0,
  "ne se sont pas": 0
};

/** The construction, which is everywhere, and the asymmetry, which is the Owns. */
export const CONSTRUCTION_EVIDENCE: Record<string, number> = {
  "s'est": 224,
  "se sont": 104,
  "nous nous sommes": 46,
  "me suis": 38,
  "vous vous êtes": 0,
  "elle s'est": 51
};
export const ASYMMETRY_EVIDENCE: Record<string, number> = {
  "j'ai lavé la voiture": 2,
  "je me suis lavé": 0
};

export const MEASURED_AT = 'read from Postgres by scripts/_a223_manifest.ts';
export const MEASURED_ROWS = {
  imported: 20,
  unagreedPublished: 3,
  a221BlockRows: 46,
  a222BlockRows: 31,
  verbesRowsBefore: 559,
  frameCellsMeasured: 13,
  frameCellsNonZero: 0,
} as const;
