// A RECORDED READ OF POSTGRES. Generated by scripts/_a224_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 18 rows imported: 10 headwords, 2 respelled pronoun phrases and
// 6 published sentences, out of 4 themes. 0 headwords authored.
// 15 respellings repaired, 6 of them BLIND to the checker.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   THE FRAME CELLS. Every one is absent as a WHOLE SENTENCE, which is the
//   claim the generator refuses on. The substring column is what the brief's
//   probe measured and it is a weaker statement. 2026-08-15:
//
//     Je parle à Marie.              exact   0   as a substring   0
//     Je lui parle.                  exact   0   as a substring   1
//     Je parle à mes parents.        exact   0   as a substring   0
//     Je leur parle.                 exact   0   as a substring   1
//     Je réponds à Paul.             exact   0   as a substring   0
//     Je lui réponds.                exact   0   as a substring   0
//     Je lui téléphone.              exact   0   as a substring   1
//     Je lui demande.                exact   0   as a substring   0
//     Je lui dis bonjour.            exact   0   as a substring   0
//     Je leur montre la photo.       exact   0   as a substring   0
//     Il lui offre un café.          exact   0   as a substring   0
//     Je leur écris.                 exact   0   as a substring   1
//     Je lui envoie une carte.       exact   0   as a substring   0
//     Je leur donne les clés.        exact   0   as a substring   0
//     Tu lui parles.                 exact   0   as a substring   0
//     Il lui répond.                 exact   0   as a substring   0
//     Elle lui écrit.                exact   0   as a substring   0
//     Nous leur parlons.             exact   0   as a substring   0
//     Vous leur écrivez.             exact   0   as a substring   0
//     Ils lui téléphonent.           exact   0   as a substring   0
//     Je lui écris.                  exact   0   as a substring   0
//     Voici leur maison.             exact   0   as a substring   0
//     Voici leurs clés.              exact   0   as a substring   0
//     Je leur montre leur maison.    exact   0   as a substring   0
//     Je parle avec lui.             exact   0   as a substring   0
//     Je pars sans lui.              exact   0   as a substring   0
//     C'est pour lui.                exact   0   as a substring   0
//     Je ne lui parle pas.           exact   0   as a substring   0
//     Je ne leur parle pas.          exact   0   as a substring   0
//     Il ne lui répond pas.          exact   0   as a substring   0
//     Je ne leur écris pas.          exact   0   as a substring   0
//     Je lui ai parlé.               exact   0   as a substring   0
//     Je leur ai parlé.              exact   0   as a substring   0
//     Je lui ai écrit.               exact   0   as a substring   0
//     Je ne lui ai pas parlé.        exact   0   as a substring   0
//     Je lui prête un stylo.         exact   0   as a substring   0
//     Elle leur explique.            exact   0   as a substring   0
//     Il lui promet.                 exact   0   as a substring   0
//     Nous lui obéissons.            exact   0   as a substring   0
//     Oui, je lui ai parlé hier.     exact   0   as a substring   0
//     Non, je ne leur ai pas écrit.  exact   0   as a substring   0
//     Je vais lui téléphoner.        exact   0   as a substring   0
//     Je leur montre les photos.     exact   0   as a substring   0
//     Oui, je leur parle souvent.    exact   0   as a substring   0
//     Je lui demande demain.         exact   0   as a substring   0
//     Tu lui as répondu ?            exact   0   as a substring   0
//     Elle leur a parlé.             exact   0   as a substring   0
//     Je lui ai donné les clés.      exact   0   as a substring   0
//     Tu leur téléphones ?           exact   0   as a substring   0
//     Je lui réponds toujours.       exact   0   as a substring   0
//
//   THE CONSTRUCTION, which is a different question from the frames and which
//   the brief answers wrongly. It is NOT almost absent:
//
//     je lui           7
//     je leur          6
//     il lui           5
//     elle lui         3
//     nous leur        2
//     lui parle        6
//     leur parle       2
//
//   THE THEME. 534 published rows, 534 of them not this build's.
//   0 pre-existing duplicate fr groups, computed article-stripped the way
//   flashhub-coverage computes it, and this build adds none.
//
//   THE RESPELL POPULATION, every published row for each word, with the count
//   the real hasPlainNasalFor flags:
//
//     répondre   (0 flagged)
//       ray-POHNDR          6   fr.a1.dictee.108 fr.a1.douane-et-immigration.075 fr.a2.disciplines.055 fr.a2.examens-et-diplomes.089 fr.a2.internet.083 fr.sons.verbes-essentiels.031
//       ray-POHⁿDR          1   fr.a2.verbes.020
//     demander   (4 flagged)
//       duh-mahn-DAY        4   fr.a1.douane-et-immigration.076 fr.a2.bureau.088 fr.sons.faux-amis.022 fr.sons.verbes-essentiels.018
//       duh-mahⁿ-DAY        1   fr.a2.verbes.019
//     montrer   (1 flagged)
//       mohn-TRAY           1   fr.a1.douane-et-immigration.059
//       mohⁿ-TRAY           1   fr.sons.verbes-essentiels.054
//     envoyer   (4 flagged)
//       ahn-vwa-YAY         2   fr.a1.rp-technologie.043 fr.a2.internet.081
//       ahn-vwah-YAY        2   fr.a2.verbes.023 fr.sons.verbes-essentiels.046
//     parler   (0 flagged)
//       par-LAY             5   fr.a1.dictee.093 fr.a1.rp-societe.045 fr.sons.consonnes.097 fr.sons.muettes.036 fr.sons.verbes-essentiels.015
//       pahr-LAY            1   fr.a1.rp-travail-etudes.042
//     donner   (0 flagged)
//       do-NAY              1   fr.a2.rp-societe.055
//       doh-NAY             2   fr.sons.consonnes.140 fr.sons.verbes-essentiels.013
//     écrire   (0 flagged)
//       ay-KREER            4   fr.a1.dictee.090 fr.a1.ecole.049 fr.a1.rp-travail-etudes.039 fr.sons.consonnes.110
//     téléphoner   (0 flagged)
//       tay-lay-foh-NAY     2   fr.a1.verbes-essentiels.003 fr.a2.bureau.083
//
//   THE FALSE POSITIVES, which corrections §6 asks every build to look for and
//   which a2.06 looked for and did not find:
//
//     téléphone    tay-lay-FOHN   FLAGGED   →   tay-lay-FON    clean
//     donne        DOHN           FLAGGED   →   DON            clean

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const PRONOMS_INDIRECT_IMPORT_ROWS: Item[] = [
  { id: "fr.a1.dictee.090", kind: "word", level: "a1", theme: "dictee", fr: "écrire", en: "to write", ipa: "e.kʁiʁ", respell: "ay-KREER", example: {"en":"You must write your name at the top of the page.","fr":"Il faut écrire son nom en haut de la page."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.a1.pronoms-essentiels.126", kind: "sentence", level: "a1", theme: "pronoms-essentiels", fr: "Je leur parle chaque matin.", en: "I speak to them every morning.", ipa: "/ʒə lœʁ paʁl ʃak ma.tɛ̃/", notes: "The indirect object pronoun 'leur' never takes an s, unlike the possessive adjective 'leurs'.", tags: ["orthographe"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.verbes-essentiels.003", kind: "word", level: "a1", theme: "verbes-essentiels", fr: "téléphoner", en: "to phone, to call", ipa: "/telefɔne/", respell: "tay-lay-foh-NAY", example: {"en":"I call my grandmother every week.","fr":"Je téléphone à ma grand-mère toutes les semaines."}, notes: "Followed by à: téléphoner à quelqu'un.", tags: ["verbe","communication"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.017", kind: "phrase", level: "a2", theme: "pronoms-essentiels", fr: "lui parler", en: "to talk to him / to her", ipa: "/lɥi paʁle/", respell: "lwee par-LAY", notes: "Lui replaces à lui or à elle; as an indirect object it never changes for gender.", tags: ["pronoun","indirect-object","lui"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.020", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Elle lui demande son avis sur le projet.", en: "She asks him for his opinion on the project.", tags: ["pronoun","indirect-object","lui"], drills: ["flashcard","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.025", kind: "phrase", level: "a2", theme: "pronoms-essentiels", fr: "leur parler", en: "to talk to them", ipa: "/lœʁ paʁle/", respell: "luhr par-LAY", notes: "Leur means to them; do not confuse it with the possessive leur, which means their.", tags: ["pronoun","indirect-object","leur"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.026", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Je leur écris chaque semaine.", en: "I write to them every week.", tags: ["pronoun","indirect-object","leur"], drills: ["flashcard","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.190", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Je le vois.", en: "I see it.", ipa: "/ʒə lə vwa/", respell: "zhuh luh VWAH", notes: "THE FRAME. Eight letters, so the dictée takes it in LETTERS mode, which is the only mode that can test a position.", tags: ["a2","pronoun","position","present"], drills: ["flashcard","voiceflash","dictation","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.196", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Je la connais.", en: "I know her.", ipa: "/ʒə la kɔ.nɛ/", respell: "zhuh lah koh-NEH", notes: "And la covers a person as readily as a thing. English changes word here, from \"Marie\" to \"her\"; French does not.", tags: ["a2","pronoun","position","present"], drills: ["flashcard","voiceflash","dictation","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.019", kind: "word", level: "a2", theme: "verbes", fr: "demander", en: "to ask for", ipa: "də.mɑ̃.de", respell: "duh-mahⁿ-DAY", example: {"en":"He asks for an appointment with the doctor.","fr":"Il demande un rendez-vous chez le médecin."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  { id: "fr.a2.verbes.020", kind: "word", level: "a2", theme: "verbes", fr: "répondre", en: "to answer", ipa: "ʁe.pɔ̃dʁ", respell: "ray-POHⁿDR", example: {"en":"You must answer before Friday.","fr":"Vous devez répondre avant vendredi."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  { id: "fr.a2.verbes.807", kind: "sentence", level: "a2", theme: "verbes", fr: "Elle s'est lavé les mains.", en: "She washed her hands.", ipa: "/ɛl sɛ la.ve le mɛ̃/", respell: "ehl seh lah-VAY lay MAHⁿ", notes: "NAMED, NOT TAUGHT. Something is named after the second word and the ending goes. The reason is a2.24s. Receptive drills only: no flashcard, no voiceflash, no dictation.", tags: ["a2","pronominal","passe-compose","etre","object","receptive"], drills: ["sentence","review"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.005", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "dire", en: "to say, to tell", ipa: "/diʁ/", respell: "DEER", notes: "irregular · je dis, vous dites, ils disent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.013", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "donner", en: "to give", ipa: "/dɔne/", respell: "doh-NAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.015", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "parler", en: "to speak, to talk", ipa: "/paʁle/", respell: "par-LAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.046", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "envoyer", en: "to send", ipa: "/ɑ̃vwaje/", respell: "ahn-vwah-YAY", notes: "spelling change · j'envoie, nous envoyons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.053", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "offrir", en: "to offer, to give (a gift)", ipa: "/ɔfʁiʁ/", respell: "oh-FREER", notes: "irregular · conjugates like an -er verb: j'offre", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.054", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "montrer", en: "to show", ipa: "/mɔ̃tʁe/", respell: "mohⁿ-TRAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** What Postgres held for each repair target when this was generated. The batch
 *  compares it against RESPELL_REPAIRS and refuses on a mismatch, so a repair
 *  table that has drifted from the database cannot silently repair nothing. */
export const STORED_RESPELL: Record<string, string> = {
  "fr.sons.verbes-essentiels.031": "ray-POHNDR",
  "fr.a1.dictee.108": "ray-POHNDR",
  "fr.a1.douane-et-immigration.075": "ray-POHNDR",
  "fr.a2.disciplines.055": "ray-POHNDR",
  "fr.a2.examens-et-diplomes.089": "ray-POHNDR",
  "fr.a2.internet.083": "ray-POHNDR",
  "fr.sons.verbes-essentiels.018": "duh-mahn-DAY",
  "fr.a1.douane-et-immigration.076": "duh-mahn-DAY",
  "fr.a2.bureau.088": "duh-mahn-DAY",
  "fr.sons.faux-amis.022": "duh-mahn-DAY",
  "fr.a1.douane-et-immigration.059": "mohn-TRAY",
  "fr.sons.verbes-essentiels.046": "ahn-vwah-YAY",
  "fr.a2.verbes.023": "ahn-vwah-YAY",
  "fr.a1.rp-technologie.043": "ahn-vwa-YAY",
  "fr.a2.internet.081": "ahn-vwa-YAY"
};

/** Whole-sentence counts for each authored frame, excluding this build's rows. */
export const FRAME_EXACT: Record<string, number> = {
  "Je parle à Marie.": 0,
  "Je lui parle.": 0,
  "Je parle à mes parents.": 0,
  "Je leur parle.": 0,
  "Je réponds à Paul.": 0,
  "Je lui réponds.": 0,
  "Je lui téléphone.": 0,
  "Je lui demande.": 0,
  "Je lui dis bonjour.": 0,
  "Je leur montre la photo.": 0,
  "Il lui offre un café.": 0,
  "Je leur écris.": 0,
  "Je lui envoie une carte.": 0,
  "Je leur donne les clés.": 0,
  "Tu lui parles.": 0,
  "Il lui répond.": 0,
  "Elle lui écrit.": 0,
  "Nous leur parlons.": 0,
  "Vous leur écrivez.": 0,
  "Ils lui téléphonent.": 0,
  "Je lui écris.": 0,
  "Voici leur maison.": 0,
  "Voici leurs clés.": 0,
  "Je leur montre leur maison.": 0,
  "Je parle avec lui.": 0,
  "Je pars sans lui.": 0,
  "C'est pour lui.": 0,
  "Je ne lui parle pas.": 0,
  "Je ne leur parle pas.": 0,
  "Il ne lui répond pas.": 0,
  "Je ne leur écris pas.": 0,
  "Je lui ai parlé.": 0,
  "Je leur ai parlé.": 0,
  "Je lui ai écrit.": 0,
  "Je ne lui ai pas parlé.": 0,
  "Je lui prête un stylo.": 0,
  "Elle leur explique.": 0,
  "Il lui promet.": 0,
  "Nous lui obéissons.": 0,
  "Oui, je lui ai parlé hier.": 0,
  "Non, je ne leur ai pas écrit.": 0,
  "Je vais lui téléphoner.": 0,
  "Je leur montre les photos.": 0,
  "Oui, je leur parle souvent.": 0,
  "Je lui demande demain.": 0,
  "Tu lui as répondu ?": 0,
  "Elle leur a parlé.": 0,
  "Je lui ai donné les clés.": 0,
  "Tu leur téléphones ?": 0,
  "Je lui réponds toujours.": 0
};
/** The same frames counted as substrings, which is what the brief's probe did. */
export const FRAME_SUBSTRING: Record<string, number> = {
  "Je parle à Marie.": 0,
  "Je lui parle.": 1,
  "Je parle à mes parents.": 0,
  "Je leur parle.": 1,
  "Je réponds à Paul.": 0,
  "Je lui réponds.": 0,
  "Je lui téléphone.": 1,
  "Je lui demande.": 0,
  "Je lui dis bonjour.": 0,
  "Je leur montre la photo.": 0,
  "Il lui offre un café.": 0,
  "Je leur écris.": 1,
  "Je lui envoie une carte.": 0,
  "Je leur donne les clés.": 0,
  "Tu lui parles.": 0,
  "Il lui répond.": 0,
  "Elle lui écrit.": 0,
  "Nous leur parlons.": 0,
  "Vous leur écrivez.": 0,
  "Ils lui téléphonent.": 0,
  "Je lui écris.": 0,
  "Voici leur maison.": 0,
  "Voici leurs clés.": 0,
  "Je leur montre leur maison.": 0,
  "Je parle avec lui.": 0,
  "Je pars sans lui.": 0,
  "C'est pour lui.": 0,
  "Je ne lui parle pas.": 0,
  "Je ne leur parle pas.": 0,
  "Il ne lui répond pas.": 0,
  "Je ne leur écris pas.": 0,
  "Je lui ai parlé.": 0,
  "Je leur ai parlé.": 0,
  "Je lui ai écrit.": 0,
  "Je ne lui ai pas parlé.": 0,
  "Je lui prête un stylo.": 0,
  "Elle leur explique.": 0,
  "Il lui promet.": 0,
  "Nous lui obéissons.": 0,
  "Oui, je lui ai parlé hier.": 0,
  "Non, je ne leur ai pas écrit.": 0,
  "Je vais lui téléphoner.": 0,
  "Je leur montre les photos.": 0,
  "Oui, je leur parle souvent.": 0,
  "Je lui demande demain.": 0,
  "Tu lui as répondu ?": 0,
  "Elle leur a parlé.": 0,
  "Je lui ai donné les clés.": 0,
  "Tu leur téléphones ?": 0,
  "Je lui réponds toujours.": 0
};
/** The CONSTRUCTION, which is not the same question and which the brief got
 *  wrong. Header §1 of the corpus file. */
export const CONSTRUCTION_COUNT: Record<string, number> = {
  "je lui": 7,
  "je leur": 6,
  "il lui": 5,
  "elle lui": 3,
  "nous leur": 2,
  "lui parle": 6,
  "leur parle": 2
};

/** Every published respelling for the eight words this build inspected. */
export const RESPELL_POPULATION: Record<string, Record<string, string[]>> = {
  "répondre": {
    "ray-POHNDR": [
      "fr.a1.dictee.108",
      "fr.a1.douane-et-immigration.075",
      "fr.a2.disciplines.055",
      "fr.a2.examens-et-diplomes.089",
      "fr.a2.internet.083",
      "fr.sons.verbes-essentiels.031"
    ],
    "ray-POHⁿDR": [
      "fr.a2.verbes.020"
    ]
  },
  "demander": {
    "duh-mahn-DAY": [
      "fr.a1.douane-et-immigration.076",
      "fr.a2.bureau.088",
      "fr.sons.faux-amis.022",
      "fr.sons.verbes-essentiels.018"
    ],
    "duh-mahⁿ-DAY": [
      "fr.a2.verbes.019"
    ]
  },
  "montrer": {
    "mohn-TRAY": [
      "fr.a1.douane-et-immigration.059"
    ],
    "mohⁿ-TRAY": [
      "fr.sons.verbes-essentiels.054"
    ]
  },
  "envoyer": {
    "ahn-vwa-YAY": [
      "fr.a1.rp-technologie.043",
      "fr.a2.internet.081"
    ],
    "ahn-vwah-YAY": [
      "fr.a2.verbes.023",
      "fr.sons.verbes-essentiels.046"
    ]
  },
  "parler": {
    "par-LAY": [
      "fr.a1.dictee.093",
      "fr.a1.rp-societe.045",
      "fr.sons.consonnes.097",
      "fr.sons.muettes.036",
      "fr.sons.verbes-essentiels.015"
    ],
    "pahr-LAY": [
      "fr.a1.rp-travail-etudes.042"
    ]
  },
  "donner": {
    "do-NAY": [
      "fr.a2.rp-societe.055"
    ],
    "doh-NAY": [
      "fr.sons.consonnes.140",
      "fr.sons.verbes-essentiels.013"
    ]
  },
  "écrire": {
    "ay-KREER": [
      "fr.a1.dictee.090",
      "fr.a1.ecole.049",
      "fr.a1.rp-travail-etudes.039",
      "fr.sons.consonnes.110"
    ]
  },
  "téléphoner": {
    "tay-lay-foh-NAY": [
      "fr.a1.verbes-essentiels.003",
      "fr.a2.bureau.083"
    ]
  }
};

export const MEASURED_AT = 'read from Postgres by scripts/_a224_manifest.ts';
export const MEASURED_ROWS = {
  imported: 18,
  headwords: 10,
  phrases: 2,
  sentences: 6,
  themeRowsBefore: 534,
  themeDuplicateGroups: 0,
  repairs: 15,
  blindRepairs: 6,
  falsePositives: 2,
  framesMeasured: 50,
  framesPresentAsWholeSentence: 0,
} as const;
