// A RECORDED READ OF POSTGRES. Generated by scripts/_a222_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 20 rows imported out of 6 themes.
// 7 rows read and refused; see READ_NOT_IMPORTED in the corpus file.
// 0 respellings repaired, 0 supplied. This build repairs nothing.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION:
//
//   THE PARADIGM EVIDENCE, published sentences per person, excluding this
//   lesson's own rows. The two that prove the pronoun moves are the two the
//   corpus does not have, which is why the paradigm is authored:
//
//     je me lève            14
//     tu te lèves            1
//     il se lève             5
//     nous nous levons       3
//     vous vous levez        0
//     ils se lèvent          0
//     je me lave             1
//     tu te laves            0
//     il se lave             2
//     nous nous lavons       1
//     vous vous lavez        0
//     ils se lavent          0
//     je ne me lève pas      0
//     je ne me lave pas      0
//
//   THE SHAPE. The corpus stores these verbs FRAMED with se, which settles the
//   ledger question doctrine §E left open:
//     framed  s'habiller 4 · se coucher 3 · se dépêcher 4 · se doucher 3 · se laver 3 · se lever 3 · se reposer 8 · se réveiller 2
//     bare    laver 3 · lever 1
//
//   THE THEMES.  routine 0 published · routines 339 published
//     The unit declares « routine ». It has no rows and no component reads the
//     declaration. Corpus file §4.
//
//   THE BLOCKS.  fr.a2.verbes holds 528 rows other than this build's.
//     a2.21's fr.a2.verbes.651..fr.a2.verbes.720 holds 46.
//     Rows inside fr.a2.verbes.721..fr.a2.verbes.790 that this build does not own: none.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const PRONOMINAUX_IMPORT_ROWS: Record<string, Item> = {
  'fr.a1.corps.209':   { id: "fr.a1.corps.209", kind: "sentence", level: "a1", theme: "corps", fr: "Je me lave les mains avant de manger.", en: "I wash my hands before eating.", ipa: "ʒə mə lav le mɛ̃ a.vɑ̃ də mɑ̃.ʒe", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, skill: "PE", register: "courant", verbCheck: {"tense":"présent","number":"s","person":"1","infinitive":"se laver"} },
  'fr.a1.cuisine.183':   { id: "fr.a1.cuisine.183", kind: "word", level: "a1", theme: "cuisine", fr: "laver", en: "to wash", ipa: "/la.ve/", respell: "lah-VAY", tags: ["verb","kitchen"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.cuisine.228':   { id: "fr.a1.cuisine.228", kind: "sentence", level: "a1", theme: "cuisine", fr: "Je lave les légumes avant de cuisiner.", en: "I wash the vegetables before cooking.", notes: "{\"tiles\":[{\"w\":\"Je lave\",\"t\":\"i wash\"},{\"w\":\"les légumes\",\"t\":\"the vegetables\"},{\"w\":\"avant de cuisiner.\",\"t\":\"before cooking\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  'fr.a1.presentation-personnelle.001':   { id: "fr.a1.presentation-personnelle.001", kind: "sentence", level: "a1", theme: "presentation-personnelle", fr: "Je m'appelle Sophie.", en: "My name is Sophie.", ipa: "ʒə ma.pɛl sɔ.fi", notes: "“appelle” doubles both the p and the l, unlike the infinitive “appeler”.", tags: ["orthographe"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a1.rencontres.105':   { id: "fr.a1.rencontres.105", kind: "word", level: "a1", theme: "rencontres", fr: "s'appeler", en: "to be called / named", ipa: "sa.p(ə).le", respell: "sah-PLAY", example: {"en":"What is your name?","fr":"Comment vous appelez-vous ?"}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  'fr.a1.routines.001':   { id: "fr.a1.routines.001", kind: "phrase", level: "a1", theme: "routines", fr: "se lever", en: "to get up", respell: "suh luh-VAY", tags: ["verbs","reflexive","daily-routine"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.003':   { id: "fr.a1.routines.003", kind: "sentence", level: "a1", theme: "routines", fr: "Je me lève à sept heures.", en: "I get up at seven o'clock.", notes: "Reflexive verbs need a pronoun: « je » goes with « me ».", tags: ["reflexive","daily-routine"], drills: ["flashcard"], audioRef: null, version: 1, cardType: "gapfill", prompt: "Je ___ lève à sept heures." },
  'fr.a1.routines.010':   { id: "fr.a1.routines.010", kind: "word", level: "a1", theme: "routines", fr: "se réveiller", en: "to wake up", ipa: "/sə ʁeveje/", respell: "suh ray-veh-YAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.011':   { id: "fr.a1.routines.011", kind: "word", level: "a1", theme: "routines", fr: "se doucher", en: "to take a shower", ipa: "/sə duʃe/", respell: "suh doo-SHAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.012':   { id: "fr.a1.routines.012", kind: "word", level: "a1", theme: "routines", fr: "s'habiller", en: "to get dressed", ipa: "/sabije/", respell: "sah-bee-YAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.019':   { id: "fr.a1.routines.019", kind: "phrase", level: "a1", theme: "routines", fr: "se brosser les dents", en: "to brush one's teeth", ipa: "/sə bʁɔse le dɑ̃/", respell: "suh bro-SAY lay DAHⁿ", tags: ["daily","hygiene"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.020':   { id: "fr.a1.routines.020", kind: "word", level: "a1", theme: "routines", fr: "se coucher", en: "to go to bed", ipa: "/sə kuʃe/", respell: "suh koo-SHAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.028':   { id: "fr.a1.routines.028", kind: "word", level: "a1", theme: "routines", fr: "se laver", en: "to wash up", respell: "suh lah-VAY", tags: ["verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.034':   { id: "fr.a1.routines.034", kind: "word", level: "a1", theme: "routines", fr: "se reposer", en: "to rest", respell: "suh ruh-poh-ZAY", tags: ["verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.087':   { id: "fr.a1.routines.087", kind: "word", level: "a1", theme: "routines", fr: "se dépêcher", en: "to hurry", ipa: "/sə de.pɛ.ʃe/", respell: "suh day-peh-SHAY", notes: "Dépêche-toi! Hurry up!", tags: ["verb","reflexive"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  'fr.a1.routines.144':   { id: "fr.a1.routines.144", kind: "sentence", level: "a1", theme: "routines", fr: "Je me douche avant de m'habiller.", en: "I shower before getting dressed.", ipa: "/ʒə mə duʃ avɑ̃ də mabije/", notes: "The silent h in 'habiller' still triggers elision, so 'me' becomes m'habiller in writing.", tags: ["elision"], drills: ["dictation"], audioRef: null, version: 1 },
  'fr.a1.routines.154':   { id: "fr.a1.routines.154", kind: "sentence", level: "a1", theme: "routines", fr: "Il se lève tout de suite après le réveil.", en: "He gets up right away after the alarm.", notes: "{\"tiles\":[{\"w\":\"Il se lève\",\"t\":\"he gets up\"},{\"w\":\"tout de suite\",\"t\":\"right away\"},{\"w\":\"après le réveil.\",\"t\":\"after the alarm\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  'fr.a1.routines.157':   { id: "fr.a1.routines.157", kind: "sentence", level: "a1", theme: "routines", fr: "Tu te douches rapidement avant l'école.", en: "You shower quickly before school.", notes: "{\"tiles\":[{\"w\":\"Tu te douches\",\"t\":\"you shower\"},{\"w\":\"rapidement\",\"t\":\"quickly\"},{\"w\":\"avant l'école.\",\"t\":\"before school\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  'fr.a1.routines.181':   { id: "fr.a1.routines.181", kind: "sentence", level: "a1", theme: "routines", fr: "Nous nous levons tard le dimanche.", en: "We get up late on Sundays.", notes: "{\"tiles\":[{\"w\":\"Nous nous levons\",\"t\":\"we get up\"},{\"w\":\"tard\",\"t\":\"late\"},{\"w\":\"le dimanche.\",\"t\":\"on sundays\"}]}", tags: [], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  'fr.sons.verbes-essentiels.056':   { id: "fr.sons.verbes-essentiels.056", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "se souvenir", en: "to remember", ipa: "/sə suvniʁ/", respell: "SUH soov-NEER", notes: "reflexive, irregular · je me souviens, conjugates like venir", tags: ["irregular","reflexive"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
};

/** What each imported row's respelling said on the day of the read, so a repair
 *  or a drift is visible without another database call. */
export const STORED_RESPELL: Record<string, string | null> = {
  'fr.a1.corps.209': null,
  'fr.a1.cuisine.183': "lah-VAY",
  'fr.a1.cuisine.228': null,
  'fr.a1.presentation-personnelle.001': null,
  'fr.a1.rencontres.105': "sah-PLAY",
  'fr.a1.routines.001': "suh luh-VAY",
  'fr.a1.routines.003': null,
  'fr.a1.routines.010': "suh ray-veh-YAY",
  'fr.a1.routines.011': "suh doo-SHAY",
  'fr.a1.routines.012': "sah-bee-YAY",
  'fr.a1.routines.019': "suh bro-SAY lay DAHⁿ",
  'fr.a1.routines.020': "suh koo-SHAY",
  'fr.a1.routines.028': "suh lah-VAY",
  'fr.a1.routines.034': "suh ruh-poh-ZAY",
  'fr.a1.routines.087': "suh day-peh-SHAY",
  'fr.a1.routines.144': null,
  'fr.a1.routines.154': null,
  'fr.a1.routines.157': null,
  'fr.a1.routines.181': null,
  'fr.sons.verbes-essentiels.056': "SUH soov-NEER",
};

/** Published sentences per person, excluding this build's own rows. */
export const CELL_EVIDENCE: Record<string, number> = {
  "je me lève": 14,
  "tu te lèves": 1,
  "il se lève": 5,
  "nous nous levons": 3,
  "vous vous levez": 0,
  "ils se lèvent": 0,
  "je me lave": 1,
  "tu te laves": 0,
  "il se lave": 2,
  "nous nous lavons": 1,
  "vous vous lavez": 0,
  "ils se lavent": 0,
  "je ne me lève pas": 0,
  "je ne me lave pas": 0
};

export const MEASURED_AT = 'read from Postgres by scripts/_a222_manifest.ts';
export const MEASURED_ROWS = {
  imported: 20,
  themeRoutine: 0,
  themeRoutines: 339,
  a221BlockRows: 46,
  verbesRowsBefore: 528,
  framedVerbsFound: 8,
  bareVerbsFound: 2,
} as const;
