// GENERATED by scripts/_a214_manifest.ts on 2026-08-13. Do not edit by hand.
//
// A recorded read of the 12 rows a2.14 imports rather than authors, out of
// 6 themes, plus the 11 it reads and refuses.
//
// NOT ONE INFINITIVE IN THIS LESSON IS AUTHORED. Sixth A2 build in a row.
//
// THE MANIFEST IS SMALL BECAUSE THE CORPUS IS. 230 published sentences hold a
// form of savoir or connaître; THREE carry a respelling and one of those three
// carries U+203F. A row without a respelling is a card the learner cannot say,
// so the importable pool of sentences is TWO, and both of them are here.
//
// Regenerate with: pnpm tsx scripts/_a214_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 2 naming forms this lesson teaches. Both in verbes-essentiels. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.009", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "savoir", en: "to know (a fact)", ipa: "/savwaʁ/", respell: "sah-VWAR", notes: "irregular · je sais, nous savons, ils savent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.048", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "connaître", en: "to know (people, places)", ipa: "/kɔnɛtʁ/", respell: "koh-NETR", notes: "irregular · je connais, nous connaissons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The two frame complements and the third leg of the trap. `nager` was
 *  reserved for this lesson by a2.13; `Paris` is a name and carries no gender. */
export const IMPORTED_FRAME_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.088", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "nager", en: "to swim", ipa: "/naʒe/", respell: "nah-ZHAY", notes: "spelling change · nous nageons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.muettes.004", kind: "word", level: "sons", theme: "muettes", fr: "Paris", en: "Paris", ipa: "/pa.ʁi/", respell: "pa-REE", notes: "No S, ever, including in the city.", tags: ["silent-final","silent-s","proper-noun"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.006", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "pouvoir", en: "to be able to, can", ipa: "/puvwaʁ/", respell: "poo-VWAR", notes: "irregular · je peux, il peut, ils peuvent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The other two verbs that go behind savoir. */
export const IMPORTED_SKILL_ROWS: Item[] = [
  { id: "fr.a1.routines.109", kind: "word", level: "a1", theme: "routines", fr: "cuisiner", en: "to cook", ipa: "/kɥizine/", respell: "kwee-zee-NAY", tags: ["verb","food","chores"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.routines.107", kind: "word", level: "a1", theme: "routines", fr: "conduire", en: "to drive", ipa: "/kɔ̃dɥiʁ/", respell: "kohⁿ-DWEER", tags: ["verb","transport"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
];

/** reconnaître, named ONCE for its endings. a2.15 owns the principle. */
export const IMPORTED_FAMILY_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.187", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "reconnaître", en: "to recognize", ipa: "/ʁəkɔnɛtʁ/", respell: "ruh-koh-NEHTR", notes: "Irregular; conjugates like connaître.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** THE ONLY RESPELLED connaître SENTENCES IN THE CORPUS that do not carry
 *  U+203F. Both are connaître landing on a thing. */
export const IMPORTED_EVIDENCE_ROWS: Item[] = [
  { id: "fr.sons.nasales.110", kind: "sentence", level: "sons", theme: "nasales", fr: "Tout le monde connaît le nom du champion.", en: "Everyone knows the champion's name.", ipa: "tu lə mɔ̃d kɔ.nɛ lə nɔ̃ dy ʃɑ̃.pjɔ̃", respell: "TOO LUH MOHⁿD ko-NEH LUH NOHⁿ DÜ shahⁿ-PYOHⁿ", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, register: "courant" },
  { id: "fr.sons.voyelles.309", kind: "sentence", level: "sons", theme: "voyelles", fr: "Il connaît la vraie raison de son retard ce matin.", en: "He knows the real reason for his lateness this morning.", ipa: "il kɔ.nɛ la vʁɛ ʁɛ.zɔ̃ də sɔ̃ ʁə.taʁ sə ma.tɛ̃", respell: "EEL ko-NEH LA VREH reh-ZOHⁿ DUH SOHⁿ ruh-TAR SUH ma-TEHⁿ", tags: [], drills: ["sentence","review"], audioRef: null, version: 1, skill: "PE", register: "courant" },
];

/** The savoir half of the evidence. The first is savoir followed by a whole
 *  sentence, published and respelled, which is the reframe's other half in a row
 *  this lesson did not write. */
export const IMPORTED_SAVOIR_EVIDENCE_ROWS: Item[] = [
  { id: "fr.sons.elision.072", kind: "sentence", level: "sons", theme: "elision", fr: "Je ne sais pas si c'est l'heure.", en: "I do not know if it is time.", ipa: "/ʒə nə sɛ pa si sɛ lœʁ/", respell: "zhuh nuh seh pa see seh LEUR", notes: "ne and si both stay whole here. Only ce and la had a vowel to collide with.", tags: ["ne","ce","la","no-elision","sentence"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.elision.033", kind: "phrase", level: "sons", theme: "elision", fr: "je ne sais pas", en: "I do not know", ipa: "/ʒə nə sɛ pa/", respell: "zhuh nuh seh PA", notes: "sais starts on a consonant, so ne stays whole. Compare je n'ai pas.", tags: ["ne","negation","consonant-initial","no-elision"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
];

/** The 11 rows read and refused. READ ONLY: never carried, never released,
 *  never in itemIds, and named on no screen. */
export const READ_ONLY_ROWS: Item[] = [
  { id: "fr.sons.liaisons.057", kind: "sentence", level: "sons", theme: "liaisons", fr: "Ils se connaissent depuis vingt ans.", en: "They have known each other for twenty years.", ipa: "il sə kɔ.nɛs də.pɥi vɛ̃.t‿ɑ̃", respell: "EEL SUH koh-NEHS duh-PÜEE vehⁿ-t‿AHⁿ", tags: ["liaison-t","liaison-obligatoire","after-determiner"], drills: ["sentence","review"], audioRef: null, version: 2, register: "courant" },
  { id: "fr.a2.collegues.009", kind: "sentence", level: "a2", theme: "collegues", fr: "« Connaître » s'utilise avec une personne ou un lieu, « savoir » avec un fait ou une compétence.", en: "« Connaître » is used with a person or a place, « savoir » with a fact or a skill.", notes: "Ex : je connais mon chef · je sais son nom · je sais travailler en équipe", tags: ["collegues","savoir","connaitre"], drills: ["flashcard"], audioRef: null, version: 1, cardType: "grammar", prompt: "Quelle est la différence entre « savoir » et « connaître » ?" },
  { id: "fr.sons.verbes-essentiels.217", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "paraître", en: "to appear", ipa: "/paʁɛtʁ/", respell: "pah-REHTR", notes: "Irregular; conjugates like connaître.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.expressions-utiles.228", kind: "phrase", level: "sons", theme: "expressions-utiles", fr: "on ne sait jamais", en: "you never know", ipa: "/ɔ̃ nə sɛ ʒamɛ/", respell: "ohn-nuh-say-zhah-MEH", notes: "hedges against certainty about the future", tags: ["filler"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.sons.expressions-utiles.105", kind: "phrase", level: "sons", theme: "expressions-utiles", fr: "qui sait", en: "who knows", ipa: "ki sɛ", respell: "KEE SEH", notes: "Shrugging at an uncertain future.", tags: ["expression"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.verbes-du-quotidien.099", kind: "sentence", level: "a1", theme: "verbes-du-quotidien", fr: "Je sais nager.", en: "I know how to swim.", tags: [], drills: ["sentence"], audioRef: null, version: 1 },
  { id: "fr.a1.verbes-essentiels.088", kind: "sentence", level: "a1", theme: "verbes-essentiels", fr: "Je sais nager depuis mon enfance.", en: "I have known how to swim since childhood.", ipa: "ʒə sɛ na.ʒe də.pɥi mɔ̃.n‿ɑ̃.fɑ̃s", notes: "\"Sais\" is the irregular je form of savoir, pronounced [sɛ].", tags: ["conjugaison"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.verbes-essentiels.089", kind: "sentence", level: "a1", theme: "verbes-essentiels", fr: "Tu sais où sont les clés.", en: "You know where the keys are.", ipa: "ty sɛ u sɔ̃ le kle", tags: ["conjugaison"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a1.pronoms-essentiels.086", kind: "sentence", level: "a1", theme: "pronoms-essentiels", fr: "Elle sait où il travaille.", en: "She knows where he works.", ipa: "/ɛl sɛ u il tʁa.vaj/", notes: "The relative pronoun 'où' is written with an accent to distinguish it from 'ou' meaning or.", tags: ["homophone"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes-du-quotidien.041", kind: "sentence", level: "a2", theme: "verbes-du-quotidien", fr: "Nous savons que la réponse est correcte.", en: "We know the answer is correct.", ipa: "nu sa.vɔ̃ kə la ʁe.pɔ̃.z‿ɛ kɔ.ʁɛkt", notes: "“savons” uses the stem “sav-”, different from the singular stem “sai-”.", tags: ["conjugaison"], drills: ["dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes-du-quotidien.042", kind: "sentence", level: "a2", theme: "verbes-du-quotidien", fr: "Nous connaissons ce restaurant depuis longtemps.", en: "We have known this restaurant for a long time.", ipa: "nu kɔ.nɛ.sɔ̃ sə ʁɛs.to.ʁɑ̃ də.pɥi lɔ̃.tɑ̃", notes: "“connaissons” adds a double ss before the ending, unlike the singular forms.", tags: ["orthographe"], drills: ["dictation"], audioRef: null, version: 1 },
];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["savoir", "fr.sons.verbes-essentiels.009"],
  ["connaître", "fr.sons.verbes-essentiels.048"],
];

/** complement -> id. */
export const FRAME_ROW_IDS: [string, string][] = [
  ["nager", "fr.sons.verbes-essentiels.088"],
  ["Paris", "fr.sons.muettes.004"],
  ["pouvoir", "fr.sons.verbes-essentiels.006"],
];

/** skill verb -> id. */
export const SKILL_ROW_IDS: [string, string][] = [
  ["cuisiner", "fr.a1.routines.109"],
  ["conduire", "fr.a1.routines.107"],
];

/** family member -> id. */
export const FAMILY_ROW_IDS: [string, string][] = [
  ["reconnaître", "fr.sons.verbes-essentiels.187"],
];

/** evidence sentence -> id, both verbs. */
export const EVIDENCE_ROW_IDS: [string, string][] = [
  ["Tout le monde connaît le nom du champion.", "fr.sons.nasales.110"],
  ["Il connaît la vraie raison de son retard ce matin.", "fr.sons.voyelles.309"],
  ["Je ne sais pas si c'est l'heure.", "fr.sons.elision.072"],
  ["je ne sais pas", "fr.sons.elision.033"],
];

/** And the refused pairing, kept apart so nothing can iterate both by accident. */
export const READ_ONLY_ROW_IDS: [string, string][] = [
  ["Ils se connaissent depuis vingt ans.", "fr.sons.liaisons.057"],
  ["« Connaître » s'utilise avec une personne ou un lieu, « savoir » avec un fait ou une compétence.", "fr.a2.collegues.009"],
  ["paraître", "fr.sons.verbes-essentiels.217"],
  ["on ne sait jamais", "fr.sons.expressions-utiles.228"],
  ["qui sait", "fr.sons.expressions-utiles.105"],
  ["Je sais nager.", "fr.a1.verbes-du-quotidien.099"],
  ["Je sais nager depuis mon enfance.", "fr.a1.verbes-essentiels.088"],
  ["Tu sais où sont les clés.", "fr.a1.verbes-essentiels.089"],
  ["Elle sait où il travaille.", "fr.a1.pronoms-essentiels.086"],
  ["Nous savons que la réponse est correcte.", "fr.a2.verbes-du-quotidien.041"],
  ["Nous connaissons ce restaurant depuis longtemps.", "fr.a2.verbes-du-quotidien.042"],
];

/** Every id this lesson may put in `itemIds`. The refused rows are deliberately
 *  absent, and the batch asserts that absence. */
export const IMPORTABLE_IDS: string[] = [
  "fr.sons.verbes-essentiels.009",
  "fr.sons.verbes-essentiels.048",
  "fr.sons.verbes-essentiels.088",
  "fr.sons.muettes.004",
  "fr.sons.verbes-essentiels.006",
  "fr.a1.routines.109",
  "fr.a1.routines.107",
  "fr.sons.verbes-essentiels.187",
  "fr.sons.nasales.110",
  "fr.sons.voyelles.309",
  "fr.sons.elision.072",
  "fr.sons.elision.033",
];

/** The themes these rows came out of. */
export const SOURCE_THEMES: string[] = ["elision","muettes","nasales","routines","verbes-essentiels","voyelles"];

/** The circumflex, re-measured on the day this manifest was generated. */
export const CIRCUMFLEX_MEASURED = { withCircumflex: 82, flat: 0, date: "2026-08-13" };
