// GENERATED by scripts/_a201_manifest.ts on 2026-08-11. Do not edit by hand.
//
// A recorded read of the 32 rows a2.01 imports rather than authors. Two
// consumers need the whole row and not just the id:
//
//   author-verbes-er-batch.ts verifies every field against Postgres before it
//   opens a transaction, so a stale manifest cannot put the lesson ahead of rows
//   nobody has looked at.
//
//   merge-verbes-er-into-seed.ts CARRIES these into seed.json. The seed is a CUT
//   and 30 of these 32 rows are in Postgres and not in the seed, so
//   without the carry every one of the thirty verb cards would draw empty.
//
// Regenerate with: pnpm tsx scripts/_a201_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The thirty infinitives, in the order the learner meets them. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.015", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "parler", en: "to speak, to talk", ipa: "/paʁle/", respell: "par-LAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.024", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "regarder", en: "to watch, to look at", ipa: "/ʁəɡaʁde/", respell: "ruh-gar-DAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.025", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "écouter", en: "to listen to", ipa: "/ekute/", respell: "ay-koo-TAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.016", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "aimer", en: "to like, to love", ipa: "/eme/", respell: "eh-MAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.026", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "habiter", en: "to live (in a place)", ipa: "/abite/", respell: "ah-bee-TAY", notes: "regular -er verb · j'habite à Paris", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.verbes.031", kind: "word", level: "a2", theme: "verbes", fr: "travailler", en: "to work", ipa: "tʁa.va.je", respell: "trah-vah-YAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.017", kind: "word", level: "a2", theme: "verbes", fr: "chercher", en: "to look for", ipa: "ʃɛʁ.ʃe", respell: "shair-SHAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.018", kind: "word", level: "a2", theme: "verbes", fr: "trouver", en: "to find", ipa: "tʁu.ve", respell: "troo-VAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.019", kind: "word", level: "a2", theme: "verbes", fr: "demander", en: "to ask for", ipa: "də.mɑ̃.de", respell: "duh-mahn-DAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.013", kind: "word", level: "a2", theme: "verbes", fr: "arriver", en: "to arrive", ipa: "a.ʁi.ve", respell: "ah-ree-VAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.015", kind: "word", level: "a2", theme: "verbes", fr: "rester", en: "to stay", ipa: "ʁɛs.te", respell: "res-TAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.016", kind: "word", level: "a2", theme: "verbes", fr: "rentrer", en: "to go home", ipa: "ʁɑ̃.tʁe", respell: "rahn-TRAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.032", kind: "word", level: "a2", theme: "verbes", fr: "gagner", en: "to earn", ipa: "ga.ɲe", respell: "gah-NYAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.sons.consonnes.140", kind: "word", level: "sons", theme: "consonnes", fr: "donner", en: "to give", ipa: "/dɔ.ne/", respell: "doh-NAY", tags: ["doubled"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a1.amis.024", kind: "word", level: "a1", theme: "amis", fr: "aider", en: "to help", ipa: "/ɛ.de/", respell: "eh-DAY", notes: "Verb, regular er group.", tags: ["amis","verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.141", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "porter", en: "to carry", ipa: "/pɔʁte/", respell: "por-TAY", tags: ["verb","er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.043", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "entrer", en: "to enter, to go in", ipa: "/ɑ̃tʁe/", respell: "ahn-TRAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.054", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "montrer", en: "to show", ipa: "/mɔ̃tʁe/", respell: "mohn-TRAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.amis.023", kind: "word", level: "a1", theme: "amis", fr: "jouer", en: "to play", ipa: "/ʒwe/", respell: "ZHWAY", notes: "Verb, regular er group.", tags: ["amis","verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.evenements-familiaux.059", kind: "word", level: "a1", theme: "evenements-familiaux", fr: "chanter", en: "to sing", ipa: "ʃɑ̃.te", respell: "shahn-TAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.evenements-familiaux.060", kind: "word", level: "a1", theme: "evenements-familiaux", fr: "danser", en: "to dance", ipa: "dɑ̃.se", respell: "dahn-SAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.129", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "visiter", en: "to visit (a place)", ipa: "/vizite/", respell: "vee-zee-TAY", notes: "for places, not people", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.amis.019", kind: "word", level: "a1", theme: "amis", fr: "inviter", en: "to invite", ipa: "/ɛ̃.vi.te/", respell: "an-vee-TAY", notes: "Verb, regular er group.", tags: ["amis","verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.verbes-essentiels.001", kind: "word", level: "a1", theme: "verbes-essentiels", fr: "étudier", en: "to study", ipa: "/etydje/", respell: "ay-tew-DYAY", tags: ["verbe","ecole"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.110", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "adorer", en: "to love, to adore", ipa: "/adɔʁe/", respell: "ah-doh-RAY", notes: "j'adore, I love it", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.109", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "détester", en: "to hate", ipa: "/detɛste/", respell: "day-teh-STAY", notes: "regular er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.035", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "fermer", en: "to close", ipa: "/fɛʁme/", respell: "fehr-MAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.routines.108", kind: "word", level: "a1", theme: "routines", fr: "marcher", en: "to walk", ipa: "/maʁʃe/", respell: "mar-SHAY", tags: ["verb","transport"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.verbes-essentiels.003", kind: "word", level: "a1", theme: "verbes-essentiels", fr: "téléphoner", en: "to phone, to call", ipa: "/telefɔne/", respell: "tay-lay-foh-NAY", notes: "Followed by à: téléphoner à quelqu'un.", tags: ["verbe","communication"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.055", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "oublier", en: "to forget", ipa: "/ublije/", respell: "oo-blee-AY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The published sentences this lesson teaches from rather than teaching. */
export const IMPORTED_SENTENCE_ROWS: Item[] = [
  { id: "fr.a2.verbes.001", kind: "sentence", level: "a2", theme: "verbes", fr: "Je parle français.", en: "I speak French.", respell: "ZHUH PARL frahn-SEH", notes: "{\"tiles\":[{\"w\":\"Je\",\"t\":\"I\"},{\"w\":\"parle\",\"t\":\"speak\"},{\"w\":\"français.\",\"t\":\"French\"}]}", tags: [], drills: ["flashcard","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.061", kind: "sentence", level: "a2", theme: "verbes", fr: "Ils habitent à Montréal depuis deux ans.", en: "They have been living in Montreal for two years.", ipa: "il.z‿a.bit a mɔ̃.ʁe.al də.pɥi dø.z‿ɑ̃", tags: [], drills: ["sentence","review"], audioRef: null, version: 1 },
];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["parler", "fr.sons.verbes-essentiels.015"],
  ["regarder", "fr.sons.verbes-essentiels.024"],
  ["écouter", "fr.sons.verbes-essentiels.025"],
  ["aimer", "fr.sons.verbes-essentiels.016"],
  ["habiter", "fr.sons.verbes-essentiels.026"],
  ["travailler", "fr.a2.verbes.031"],
  ["chercher", "fr.a2.verbes.017"],
  ["trouver", "fr.a2.verbes.018"],
  ["demander", "fr.a2.verbes.019"],
  ["arriver", "fr.a2.verbes.013"],
  ["rester", "fr.a2.verbes.015"],
  ["rentrer", "fr.a2.verbes.016"],
  ["gagner", "fr.a2.verbes.032"],
  ["donner", "fr.sons.consonnes.140"],
  ["aider", "fr.a1.amis.024"],
  ["porter", "fr.sons.verbes-essentiels.141"],
  ["entrer", "fr.sons.verbes-essentiels.043"],
  ["montrer", "fr.sons.verbes-essentiels.054"],
  ["jouer", "fr.a1.amis.023"],
  ["chanter", "fr.a1.evenements-familiaux.059"],
  ["danser", "fr.a1.evenements-familiaux.060"],
  ["visiter", "fr.sons.verbes-essentiels.129"],
  ["inviter", "fr.a1.amis.019"],
  ["étudier", "fr.a1.verbes-essentiels.001"],
  ["adorer", "fr.sons.verbes-essentiels.110"],
  ["détester", "fr.sons.verbes-essentiels.109"],
  ["fermer", "fr.sons.verbes-essentiels.035"],
  ["marcher", "fr.a1.routines.108"],
  ["téléphoner", "fr.a1.verbes-essentiels.003"],
  ["oublier", "fr.sons.verbes-essentiels.055"],
];
