// GENERATED by scripts/_a211_manifest.ts on 2026-08-12. Do not edit by hand.
//
// A recorded read of the 7 rows a2.11 imports rather than authors, plus the
// 2 it NAMES as exceptions and conjugates nowhere. Two consumers need the
// whole row and not just the id:
//
//   author-verbes-re-batch.ts verifies every field against Postgres before it
//   opens a transaction, so a stale manifest cannot put the lesson ahead of rows
//   nobody has looked at.
//
//   merge-verbes-re-into-seed.ts CARRIES the imported ones into seed.json. The
//   seed is a CUT, and neither fr.a2.verbes.027 (vendre) nor fr.a2.verbes.020
//   (répondre) is in it today, so without the carry the verb cards would draw
//   empty.
//
// THE NAMED-NOT-TAUGHT ROWS ARE NOT CARRIED AND NOT RELEASED. They are read so
// the batch can prove the boundary verbs exist and so a later author can see the
// decision was taken with the rows in front of it. a2.10 settled the rule: a
// boundary verb is a display string, not a row in the hub.
//
// Regenerate with: pnpm tsx scripts/_a211_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 7 infinitives this lesson teaches, in learner order. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.a2.verbes.027", kind: "word", level: "a2", theme: "verbes", fr: "vendre", en: "to sell", ipa: "vɑ̃dʁ", respell: "VAHNDR", example: {"en":"The store sells cheap furniture.","fr":"Le magasin vend des meubles pas chers."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  { id: "fr.sons.verbes-essentiels.028", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "attendre", en: "to wait for", ipa: "/atɑ̃dʁ/", respell: "ah-TAHNDR", notes: "regular -re verb · j'attends, nous attendons", tags: ["re-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.verbes.020", kind: "word", level: "a2", theme: "verbes", fr: "répondre", en: "to answer", ipa: "ʁe.pɔ̃dʁ", respell: "ray-PONDR", example: {"en":"You must answer before Friday.","fr":"Vous devez répondre avant vendredi."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  { id: "fr.sons.verbes-essentiels.029", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "entendre", en: "to hear", ipa: "/ɑ̃tɑ̃dʁ/", respell: "ahn-TAHNDR", notes: "regular -re verb · j'entends", tags: ["re-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.032", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "perdre", en: "to lose", ipa: "/pɛʁdʁ/", respell: "PEHRDR", notes: "regular -re verb · je perds", tags: ["re-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.128", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "rendre", en: "to give back", ipa: "/ʁɑ̃dʁ/", respell: "RAHNDR", notes: "regular re verb · je rends, nous rendons", tags: ["re-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.transports-quotidiens.045", kind: "word", level: "a1", theme: "transports-quotidiens", fr: "descendre", en: "to get off", ipa: "/de.sɑ̃dʁ/", respell: "day-SAHN-druh", tags: ["verb","movement"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The 2 it names and refuses to conjugate. READ ONLY: never carried, never
 *  released, never in itemIds. */
export const BOUNDARY_VERB_ROWS: Item[] = [
  { id: "fr.sons.consonnes.107", kind: "word", level: "sons", theme: "consonnes", fr: "prendre", en: "to take", ipa: "/pʁɑ̃dʁ/", respell: "PRAHⁿDR", notes: "Two clusters and a nasal, and not one extra vowel anywhere.", tags: ["r","r-cluster","nasal"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.014", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "mettre", en: "to put", ipa: "/mɛtʁ/", respell: "METR", notes: "irregular · je mets, nous mettons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The published sentences this lesson teaches from rather than teaching. */
export const IMPORTED_SENTENCE_ROWS: Item[] = [

];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["vendre", "fr.a2.verbes.027"],
  ["attendre", "fr.sons.verbes-essentiels.028"],
  ["répondre", "fr.a2.verbes.020"],
  ["entendre", "fr.sons.verbes-essentiels.029"],
  ["perdre", "fr.sons.verbes-essentiels.032"],
  ["rendre", "fr.sons.verbes-essentiels.128"],
  ["descendre", "fr.a1.transports-quotidiens.045"],
];

/** And the boundary pairing, kept apart so nothing can iterate both by accident. */
export const BOUNDARY_ROW_IDS: [string, string][] = [
  ["prendre", "fr.sons.consonnes.107"],
  ["mettre", "fr.sons.verbes-essentiels.014"],
];
