// GENERATED by scripts/_a210_manifest.ts on 2026-08-12. Do not edit by hand.
//
// A recorded read of the 10 rows a2.10 imports rather than authors. Two
// consumers need the whole row and not just the id:
//
//   author-verbes-ir-batch.ts verifies every field against Postgres before it
//   opens a transaction, so a stale manifest cannot put the lesson ahead of rows
//   nobody has looked at.
//
//   merge-verbes-ir-into-seed.ts CARRIES these into seed.json. The seed is a CUT,
//   so without the carry the verb cards would draw empty.
//
// Regenerate with: pnpm tsx scripts/_a210_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 10 infinitives, in learner order. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.037", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "finir", en: "to finish", ipa: "/finiʁ/", respell: "fee-NEER", notes: "regular -ir verb · je finis, nous finissons", tags: ["ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.038", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "choisir", en: "to choose", ipa: "/ʃwaziʁ/", respell: "shwah-ZEER", notes: "regular -ir verb · je choisis, nous choisissons", tags: ["ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.112", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "réussir", en: "to succeed", ipa: "/ʁeysiʁ/", respell: "ray-ü-SEER", notes: "regular ir verb · je réussis, nous réussissons", tags: ["ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.230", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "réfléchir", en: "to reflect", ipa: "/ʁefleʃiʁ/", respell: "ray-flay-SHEER", notes: "", tags: ["verb","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.verbes.021", kind: "word", level: "a2", theme: "verbes", fr: "remplir", en: "to fill out", ipa: "ʁɑ̃.pliʁ", respell: "rahn-PLEER", example: {"en":"Fill out this form, please.","fr":"Remplissez ce formulaire, s'il vous plaît."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  { id: "fr.a2.famille.007", kind: "word", level: "a2", theme: "famille", fr: "grandir", en: "to grow up", ipa: "gʁɑ̃.diʁ", respell: "grahn-DEER", example: {"en":"Children grow up fast.","fr":"Les enfants grandissent vite."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.a2.verbes.036", kind: "word", level: "a2", theme: "verbes", fr: "guérir", en: "to heal, to recover", ipa: "ge.ʁiʁ", respell: "gay-REER", example: {"en":"He recovered quickly from his flu.","fr":"Il a guéri rapidement de sa grippe."}, tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1, skill: "PO", register: "courant" },
  { id: "fr.a2.animaux-domestiques.078", kind: "word", level: "a2", theme: "animaux-domestiques", fr: "obéir", en: "to obey", ipa: "/ɔbeiʁ/", respell: "oh-bay-EER", tags: ["verb","behavior","pet"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.cinema.051", kind: "word", level: "a2", theme: "cinema", fr: "applaudir", en: "to applaud", ipa: "a.plo.diʁ", respell: "ah-ploh-DEER", example: {"en":"The audience applauded for several minutes.","fr":"Le public a applaudi pendant plusieurs minutes."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  { id: "fr.a2.transports-quotidiens.043", kind: "word", level: "a2", theme: "transports-quotidiens", fr: "ralentir", en: "to slow down", ipa: "/ʁa.lɑ̃.tiʁ/", respell: "rah-lahn-TEER", tags: ["verb","driving"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The published sentences this lesson teaches from rather than teaching. */
export const IMPORTED_SENTENCE_ROWS: Item[] = [

];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["finir", "fr.sons.verbes-essentiels.037"],
  ["choisir", "fr.sons.verbes-essentiels.038"],
  ["réussir", "fr.sons.verbes-essentiels.112"],
  ["réfléchir", "fr.sons.verbes-essentiels.230"],
  ["remplir", "fr.a2.verbes.021"],
  ["grandir", "fr.a2.famille.007"],
  ["guérir", "fr.a2.verbes.036"],
  ["obéir", "fr.a2.animaux-domestiques.078"],
  ["applaudir", "fr.a2.cinema.051"],
  ["ralentir", "fr.a2.transports-quotidiens.043"],
];
