// GENERATED by scripts/_a209_manifest.ts on 2026-08-11. Do not edit by hand.
//
// A recorded read of the 17 rows a2.09 imports rather than authors. Two
// consumers need the whole row and not just the id:
//
//   author-verbes-er-exceptions-batch.ts verifies every field against Postgres
//   before it opens a transaction, so a stale manifest cannot put the lesson
//   ahead of rows nobody has looked at.
//
//   merge-verbes-er-exceptions-into-seed.ts CARRIES these into seed.json. The
//   seed is a CUT, so without the carry the verb cards would draw empty.
//
// Regenerate with: pnpm tsx scripts/_a209_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 17 infinitives, grouped by pattern, in learner order. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.a1.routines.185", kind: "word", level: "a1", theme: "routines", fr: "manger", en: "to eat", ipa: "/mɑ̃ʒe/", respell: "mahⁿ-ZHAY", tags: ["daily","verbs"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.088", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "nager", en: "to swim", ipa: "/naʒe/", respell: "nah-ZHAY", notes: "spelling change · nous nageons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.130", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "voyager", en: "to travel", ipa: "/vwajaʒe/", respell: "vwah-yah-ZHAY", notes: "spelling change · nous voyageons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.routines.033", kind: "word", level: "a1", theme: "routines", fr: "ranger", en: "to tidy up", respell: "rahn-ZHAY", tags: ["verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.communaute.052", kind: "word", level: "a2", theme: "communaute", fr: "partager", en: "to share", ipa: "paʁ.ta.ʒe", respell: "par-tah-ZHAY", tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.036", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "commencer", en: "to start, to begin", ipa: "/kɔmɑ̃se/", respell: "koh-mahn-SAY", notes: "spelling change · nous commençons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.132", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "lancer", en: "to throw", ipa: "/lɑ̃se/", respell: "lahn-SAY", tags: ["verb","er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.dictee.099", kind: "word", level: "a1", theme: "dictee", fr: "effacer", en: "to erase", ipa: "e.fa.se", respell: "ay-fa-SAY", tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.050", kind: "word", level: "a2", theme: "verbes", fr: "appeler", en: "to call", ipa: "a.ple", respell: "ah-PLAY", tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.051", kind: "word", level: "a2", theme: "verbes", fr: "rappeler", en: "to call back", ipa: "ʁa.ple", respell: "rah-PLAY", tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.069", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "jeter", en: "to throw away", ipa: "/ʒəte/", respell: "zhuh-TAY", notes: "spelling change · je jette, nous jetons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.verbes.026", kind: "word", level: "a2", theme: "verbes", fr: "acheter", en: "to buy", ipa: "aʃ.te", respell: "ahsh-TAY", tags: [], drills: ["flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.meteo.167", kind: "word", level: "a1", theme: "meteo", fr: "geler", en: "to freeze", ipa: "ʒə.le", respell: "zhuh-LAY", tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.sons.verbes-essentiels.108", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "préférer", en: "to prefer", ipa: "/pʁefeʁe/", respell: "pray-fay-RAY", notes: "spelling change · je préfère, nous préférons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.107", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "espérer", en: "to hope", ipa: "/ɛspeʁe/", respell: "eh-spay-RAY", notes: "spelling change · j'espère, nous espérons", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.209", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "répéter", en: "to repeat", ipa: "/ʁepete/", respell: "ray-pay-TAY", tags: ["verb","er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.verbes.055", kind: "word", level: "a2", theme: "verbes", fr: "protéger", en: "to protect", ipa: "pʁo.te.ʒe", respell: "proh-tay-ZHAY", tags: [], drills: ["voiceflash","review"], audioRef: null, version: 1 },
];

/** The published sentences this lesson teaches from rather than teaching. */
export const IMPORTED_SENTENCE_ROWS: Item[] = [

];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["manger", "fr.a1.routines.185"],
  ["nager", "fr.sons.verbes-essentiels.088"],
  ["voyager", "fr.sons.verbes-essentiels.130"],
  ["ranger", "fr.a1.routines.033"],
  ["partager", "fr.a2.communaute.052"],
  ["commencer", "fr.sons.verbes-essentiels.036"],
  ["lancer", "fr.sons.verbes-essentiels.132"],
  ["effacer", "fr.a1.dictee.099"],
  ["appeler", "fr.a2.verbes.050"],
  ["rappeler", "fr.a2.verbes.051"],
  ["jeter", "fr.sons.verbes-essentiels.069"],
  ["acheter", "fr.a2.verbes.026"],
  ["geler", "fr.a1.meteo.167"],
  ["préférer", "fr.sons.verbes-essentiels.108"],
  ["espérer", "fr.sons.verbes-essentiels.107"],
  ["répéter", "fr.sons.verbes-essentiels.209"],
  ["protéger", "fr.a2.verbes.055"],
];
