// GENERATED by scripts/_a210l2_manifest.ts on 2026-08-12. Do not edit by hand.
//
// A recorded read of the 14 rows a2.10.l2 imports rather than authors.
// Verified field by field by author-verbes-ir-familles-batch.ts before it opens a
// transaction, and CARRIED into seed.json by the merge, because `verbes` and
// `verbes-essentiels` are both outside the seed cut.
//
// Regenerate with: pnpm tsx scripts/_a210l2_manifest.ts

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

/** The 12 infinitives, in learner order. */
export const IMPORTED_VERB_ROWS: Item[] = [
  { id: "fr.sons.verbes-essentiels.040", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "partir", en: "to leave, to depart", ipa: "/paʁtiʁ/", respell: "par-TEER", notes: "irregular · je pars, nous partons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.041", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "sortir", en: "to go out", ipa: "/sɔʁtiʁ/", respell: "sor-TEER", notes: "irregular · je sors, nous sortons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.039", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "dormir", en: "to sleep", ipa: "/dɔʁmiʁ/", respell: "dor-MEER", notes: "irregular · je dors, nous dormons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a2.courses.080", kind: "word", level: "a2", theme: "courses", fr: "servir", en: "to serve", ipa: "/sɛʁ.viʁ/", respell: "sehr-VEER", tags: ["verb","shopping"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.074", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "sentir", en: "to smell, to feel", ipa: "/sɑ̃tiʁ/", respell: "sahn-TEER", notes: "irregular · je sens, tu sens, il sent", tags: ["irregular","ir-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.204", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "mentir", en: "to lie", ipa: "/mɑ̃tiʁ/", respell: "mahn-TEER", notes: "Irregular; conjugates like partir.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.034", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "ouvrir", en: "to open", ipa: "/uvʁiʁ/", respell: "oo-VREER", notes: "irregular · conjugates like an -er verb: j'ouvre", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.053", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "offrir", en: "to offer, to give (a gift)", ipa: "/ɔfʁiʁ/", respell: "oh-FREER", notes: "irregular · conjugates like an -er verb: j'offre", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.157", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "couvrir", en: "to cover", ipa: "/kuvʁiʁ/", respell: "koo-VREER", notes: "Irregular: conjugates like ouvrir, je couvre.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.158", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "découvrir", en: "to discover, to uncover", ipa: "/dekuvʁiʁ/", respell: "day-koo-VREER", notes: "Irregular: conjugates like ouvrir, je découvre.", tags: ["verb","irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.b1.verbes.054", kind: "word", level: "b1", theme: "verbes", fr: "souffrir", en: "to suffer", ipa: "su.fʁiʁ", respell: "soo-FREER", example: {"en":"He has been suffering from back pain for several weeks.","fr":"Il souffre de maux de dos depuis plusieurs semaines."}, tags: [], drills: ["flashcard","review"], audioRef: null, version: 1, skill: "CE", register: "courant" },
  { id: "fr.sons.verbes-essentiels.045", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "courir", en: "to run", ipa: "/kuʁiʁ/", respell: "koo-REER", notes: "irregular · je cours, nous courons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** The published sentences this lesson teaches from rather than teaching. */
export const IMPORTED_SENTENCE_ROWS: Item[] = [
  { id: "fr.a2.verbes.202", kind: "sentence", level: "a2", theme: "verbes", fr: "Les voitures ralentissent ici.", en: "The cars slow down here.", ipa: "/le vwa.tyʁ ʁa.lɑ̃.tis i.si/", respell: "lay vwah-tür ra-lahⁿ-tees ee-SEE", notes: "Nothing in the sentence is plural to the ear except the verb.", tags: ["ir-verb","apply","plural","nasal"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.verbes.198", kind: "sentence", level: "a2", theme: "verbes", fr: "Ils guérissent vite.", en: "They get better quickly.", ipa: "/il ɡe.ʁis vit/", respell: "eel gay-rees VEET", tags: ["ir-verb","apply","plural"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
];

/** verb -> id, in learner order. The only place this pairing is written down. */
export const VERB_ROW_IDS: [string, string][] = [
  ["partir", "fr.sons.verbes-essentiels.040"],
  ["sortir", "fr.sons.verbes-essentiels.041"],
  ["dormir", "fr.sons.verbes-essentiels.039"],
  ["servir", "fr.a2.courses.080"],
  ["sentir", "fr.sons.verbes-essentiels.074"],
  ["mentir", "fr.sons.verbes-essentiels.204"],
  ["ouvrir", "fr.sons.verbes-essentiels.034"],
  ["offrir", "fr.sons.verbes-essentiels.053"],
  ["couvrir", "fr.sons.verbes-essentiels.157"],
  ["découvrir", "fr.sons.verbes-essentiels.158"],
  ["souffrir", "fr.b1.verbes.054"],
  ["courir", "fr.sons.verbes-essentiels.045"],
];
