// A RECORDED READ OF POSTGRES. Generated by scripts/_a225_manifest.ts.
// DO NOT EDIT BY HAND. Re-run the generator instead.
//
// 27 rows imported: 7 headwords, 8 respelled phrases and
// 12 published sentences, out of 9 themes. 0 headwords authored.
// 5 respellings repaired, 1 of them BLIND to the checker.
//
// THE MEASUREMENTS, RE-RUN ON EVERY REGENERATION, 2026-08-16:
//
//   THE SIX-ROW SET, which the corpus header's §1 rests on and which the
//   generator refuses on if any of them has moved:
//
//     fr.a2.pronoms-essentiels.028   « j'y pense »
//     fr.a2.pronoms-essentiels.029   « Je vais à Paris ; j'y vais en train. »
//     fr.a2.pronoms-essentiels.030   « Tu penses à ton examen ? Oui, j'y pense souvent. »
//     fr.a2.pronoms-essentiels.031   « j'en veux »
//     fr.a2.pronoms-essentiels.032   « Tu veux du café ? Oui, j'en veux bien. »
//     fr.a2.pronoms-essentiels.033   « Elle a trois frères ; elle en parle souvent. »
//
//   THE CONSTRUCTION, which the brief calls rare and which is not:
//
//     j'y            11
//     j'en           30
//     n'y            61
//     n'en           27
//     il y a        245
//     il y en a       2
//     y aller         7
//     elided total  192   rows carrying j'y / j'en / n'y / n'en
//
//   il y a. THE BRIEF LISTS ITS USABILITY AS UNVERIFIED:
//
//      223 published rows carry it
//       18 of those have a respelling and no gender
//        0 of those are in pronoms-essentiels
//
//   THE BROKEN-NASAL SWEEP. Every published row carrying an elided y or en
//   pronoun AND a respelling:
//
//       19 rows,   14 FLAGGED by the real hasPlainNasalFor
//       fr.sons.expressions-utiles.059           [zhuh tahn PREE]
//       fr.sons.expressions-utiles.130           [zhahn-NAY MAHR]
//       fr.sons.expressions-utiles.136           [ZHAHN NAY buh-ZWUHN]
//       fr.sons.expressions-utiles.157           [EEL NYAH PLÜ DUH PUHN]
//       fr.sons.expressions-utiles.158           [EEL YAHN NAH ahn-KOR]
//       fr.b2.expressions-argot.034              [SAHN FOOTR]
//       fr.b2.expressions-argot.035              [SAHN fee-SHAY]
//       fr.sons.mots-de-liaison.075              [eel-nahn-duh-MUR-pa-mwan-KUH]
//       fr.sons.expressions-utiles.202           [eel-nahn-neh-pah-kess-TYOHN]
//       fr.sons.expressions-utiles.218           [zhuh-nahn-ruh-vyehn-PAH]
//       fr.sons.expressions-utiles.219           [zhuh-nahn-krwah-pah-may-ZYUH]
//       fr.sons.expressions-utiles.237           [nuh-tahn-feh-PAH]
//       fr.a2.pronoms-essentiels.031             [zhahn VUH]
//       fr.sons.alphabet.238                     [EEL NYA PA dak-SAHⁿ DAHⁿ mohⁿ-n‿a-DREHS koo-RYEHL MEHM SEE MOHⁿ pray-NOHⁿ ahⁿ-n‿A UHⁿ]
//
//   THE FRAME CELLS. Every one is absent as a WHOLE SENTENCE, which is the
//   claim the generator refuses on. The substring column is what the brief's
//   probe measured and it is a weaker statement.
//
//     Tu vas à Paris ?                 exact   0   as a substring   0
//     J'y vais.                        exact   0   as a substring   1
//     Je pense à mon examen.           exact   0   as a substring   0
//     J'y pense souvent.               exact   0   as a substring   1
//     Je parle de mon travail.         exact   0   as a substring   0
//     J'en parle.                      exact   0   as a substring   0
//     Tu bois du café ?                exact   0   as a substring   0
//     J'en bois.                       exact   0   as a substring   1
//     Tu as du sucre ?                 exact   0   as a substring   0
//     Oui, j'en ai.                    exact   0   as a substring   0
//     Tu prends du sucre ?             exact   0   as a substring   0
//     Oui, j'en prends.                exact   0   as a substring   0
//     Tu as des enfants ?              exact   0   as a substring   0
//     Oui, j'en ai trois.              exact   0   as a substring   0
//     J'en ai beaucoup.                exact   0   as a substring   0
//     J'en veux un peu.                exact   0   as a substring   0
//     J'en ai assez.                   exact   0   as a substring   0
//     Tu vas au marché ?               exact   0   as a substring   1
//     Oui, j'y vais demain.            exact   0   as a substring   0
//     Je joue au tennis.               exact   0   as a substring   0
//     J'y joue le samedi.              exact   0   as a substring   0
//     Nous y allons ensemble.          exact   0   as a substring   0
//     Tu vas au bureau ?               exact   0   as a substring   0
//     Oui, j'y vais.                   exact   0   as a substring   0
//     Elle en parle.                   exact   0   as a substring   1
//     Elle habite en France.           exact   0   as a substring   2
//     Il y a du pain.                  exact   0   as a substring   2
//     Il y en a.                       exact   0   as a substring   1
//     Il y en a trois.                 exact   0   as a substring   0
//     Je n'y vais pas.                 exact   0   as a substring   0
//     Je n'en veux pas.                exact   0   as a substring   0
//     Il n'y pense pas.                exact   0   as a substring   0
//     Nous n'en parlons pas.           exact   0   as a substring   0
//     Tu y vas souvent ?               exact   0   as a substring   0
//     Elle y va tous les jours.        exact   0   as a substring   0
//     Nous en prenons.                 exact   0   as a substring   0
//     Vous en voulez ?                 exact   0   as a substring   0
//     Ils y pensent.                   exact   0   as a substring   0
//     Tu en as ?                       exact   0   as a substring   1
//     J'en ai parlé.                   exact   0   as a substring   0
//     Je n'en ai pas parlé.            exact   0   as a substring   0
//     J'y ai pensé.                    exact   0   as a substring   0
//     Il en rêve.                      exact   0   as a substring   0
//     Nous en revenons.                exact   0   as a substring   0
//     Elle y répond.                   exact   0   as a substring   1
//     J'en ai besoin.                  exact   0   as a substring   0
//     Oui, j'y vais tous les samedis.  exact   0   as a substring   0
//     Non, je n'en ai plus.            exact   0   as a substring   0
//     J'en prends un, merci.           exact   0   as a substring   0
//     Oui, j'en ai parlé hier.         exact   0   as a substring   0
//
//   THE THEME. 584 published rows, 584 of them not this build's.
//   0 pre-existing duplicate fr groups, computed article-stripped the way
//   flashhub-coverage computes it, and this build adds none.
//
//   THE RESPELL POPULATION, every published row for each word, with the count
//   the real hasPlainNasalFor flags:
//
//     aller   (0 flagged)
//       a-LAY               1   fr.sons.consonnes.143
//       ah-LAY              1   fr.sons.verbes-essentiels.003
//     penser   (2 flagged)
//       pahn-SAY            2   fr.b1.verbes.083 fr.sons.verbes-essentiels.020
//     jouer   (0 flagged)
//       ZHWAY               3   fr.a1.amis.023 fr.a1.animaux-domestiques.101 fr.sons.verbes-essentiels.023
//       zhoo-AY             1   fr.a1.rp-loisirs.035
//     vouloir   (0 flagged)
//       voo-LWAR            1   fr.sons.verbes-essentiels.007
//     avoir   (0 flagged)
//       ah-VWAR             1   fr.sons.verbes-essentiels.002
//     boire   (0 flagged)
//       BWAHR               2   fr.a1.cuisine.042 fr.a1.rp-repas.014
//     prendre   (0 flagged)
//       PRAHⁿDR             3   fr.a1.transports-quotidiens.041 fr.sons.consonnes.107 fr.sons.verbes-essentiels.012
//
//   THE FALSE POSITIVES. Corrections §6 asks every build to look for the real
//   /n/ false positive and to report the ABSENCE if it finds none. a2.06 found
//   none, a2.24 found two. THIS BUILD FOUND 0.

import type { Item } from '../../../ealch-v2/src/content/schema.ts';

export const Y_EN_IMPORT_ROWS: Item[] = [
  { id: "fr.a1.cafe.151", kind: "phrase", level: "a1", theme: "cafe", fr: "du café", en: "some coffee", ipa: "/dy ka.fe/", respell: "dü ka-FAY", notes: "Coffee, the substance. Not a cup of it, and not coffee in general.", tags: ["article-partitif","boisson"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a1.cuisine.042", kind: "word", level: "a1", theme: "cuisine", fr: "boire", en: "to drink", respell: "BWAHR", tags: ["verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.a1.cuisine.268", kind: "sentence", level: "a1", theme: "cuisine", fr: "Je bois du café.", en: "I drink coffee.", ipa: "/ʒə bwa dy ka.fe/", tags: ["article-partitif","nourriture"], drills: ["sentence","flashcard","review"], audioRef: null, version: 1 },
  { id: "fr.a1.expressions-de-quantite.001", kind: "phrase", level: "a1", theme: "expressions-de-quantite", fr: "beaucoup de", en: "a lot of, many, much", ipa: "/bo.ku də/", respell: "boh-koo duh", notes: "Invariable: works with countable and uncountable nouns. Always followed by de/d', never du/de la/des.", tags: ["beaucoup","quantity"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1 },
  { id: "fr.a2.prepositions-essentielles.130", kind: "sentence", level: "a2", theme: "prepositions-essentielles", fr: "Je vais à Paris.", en: "I am going to Paris.", ipa: "/ʒə vɛ a pa.ʁi/", respell: "zhuh veh a pa-REE", notes: "A city has no article to fold with, so à goes straight on. Twelve letters.", tags: ["prepositions","lieu","ville"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.prepositions-essentielles.131", kind: "sentence", level: "a2", theme: "prepositions-essentielles", fr: "Je vais en France.", en: "I am going to France.", ipa: "/ʒə vɛ ɑ̃ fʁɑ̃s/", respell: "zhuh veh ahⁿ FRAHⁿSS", notes: "La France has an article and en throws it away. Fourteen letters, and the country half of this is a1.22's.", tags: ["prepositions","lieu","pays"], drills: ["sentence","flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.prepositions-essentielles.173", kind: "sentence", level: "a2", theme: "prepositions-essentielles", fr: "Je finis en deux heures.", en: "I finish in two hours.", ipa: "/ʒə fi.ni ɑ̃ dø zœʁ/", respell: "zhuh fee-NEE AHⁿ duh ZUHR", notes: "How long the job takes, start to finish. Nineteen letters. Reuses a2.10's frame verb on purpose: « Il finit tôt » is that lesson's dictée and this is the same verb with a length on it.", tags: ["prepositions","temps","en"], drills: ["sentence","flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.prepositions-essentielles.185", kind: "phrase", level: "a2", theme: "prepositions-essentielles", fr: "en deux heures", en: "in two hours, that is how long it took", ipa: "/ɑ̃ dø zœʁ/", respell: "AHⁿ duh ZUHR", notes: "Twelve letters, and the shortest thing in the lesson. Same two hours as pendant and depuis, and a third answer.", tags: ["prepositions","temps"], drills: ["flashcard","voiceflash","review","dictation"], audioRef: null, version: 1 },
  { id: "fr.a2.prepositions-essentielles.186", kind: "phrase", level: "a2", theme: "prepositions-essentielles", fr: "il y a trois jours", en: "three days ago", ipa: "/il i a tʁwa ʒuʁ/", respell: "EEL EE AH trwah ZHOOR", notes: "Fourteen letters and NO DICTATION DRILL, because the dictée is a production surface and this phrase needs a tense the learner does not have.", tags: ["prepositions","temps"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.028", kind: "phrase", level: "a2", theme: "pronoms-essentiels", fr: "j'y pense", en: "I think about it", ipa: "/ʒi pɑ̃s/", respell: "zhee PAHNSS", notes: "Y replaces à + a place or a thing already mentioned, and it goes right before the verb.", tags: ["pronoun","y"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.029", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Je vais à Paris ; j'y vais en train.", en: "I'm going to Paris; I'm going there by train.", tags: ["pronoun","y"], drills: ["flashcard","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.030", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Tu penses à ton examen ? Oui, j'y pense souvent.", en: "Are you thinking about your exam? Yes, I think about it often.", tags: ["pronoun","y"], drills: ["flashcard","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.031", kind: "phrase", level: "a2", theme: "pronoms-essentiels", fr: "j'en veux", en: "I want some", ipa: "/ʒɑ̃ vø/", respell: "zhahn VUH", notes: "En replaces de + a noun already mentioned, often showing a quantity.", tags: ["pronoun","en"], drills: ["flashcard","voiceflash","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.032", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Tu veux du café ? Oui, j'en veux bien.", en: "Do you want some coffee? Yes, I'd like some.", tags: ["pronoun","en"], drills: ["flashcard","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.033", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Elle a trois frères ; elle en parle souvent.", en: "She has three brothers; she talks about them often.", tags: ["pronoun","en"], drills: ["flashcard","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.190", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Je le vois.", en: "I see it.", ipa: "/ʒə lə vwa/", respell: "zhuh luh VWAH", notes: "THE FRAME. Eight letters, so the dictée takes it in LETTERS mode, which is the only mode that can test a position.", tags: ["a2","pronoun","position","present"], drills: ["flashcard","voiceflash","dictation","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.237", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Je parle à Marie.", en: "I talk to Marie.", ipa: "/ʒə paʁl a ma.ʁi/", respell: "zhuh PARL ah mah-REE", notes: "The à half. The person is named and the little word in front of them is what this lesson is about. English says \"to\" here too, which is why parler is one of the four rather than one of the six.", tags: ["a2","pronoun","indirect","present"], drills: ["flashcard","voiceflash","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.pronoms-essentiels.238", kind: "sentence", level: "a2", theme: "pronoms-essentiels", fr: "Je lui parle.", en: "I talk to him.", ipa: "/ʒə lɥi paʁl/", respell: "zhuh lwee PARL", notes: "THE FRAME. Ten letters through the real dicteeMode, so the dictée takes it in LETTERS mode. The brief says twelve.", tags: ["a2","pronoun","indirect","present"], drills: ["flashcard","voiceflash","dictation","sentence","review"], audioRef: null, version: 1 },
  { id: "fr.a2.rp-voyage.007", kind: "sentence", level: "a2", theme: "rp-voyage", fr: "Il y en a un à quatorze heures, quai trois.", en: "There's one at 2pm, platform three.", ipa: "i.li.ɑ̃.n‿a œ̃.n‿a ka.tɔʁ.z‿œʁ kɛ tʁwa", notes: "Il y en a combines il y a with the pronoun en, referring back to trains.", tags: ["il-y-a"], drills: ["dictation","sentence"], audioRef: null, version: 1 },
  { id: "fr.sons.expressions-utiles.158", kind: "phrase", level: "sons", theme: "expressions-utiles", fr: "il y en a encore", en: "there's still some left", ipa: "/il jɑ̃n a ɑ̃kɔʁ/", respell: "EEL YAHN NAH ahn-KOR", notes: "The happy answer to is there any left.", tags: ["expression"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.jours-et-mois.081", kind: "phrase", level: "sons", theme: "jours-et-mois", fr: "il y a une heure", en: "an hour ago", ipa: "/i.li.a.yn.œʁ/", respell: "EEL EE AH ÜN UHR", notes: "Il y a plus a duration points to the past: an hour back.", tags: ["time","expressions"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.002", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "avoir", en: "to have", ipa: "/avwaʁ/", respell: "ah-VWAR", notes: "irregular · j'ai, tu as, il a, nous avons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.003", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "aller", en: "to go", ipa: "/ale/", respell: "ah-LAY", notes: "irregular · je vais, tu vas, il va, nous allons", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.007", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "vouloir", en: "to want", ipa: "/vulwaʁ/", respell: "voo-LWAR", notes: "irregular · je veux, il veut, ils veulent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.012", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "prendre", en: "to take", ipa: "/pʁɑ̃dʁ/", respell: "PRAHⁿDR", notes: "irregular · je prends, nous prenons, ils prennent", tags: ["irregular"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.020", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "penser", en: "to think", ipa: "/pɑ̃se/", respell: "pahn-SAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
  { id: "fr.sons.verbes-essentiels.023", kind: "word", level: "sons", theme: "verbes-essentiels", fr: "jouer", en: "to play", ipa: "/ʒwe/", respell: "ZHWAY", notes: "regular -er verb", tags: ["er-verb"], drills: ["flashcard","voiceflash"], audioRef: null, version: 1, cardType: "vocab" },
];

/** What Postgres held for each repair target when this was generated. The batch
 *  compares it against RESPELL_REPAIRS and refuses on a mismatch, so a repair
 *  table that has drifted from the database cannot silently repair nothing. */
export const STORED_RESPELL: Record<string, string> = {
  "fr.sons.verbes-essentiels.020": "pahn-SAY",
  "fr.b1.verbes.083": "pahn-SAY",
  "fr.a2.pronoms-essentiels.028": "zhee PAHNSS",
  "fr.a2.pronoms-essentiels.031": "zhahn VUH",
  "fr.sons.expressions-utiles.158": "EEL YAHN NAH ahn-KOR"
};

/** The six consecutive published rows the corpus header's §1 rests on, as they
 *  read on the day this was generated. */
export const SIX_ROW_SET: Record<string, string> = {
  "fr.a2.pronoms-essentiels.028": "j'y pense",
  "fr.a2.pronoms-essentiels.029": "Je vais à Paris ; j'y vais en train.",
  "fr.a2.pronoms-essentiels.030": "Tu penses à ton examen ? Oui, j'y pense souvent.",
  "fr.a2.pronoms-essentiels.031": "j'en veux",
  "fr.a2.pronoms-essentiels.032": "Tu veux du café ? Oui, j'en veux bien.",
  "fr.a2.pronoms-essentiels.033": "Elle a trois frères ; elle en parle souvent."
};

/** Whole-sentence counts for each authored frame, excluding this build's rows. */
export const FRAME_EXACT: Record<string, number> = {
  "Tu vas à Paris ?": 0,
  "J'y vais.": 0,
  "Je pense à mon examen.": 0,
  "J'y pense souvent.": 0,
  "Je parle de mon travail.": 0,
  "J'en parle.": 0,
  "Tu bois du café ?": 0,
  "J'en bois.": 0,
  "Tu as du sucre ?": 0,
  "Oui, j'en ai.": 0,
  "Tu prends du sucre ?": 0,
  "Oui, j'en prends.": 0,
  "Tu as des enfants ?": 0,
  "Oui, j'en ai trois.": 0,
  "J'en ai beaucoup.": 0,
  "J'en veux un peu.": 0,
  "J'en ai assez.": 0,
  "Tu vas au marché ?": 0,
  "Oui, j'y vais demain.": 0,
  "Je joue au tennis.": 0,
  "J'y joue le samedi.": 0,
  "Nous y allons ensemble.": 0,
  "Tu vas au bureau ?": 0,
  "Oui, j'y vais.": 0,
  "Elle en parle.": 0,
  "Elle habite en France.": 0,
  "Il y a du pain.": 0,
  "Il y en a.": 0,
  "Il y en a trois.": 0,
  "Je n'y vais pas.": 0,
  "Je n'en veux pas.": 0,
  "Il n'y pense pas.": 0,
  "Nous n'en parlons pas.": 0,
  "Tu y vas souvent ?": 0,
  "Elle y va tous les jours.": 0,
  "Nous en prenons.": 0,
  "Vous en voulez ?": 0,
  "Ils y pensent.": 0,
  "Tu en as ?": 0,
  "J'en ai parlé.": 0,
  "Je n'en ai pas parlé.": 0,
  "J'y ai pensé.": 0,
  "Il en rêve.": 0,
  "Nous en revenons.": 0,
  "Elle y répond.": 0,
  "J'en ai besoin.": 0,
  "Oui, j'y vais tous les samedis.": 0,
  "Non, je n'en ai plus.": 0,
  "J'en prends un, merci.": 0,
  "Oui, j'en ai parlé hier.": 0
};
/** The same frames counted as substrings, which is what the brief's probe did. */
export const FRAME_SUBSTRING: Record<string, number> = {
  "Tu vas à Paris ?": 0,
  "J'y vais.": 1,
  "Je pense à mon examen.": 0,
  "J'y pense souvent.": 1,
  "Je parle de mon travail.": 0,
  "J'en parle.": 0,
  "Tu bois du café ?": 0,
  "J'en bois.": 1,
  "Tu as du sucre ?": 0,
  "Oui, j'en ai.": 0,
  "Tu prends du sucre ?": 0,
  "Oui, j'en prends.": 0,
  "Tu as des enfants ?": 0,
  "Oui, j'en ai trois.": 0,
  "J'en ai beaucoup.": 0,
  "J'en veux un peu.": 0,
  "J'en ai assez.": 0,
  "Tu vas au marché ?": 1,
  "Oui, j'y vais demain.": 0,
  "Je joue au tennis.": 0,
  "J'y joue le samedi.": 0,
  "Nous y allons ensemble.": 0,
  "Tu vas au bureau ?": 0,
  "Oui, j'y vais.": 0,
  "Elle en parle.": 1,
  "Elle habite en France.": 2,
  "Il y a du pain.": 2,
  "Il y en a.": 1,
  "Il y en a trois.": 0,
  "Je n'y vais pas.": 0,
  "Je n'en veux pas.": 0,
  "Il n'y pense pas.": 0,
  "Nous n'en parlons pas.": 0,
  "Tu y vas souvent ?": 0,
  "Elle y va tous les jours.": 0,
  "Nous en prenons.": 0,
  "Vous en voulez ?": 0,
  "Ils y pensent.": 0,
  "Tu en as ?": 1,
  "J'en ai parlé.": 0,
  "Je n'en ai pas parlé.": 0,
  "J'y ai pensé.": 0,
  "Il en rêve.": 0,
  "Nous en revenons.": 0,
  "Elle y répond.": 1,
  "J'en ai besoin.": 0,
  "Oui, j'y vais tous les samedis.": 0,
  "Non, je n'en ai plus.": 0,
  "J'en prends un, merci.": 0,
  "Oui, j'en ai parlé hier.": 0
};
/** The CONSTRUCTION, which the brief calls rare. Header §3. */
export const CONSTRUCTION_COUNT: Record<string, number> = {
  "j'y": 11,
  "j'en": 30,
  "n'y": 61,
  "n'en": 27,
  "il y a": 245,
  "il y en a": 2,
  "y aller": 7
};

/** Every published respelling for the seven verbs this build imports. */
export const RESPELL_POPULATION: Record<string, Record<string, string[]>> = {
  "aller": {
    "a-LAY": [
      "fr.sons.consonnes.143"
    ],
    "ah-LAY": [
      "fr.sons.verbes-essentiels.003"
    ]
  },
  "penser": {
    "pahn-SAY": [
      "fr.b1.verbes.083",
      "fr.sons.verbes-essentiels.020"
    ]
  },
  "jouer": {
    "ZHWAY": [
      "fr.a1.amis.023",
      "fr.a1.animaux-domestiques.101",
      "fr.sons.verbes-essentiels.023"
    ],
    "zhoo-AY": [
      "fr.a1.rp-loisirs.035"
    ]
  },
  "vouloir": {
    "voo-LWAR": [
      "fr.sons.verbes-essentiels.007"
    ]
  },
  "avoir": {
    "ah-VWAR": [
      "fr.sons.verbes-essentiels.002"
    ]
  },
  "boire": {
    "BWAHR": [
      "fr.a1.cuisine.042",
      "fr.a1.rp-repas.014"
    ]
  },
  "prendre": {
    "PRAHⁿDR": [
      "fr.a1.transports-quotidiens.041",
      "fr.sons.consonnes.107",
      "fr.sons.verbes-essentiels.012"
    ]
  }
};

/** Every published row carrying an elided y or en pronoun AND a respelling that
 *  the real checker flags. Four are repaired; the rest are in
 *  RESPELL_LEFT_ALONE with the reason. */
export const FLAGGED_PRONOUN_ROWS: readonly string[] = [
  "fr.sons.expressions-utiles.059",
  "fr.sons.expressions-utiles.130",
  "fr.sons.expressions-utiles.136",
  "fr.sons.expressions-utiles.157",
  "fr.sons.expressions-utiles.158",
  "fr.b2.expressions-argot.034",
  "fr.b2.expressions-argot.035",
  "fr.sons.mots-de-liaison.075",
  "fr.sons.expressions-utiles.202",
  "fr.sons.expressions-utiles.218",
  "fr.sons.expressions-utiles.219",
  "fr.sons.expressions-utiles.237",
  "fr.a2.pronoms-essentiels.031",
  "fr.sons.alphabet.238"
];

export const MEASURED_AT = 'read from Postgres by scripts/_a225_manifest.ts';
export const MEASURED_ROWS = {
  imported: 27,
  headwords: 7,
  phrases: 8,
  sentences: 12,
  themeRowsBefore: 584,
  themeDuplicateGroups: 0,
  repairs: 5,
  blindRepairs: 1,
  falsePositives: 0,
  framesMeasured: 50,
  framesPresentAsWholeSentence: 0,
  elidedPronounRows: 192,
  respelledPronounRows: 19,
  flaggedPronounRows: 14,
  ilYaRows: 223,
  ilYaImportable: 18,
  ilYaInTheme: 0,
} as const;
