// Write a TCF paper's common.ts from its approved plan.
//
// Built after doing it by hand twice. The file is entirely derived — the topic
// ledger is the plan's own ids and the ITEMS block is pick-items.ts output — so
// hand-assembling it risks exactly the transcription error the ledger exists to
// prevent. TEF's blanc-01 typed its ledger by hand and both figures were wrong.
//
// It REFUSES to overwrite. A paper's common.ts is read back by `spent()` to
// tell later papers what to avoid, so clobbering one silently changes what
// every subsequent paper draws.
//
// Usage (from ealch-admin/):
//   pnpm tsx scripts/tcf/scaffold-paper.ts 3
import '../env';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

const no = Number(process.argv.slice(2).find((a) => /^\d+$/.test(a)));
if (!no) throw new Error('give a paper number, e.g. `scaffold-paper.ts 3`');
const pad = String(no).padStart(2, '0');
const dir = resolve(HERE, `../tcf-blanc${pad}`);
const out = resolve(dir, 'common.ts');

if (existsSync(out)) {
  console.error(`\n✖ ${out} already exists.\n  Refusing to overwrite: spent() reads it to tell papers ${no + 1}+ what to avoid.\n`);
  process.exit(1);
}

const plan = readFileSync(resolve(HERE, `../../exam-blueprints/PLAN-tcf-blanc-${pad}.md`), 'utf8');

function section(title: string): string {
  const i = plan.indexOf(`## ${title}`);
  if (i < 0) throw new Error(`the plan has no "${title}" section`);
  const j = plan.indexOf('\n## ', i + 1);
  return plan.slice(i, j > 0 ? j : plan.length);
}

const ids = (block: string) => [...block.matchAll(/^\| (TCF-\d+) \|/gm)].map((m) => m[1]!);
const co = ids(section('Compréhension orale'));
const ce = ids(section('Compréhension écrite'));
const open = [...section('Expression écrite et orale').matchAll(/^\| (E[EO]-T\d) \| (TCF-\d+) \|/gm)].map(
  (m) => [m[1]!, m[2]!] as const
);

if (co.length !== 24 || ce.length !== 23) {
  throw new Error(`plan has ${co.length} CO and ${ce.length} CE documents; expected 24 and 23`);
}
if (open.length !== 6) throw new Error(`plan has ${open.length} open tasks; expected 6`);

const wrap = (list: string[]) => {
  const rows: string[] = [];
  for (let i = 0; i < list.length; i += 8) rows.push('//       ' + list.slice(i, i + 8).join(' · '));
  return rows.join('\n');
};
const suits = (prefix: string) =>
  open.filter(([s]) => s.startsWith(prefix)).map(([s, id]) => `${id} (${s.split('-')[1]})`).join(' · ');

// The ITEMS block comes from pick-items on stdin, so this script never queries
// the database itself and the two cannot disagree about the plan.
const items = readFileSync(0, 'utf8');
const marker = '} as const;';
const end = items.lastIndexOf(marker);
if (!items.includes('export const ITEMS') || end < 0) {
  throw new Error('stdin did not contain a pick-items ITEMS block; pipe `pick-items.ts N` into this');
}
const itemsBlock = items.slice(items.indexOf('/** Corpus items'), end + marker.length);

const body = `// TCF Canada blanc-${pad} — shared constants and the paper plan.
//
// ── The paper plan ──────────────────────────────────────────────────────────
//
// TOPICS-tcf-canada.md rule 1: no topic is reused across TCF papers. The ids
// below are what scripts/tcf/plan-paper.ts emitted for this paper and what it
// reads back to know what paper ${no + 1} must avoid, so this ledger is DERIVED
// rather than re-typed. Generated by scripts/tcf/scaffold-paper.ts.
//
// The full layout, including which document carries how many questions, is in
// exam-blueprints/PLAN-tcf-blanc-${pad}.md. Re-run the planner to regenerate it.
//
//   CO
${wrap(co)}
//   CE
${wrap(ce)}
//   EE  ${suits('EE')}
//   EO  ${suits('EO')}
//
// ── The ramp is the instrument ──────────────────────────────────────────────
//
// 39 questions per comprehension épreuve, A1 to C2, in order: 3/6/10/10/7/3.
// Order is CONTENT here in a way it is not on TEF — item 4 is A2 because it is
// item 4 — so nothing may reorder a section, and scripts/tcf/paper-rules.ts
// refuses a paper whose ramp goes backwards even when the counts balance.
//
// ── Integrity ───────────────────────────────────────────────────────────────
//
// Every proper noun below is invented (STANDARD-common §6.1). Every figure is
// either invented and attributed to an invented source, or a plain fact of the
// document itself. No real institution, business or person appears anywhere.

export const FORMAT = 'tcf_canada' as const;
export const VARIANT = 'blanc-${pad}';
export const FORMAT_VERSION = 'tcf-canada-2026.01';
export const PAPER_ID = \`paper.\${FORMAT}.\${VARIANT}.${no}\`;

export const taskId = (taskType: string, seq: string) =>
  \`exam.\${FORMAT}.\${VARIANT}.\${taskType}.\${seq}\`;

/** Carried by every closed task. STANDARD-common §7, plus the scoring
 *  disclaimer. CO and CE use SEPARATE NCLC tables on this format. */
export const NOTES_CLOSED = [
  'Épreuve blanche rédigée par Ealch d’après le format publié. Ce n’est pas un sujet officiel et aucun extrait ne provient d’un sujet réel.',
  'Le barème brut vers échelle est une estimation experte, pas une équivalence officielle. Les seuils NCLC proviennent de la grille IRCC.',
];

export const NOTES_OPEN = [
  'Épreuve blanche rédigée par Ealch d’après le format publié. Ce n’est pas un sujet officiel.',
  'La grille de correction est notre propre construction : le centre d’examen ne publie pas le libellé de ses descripteurs.',
  'La correction est assistée par IA et s’appuie sur cette grille et sur cette réponse modèle. Le résultat est une estimation d’entraînement, jamais un score équivalent.',
];

export const uniq = (...groups: readonly (readonly string[])[]) => [...new Set(groups.flat())];

${itemsBlock}
`;

mkdirSync(dir, { recursive: true });
writeFileSync(out, body, 'utf8');
console.log(`\n  wrote ${out}`);
console.log(`  CO ${co.length} · CE ${ce.length} · open ${open.length} situations\n`);
