// TEF Canada blanc-02 — shared constants and the paper plan.
//
// ── The paper plan ──────────────────────────────────────────────────────────
//
// GENERATED, then pasted here. `scripts/plan-paper.ts 2` drew it from the topic
// bank; `exam-blueprints/PLAN-tef-blanc-02.md` is the approved copy and this is
// the ledger the planner reads back when it draws papers 3 to 5.
//
// It is a comment rather than data on purpose: nothing at runtime needs it, but
// `plan-paper.ts` scans this header for `TEF-\d+` to know what is spent. Do not
// reformat the ids out of it.
//
// blanc-01's equivalent was typed by hand and got both its figures wrong (it
// said 37 of 66 spent, 29 left; the truth was 45 and 21), which is why this one
// is generated and why `scripts/topic-demand.ts` computes the arithmetic.
//
//   CO-A   TEF-69 · TEF-90 · TEF-118 · TEF-127
//   CO-B   TEF-76 · TEF-98 · TEF-103 · TEF-113
//   CO-C   TEF-107 · TEF-119
//   CO-D   TEF-12
//   CO-E   TEF-08
//   CO-F   TEF-19
//   CO-G   TEF-82 · TEF-71 · TEF-93 · TEF-63 · TEF-72 · TEF-89 · TEF-80 · TEF-115
//          TEF-73 · TEF-75 · TEF-112 · TEF-105 · TEF-130 · TEF-83 · TEF-81 · TEF-208
//          TEF-94
//   CE-A   TEF-68 · TEF-88 · TEF-91 · TEF-100 · TEF-122 · TEF-137 · TEF-142
//   CE-BC (no topic: gap-fill is written to the grammar point, per TOPICS)
//   CE-DE  TEF-164 · TEF-173
//   CE-F   TEF-10 · TEF-13
//   CE-G   TEF-37
//   EE-A   TEF-78
//   EE-B   TEF-24
//   EO-A   TEF-36
//   EO-B   TEF-202
//
// 46 of the bank's 255 situations, none of them twice, and none shared with
// blanc-01. `scripts/plan-paper.test.ts` asserts both.
//
// ── Integrity ───────────────────────────────────────────────────────────────
//
// Every proper noun in the finished stimuli is invented (STANDARD-common §6.1),
// and none of blanc-01's invented names are reused — a candidate sitting both
// papers should not meet Sainte-Ambre twice. Every figure is either invented and
// attributed to an invented source, or is a plain fact of the document itself.
// No real institution, business or person appears in any stimulus.
import { NOTES_CLOSED, NOTES_OPEN, taskIdFor, paperIdFor, FORMAT, FORMAT_VERSION, uniq } from '../tef/common.ts';

export { NOTES_CLOSED, NOTES_OPEN, FORMAT, FORMAT_VERSION, uniq };

export const VARIANT = 'blanc-02';
export const PAPER_ID = paperIdFor(VARIANT, 2);
export const taskId = taskIdFor(VARIANT);

/**
 * Where a miss in this block routes back to for review.
 *
 * GENERATED by `scripts/tef/pick-items.ts 2` from the published corpus, not
 * hand-picked as blanc-01's was. Every entry was filled at the block's own band
 * — the script reports any theme that could not, and none did.
 *
 * The schema carries `targetItemIds` on the TASK, so the decomposition is per
 * block rather than per item: a missed block G listening item routes to block
 * G's themes. Coarser than the authoring standard asks for, and recorded as
 * such in the phase notes.
 */
export const ITEMS = {
  affaires: ['fr.b2.affaires.001', 'fr.b2.affaires.002', 'fr.b2.affaires.003', 'fr.b2.affaires.004', 'fr.b2.affaires.005'],
  argentQuotidien: ['fr.b1.argent-quotidien.001', 'fr.b1.argent-quotidien.002', 'fr.b1.argent-quotidien.003', 'fr.b1.argent-quotidien.004', 'fr.b1.argent-quotidien.005'],
  bienEtre: ['fr.b1.bien-etre.001', 'fr.b1.bien-etre.002', 'fr.b1.bien-etre.003', 'fr.b1.bien-etre.004', 'fr.b1.bien-etre.005'],
  bricolage: ['fr.a2.bricolage.001', 'fr.a2.bricolage.002', 'fr.a2.bricolage.003', 'fr.a2.bricolage.004', 'fr.a2.bricolage.005'],
  bureau: ['fr.b1.bureau.001', 'fr.b1.bureau.002', 'fr.b1.bureau.003', 'fr.b1.bureau.004', 'fr.b1.bureau.005'],
  collegues: ['fr.a2.collegues.001', 'fr.a2.collegues.002', 'fr.a2.collegues.003', 'fr.a2.collegues.004', 'fr.a2.collegues.005'],
  conflitsReconciliation: ['fr.b1.conflits-reconciliation.001', 'fr.b1.conflits-reconciliation.002', 'fr.b1.conflits-reconciliation.003', 'fr.b1.conflits-reconciliation.004', 'fr.b1.conflits-reconciliation.005'],
  corps: ['fr.a2.corps.001', 'fr.a2.corps.002', 'fr.a2.corps.003', 'fr.a2.corps.004', 'fr.a2.corps.005'],
  courses: ['fr.a2.courses.001', 'fr.a2.courses.002', 'fr.a2.courses.003', 'fr.a2.courses.004', 'fr.a2.courses.005'],
  deplacements: ['fr.a2.deplacements.001', 'fr.a2.deplacements.002', 'fr.a2.deplacements.003', 'fr.a2.deplacements.004', 'fr.a2.deplacements.005'],
  douaneEtImmigration: ['fr.b1.douane-et-immigration.006', 'fr.b1.douane-et-immigration.010', 'fr.b1.douane-et-immigration.016', 'fr.b1.douane-et-immigration.017', 'fr.b1.douane-et-immigration.023'],
  droit: ['fr.b1.droit.001', 'fr.b1.droit.002', 'fr.b1.droit.003', 'fr.b1.droit.004', 'fr.b1.droit.005'],
  ecole: ['fr.a2.ecole.001', 'fr.a2.ecole.002', 'fr.a2.ecole.003', 'fr.a2.ecole.004', 'fr.a2.ecole.005'],
  economie: ['fr.b2.economie.001', 'fr.b2.economie.002', 'fr.b2.economie.003', 'fr.b2.economie.004', 'fr.b2.economie.005'],
  gouvernement: ['fr.a2.gouvernement.001', 'fr.a2.gouvernement.002', 'fr.a2.gouvernement.003', 'fr.a2.gouvernement.004', 'fr.a2.gouvernement.005'],
  hebergement: ['fr.a2.hebergement.001', 'fr.a2.hebergement.002', 'fr.a2.hebergement.003', 'fr.a2.hebergement.004', 'fr.a2.hebergement.005'],
  immigrationEtCitoyennete: ['fr.b1.immigration-et-citoyennete.001', 'fr.b1.immigration-et-citoyennete.005', 'fr.b1.immigration-et-citoyennete.006', 'fr.b1.immigration-et-citoyennete.007', 'fr.b1.immigration-et-citoyennete.008'],
  internet: ['fr.a2.internet.001', 'fr.a2.internet.002', 'fr.a2.internet.003', 'fr.a2.internet.004', 'fr.a2.internet.005'],
  jardinage: ['fr.a2.jardinage.001', 'fr.a2.jardinage.002', 'fr.a2.jardinage.003', 'fr.a2.jardinage.004', 'fr.a2.jardinage.005'],
  maison: ['fr.a2.maison.001', 'fr.a2.maison.002', 'fr.a2.maison.003', 'fr.a2.maison.004', 'fr.a2.maison.005'],
  marche: ['fr.a2.marche.001', 'fr.a2.marche.002', 'fr.a2.marche.003', 'fr.a2.marche.004', 'fr.a2.marche.005'],
  metiers: ['fr.a2.metiers.001', 'fr.a2.metiers.002', 'fr.a2.metiers.003', 'fr.a2.metiers.004', 'fr.a2.metiers.005'],
  musique: ['fr.a2.musique.001', 'fr.a2.musique.002', 'fr.a2.musique.003', 'fr.a2.musique.004', 'fr.a2.musique.005'],
  rechercheEmploi: ['fr.a2.recherche-emploi.001', 'fr.a2.recherche-emploi.002', 'fr.a2.recherche-emploi.003', 'fr.a2.recherche-emploi.004', 'fr.a2.recherche-emploi.005'],
  sportsEtLoisirs: ['fr.a2.sports-et-loisirs.001', 'fr.a2.sports-et-loisirs.002', 'fr.a2.sports-et-loisirs.003', 'fr.a2.sports-et-loisirs.004', 'fr.a2.sports-et-loisirs.005'],
  systemeDeSante: ['fr.a2.systeme-de-sante.001', 'fr.a2.systeme-de-sante.002', 'fr.a2.systeme-de-sante.003', 'fr.a2.systeme-de-sante.004', 'fr.a2.systeme-de-sante.005'],
  transportsQuotidiens: ['fr.a2.transports-quotidiens.001', 'fr.a2.transports-quotidiens.002', 'fr.a2.transports-quotidiens.003', 'fr.a2.transports-quotidiens.004', 'fr.a2.transports-quotidiens.005'],
  valeurs: ['fr.b2.valeurs.001', 'fr.b2.valeurs.002', 'fr.b2.valeurs.003', 'fr.b2.valeurs.004', 'fr.b2.valeurs.005'],
  vetements: ['fr.a2.vetements.001', 'fr.a2.vetements.002', 'fr.a2.vetements.003', 'fr.a2.vetements.004', 'fr.a2.vetements.005'],
  voisinage: ['fr.a2.voisinage.001', 'fr.a2.voisinage.002', 'fr.a2.voisinage.003', 'fr.a2.voisinage.004', 'fr.a2.voisinage.005'],
} as const;
